### ISSUE TITLE
Use a configuration first method (modifiers and states) for Gallery

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-next#1005]
Relates directly back to #273

**Comment by mcoker** [comment]
@christiemolloy I don't think we need to do anything with this layout. If you agree, can you go ahead and close this?

**Comment by christiemolloy** [comment]
@mcoker I believe theres a variable name that needs to be changed to incorporate its modifier.

`--pf-l-gallery--GridGap` should be `--pf-l-gallery--m-gutter--GridGap`

**Comment by mcoker** [comment]
@christiemolloy good call!
