### ISSUE TITLE
Use a configuration first method (modifiers and states) for Grid 

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-next#1006]
Relates directly back to #273

**Comment by christiemolloy** [comment]
@mcoker closing this issue as i don't believe anything needs to be updated - want to double check?

**Comment by mcoker** [comment]
@mattnolting what's the purpose of `.pf-l-grid__item`? Can we remove that? Or do we need to add it to this selector? https://github.com/patternfly/patternfly-next/blob/master/src/patternfly/layouts/Grid/grid.scss#L9

**Comment by mcoker** [comment]
@christiemolloy I think we can create a var for the grid items' `grid-column-[start/end]` and redefine that in the `@mixin`s, I put up a PR. And we probably need to do something with the `.pf-l-grid__item` question above.
