### ISSUE TITLE
Review and Test Page Layout

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#101]
Review and Test Page Layout this also includes adjustments required for IE11. Create a fallback and replacement where needed.

**Comment by cliffpyles** [comment]
@LHinson @andresgalante There haven't been any PRs created for the Page layout yet. Should I Add the layout as part of this issue also, or is there some existing work we want to use?

**Comment by LHinson** [comment]
@cliffpyles Yeah, let's hold off on this one... This is currently blocked by #103

**Comment by LHinson** [comment]
Closing as this is redundant, covered by #127
