### ISSUE TITLE
About demo

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#104]
Use pf-next layouts and components to create the "About" demo

[Latest Design PDF](https://drive.google.com/open?id=1emU3QKb9-sU4Z5z6EIVcu9AtlIhbShWR)
[Latest Design AI](https://drive.google.com/open?id=1DGd-flAiPnNVI01IwfK9iGtzTiO4DxHP)

Component lifecycle: 
- [X] Interaction design requirements 
- [X] Visuals
- [X] First checkpoint complete and approved 
- [ ] CSS 
- [ ] React
- [ ] Second checkpoint complete and approved 

Contacts: 
- Visual @kybaker 
- CSS

**Comment by mcarrano** [comment]
Maintain content and behavioral consistency with http://www.patternfly.org/pattern-library/communication/about-modal/

**Comment by mceledonia** [comment]
[PDF ](https://drive.google.com/open?id=1emU3QKb9-sU4Z5z6EIVcu9AtlIhbShWR)
[AI](https://drive.google.com/open?id=1DGd-flAiPnNVI01IwfK9iGtzTiO4DxHP)
Non-about modal coming soon

**Comment by mceledonia** [comment]
[Latest Design PDF](https://drive.google.com/open?id=1emU3QKb9-sU4Z5z6EIVcu9AtlIhbShWR)

**Comment by LHinson** [comment]
@kybaker we need to determine if this close button merits something unique or if it should use the reusable ghost button.

**Comment by mattnolting** [comment]
Closed by #462
