### ISSUE TITLE
Page Layout Templates 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#106]
Page layouts needs to be revisited to ensure that we are addressing how content is laid out and how components respond in various screen sizes. Components include: nav, header. This will impact layouts and is an enhancement to layouts. 

[Requirements and Designs](https://drive.google.com/open?id=1nsRbVqeqK7zvn2ABQnAlYxQDkj93U7AX)

**Comment by mcarrano** [comment]
Questions and thoughts on needs and scope:

* Consider separate layouts for different navigation styles - vertical nav, horizontal nav, context selector, others?
* Required elements in page header include: Branding/product logotype, utility bar with user menu and notification drawer. Other items including application launcher optional
* Any variations for specific page types needed? Potential page variants include dashboard, content view, form, or detail view pages.

**Comment by mcarrano** [comment]
Collected sample page layouts from product can be found here: https://docs.google.com/presentation/d/1lsas3zrjKm1RD8ZfgQaHdXVrOLDUfNr9m9HLdFQuvEY/edit?usp=sharing Want to identify a small set of page layouts/templates that can be applied to different categories of content.

**Comment by mcarrano** [comment]
Per meeting on May 20 with UX leads, want to start by understanding requirements for different navigation patterns that will drive page layout templates that are needed. Following actions will be taken:

1. @mcarrano will analyze collected screen shots and identify required layouts based on IA models that these represent. These layout types will be communicated to visual design in wireframe form. Wireframe layouts may include combinations of vertical and horizontal navigation patterns.

2. Proposed page layouts will be reviewed with visual design and CSS.

3. @kybaker will work from this set to deliver hi-fidelity mockups for all required page templates that can be queued up for implementation.

4. Navigation guidelines page will be developed that communicates criteria for choosing the appropriate layout to match needs of a given project.

Goal to have initial wireframe level mockups for review by COB this week.  @LHinson FYI.

**Comment by mcarrano** [comment]
@kybaker @matthewcarleton and I met today to review preliminary wireframes as referenced above. Based on that we arrived at an approach for navigation as outlined here that includes a simple horizonal nav, a two-level vertical nav, and a level 3 subnav. https://drive.google.com/open?id=1Q6T734QWVEQ-Gjw0jlRf1StxdK8_Z43C  Next steps will be to move to hi-fi mockups.

**Comment by mcarrano** [comment]
Made some changes to add back a hybrid pattern for use cases with with simple horizontal and deeper vertical navigation. https://drive.google.com/open?id=1f043HaRo7B-4e1dmHEKsrlQFChJA9tDA

**Comment by mcarrano** [comment]
Page layouts will be driven by a navigation system that is flexible and designed to accommodate a variety of use cases. These options are summarized here: https://docs.google.com/presentation/d/1Ye5Vhj3AqQStZINtqUJ4Y8-mzKX3qBWRmlMQdP-lnwY/edit?usp=sharing

**Comment by kybaker** [comment]
Reviewed the initial designs with @matthewcarleton and @mceledonia 6/6. The structure of the pages is in a good place but requires content to verify that the system works. Michael is working on the story for data visualization design. While he completes this story he will try the new components in the layouts verifying that both elements work together. Michael will share the designs in the story once they are further along. I recommend this story stay in visual design stage in the meantime.

**Comment by kybaker** [comment]
After feedback last week this requires exploration of interactions to accommodate additional content. It also requires content to validate the designs as stated above.

**Comment by LHinson** [comment]
Leaving this open as the following still needs addressed: 
- design on page 8
- columns on page 10

**Comment by LHinson** [comment]
a sync between @andresgalante and @kybaker identified that columns on page 10 is not a requirement.

**Comment by LHinson** [comment]
Closing issue since the design on page 8 has been addressed by #686
