### ISSUE TITLE
Convert Design Assets To Sketch

### ISSUE THREAD

**Issue by kybaker** [patternfly/patternfly-next#108]
- Covert the existing design assets from Illustrator to Sketch. This includes all of the base components and layouts.
- This does not include creating the new symbols or template library.

- [x] Spacers | Michael
- [x] Colors | Michael - Pull the colors from the PF3 Design Kit
- [x] Typography | Michael - setup the text styling and include a line height guide
- [x] Shadows | Michael
- [x] Buttons | Kyle - including states and spacers
- [x] Dropdowns, Input fields, Search | Kyle
- [x] Pagination | Jenny
- [x] Form Elements - Radio, checkbox, button groups and controls | Jenny
- [x] List view
- [x] Calendar widget
- [x] Card with chart
- [x] Navigation

**Comment by LHinson** [comment]
@cliffpyles there has been conversation about being able to convert code to sketch components. Will you elaborate on what's possible there? Trying to determine how this might impact this issue.

**Comment by LHinson** [comment]
After meeting with @cliffpyles @andresgalante @kybaker, we've determined that we should proceed with this issue and should hold off on automation at this time.

**Comment by kybaker** [comment]
- [ ] Testing the checklist

**Comment by kybaker** [comment]
- [ ] Trying this again 
- [x] Trying this again 
- [ ] Trying this again 
- [ ] Trying this again

**Comment by kybaker** [comment]
This will continue as we move forward.

**Comment by LHinson** [comment]
@kybaker since the checklist has been completed and this will just be part of the process moving forward, any reason why we wouldn't close this issue?
