### ISSUE TITLE
Introduce Options Menu component

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#1088]
We require an options menu that is similar to a Dropdown, but is used to select among groups of options rather than to trigger an action. This is required for toolbar features like sorting or Items per Page selection, and may have general use elsewhere. Visual designs can be seen as part of the Toolbar work here: https://redhat.invisionapp.com/share/67PFEYCRWZF#/335107769_V2_Toolbar_-PDF-

It should be possible to open the menu from a labeled button or an icon button (as shown for Sort referenced above). This may be considered as a new variant of a Dropdown or a new component.

**Comment by mcarrano** [comment]
@LHinson @rachael-phillips This is something that we should get on the roadmap as a requirement for the toolbar.

**Comment by mcoker** [comment]
After talking with @jgiardino, we will model this after the [collapsible listbox](https://www.w3.org/TR/wai-aria-practices-1.1/examples/listbox/listbox-collapsible.html)
