### ISSUE TITLE
Bulk Selection

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#1089]
Bulk selection enables a user to select multiple items in a table, list, or card view to perform global actions. Bulk selection should:

* Allow the user to select all items in the current view
* Select all items in a data set across pages (when pagination is used).
* Report current number of items selected and indicate partial selection.

See PatternFly 3 documentation here: https://www.patternfly.org/pattern-library/forms-and-controls/bulk-selector/ for reference

This issue should identify any new components or modifications to existing components as required.

**Comment by rachael-phillips** [comment]
Hi Matt, thanks for the heads up! I can add this to our component status
spreadsheet

**Comment by katierik** [comment]
I'd like to propose some additional content for bulk selector. Specifically, around how bulk selection works for a table, how it works with filters, and some additional select all/some options.
I put together a file with reference to the current documentation (as of 4/22) and the proposal.

File: https://docs.google.com/document/d/1o6Uippbb2gCrMOYzzJ1kQmXOLRY-SucofanDpKLxcYQ/edit?usp=sharing

**Comment by mcarrano** [comment]
Met with @katierik to discuss requirements and potential design approaches. We agreed that it makes sense to focus initially on bulk selection for tables since this is the primary use case. Based on that, we will see how this extends to other views. @katierik will work up some initial design proposals for further review.

**Comment by katierik** [comment]
Sharing a prototype I made to demonstrate the proposed pattern:
https://marvelapp.com/5312gfj

There are 2 paths to go down. See the intro slide for details.

**Comment by mcarrano** [comment]
The prototype looks great @katierik . I really like this approach of refreshing the toolbar with only relevant actions upon selection. @mcoker @dlabaj @mceledonia @kybaker @jgiardino @mattnolting would welcome any feedback.

**Comment by jgiardino** [comment]
These designs look really nice!  I included a few thoughts below on screen reader experience...

It would be worth testing what the screen reader experience would be for the bulk checkbox before and after selecting it. I was thinking the label (not visible) would be "Select all", and when selected, we would want to keep that label and somehow combine it with the "25 selected" text. Maybe using aria-describedby on the "25 selected" text would make the most sense, but it would be worth testing the experience where it's used as part of the label, too.

I'm not really sure what gets announced when the checkbox is in the indeterminate state (e.g. partial selection), so it would be good to test that, too, just to know for sure.

Do you know what the options in the menu would be? If there are a standard set of options we would recommend, then we should also consider what the screen reader label for the toggle (i.e. arrow button) should be.

**Comment by mcarrano** [comment]
I have converted this to an epic that covers multiple component updates plus a demo as discussed during our meeting on Aug 9. Related issues include:

Create tri-state checkbox: #1411
Adding text to the split-button #2161
Allowing the table selection to be controlled from the toolbar #1262
Bulk selection demo to pull everything together #1878

@mcoker @rachael-phillips @LHinson Let me know if I've missed anything.

**Comment by LHinson** [comment]
OK, i've moved out "bulk select" out of the current spreadsheet for this milestone and instead opted to pull in the tri-state checkbox and split button issue. cc @rachael-phillips 

@mcoker let us know if there is any concerns from this from an implementation standpoint.

**Comment by rachael-phillips** [comment]
Added latest OpenShift bulk select designs to this issue: http://openshift.github.io/openshift-origin-design/web-console/future-openshift/bulk-actions/bulk-actions

**Comment by rachael-phillips** [comment]
Closing this epic because it has been completed.
