### ISSUE TITLE
CSS vars referenced, but never defined

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-next#1097]
In the _distribution_ patternfly.css, there are several variables that are used but don't seem to have a definition.

- `--pf-c-form--group--MarginLeft`
- `--pf-c-about-modal-box__content--PaddingBottom`
- `--pf-c-about-modal-box__content--PaddingTop`
- `--pf-global--LineHeight--lg`
- `--pf-c-about-modal-box__header--PaddingTop`
- `--pf-global--ListStyle`
- `--pf-global--link--normal`
- `--pf-c-chip--Color`
- `--pf-c-breadcrumb__heading--FontSize`
- `--pf-c-chip-group--BackgroundColor`

This causes a conversion script to older css formats to blow up. We probably wanna add some type of check to prevent this from happening going forward. I imagine it's easy to overlook when refactoring.

**Comment by srambach** [comment]
Great catch! I'd say to leave the global variables.
