### ISSUE TITLE
Empty state doesn't stretch to fill container

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly-next#1098]
The empty state currently has a max-width on it. Our convention is that a component fills available space, and the parent container is responsible for sizing and placement. I recommend removing the max-width. A modifier could be used to limit the width if absolutely necessary.

@mcoker @mceledonia what do you think?

**Comment by mceledonia** [comment]
@srambach It's mainly a design decision to have a max-width on the empty state, to prevent the line length from getting too long on large pages. We are aiming for a [readable line length](https://practicaltypography.com/line-length.html), but we also don't want it too short either. I am open to widening it a bit more if it feels to short, but we do want the constraint at a certain point so we don't end up with very long lines of text on wide monitors or viewports. 

@kybaker Looping you in as this is a decision that impacts other areas of the system as well.

**Comment by mcoker** [comment]
@mceledonia @kybaker how about we do something similar to modal where we have 2 modifiers, one for small and one for large, that set a small/large `max-width`. Then without a modifier, the component is 100% width and the paren't container can set the size, or potentially react could then add a `width` prop, too, that would allow you to pass a custom size to the react component (the modal does that currently, too).
