### ISSUE TITLE
Popover Enhancement

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-next#1101]
Currently we have set min and max width variables for the popover - as per design specs. 
React was asking how a consumer would override the max-width for the popover? 
Should we create a pf-m-lg modifier to modify the max-width of the popover so that we can handle it in Core first?

 @mcarrano @jschuler @mceledonia @jgiardino

**Comment by mcoker** [comment]
I think we could add a prop for `maxWidth` (and `minWidth`?) that overwrites these properties:

```
    min-width: var(--pf-c-popover--MinWidth);
    max-width: var(--pf-c-popover--MaxWidth);
```

In their application, they can also overwrite `--pf-c-popover--MinWidth` and `--pf-c-popover--MaxWidth`

**Comment by christiemolloy** [comment]
If that works then that sounds good to me. @mcoker

**Comment by mcoker** [comment]
The only concern I might have is with regards to consistency. If I'm not mistaken, the modal component takes a `width` prop, not a `maxWidth` prop. I'm not sure if we should offer consistency between these components with regards to how you modify the width/max-width. Do you want to follow up with who made the original request or want me to follow up with someone?

**Comment by christiemolloy** [comment]
@mcoker IMO the modal uses a width prop to determine its size on the screen and the popover, uses a max-width so that the text wraps at a certain breakpoint. I'll talk with Titani on the React side.

**Comment by christiemolloy** [comment]
@mcoker spoke with @tlabaj and she said they can add a prop for maxWidth and minWidth.
In terms of being consistent across components - I feel like thats more of a question for design. Last I spoke with @mceledonia he mentioned it should be a max-width which is what we currently have.

**Comment by mcoker** [comment]
Cool. Re: consistency, I meant with the props we offer on the react side for people to configure, but I agree it makes sense for popover and modal to be different in core because a modal will be as wide as possible, limited by a max-width, and the popover (and tooltip) are as narrow as possible (only growing as large as the content inside), also limited by a max-width.
