### ISSUE TITLE
Remove the List Component

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-next#1107]
Creating this issue as I just met with @mcarrano and @gdoyle1 about List/Data List. We came to the conclusion that they are the same thing. And currently new examples are being made for the datalist by @gdoyle1 .

The list component #675 was created for use in the login page but the list being used in the login page is not actually the List component that was designed.

1) Investigate whether to use the "Grid Layout" in footer of the "Login" component to replace the list that is there
2) make sure the list is not being used anywhere else
3) Remove the "List" component

**Comment by mcoker** [comment]
I think the grid layout would work in the login component. And I think the new "flex/row" layout will do the current `.pf-c-list.pf-m-inline` layout. I guess is there any benefit to having a generic numeric/bulleted list component like this that can be used outside of `.pf-c-content`?

**Comment by christiemolloy** [comment]
@mcarrano @gdoyle1 can you answer the question above ^. I think I saw one example in the Data List sketch file that has a numeric/bulleted list, what do you guys think?

**Comment by mcarrano** [comment]
I'm not sure. I guess I would turn the question back to you @christiemolloy @mcoker . If I wanted to create a block of text content that included a bulleted or numbered list, is that covered by the Content component or would you want a list component that stands on it's own. What exactly is the purpose of the Content component?

**Comment by gdoyle1** [comment]
Would you need the list grid to create the column headers of a data table? @christiemolloy @mcoker

**Comment by mcoker** [comment]
@mcarrano the content component basically allows you to write common HTML without special classes or having to define components, and the elements are well formatted and play nicely together. It styles things like `<h1>-<h6>`, `<ul>/<ol>/<dl>`, `<p>`, `<blockquote>`, etc. You can get an idea here - https://pf-next.com/components/content/examples/.

> If I wanted to create a block of text content that included a bulleted or numbered list, is that covered by the Content component or would you want a list component that stands on it's own.

If all you were doing was creating a list (with no text or anything around it), it would be a nice to have just to be able to define a list without having to wrap it in a `.pf-c-content` element to get the bulleted/number styling. I think it's fine to keep around for users to use even if we aren't using it in any other components. It's a pretty common pattern. But it could be argued that you should just use `.pf-c-content` for it, too.

@gdoyle1 the only place we're using the list component now is for the social links in the footer of the login page. Are you referring to the column headers now or is this in an upcoming change?

**Comment by gdoyle1** [comment]
@mcoker I was referring to the column headers as they are now so you answered my question! So the design of the list component would then just be text? It seems kind of repetitive with the content section that Matt was referring to. I don't have a strong opinion either way though.

**Comment by mcoker** [comment]
cool! yep the difference is just that having a list component allows us to write...

`<ul class="pf-c-list">...`

instead of

```
<div class="pf-c-content">
  <ul>...
</div>
```

**Comment by christiemolloy** [comment]
So if we keep the generic list component, I think:
a) we should use the component in our own components like (Nav?)
b) DataList would need to be an extension on the List component

**Comment by mcoker** [comment]
Hmm... I'm not sure I understand. The nav and datalist components wouldn't benefit from the presentation of the list component as far as I'm aware. I'm not sure why you would want to use the list component in those 2 components.

**Comment by christiemolloy** [comment]
Closing this issue and reopening #1086 as we have decided to keep the list component and make updates at this stage.
