### ISSUE TITLE
PF-Next Workspace: Test Webpack Loader for Handlebars

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#111]
There is a webpack loader for handlebars. It might work well with Gatsby.
https://github.com/pcardune/handlebars-loader

This is an issue to try and test if this would be a viable solution for our workspace.

**Comment by cliffpyles** [comment]
@dgutride @LHinson @andresgalante

The handlebars-loader that could be a good alternative. It won't remove the need to write JSX or JS in all situations, but it could come pretty close, depending on how we use it. It also would allow us to keep the existing Gatsby solution.

https://github.com/pcardune/handlebars-loader

I'm putting together a complex demo for further review.
