### ISSUE TITLE
Focus indication for Tabs in Chrome

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-next#1113]
Until we implement #790, we're relying on default styles provided by browsers for indicating focus.

Currently, the focus styles in chrome are partially hidden, which could make it difficult for sighted keyboard users to figure out which tab has focus. 

![image](https://user-images.githubusercontent.com/21063328/50016765-1fe4cb80-ff98-11e8-8e6b-ec80c8dc9c34.png)

It looks like this issue is related to this [overflow-x property](https://github.com/patternfly/patternfly-next/blob/master/src/patternfly/components/Tabs/tabs.scss#L129)

**Comment by srambach** [comment]
@jgiardino Just to clarify - is the desired behavior that the blue focus ring is shown completely circling the tab? Or just to make sure that both left and right are shown?

**Comment by jgiardino** [comment]
I'm not sure what our options are at this point. If it's super easy to get just left and right highlights, but a major rework to get all around, then maybe we go with the super easy for now, and bring this up with the css and visual design teams to figure out what we want moving forward.

Do you have an idea yet how much of a change it would require to get all around? Or even just showing sides and top?

**Comment by srambach** [comment]
No :-/ It's complicated with the scrolling and overflow and the vertical height with/without the scrollbar. Before I went too deep, I wanted to know for sure where to head.

**Comment by jgiardino** [comment]
Copying @mceledonia on this to loop him in. I'm curious what his thoughts are on implementing a custom focus style for this. 

Custom focus styles might be something we can consider depending on what our options are for enabling the default focus styles to display.

**Comment by mceledonia** [comment]
I am definitely interested in an overall approach of utilizing default styles when we can, and using our custom style as a backup for when we can't. 

If we can use a default focus style here for tabs we should go for it.
