### ISSUE TITLE
Regression testing - investigation

### ISSUE THREAD

**Issue by dgutride** [patternfly/patternfly-next#1123]
Investigate and prototype a regression testing solution that will provide build/pr time feedback on breaking changes.  

Visual regression has been deemed too fragile to qualify for this - one idea the team has is to use a snapshot of the DOM w/applied styles (see this repo:  https://azaslavsky.github.io/domJSON/).  We could store these representations and compare at build time to make sure we haven't broken anything.

**Comment by ibolton336** [comment]
After looking into this, the domjson library is currently broken so this wouldn't be a viable route. When adding the library to a node script and running it, I was seeing " TypeError: Cannot read property 'href' of undefined" in a few places. Other than visual regression testing, I am out of ideas.

**Comment by rachael-phillips** [comment]
How is this issue coming along? It would be great to have a status update. Thanks!

**Comment by redallen** [comment]
Closing in favor of #2673.
