### ISSUE TITLE
Distinguish Radio Button and Checkbox as separate components

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-next#1137]
The Radio button component and the checkbox component should live on two different component pages because of their differing functionality and use cases. 

IxD Notes:
- In a list of radio buttons, only one radio button may be selected
- A checkbox implies that the user can multi-select options from a list

**Comment by jgiardino** [comment]
just fyi, I think this is a duplicate of #482

**Comment by rachael-phillips** [comment]
Closing because it was a duplicate
