### ISSUE TITLE
Accordion

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#116]
Introduce the Accordion. @maryshak1996 is the visual design contact for this issue and should be added as a reviewer for a PR related to accrodion.

Both the fluid and fixed height flows can be seen in this prototype: https://redhat.invisionapp.com/share/4DOQCKDENBK

Here are the specs that I have for right now:
**Fluid Content Height:** 
![screen shot 2018-10-23 at 11 30 40 am](https://user-images.githubusercontent.com/19824574/47372129-200ecc00-d6b7-11e8-8c84-4cf7cfecd847.png)
Fixed Content Height: 
![screen shot 2018-10-23 at 11 37 22 am](https://user-images.githubusercontent.com/19824574/47372573-0ae66d00-d6b8-11e8-8a90-efe4203f06cd.png)
_** text content area has a height of 128px (or two dark purple spacers)_

**Comment by mcarrano** [comment]
There are two variations of accordions in PatternFly 3, a [standard accordion](http://www.patternfly.org/pattern-library/widgets/#accordion) and a [fixed height accordion](http://www.patternfly.org/pattern-library/widgets/#fixed-height-accordion). Both should be supported.

**Comment by maryshak1996** [comment]
ps. I will also be coming up with a design for the fixed height version that was in @mcarrano 's mocks too... stay tuned :)

**Comment by maryshak1996** [comment]
**Quick Updates:**
1) modified the interaction to more closely align with that of vertical navigation (on hover the text color goes to Blue-400 and on selected it stays Blue-400 and font-weight becomes semi-bold)
2) I've mocked up fixed height as well

Both the fluid and fixed height flows can be seen in this prototype: https://redhat.invisionapp.com/share/4DOQCKDENBK

Here are the specs that I have for right now:
**Fluid Content Height:** 
![screen shot 2018-10-23 at 11 30 40 am](https://user-images.githubusercontent.com/19824574/47372129-200ecc00-d6b7-11e8-8c84-4cf7cfecd847.png)
Fixed Content Height: 
![screen shot 2018-10-23 at 11 37 22 am](https://user-images.githubusercontent.com/19824574/47372573-0ae66d00-d6b8-11e8-8a90-efe4203f06cd.png)
_** text content area has a height of 128px (or two dark purple spacers)_

@mcarrano any concerns/ thoughts?

**Comment by mcarrano** [comment]
Looks good to me @maryshak1996

**Comment by maryshak1996** [comment]
@andresgalante what are your thoughts from the dev side?

**Comment by LHinson** [comment]
@michael-coker can review this from a CSS perspective!

**Comment by michael-coker** [comment]
Looks great to me @maryshak1996! 👍

**Comment by LHinson** [comment]
Thanks for the review @mcoker. 
@maryshak1996 @kybaker I assume this is good to proceed to css dev?

**Comment by kybaker** [comment]
@LHinson Looks good!

**Comment by LHinson** [comment]
@mcarrano I know this is pretty straight forward but do we want to add this one to the agenda for review with stakeholders?
