### ISSUE TITLE
Button example updates

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-next#1171]
After a recent discussion about use of `<a>` vs `<button>` elements, there was some concern about whether we should include examples that show `<a>` elements styled to look like buttons, over concerns that we would be promoting the use of button styles for links when displaying links as links might be better.  

Updates for this issue are to remove the example labeled "Links as Buttons"

**Comment by jgiardino** [comment]
I added the label `on hold` for this one, since there's another issue #1176 related to design documentation on when to use links vs buttons.

**Comment by jgiardino** [comment]
Closing this issue. After discussion with CSS team, we want to keep options available to consumers to use as they need to, and will cover the topic of which html element to use in the accessibility guide, but that how these elements are styled is up to the discretion of the designer.

**Comment by mcoker** [comment]
@jgiardino did you mean to close this?

**Comment by jgiardino** [comment]
Yes. 😞  Thanks!
