### ISSUE TITLE
Login page link design

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-next#1173]
Currently, there are links on the login page that are not obviously links due to the visual presentation (i.e. links are undecorated white text following a paragraph that's also white text). And the only blue pf color variables that pass color contrast are `pf-color-blue-100` and `pf-color-light-blue-100`, which don't provide much improvement over using white. 

As part of the issue, visual design will review what the best solution for handling this is and provide a recommendation for CSS.

Comment from @kybaker:
> I think we need to figure out if the SVG filter is working as intended. I believe the image is much too light.

![image](https://user-images.githubusercontent.com/21063328/50653581-f516e300-0f57-11e9-89ef-212608624424.png)

**Comment by maryshak1996** [comment]
https://pf-next.com/components/login/examples-full/?component=Login
^ has been updated to fix the CSS bug, but we'll still do more exploration to figure out the contrast situation

**Comment by maryshak1996** [comment]
Proposed visual updates:
- CSS SVG filter tweaked to alter background to have a color range from #333333 to #000000, which darkens the background image
- the links ('Terms of Use', 'Help', and 'Privacy Policy') will use #39a5dc [blue-300] as already agreed on for link color over a dark background
- more information to come regarding hover color/treatment of link over a dark background
@kybaker @mceledonia @mcoker

**Comment by maryshak1996** [comment]
here is the design for a link over dark on hover for this login page
![screen shot 2019-01-09 at 10 01 18 am](https://user-images.githubusercontent.com/19824574/50909477-e5851780-13f9-11e9-8600-e8a094b8943f.png)

**Comment by rachael-phillips** [comment]
Closing this issue

**Comment by jgiardino** [comment]
@rachael-phillips I see that this issue is closed, but am not able to find a reference to a PR where this was fixed (or a duplicate issue if that's the case). Could you update this issue with a link/statement to what the resolution of this issue was?
