### ISSUE TITLE
`.pf-l-page__sidebar` needs `-webkit-overflow-scrolling: touch` to enable momentum-based scrolling

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-next#1175]
Without `-webkit-overflow-scrolling: touch`, sidebar scrolling is tedious in iOS.

cc: @spadgett, @janwright73

**Comment by matthewcarleton** [comment]
Hey @rhamilto this is already in core. It may require the update from a layout to a component though, although I thought was done before that switch. I'll sync with @priley86 on this.

**Comment by rhamilto** [comment]
Thanks, @matthewcarleton.  We're good in OpenShift now.  @dtaylor113 bumped us to the new component with the fix in https://github.com/openshift/console/pull/989.  Will close this issue.
