### ISSUE TITLE
Update Buttons design doc to include guidance to designers about when to use buttons vs links

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#1176]
It is not always obvious when to use a Button vs a link. Ghost buttons, for example, and styled to look like links but should actually be used to represent actions. For accessibility considerations, it is important to differentiate links that use the <a> tag to navigate to a new page from actions that keep the user on the current page. Providing some examples of common use cases like buttons and actions in cards or toolbars would be helpful.

Current Button design doc here: https://github.com/patternfly/patternfly-design/blob/master/patternfly-4/components/button/design.md

**Comment by jgiardino** [comment]
From an implementation perspective, there is a difference in the html elements that would be used. A "link" is anything that navigates to a new url. The url could be a section on the current page, or a new page. Anything else is a button. 

At our last a11y meeting, there was a general consensus that users should know when a clickable element is a navigation link or an action button, but I would be hesitant to make a statement that `<a>` elements must always look like links and `<button>` elements must always look like buttons. 

There are many use cases when designers would swap the visual styles for the element being used. For example:
-  a link that displays in a toolbar along with other buttons (e.g. when the action to open a wizard is a full page wizard and not in a modal) 
- a link that is the main call to action on a web page
- icons in the masthead could be a mix of buttons and links. Alternatively, the settings icon could be a link to a settings page in one product and a button that opens a modal in another product, depending on how complex the settings are.
- a button that displays inline within a body of text (e.g. "Download product documentation for... ". 

As part of this issue, it would be great to make sure these cases are considered.
