### ISSUE TITLE
Use of `vh` units in `.pf-c-about-modal-box` causes content to be clipped by iOS browser chrome

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-next#1177]
![screen shot 2019-01-03 at 3 25 01 pm](https://user-images.githubusercontent.com/895728/50659830-c276e580-0f6b-11e9-993c-8b61e252caf1.png)

https://css-tricks.com/the-trick-to-viewport-units-on-mobile/#article-header-id-0 outlines the issue in detail.  IMO, PatternFly should not be using `vh` or `vw` units.

Related:  https://github.com/patternfly/patternfly-next/issues/1174

cc:  @spadgett, @janwright73

**Comment by christiemolloy** [comment]
Closing this issue as the problem was solved by @mcoker 's refactoring work which removed 'vh' units.
