### ISSUE TITLE
Button component modifier for displaying inline

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-next#1182]
Updates for this issue include:
- Add a modifier class `pf-m-inline` to the Button component so that `<button>` elements can be displayed inline in a body of text. This class should: 
  - remove spacing styles
  - display the button inline
- Check that the Button component with the following classes displays as intended within a paragraph: `<button class="pf-c-button pf-m-link pf-m-inline">`

There are some use cases that require the ability to include a `<button>` element in a body of text. 

For example, in the context of a toast notification / dynamic alert, the recommended way for identifying the main action of the alert is to include it within the text so that it's accessible to sighted and screen reader users. Depending on context, this action could be a link or could be a button. Another example is in the Content component, where including a statement like "[Download the product documentation](#) for additional information about..." could be included. In these cases, the recommended element to use is a `<button>` since the action isn't navigating to another page. 

Currently, links can be included within a body of text by simply using the `<a>` element. But additional styles are needed to support the use of `<button>` elements in this way. The recommended solution would be to include the following classes so that the button looks like a link and also displays properly inline:
`<button class="pf-c-button pf-m-link pf-m-inline">`

**Comment by jgiardino** [comment]
@mcarrano @kybaker 
There was a recent discussion regarding how to handle the use case where a `<button>` element is included within a body of text, like the examples shown in #854 for including actions in toast notifications:

The build is complete. Go to the Builds page to [download](#).

In the case where a button is included in a body of text, do you have any suggestions on how these elements should be styled? Should they be identical to links (i.e. underline on hover)? or just use the current link modifier on the button (i.e. no underline on hover)?

This topic is also related to #1176

**Comment by jgiardino** [comment]
We did talk about that as a possible alternative, where a link to the Builds page is provided instead of the action button to download. But there were several reasons why we felt that we should support either use case:

- If there isn't a link available, or if the preferred design is to make "download" clickable instead of sending the user to the page that has the action, and these styles for `<button>` aren't available, the developer would use `<a>` for the "download" action anyway, which wouldn't be best practice
- Providing the ability to use a more semantic element but styled appropriately provides more flexibility to designers to support their specific use cases, which supports the case that PF4 is more modular. 
- The toast notification is just one example. Anytime a clickable element needs to be included in a body of text, these elements aren't always navigating to another page.

**Comment by andybraren** [comment]
When this is implemented, a new toast alert example containing an inline button should probably be added to the AlertGroup component of #1136, along with usage guidelines.
