### ISSUE TITLE
Link over dark hover color

### ISSUE THREAD

**Issue by maryshak1996** [patternfly/patternfly-next#1199]
Explore color/treatment of link color over a dark background on hover. Discussed a bit in https://github.com/patternfly/patternfly-next/issues/1173

**Comment by maryshak1996** [comment]
@kybaker opened a story for this since this would be a change made globally

**Comment by maryshak1996** [comment]
https://redhat.invisionapp.com/share/ECPZLWV2F6Y
this invision flow outlines the treatment and color for links both over white and dark backgrounds with examples of both. the real takeaways are below
![screen shot 2019-01-15 at 11 31 43 am](https://user-images.githubusercontent.com/19824574/51194488-29c05e00-18b9-11e9-9bfb-114cb0facc83.png)

**Comment by maryshak1996** [comment]
![at-a-glance](https://user-images.githubusercontent.com/19824574/51280601-19d67600-19ae-11e9-8232-8105ab4f46b8.png)
these are the colors that we will be using for links
https://redhat.invisionapp.com/share/ECPZLWV2F6Y

**Comment by maryshak1996** [comment]
@mcoker 
what is currently on pf-next for hover colors for links is off -- not sure what needs to happen to move forward with these updated link colors??

**Comment by mcoker** [comment]
thanks @maryshak1996 submitted a PR - https://github.com/patternfly/patternfly-next/pull/1247
