### ISSUE TITLE
Modal Close Button Focus Marker overlaps Title

### ISSUE THREAD

**Issue by TimoSta** [patternfly/patternfly-next#1203]
If the title of a modal is fairly long and wider than the content, the focus marker of the close button currently overlaps the title text:

![image](https://user-images.githubusercontent.com/5621996/50908795-778c2080-13f8-11e9-8eca-ffa039d8274e.png)

---

This is clearly a fairly minor visual issue and doesn't impact any functionality. It might however be easily fixed though by adjusting the spacing around the close buttton?

**Comment by rachael-phillips** [comment]
Hi @TimoSta! Thank you for filing this and I will make sure our team members see this tomorrow.

**Comment by mcarrano** [comment]
@mcoker can you take a look at this? I know we had some discussion last week on this topic and not sure if this is looking at the most recent code. The long title should truncate, correct?

**Comment by mcoker** [comment]
@TimoSta @mcarrano this should be fixed in https://github.com/patternfly/patternfly-next/pull/1041

**Comment by mcoker** [comment]
@TimoSta can we close this one?

**Comment by TimoSta** [comment]
@mcoker Just verified that it's resolved in our app, and it looks good! 👍
