### ISSUE TITLE
Create App Launcher component

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-next#1213]
We will need the app launcher to be more than just a dropdown component. It will require future design enhancements which justify it being a unique component. 

In the first phase of this component it will offer just a simple dropdown list.

**Comment by rachael-phillips** [comment]
@mceledonia I am writing some notes here based on our conversation the other day with @serenamarie125 and @chart. Here are some notes to consider for the OpenShift team: 

'I would expect that if there are visual “sections” in the left/right layout of icons, that should translate to “sections” in the dropdown, separated by a horizontal divider."

**Comment by matthewcarleton** [comment]
@rachael-phillips are you saying we need a separator in the app launcher or is this related to how all the menus are combined into one when the get condensed for smaller screens?

**Comment by matthewcarleton** [comment]
ah ok thanks @serenamarie125 I don't think this is specific to the issue of creating the app launcher component but more so what happens when they all get combined, which I believe would be an implementation issue for react but I could be wrong. Does that make sense @rachael-phillips ?

**Comment by dlabaj** [comment]
This is currently supported in react by using a Dropdown separator.  For example they can add the following <DropdownSeparator /> between <DropdownItems/>.  I can update our example with one with a separator.  This feature is already there so it shouldn't be blocking.

**Comment by serenamarie125** [comment]
if we can be sure that our example follows the desired behavior @dlabaj , that would be great !
