### ISSUE TITLE
Gatsby - workspace should extract required css into separate css file

### ISSUE THREAD

**Issue by dgutride** [patternfly/patternfly-next#1223]
We'd like to remove the inline styling that is being used right now to work around default gatsby behavior.

- Remove the custom sass plugin added for gatsby v2 upgrade
- Use the normal mechanism in gatsby-node/gatsby-config to overwrite the bundling configuration for minicssextract and extract-text behavior

**Comment by michaelkro** [comment]
Could possibly be a related issue https://github.com/gatsbyjs/gatsby/issues/9733

**Comment by dgutride** [comment]
Closing via https://github.com/patternfly/patternfly-next/pull/1232
