### ISSUE TITLE
Add support for FA to be added via CDN

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-next#1229]
The [upgrade guide](https://pf-next.com/upgrade-guide) references a way to disable the local FA5 icon font config and use a CDN instead, but we don't actually have support in PF4 to do this. We should update PF4 to support that.

**Comment by mindreeper2420** [comment]
@mcoker when I wrote the initial guide, the use of a Font Awesome CDN existed in the codebase (the same way that we use the PatternFly 3 CDN for running PF3 and PF4 together). I was unable to find the commit that it was removed in, but it existed in the early goings of PatternFly 4 (around the same time Font Awesome icons were added).
