### ISSUE TITLE
Variable overrides before definitions in distribution css

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-next#1235]
In our distribution css (patternfly.css and patternfly-base.css) I see that the `:root {}` selector doesn't come first, although I believe it should. See screenshot below, we're overwriting variable values before they have even been defined initially. Seems to be the theme related styles introduced using `@extend` directive.

<img width="781" alt="screen shot 2019-01-15 at 10 21 57 am" src="https://user-images.githubusercontent.com/5942899/51190090-6d15cf00-18af-11e9-9def-b5c9bed493af.png">

Modern browsers don't have a problem with this, as the variable definitions are essentially hoisted before being processed. Older browsers, however, see these different selectors as different scopes and so post-processing becomes a nightmare. It requires breaking apart these files and re-stitching them back together in an acceptable order.

Can we re-structure our scss setup in a way that ensures all global variable declarations are output before any of the overrides? It's one small piece of the puzzle to allow for [IE11 support](https://github.com/patternfly/patternfly-next/issues/450).

**Comment by mcoker** [comment]
@seanforyou23 has this been resolved or do you want to revisit it?
