### ISSUE TITLE
Revisit dropdown component to update styles

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-next#1243]
The dropdown was an early component and since then I think we've changed our approach. There are some styles that can be cleaned up.

The dropdown toggle when just an icon is also only 28px high. We should look at increasing this so it matches all other actionable icons (pf-c-button.pf-m-plain).

This also includes the custom select component as it pulls a lot of styles from the dropdown.

**Comment by mcoker** [comment]
@matthewcarleton can we close this one out? the plain toggles in the dropdown components are all a consistent height now.

**Comment by LHinson** [comment]
Thanks for the update @mcoker. I'll pull the trigger and close :)
