### ISSUE TITLE
Should the InputGroup's text area have a background

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-next#1255]
This is small but I noticed this when I was doing the react review for Input Group, and I think its something that we should be consistent on.

The screenshot attached shows that the components making up the input group vary in their background color (transparent/white). I think we should be consistent here, where possible. And I'm not sure if the text area needs to have a white background, it looks inconsistent next to the button, unless it is for accessibility reasons. 
<img width="542" alt="screen shot 2019-01-17 at 12 55 10 pm" src="https://user-images.githubusercontent.com/20118816/51338463-db959100-1a57-11e9-8d8e-bf8d132b7900.png">

**Comment by mceledonia** [comment]
This has been noted in the component completion doc as high priority. @matthewcarleton 
https://docs.google.com/document/d/1K7oNUPWJUW-qEppUFBKEM9_GqqSE_wobRzSr6bdOwjo/edit#heading=h.d6080xbwafut

**Comment by christiemolloy** [comment]
@mceledonia is there an issue created? I can close this one.

**Comment by mceledonia** [comment]
@christiemolloy I don't think so, this should be the one!
