### ISSUE TITLE
Fix tab text becoming white while clicked

### ISSUE THREAD

**Issue by andybraren** [patternfly/patternfly-next#1260]
Safari's user agent stylesheet makes any button text without a defined color become white when `:active`.

![button-text-safari-chrome](https://user-images.githubusercontent.com/9122899/51393040-c0cd2600-1b04-11e9-8a61-5cc9a7aa3c23.png)

Elements with `.pf-c-button` are styled with `color: var(--pf-global--Color--100)` to override this, but the `button` elements within the Tabs component don't currently use `.pf-c-button`.

We could either add `.pf-c-button` to the buttons within Tabs (which affects a bunch of other styling like `font-weight` and padding), or just add `color: var(--pf-global--Color--100);` to `.pf-c-tabs__button` to fix this.

(Side note: this doesn't visually affect the React implementation because any `:active` tab buttons immediately receive `.pf-m-current` which sets a color.)

**Comment by mcoker** [comment]
fixed in https://github.com/patternfly/patternfly-next/pull/1397
