### ISSUE TITLE
Implement a handlebars transformer for handlebars support

### ISSUE THREAD

**Issue by cliffpyles** [patternfly/patternfly-next#128]
Using this method would allow for better support of handlebars in Gatsby. It would also gives us more control of the build.

This would be an iteration on #111 

More context can be seen here: https://github.com/patternfly/patternfly-next/pull/120#discussion_r179473027

@dmiller9911 Anything that I missed?

**Comment by dgutride** [comment]
Closing as this might not be necessary for now
