### ISSUE TITLE
Add gutters to the layouts

### ISSUE THREAD

**Issue by cliffpyles** [patternfly/patternfly-next#132]
To account for spacing between the layouts' child elements we need to add gutter values to the layouts. Design will provide the appropriate gutter sizes.

**Comment by LHinson** [comment]
per @andresgalante and @kybaker 
>use the `--lg` spacer for the gutters when the `has-gutter` class is present

**Comment by LHinson** [comment]
This is related to #100 and should be done together

**Comment by dgutride** [comment]
Work completed via #190 - closing
