### ISSUE TITLE
Data-List with Modifiers issue

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-next#1327]
In the Data List with modifiers example, at a certain screen size, the Data List looks like this (this doesn't happen in React):
<img width="648" alt="screen shot 2019-01-28 at 10 57 13 am" src="https://user-images.githubusercontent.com/20118816/51848529-bf151680-22eb-11e9-9a5d-6b99e4b3688e.png">

-  the kebab icon is filtering into .pf-c-data-list__expandable-content
- .pf-c-data-list__expandable-content is not full width

**Comment by michpetrov** [comment]
This is somehow caused by the negative margin on `pf-c-data-list__expandable-content`, if you increase either the `margin-left` or the `width` of `pf-c-data-list__action` the items will realign.

**Comment by rachael-phillips** [comment]
Hi @christiemolloy and @michpetrov. How high priority is this issue? Is this blocking implementation?

**Comment by christiemolloy** [comment]
@rachael-phillips its a bug, but not blocking implementation. Ill take it on.
