### ISSUE TITLE
Toolbar layout

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#136]
The toolbar layout is a container of components but has no components inside, it's just a container layout.

The layout has groups and items and accomodate them in a row with spacers between them. The space between groups is larger than the space between items. Visuals should define what those spaces are.

The modal demo can use the toolbar on the footer actions.

Component lifecycle: 
- [x] Interaction design requirements 
- [x] Visuals 
- [x] First checkpoint complete and approved 
- [ ] CSS 
- [ ] React
- [ ] Second checkpoint complete and approved 

Contacts: 
- IxD n/a
- Visual @kybaker 
- CSS

**Comment by mattnolting** [comment]
Hey @kybaker, do you have a link to visuals?
