### ISSUE TITLE
PF Shield Selector Conflict

### ISSUE THREAD

**Issue by jameslau** [patternfly/patternfly-next#1368]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
There is a conflict with the shield selector between PF3 and PF4. The namespace doesn't properly reset styles between the two systems. Below is an screenshot of a product that has it's main body or international components effected when toggling `padding` settings on and off. 

![screen shot 2019-02-04 at 2 35 24 pm](https://user-images.githubusercontent.com/1402829/52232481-a7f59c00-288a-11e9-92d8-3ed5e76ad00b.png)

**Comment by mindreeper2420** [comment]
I have also run into this in the Integ8ly project when using the PatternFly 3 alerts.
