### ISSUE TITLE
Page Component no longer takes up the full viewport

### ISSUE THREAD

**Issue by mindreeper2420** [patternfly/patternfly-next#1378]
In the component `pf-c-page`, previous iterations (pre- v1.0.149 release) set the height property to `height: 100vh`, which allowed the `<Section>` elements to stretch the full height of the browser, when content did not fill the space.

From an initial investigation, the commit [4fb055b97](https://github.com/patternfly/patternfly-next/commit/4fb055b9787cd2f4e5f85497d06ac301a18cd8bf) set the property to `height: 100%;`. As such, `<Section>` elements no longer reach the bottom of a browser window.

I've included before and after screenshots for clarification.

**Before**
![screen shot 2019-02-06 at 1 37 49 pm](https://user-images.githubusercontent.com/4032718/52365005-73ade700-2a14-11e9-9df9-21d4a999b939.png)

**After**
![screen shot 2019-02-06 at 1 38 03 pm](https://user-images.githubusercontent.com/4032718/52365011-79a3c800-2a14-11e9-9acd-05afa7c59a66.png)

**Comment by mcoker** [comment]
hey @mindreeper2420, this change assumes that any ancestors of something that needs to be full height would also have `height: 100%;` assigned. Will that not work for you? This was a solution to a bug reported by OpenShift in https://github.com/patternfly/patternfly-next/issues/1174

**Comment by mindreeper2420** [comment]
@mcoker That isn't how it appears to be working in Integr8ly - I'm assuming that the `<section>` element should then be 100% of the page, which would cause it to appear like screenshot 1 vs screenshot 2, correct? The only thing that fixed the `<section>` being cut short was resetting `pf-c-page` to `100vh`.

From looking at the bug, the change was made to fix a very specific iOS/mobile issue on a single product and not for a desktop browser issue in Core as a whole. Is it possible to reset this back to `100vh` for desktop and add a media query for browsers so that it uses `100%`? That 'should' satisfy all needs.

**Comment by mindreeper2420** [comment]
@mcoker I'm also wondering if an additional helper class might be useful in a case like this, rather than adding a media query - something simple like `pf-m-100vh` (not a correct usage, but just an idea).

**Comment by mcoker** [comment]
closed via https://github.com/patternfly/patternfly-next/issues/1400
