### ISSUE TITLE
Add support on adding an Icon to the DataListItem.

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-next#1389]
Issue [#1338](https://github.com/patternfly/patternfly-react/issues/1338) was opened in the React repo.  The consumer would like to add an icon to the DataListCell.  The consumer followed the [pattern library](https://www.patternfly.org/pattern-library/content-views/list-view/) and tried to add an icon on the left.  This Pattern Library is PF3 specific and currently PF4 does not support the icon being placed to the left as in PF3.

**Comment by karelhala** [comment]
I would make it more generic and allow small size (same as action, collapse or select) of DataListItem.
