### ISSUE TITLE
Ensure CSS can be consumed modularly

### ISSUE THREAD

**Issue by priley86** [patternfly/patternfly-next#139]
Hi PF Next 👋 😸 

I am really excited about the work taking place here and looking forward to starting to consume some of the components being developed. One thing I have noticed downstream and that has been raised in some recent UXD Dev discussions w/ @cliffpyles @dgutride @dmiller9911 @jeff-phillips-18  is the ability to load component/layout/pattern CSS individually along w/ a JS module. We are beginning to look at modularizing the JS bundles to reduce the page weight and improve performance downstream. It would be great to do the same w/ CSS.

So I'd like to open this issue as an initial request/discussion issue and request guidance on how best to load the CSS for PF Next modules. Some things that would be really nice after initial discussion:

* guidance on what sass includes (utilities/mixins/global variables/component/pattern sass) are needed for each component/layout/pattern
* guidance on component/pattern structuring and terminology from a JS standpoint
* guidance on bundling strategy to reduce the page weight as much as possible

This should further enable adoption sooner downstream (as modular consumption becomes available and can be targeted in our apps).

@cliffpyles @dgutride @dmiller9911 @jeff-phillips-18 - thanks for your support and discussions on this so far.

**Comment by matthewcarleton** [comment]
hey @priley86 I think this issue has been addressed so I am going to close it. If you fee like you'd like to have further discussion feel free to re-open.
