### ISSUE TITLE
Need Inline Alert variation

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#1390]
It has been shown that the current Alert component does not look good when dropped into a page as an inline alert as the drop shadow causes it to appear floating above the content. The request is to create a new variant of the alert component with different styling.

**Comment by mcarrano** [comment]
@rachael-phillips @kybaker Here is the new issue I promised to request an Inline Alert variation. @andybraren could you add a screen shot of what you showed me yesterday as it does a good job highlighting the current problem.

**Comment by andybraren** [comment]
![2-2b-1-error-modal](https://user-images.githubusercontent.com/9122899/52436490-6b23e200-2ae2-11e9-9f31-8aaacbae51aa.png)

**Comment by tiffanynolan** [comment]
We also have a similar issue for the inline alert style in Integreatly.
![image](https://user-images.githubusercontent.com/15326290/52737640-d534ff00-2f9a-11e9-95b8-2fb5c7f678b6.png)

**Comment by tiffanynolan** [comment]
For the Integreatly team, we have a fairly immediate need to push through a solution for this as we fully convert Red Hat Solution Explorer to PF4. One proposed solution for this is from @bdellasc. The proposed inline style would be a modification of the existing style to:
- Remove the shadow
- Remove the background color for the side area and use that color for the icon instead. 
- Add that same color as a border around the element

Here is a screenshot: 
![image](https://user-images.githubusercontent.com/15326290/52738455-b2a3e580-2f9c-11e9-89e3-b6f45faebd0d.png)

**Comment by tiffanynolan** [comment]
Played around with another idea to throw in the mix:
![image](https://user-images.githubusercontent.com/15326290/52809252-ccf1c800-305d-11e9-8495-7e88089e7f38.png)

**Comment by tiffanynolan** [comment]
@kybaker @mcarrano I built out a Sketch file to further show our proposal. Please let me know if this is enough information to get this reviewed and approved or if you need additional information. I also chatted with @maryshak1996 about how this proposal ties in to the notification drawer design ideas, so they match up. The Integreatly team should also be able to provide assistance with the dev side, when/if this is approved. 

https://drive.google.com/file/d/1btGgm_pKchb4I5Pbe4BiW3hPHveFpIye/view?usp=sharing

**Comment by rachael-phillips** [comment]
Hi @tiffanynolan I've added this to our roadmap, and after tomorrow I can let you know timeline on this.

**Comment by rachael-phillips** [comment]
Hi @tiffanynolan we have this on the roadmap for our March 22 for our release! Thank you so much, and let me know if you have any questions!

**Comment by tiffanynolan** [comment]
@rachael-phillips Does this have a PF4 designer assigned to it yet? It would be great to have the chance to collaborate with them for any modifications.

**Comment by rachael-phillips** [comment]
It does. @mceledonia is assigned to this issue, and you can find that on the top right of any issue. I have a meeting tomorrow that will determine when we begin design work on this issue.

**Comment by rachael-phillips** [comment]
Hi @tiffanynolan I wanted to update you that after timeline discussions today this will be a variation that gets taken in during our May 5 milestone.

**Comment by tiffanynolan** [comment]
@rachael-phillips Thanks for the updates. Is there a way to reduce the timeline? The Integreatly team is willing to help usher this through the process with stakeholder checkpoints, etc. This is our final element to convert to be fully on PatterFly 4. Even if it's not fully approved, if the direction of the proposed designs is inline with what others are thinking, can we go ahead and use the proposal in our web app? The current inline alert style for PF4 will not work and will likely cause confusion with our users.

**Comment by rachael-phillips** [comment]
Hi @tiffanynolan , I spoke with @mcarrano and @mceledonia and we think it's a fantastic idea to go ahead and move forward with crafting the inline alert variation together. @mcarrano has put together a really helpful template for design proposals here: https://docs.google.com/document/d/1w6O_d6ZSEBoEBgsMMYNUtSMGw73LjEsV3w1pjHtRtVY/edit I'll put a meeting on the calendar to kick off the design conversations, and we can use this template to build it out.

**Comment by mcoker** [comment]
FWIW, I was working with @priley86 on Kiali and they're attempting to use an inline alert on their login screen. I'm not sure if that's an acceptable use of the login component, but since the login component's error message maintains layout on the page even when it isn't shown, if someone drops an inline alert in that area, this is what the default login state looks like.

<img width="1437" alt="Screen Shot 2019-03-25 at 10 45 50 AM" src="https://user-images.githubusercontent.com/35148959/55012556-99d41a00-4fb5-11e9-8ba7-0b2b1358d6fc.png">

**Comment by bdellasc** [comment]
Hi @mcarrano @mceledonia @rachael-phillips @tiffanynolan. I completed the design doc, echoing mocks for toast notifications, and integrating new material where appropriate. Please let me know if you notice any gaps. [Inline alerts design doc](https://docs.google.com/document/d/1HTkvK8_zFJAX-rhBw1aNrmZYzywixik31DzaiKCUbW4/edit?usp=sharing)

**Comment by katierik** [comment]
Hi all - Wanted to throw one more use case into the mix here that @jknilans brought up.
This is the case where the alert/notification is inline, and required to be on a white background. The proposed design looks a little odd (since there is no definition around it). This is the proposal that Josh & I noodled around with:
 
![Screen Shot 2019-04-03 at 9 57 19 AM](https://user-images.githubusercontent.com/23172038/55485125-ca403780-55f7-11e9-9fec-4072d92fc70b.png)

**Comment by catrobson** [comment]
@katierik can you try @bdellasc's proposal in your use case and see if it works for you?  If not this might be another 'variant' we need to consider.

**Comment by ncameronbritt** [comment]
Here is a not-pixel-perfect version where I tried Brian's in the existing openshift ui. 
![Screen Shot 2019-04-03 at 10 28 21 AM](https://user-images.githubusercontent.com/8974593/55487049-60299180-55fb-11e9-96c3-f484d59edb18.png)

**Comment by tiffanynolan** [comment]
@ncameronbritt Thanks for sharing another use case. Do you feel like this pattern/style meets your needs?

**Comment by mcarrano** [comment]
@stacymcauliffe following up on our conversation today about "embedded help." Does the approach outlined here meet the needs you expressed?

**Comment by ncameronbritt** [comment]
@tiffanynolan, I think for inline alerts this pattern works fine for us. For the particular use case I'm working on now, it may not make sense to surface this information as an alert. @stacymcauliffe and I have discussed other possibilities.

**Comment by rachael-phillips** [comment]
@katierik following up here. Did @bdellasc's use case work for your needs?

**Comment by LHinson** [comment]
@mcarrano @rachael-phillips: @srambach is going to go ahead and take this one and add a modifier to the current inline alert to address @tiffanynolan's needs. Right now Integrately only has one remaining component to convert from pf3 to pf4 and they would like to drop pf3 entirely this summer.

**Comment by mcarrano** [comment]
@mceledonia is currently assigned to this issue to review/finalize visuals. @srambach can you sync with Michael to make sure you are working with the correct visual designs? Thanks.

**Comment by mceledonia** [comment]
Finally got around to checking this out, I think the latest version is looking good. Wanted to check back in regarding the discussion earlier in this issue, were there any conclusions on the support of those use cases?

**Comment by mceledonia** [comment]
Small (hopefully quick) update here that I missed before... Icons should be 18px, looks like they're 16px here. I updated a few in the sketch file and everything still works with the current padding shown, just need to update the size of the icon itself! 

@bdellasc @srambach

**Comment by bdellasc** [comment]
Given the changes to the icon size etc this week based on conversations here and with @mceledonia & @srambach,  I updated the source file [InlineAlertsV3.sketch](https://drive.google.com/open?id=1ZLl8gXAP7n5gkCdS6MN3W_Cf4lC1Ob-j) to reflect those changes.

@mcarrano I'd be happy to generate the inline graphics for the design page on the PF site, but I'd just need guidance on any naming conventions we have for those inline images.

**Comment by mcarrano** [comment]
Thanks for the offer to update the graphics @bdellasc . But I've already put up a PR here: https://github.com/patternfly/patternfly-org/pull/1138 Do you think the 2 pixels will be noticeable to redo these? Does this change affect all alerts or only the new inline examples?

**Comment by bdellasc** [comment]
@mcarrano The spacing between the icon and color band is different and the icon is a bit larger than the ones in those v2 mocks. I'd prefer we update them with the most up-to-date graphics if possible. If you want to send me the images you generated, I can re-create them with my new source doc and post them this morning.

**Comment by bdellasc** [comment]
I was messaging with @mcarrano last week and I had posted the updated source file here: https://drive.google.com/open?id=1MZzqkM8wJITbdU1k80muE_ifiL1EPU2F

**Comment by mceledonia** [comment]
Thanks for working that out @bdellasc @mcarrano!
