### ISSUE TITLE
Allow treeshape tables

### ISSUE THREAD

**Issue by karelhala** [patternfly/patternfly-next#1393]
We need to allow consumers to nest multiple collapsible rows so we can achieve tree like design. Example can be seen in [patternfly-4/components/table](http://patternfly-react.surge.sh/patternfly-4/components/table) in collapsible example.

**Comment by rachael-phillips** [comment]
Hi @karelhala do you mind providing me more information on our priorities and timeline on when this si needed?

**Comment by karelhala** [comment]
It's not needed at the moment, it's nice to have, but we will need this functionality in future and need to update table design to allow such thing.

**Comment by rachael-phillips** [comment]
Thanks so much for the update, @karelhala !

**Comment by mcarrano** [comment]
This is being worked on in a more current issue here: https://github.com/patternfly/patternfly-next/issues/2455 Will close.
