### ISSUE TITLE
Firefox padding issue with elements that overflow

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-next#1405]
On an element that has overflow that scrolls, any bottom padding will be ignored.

Read more about it here - https://github.com/w3c/csswg-drafts/issues/129

Some components we should look at
* expanded content in data list
* ^ in table
* page component vertical navigation (`.pf-c-page__sidebar`)

**Comment by christiemolloy** [comment]
FYI the fix - When the parent has the `max-height` and `overflow` properties, the child must have the padding.
