### ISSUE TITLE
placeholders.scss content being included multiple times

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-next#1406]
`placeholders.scss` is being imported by each component so we currently have 52 instances of it in the compiled `patternfly.css` file. we need to figure out a way to still use the SCSS in that file to the theme components and not have it include CSS with every component.

cc @dgutride

**Comment by mcoker** [comment]
Looks like this is a general issue with importing in SASS and has been [reported](https://github.com/sass/sass/issues/869) [multiple](https://github.com/sass/sass/issues/139) [times](https://github.com/sass/sass/issues/156), and is officially being tracked in an issue overhauling the `@import` system - https://github.com/sass/sass/issues/1094

A workaround could be to use https://www.npmjs.com/package/dedupcss-webpack-plugin

Other options
* use a `@mixin` - not preferred as it will duplicate the variables unnecessarily.
* just write normal CSS and write out the component names in the theme selectors instead of using `%extend` - probably preferred. We don't extend many classes, it would be a manageable way to do it.
* use the `.pf-t-light` and `.pf-t-dark` classes in place of `%extend` so you would just add the theme class to the element you want to always have that theme. not preferred as it would require adding the class in the markup, and not controlled just via CSS, and we would probably need to add `!important` to the variable overrides, and `!important` should be avoided if possible.

@dgutride this may be a silly question as I haven't worked with how SCSS is read in an app before, but is there a way we could alter the way the SCSS is served that would allow us to access the placeholders SCSS in `patternfly-base.scss` (it's imported via `@import "./sass-utilities/_all";`) from the individual components' SCSS? Then we could potentially remove `@import "../../patternfly-imports";` from the top of every component since they would have access to all of that from `patternfly-base.scss`?

**Comment by dgutride** [comment]
The gulp task used to remove the patternfly-utilities import before that file was changed to patternfly-imports.  How about we just add the line below that clears that out when creating the full css?

gulp.task('build-tmp', () =>
  gulp
    .src(['./src/patternfly/**/*.scss', '!./src/patternfly/**/examples/*.scss'])
    .pipe(
      sassGlob({
        ignorePaths: ['**/examples/*.scss']
      })
    )
    .pipe(replace('@import "../../patternfly-utilities";', ''))
    .pipe(gulp.dest('./tmp'))
);

**Comment by mcoker** [comment]
@dgutride looks good to me now. ok to close?

**Comment by dgutride** [comment]
Fixed by #1409
