### ISSUE TITLE
Single Select component is missing a Selected state

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#1410]
During React implementation we noticed that there is no way to reflect the current selection in the drop-down menu when it is opened. This is standard behavior for select lists and you can see an example of it in the PF3 Select component (Bootstrap Select): https://www.patternfly.org/pattern-library/widgets/#bootstrap-select

This should be added as an additional state.

**Comment by rachael-phillips** [comment]
Hi Matt, would you consider this a bug or an enhancement?

**Comment by mcarrano** [comment]
A bug. It was really just an oversight and not the result of a new requirement.

**Comment by mceledonia** [comment]
Let's go with something like this, going to ping @mcoker to be sure I handled the spacing correctly.

Design
![image](https://user-images.githubusercontent.com/30935938/53970630-27180300-40c9-11e9-960d-a168a08dabcb.png)

Spec
![image](https://user-images.githubusercontent.com/30935938/53970651-339c5b80-40c9-11e9-82a9-ea5ea5181f31.png)
![image](https://user-images.githubusercontent.com/30935938/53970745-5fb7dc80-40c9-11e9-8eb6-d7534cff1eb1.png)

**Comment by mcoker** [comment]
We already have this state in the [options menu](https://pf4.patternfly.org/components/OptionsMenu/examples/). Should the select and options menu match? If so, fwiw, the options menu has 16px padding on the right of the check icon, and 24px between the check and the menu item text.

**Comment by rachael-phillips** [comment]
@mcarrano did you see @mcoker 's question above?

**Comment by mcarrano** [comment]
I guess this is more of a question for @mceledonia . I feel like it would be good for them to match but is not a major issue.

**Comment by mcoker** [comment]
To clarify, the options menu check icon is aligned to the right edge of the menu item. The check sits flush along the right edge of the item's padding, which is 16px (16px left/right padding on menu items).

And there is 24px left padding on the icon, but the icon is also aligned right. So there will always be at least 24px between the text and the icon, but more if the available space in the item is wider than just the width of the text + icon. You can see what I mean below.

<img width="169" alt="Screen Shot 2019-03-29 at 4 29 44 PM" src="https://user-images.githubusercontent.com/35148959/55263698-e0d54000-523f-11e9-8636-3d4d3774fa07.png">

**Comment by mceledonia** [comment]
@mcoker Nailed it!
