### ISSUE TITLE
Overflow for tables

### ISSUE THREAD

**Issue by karelhala** [patternfly/patternfly-next#1418]
We have table with a few cells, this table is inserted in card body and we were wondering what would be the best solution for such tables. Because as of right now the view looks like this (notice the oveflow)
![small-table](https://user-images.githubusercontent.com/3439771/52740551-89eb1280-2fd3-11e9-8a84-a6fac58c7a2c.JPG)

We could add `overflow: auto` but that doesn't look that appealing either
![overflow-table](https://user-images.githubusercontent.com/3439771/52740620-b69f2a00-2fd3-11e9-862a-bd53d77fb982.JPG)

So this is more of a question of styling wide tables in relatively small containers (these images are as example because to show actual table and behavior is a bit harder)
![real-table](https://user-images.githubusercontent.com/3439771/52740784-1f86a200-2fd4-11e9-8a65-20b21eed2460.JPG)

**Comment by karelhala** [comment]
@christiemolloy yes, that helps! Thank you, I will update our tables to use this logic if they have multiple cells to break at some specific size.

**Comment by christiemolloy** [comment]
Great! Feel free to reach out to me if you have any troubles. Going to close this issue!
