### ISSUE TITLE
Empty State variation when used on full page (screen)

### ISSUE THREAD

**Issue by tiffanynolan** [patternfly/patternfly-next#1423]
In Integreatly, one of the locations that we use the empty state pattern is on a congrats screen. In this instance the pattern is being used without the constraints of some container element (such as a card) and is being shown at the page/screen level. 

Given the size of the text and images in this style and it's usage on a full screen, we feel like the elements are getting lost. 

We're proposing that there is an option for a larger version of the empty state pattern that uses larger font sizes as well as the option to include a larger standard marketing image instead of a fontawesome icon. 

DEFAULT DESIGN
![image](https://user-images.githubusercontent.com/15326290/52807898-b39b4c80-305a-11e9-89f0-aaf50dac0e05.png)

PROPOSED DESIGN for variation
![image](https://user-images.githubusercontent.com/15326290/52807958-d9c0ec80-305a-11e9-9fdb-f57b212737fe.png)

FYI - @mcarrano - This is one of the designs I mentioned when we met yesterday.

**Comment by rachael-phillips** [comment]
Thanks @tiffanynolan! We've seen this and will be talking about this over the next couple of weeks as we prioritize issues over the months to come.

**Comment by mceledonia** [comment]
Just want to jot down some notes here:

- I think we should support this, but it should probably be called something other than an empty state as it's more of a success screen rather than a void of content.
- We could connect the two in documentation as empty state is a pretty logical conclusion to make when searching for a layout like this.
- This can be differentiated from an empty state visually because: 
1) It uses illustration (brand icons) rather than FA5 icons
2) Larger illustration size
3) Larger headline size
4) Larger spacers between the content.

**Comment by tiffanynolan** [comment]
@mceledonia Do you know if other products have a need for some sort of congrats or completion pattern? I agree that it seems odd to call this an "empty state" when it's more of a "yay, you're done" but the empty state pattern is very close to what we think the layout should be.

**Comment by mcarrano** [comment]
While I agree that "empty state" may not be the best title, I would like to see these as variations of the same thing. Maybe there's something better to call these messages? @stacymcauliffe any thoughts?

**Comment by mceledonia** [comment]
Definitely agreed it should be the same layout @tiffanynolan , I think what you have above is great I would just do some minor fine tuning for the spacing. And I think you have a good point @mcarrano . They are so similar it makes sense to group them conceptually, I just want to be sure avoid confusion between the two (i.e. someone using this as an empty state and vice versa). I think keeping them close and treating this as a variation should be enough to avoid that happening.

Maybe we can call this something like a "success display" or something along those lines? I will leave that to Stacy :)

**Comment by stacymcauliffe** [comment]
The empty state pattern use cases we document will include guidelines for several different types of states, like: first use scenarios, user is not entitled, there was a backend error, the user role doesnt have access, the user needs to configure something, etc. I think these use cases are fairly common. 

That being said, I'm not sure how common this type of success state would be. Outside of completing something like a tutorial, I can't think of a use case when we would want to disrupt normal task flow with a full page success message like this. But I also don't think it hurts to include this as another example of how **you can use the empty state pattern to deliver positive and proactive information in any situation where there is nothing else to show.** I would call this example a success state.

**Comment by bdellasc** [comment]
@mceledonia - FYI The celebration illustration was a custom SVG I did emulating the brand icon look & feel.

**Comment by tiffanynolan** [comment]
D'oh! Sorry for not posting the Sketch file here too. I sent an initial version to @mceledonia back on March 7 via email. I had thought it was just going to be added to the master Sketch file and I forgot to follow-up. I'll be sure to post stuff to the related github threads from now on. I know it's difficult keeping track of all of this otherwise. ;) 

https://drive.google.com/open?id=1YZDk3NgucaMfhAIPubwsELLJAH1uiSTo

**Comment by mcarrano** [comment]
Thanks, @tiffanynolan !

**Comment by tiffanynolan** [comment]
@rachael-phillips @mcarrano What are the next steps to move this through the process so it can be added to Core and React?

**Comment by rachael-phillips** [comment]
Hi @tiffanynolan great news! This is on the roadmap and we hope to pick it up in the next few milestones: https://docs.google.com/spreadsheets/d/17aEfvG1DZ0dZmpwacYaCzKv4sog0LuatXCwNizJ7HhE/edit#gid=205680820

**Comment by mcarrano** [comment]
@mcoker @LHinson @rachael-phillips Can anyone tell me why this was closed? Was it ever implemented?  I'm working with @mmenestr and @mceledonia to refine our empty state guidelines and we are wondering about this. Don't see it in the component library.

**Comment by mcarrano** [comment]
Based on discussion with @LHinson I'd like to reopen to get it back on the PF roadmap. Seems there are multiple teams that could use a more standard pattern for a "get started" type screen. @mmenestr @mceledonia can we revisit and post exactly what the design for this should be so it can be handed off to CSS? Looks like there was earlier work done by @tiffanynolan and @bdellasc .

**Comment by mmenestr** [comment]
I have been working with @mcarrano and @mceledonia to update all empty state standards which lead us to make changes to this proposed variation. We decided that this bigger variation would also be useful for something like a get started/first use page empty state, and therefore renamed this variation to "Extra large empty state" that could be used for both get started situations, as well as the originally proposed success/congratulatory state.

I have attached the updated designs in a sketch file here.
Changes include: 
- icon size to be 100px font size
- Header Size 4XL
- Body size XL
*Mockups reflect future color changes of background color to #F0F0F0 and grey body text to #6A6E73

[Extra large empty state design.zip](https://github.com/patternfly/patternfly-next/files/3858989/Extra.large.empty.state.design.zip)

**Comment by mcarrano** [comment]
Thanks @mmenestr . 

@mcoker can you take a look at the designs and let us know if you see any issues? If not, I can close this out and open a new issue to create a new variant of Empty State in core.

**Comment by mcoker** [comment]
@mmenestr thanks for the designs! My notes:

* We don't currently have a 100px icon (or otherwise) font-size in the system. Will we be adding this, or will it be a one-off? 
* We currently have small and large variations of the empty state that adjust width, not scale of the contents inside, so I wonder if we should call this something else.
* The issue calls for a 624px box for the content, but the "large" variation already defines a 600px width. Should we update this or the large variation so they can be the same?

**Comment by mmenestr** [comment]
@mcoker:
- @mceledonia would you be able to that question about the icon - ie: will we be adding a new 100px or will it be a one off. @mcarrano were discussing this, and thought it would probably be just a one off, for the rocket get started icon, and the success icon for the full pages.
- Documenting our slack conversation here - we've decided to leave the small and large variations as is, and to add a new variation called "extra large empty state" which has bigger everything (icon, text size and spacing)

**Comment by mcoker** [comment]
@mcarrano @mceledonia are we still working out any details, or is this ready to go to CSS?

**Comment by mmenestr** [comment]
@mcoker I believe we're good to go! Per our conversations, the only thing that was left to discuss was the icon issue, which we decided would be a one-off thing.
but please confirm this @mcarrano!

**Comment by mcarrano** [comment]
@mcoker Yes, we should be good to move forward with this. Do you need me to open a new/clean issue?

**Comment by mcoker** [comment]
@mcarrano that would be great! Thanks!

**Comment by mcarrano** [comment]
I've opened #2472 to track the CSS work. Will close out this design story.
