### ISSUE TITLE
Table expanding rows have large margins

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-next#1424]
Implemented the Table component from patternfly/patternfly-react, but the expanding row layout looks odd in the Insights/Cost Management UI.

It appears that the expandable row reserves space on the left side, presumably for additional `td` tags containing toggles, check boxes, etc? As a result, it looks like there is a large margin on the left. 

Looking at the core examples, the expandable row also has extra `td` tags.

In order to implement the designs created for Insights/Cost Management, I want to make use of that additional space in the expandable row. Currently, everything is shifted to the right.

![screen shot 2019-02-12 at 1 59 47 pm](https://user-images.githubusercontent.com/17481322/52660800-7a35d600-2ece-11e9-9d04-382222f03d68.png)

I filed the issue below against patternfly/patternfly-core, but it was closed stating this was deliberate? Seems that we could make the td tags span the entire row, so we can make use of the space.

Still, the margins for the implementation in patternfly/patternfly-react don't appear to match core. The margin on the left appears to be larger than core, while right is minimal.

https://github.com/patternfly/patternfly-react/issues/1376

**Comment by christiemolloy** [comment]
Hey @dlabrecq , 
Right now the extra tds are optional, and the content in the expandable row is set to span 4 cols. But you can change this.
You should be able to remove all of the unused ` table-td's` and then update `table-td` which has the child `pf-c-table__expandable-row-content` class to have a `colspan=[total number of table cols]` .
I tested this and it worked, but let me know if you have any questions.

**Comment by dlabrecq** [comment]
Thanks, @christiemolloy. That's good to hear. 

Unfortunately, it's not optional for the patternfly-react component. I opened an issue there and it was immediately closed stating that this is how core does it -- or something to that affect.

I'll re-open the issue in patternfly-react. However, would it be possible to document this in the example or provide another example showing it's optional?

**Comment by christiemolloy** [comment]
Hey @dlabaj just spoke with @kybaker and he advised that we defer to what we have in the expandable row in the data list component. So I'm going to make the update to remove the td's and add padding to the expandable-row-content.
