### ISSUE TITLE
Modal padding

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-next#1425]
I've implemented the modal component from patternfly/patternfly-react and noticed that content in the body scrolls oddly under the modal title.

The pf-c-modal-box__body selector currently uses a padding-top properly, which results in scrollable content like this:

![screen shot 2019-02-14 at 1 51 47 pm](https://user-images.githubusercontent.com/17481322/52810084-c2383280-305f-11e9-85fa-e0d8ea3222e5.png)

However, if the pf-c-modal-box__body selector used a margin-top property, the scrollable content looks more like this:

![screen shot 2019-02-14 at 1 48 27 pm](https://user-images.githubusercontent.com/17481322/52810128-dbd97a00-305f-11e9-9977-6bb2dbad80ea.png)

Ideally, it would have the same margin as the left, right, and bottom of the modal.

**Comment by mcoker** [comment]
Thanks @dlabrecq. Will change the padding to margin. Re: the margin size matching, I chatted with @mceledonia and we think the top/left/bottom padding (32px) creates too much space, but increasing it from 16px to 24px looks good, so we'll go with that.
