### ISSUE TITLE
Register patternfly npm package with a cdn

### ISSUE THREAD

**Issue by dgutride** [patternfly/patternfly-next#1435]
Should be consistent with patternfly cdn registration

**Comment by redallen** [comment]
Quick comparison:
|                             | Monthly Cost | Hosting | Image Optimization | Cache TTL | Instant purging | Configurability | Points of Presence |
|-----------------------------|--------------|---------|--------------------|-----------|-----------------|-----------------|--------------------|
| Unpkg                       | $0           | Yes     | No                 | Forever   | No              | None            | Uses Cloudflare    |
| jsDelivr                    | $0           | Yes     | No                 | Forever   |  No             | None            | Best Worldwide     |
| cdnjs                       | $0           | Yes     | No                 | Forever   | No              | None            | Uses Cloudflare    |
| Cloudflare                  | $0-50        | No      | Yes                | 2hr-30s   | Yes             | Low             | Worldwide          |
| Fastly                      | $50-100      | No      | Yes                | <1s       | Yes             | High            | Worldwide          |
| KeyCDN                      | $0-20        | Yes     | No                 | ?         | Yes             | High            | Less Worldwide     |
| MetaCDN                     | $0-100       | Yes     | No                 | ?         | Yes             | Low             | Best Worldwide     |
| Amazon Cloudfront           | $0-20        | S3      | No                 | ?         | Yes             | High            | Worldwide, growing |
| Stackpath (formerly MaxCDN) | $10          | Yes     | No                 | ?         | Yes             | High            | Worldwide          |

**Comment by redallen** [comment]
Closed in #1442.
