### ISSUE TITLE
Label variations to represent state with colors

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-next#1446]
From https://github.com/patternfly/patternfly-react/issues/1339#issuecomment-465337698

Should we add variations of the label component that represent the states we offer in alerts, similar to [patternfly 3 lables](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/labels.html)?

cc @mcarrano @mceledonia @kybaker

**Comment by mcarrano** [comment]
I think this should be treated as a new feature. @rachael-phillips let's consider for 4.x

**Comment by mcoker** [comment]
@mcarrano @rachael-phillips I had a product ask about colored labels today. Is this something we still want to get on to the roadmap at some point?

**Comment by rachael-phillips** [comment]
@mcoker what product was it? It sounds like we should surface this to @LHinson , so she can determine priority,

**Comment by mcoker** [comment]
Vanessa Busch with AMQ Online. They also referenced OpenShift, which has something similar.

<img width="633" alt="Screen Shot 2019-10-23 at 3 46 27 PM" src="https://user-images.githubusercontent.com/35148959/67432681-4b6b1600-f5ac-11e9-9bf7-6d1741e644b1.png">

**Comment by mcarrano** [comment]
The only concern that has been voiced here came from accessibility, i.e. using color alone to reflect status. That said it's definitely something that we should consider. We still currently have pending work to finalize our overall approach for tags and labels. https://github.com/patternfly/patternfly-next/issues/759

**Comment by mcarrano** [comment]
I've opened a new issue in the patternfly-design repo to track this request here: https://github.com/patternfly/patternfly-design/issues/751  Closing this one out.
