### ISSUE TITLE
Switch enhancements - move text strings from css to html

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-next#1452]
Currently the text strings that are included in the Switch component are defined in the css. This can be problematic for consumers that want to either translate their text strings or customize these strings to be different (e.g. enabled/disabled vs on/off).

I copied bits from comments in issue #915 to show a solution that might work for this.

With the html shown below, a couple of things are happening:

- The checkbox is always labelled by the positive label, so that what gets announced makes sense. E.g. "On, checkbox, checked" or "Enabled, checkbox, checked"
- The text inside `.pf-c-switch__label is-on` gets announced when the checkbox receives focus because of the `aria-labelledby` on the checkbox. But otherwise, the visible labels are ignored by the screen reader due to `aria-hidden`.
- The combination of the classes used on these labels plus the CSS shown below will control which label is visible depending on the state of the checkbox.

HTML
```
<label class="pf-c-switch" for="switch-on-example">
  <input 
    class="pf-c-switch__input" 
    type="checkbox" 
    id="switch-on-example" 
    aria-labelledby="switch-label" 
    checked
  >
  <span class="pf-c-switch__toggle">
  </span>
  <span class="pf-c-switch__label is-off" aria-hidden="true">
      Message when off
  </span>
  <span class="pf-c-switch__label is-on" aria-hidden="true" id="switch-label">
      Message when on
  </span>
</label>
```

CSS
```
.pf-c-switch__input:not(:checked) ~ .is-on,
.pf-c-switch__input:checked ~ .is-off {
  display: none;
}
```

**Comment by karelhala** [comment]
Yes please! Current implementation is causing a lot of problems in our product because if we set custom label for our switch it always shows `OnLabel` and `OffLabel`.
