### ISSUE TITLE
Add support for sub-header text in Login component 

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-next#1487]
Related to https://github.com/patternfly/patternfly-next/issues/354

Need to add support for the "Log in to Application" text as seen on https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/login-single-sign-on.html

Details to come.

cc @tlabaj @mceledonia

**Comment by mceledonia** [comment]
Let's go with small text style (14px) underneath the header with spacing: 16px top, 32px below..

![image](https://user-images.githubusercontent.com/30935938/53441825-a58fe900-39d5-11e9-9c0b-5bded967acfb.png)

**Comment by mcoker** [comment]
@mceledonia the bottom spacing is a bit different. After the header text currently, there is 16px bottom padding on the header, then the hidden error message, and then 24px (lg) spacer as the gap between the error message and first form field. 

Here I just left all of the existing spacing the way it is and added the sub-header text (description) with 16px between it and the content above it. Then on mobile, there is 16px between the title, description, and dropdown.

## Desktop
<img width="916" alt="screen shot 2019-03-04 at 5 11 50 pm" src="https://user-images.githubusercontent.com/35148959/53769435-81367f80-3ea1-11e9-95f0-5f7d9df5c84b.png">


## Desktop with error
<img width="916" alt="screen shot 2019-03-04 at 5 11 52 pm" src="https://user-images.githubusercontent.com/35148959/53769446-85fb3380-3ea1-11e9-9830-55a55788c268.png">


## Mobile
<img width="355" alt="screen shot 2019-03-04 at 5 12 36 pm" src="https://user-images.githubusercontent.com/35148959/53769451-88f62400-3ea1-11e9-8c68-d946b8d64304.png">


## Mobile with error
<img width="359" alt="screen shot 2019-03-04 at 5 12 46 pm" src="https://user-images.githubusercontent.com/35148959/53769457-8abfe780-3ea1-11e9-9452-453e4c2f2874.png">

I think it looks OK, but the spacing between the description and error on desktop seems too tight. Here it is with an 8px (sm) spacer below the description on desktop only.

## Regular
<img width="1050" alt="screen shot 2019-03-04 at 5 23 59 pm" src="https://user-images.githubusercontent.com/35148959/53769705-57ca2380-3ea2-11e9-9256-2004b58f849b.png">


## Error
<img width="1050" alt="screen shot 2019-03-04 at 5 24 02 pm" src="https://user-images.githubusercontent.com/35148959/53769707-5ac51400-3ea2-11e9-8ab5-4da27810fc1d.png">

**Comment by mceledonia** [comment]
This all looks great, thanks @mcoker !!
