### ISSUE TITLE
Add support for <caption> in table component

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-next#1494]
The [PF4-React table component](http://patternfly-react.surge.sh/patternfly-4/components/table) takes a `caption` prop that defines a table `<caption>`, but we don't have support for that element in core, so the default browser styles are applied which looks weird.

Looks like the [PF3-React table component](http://patternfly-react.surge.sh/patternfly-3/index.html?selectedKind=patternfly-react%2FContent%20Views%2FTable%20View&selectedStory=Bootstrap%20Table%20Styles&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs) supports a caption, so we should add support for this to core.

cc @jgiardino

**Comment by mceledonia** [comment]
Captions should be styled as our secondary text color and small text style (14px).

**Comment by mcoker** [comment]
And we'll use 16px top/bottom margin and 32px left margin
