### ISSUE TITLE
Dropdown hover text is white in user menu

### ISSUE THREAD

**Issue by mindreeper2420** [patternfly/patternfly-next#1509]
In the masthead, the user dropdown text changes to white on hover. Expected color is black, based on designs.

This was found using version `"@patternfly/patternfly": "1.0.208"`, as well as on the [PatternFly 4 React demo page](http://patternfly-react.surge.sh/patternfly-4/demos/pagelayout/examples/page-layout-default-nav) (02/28/2019).

![user-menu-hover](https://user-images.githubusercontent.com/4032718/53574524-d12de300-3b3d-11e9-890a-06eaed00a557.png)

**Comment by mcoker** [comment]
@mindreeper2420 this should be fixed. I'm no longer seeing it on the demo page you linked. Would you mind verifying and letting me know if you're still seeing it?

**Comment by mindreeper2420** [comment]
@mcoker I'm still seeing it on https://patternfly.surge.sh/documentation/react/demos/pagelayout/examples/page-layout-default-nav. Is that the correct URL to use for documentation, or is there an updated one?

**Comment by mcoker** [comment]
Ah, I think that's for the website which may be out of date. I was verifying against the pf4 react workspace

http://patternfly-react.surge.sh/patternfly-4/

http://patternfly-react.surge.sh/patternfly-4/demos/pagelayout/examples/page-layout-default-nav

**Comment by mcoker** [comment]
@mindreeper2420 do you mind checking this again and let me know if we should still leave this one open? The current workspace for what's on master is at http://patternfly-react.surge.sh/patternfly-4/

**Comment by mcoker** [comment]
@mindreeper2420 ping - can you let me know if this is still applicable? Should have been resolved a while ago.

**Comment by mindreeper2420** [comment]
@mcoker Looks fixed to me.
