### ISSUE TITLE
Background image component size

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-next#1517]
There is concern about the background-image size. For example pfbg_2000.jpg is 629k and pfbg_992@2x.jpg is 575k.

Can we compress this image, offer high/low resolutions? Maybe offer a smaller version of the background-image that is for use on the page component that only occupies the masthead?

**Comment by rachael-phillips** [comment]
Closing because it will be addressed in https://github.com/patternfly/patternfly-next/issues/1523
