### ISSUE TITLE
Fix Tertiary Nav Scroll

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-next#1519]
This is how the Tertiary Nav looks in Chrome vs Firefox. We should hide the scrollbar in the css like we will do in the Tab component #1514 Also fix Horizontal Nav

<img width="829" alt="screen shot 2019-03-01 at 11 06 06 am" src="https://user-images.githubusercontent.com/20118816/53650269-22a7a200-3c12-11e9-8661-77d8012c2abe.png">

**Comment by rachael-phillips** [comment]
Hi @mcarrano and @mceledonia making you aware of this enhancement. What indicator do you think should be used here?

**Comment by mcarrano** [comment]
I agree that the scrollbar should be hidden. @kybaker I'm pretty sure that we talked about this when designing the nav and just decided that the user can swipe to scroll the nav. Can you confirm?

**Comment by mceledonia** [comment]
We had decided on a white-colored shadow overlay to create the look of the tabs fading away as they go right. Not sure of the best way to implement this (shadow colored white or white gradient) but I will attach a quick visual here: 

![image](https://user-images.githubusercontent.com/30935938/54548546-8e15a180-497e-11e9-854a-6df0cf7e5d74.png)

![image](https://user-images.githubusercontent.com/30935938/54548567-94a41900-497e-11e9-939d-345e727c7b53.png)

Happy to help consult on getting this implemented if we agree this is a good solution.
