### ISSUE TITLE
Table: incorrect borders in Firefox

### ISSUE THREAD

**Issue by suomiy** [patternfly/patternfly-next#1520]
The borders are not rendered correctly when the table has more than 2 rows in firefox.

![s](https://user-images.githubusercontent.com/3648838/53652975-76ce7880-3c4a-11e9-897d-d35f4650e96c.png)

This issue was found when implementing inline editing, where it is also present: https://github.com/patternfly/patternfly-react/pull/1227

this issue seems to cause that: https://bugzilla.mozilla.org/show_bug.cgi?id=688556

**Comment by mcoker** [comment]
@suomiy thanks! I put up a PR if you'd like to verify https://github.com/patternfly/patternfly-next/pull/1535

**Comment by mcoker** [comment]
@suomiy actually I had another look at this, and I think I found the culprit with a much easier fix. Added a PR if you want to check it out. https://github.com/patternfly/patternfly-next/pull/1545
