### ISSUE TITLE
Page Header and Navigation Changes   

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-next#1523]
Some updates should be made to page header:

- Accommodate logos that scale
- Resize and change color
- Remove image out of background

**Comment by rachael-phillips** [comment]
We will not start work on this issue until we have been notified to continue.

**Comment by LHinson** [comment]
@mcoker does this need a follow up issue for react?

**Comment by mcoker** [comment]
@kybaker says this is good to close.
