### ISSUE TITLE
Update font to Red Hat Font

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-next#1524]
Pull in Red Hat fonts - 3 variations

**Comment by rachael-phillips** [comment]
We will not start work on this issue until we have been notified to continue.

**Comment by mcoker** [comment]
https://github.com/RedHatOfficial/RedHatFont

**Comment by stacymcauliffe** [comment]
Hi @mcoker @kybaker -- I have issue[ #1090](https://github.com/patternfly/patternfly-org/issues/1090) in the pf org repo to update the typography page on the website [here](https://www.patternfly.org/v4/design-guidelines/styles/typography).

Can you tell me, is it just a matter of changing any instance of *overpass* to *Red Hat font*? Or will I need to update the font weights and sizes? 

Also, which link do we want to direct users to for download? 

Happy to hop on a quick call about this if it's easier. Thanks!

**Comment by mcoker** [comment]
@stacymcauliffe great question. The new font is actually 2 fonts and we're currently still working out the rules behind which font, font weights, etc to use when. As for the download link I think https://github.com/RedHatOfficial/RedHatFont would probably be best. wdyt @kybaker?

**Comment by kybaker** [comment]
@mcoker @stacymcauliffe  Yes that is the best link. We are still working out the specifics so we can assure there are no broken elements and we maintain consistency across the portfolio.

**Comment by rachael-phillips** [comment]
@kybaker have we firmed anything up since Tuesday or still in progress on specifics?

**Comment by kybaker** [comment]
@rachael-phillips We are still in progress. I am planning to give specifics at the visual design meeting today.

**Comment by rachael-phillips** [comment]
Great! Thank you!
