### ISSUE TITLE
Tabs - remove aria-label from .pf-c-tabs

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-next#1537]
In any examples of Tabs that use a `<div>` for the parent wrapper `.pf-c-tabs`, we should not include `aria-label`. This attribute only works reliably for [certain elements](https://developer.paciellogroup.com/blog/2017/07/short-note-on-aria-label-aria-labelledby-and-aria-describedby/). 

However, if there are any examples of Tabs that use `<nav>`, then `aria-label` should definitely be used. I don't think there are, but mentioning it just in case.

**Comment by christiemolloy** [comment]
@jgiardino should we be supporting tabs using `<nav>` currently we don't but I feel like we should add it as support.
