### ISSUE TITLE
Helper text missing top margin

### ISSUE THREAD

**Issue by keithjgrant** [patternfly/patternfly-next#1546]
See the attached screenshot. Form helper text has a 4px top margin after a `pf-c-form-control` ("Ansible Environment" input), but it's missing after a `pf-c-input-group` ("Instance Groups" lookup)

![Screen Shot 2019-03-11 at 11 46 51 AM](https://user-images.githubusercontent.com/410794/54139298-9e1a0800-43f7-11e9-9678-41f66bda68cc.png)

**Comment by rachael-phillips** [comment]
Hi @keithjgrant a couple of questions for you:

* List any product/project release(s) and timelines your trying to align with
* Is this currently blocking implementation?

**Comment by keithjgrant** [comment]
We decided to go a different direction with this form, so there's no immediate need; not currently blocking us.

**Comment by rachael-phillips** [comment]
Thanks for letting me know!

**Comment by mcoker** [comment]
@mcarrano could you provide guidance on how to handle this? Currently we only create a top margin on helper text when it follows a form control element. We could go a couple of directions with this. The approach we choose should be dictated by our recommendation on where helper text goes in a form, and how flexible we want to be should a user place the helper text somewhere we don't necessary recommend or aren't anticipating.

We could have a list of elements we expect the helper text to follow, and when the helper text follows one of those elements, we apply a margin-top. This is what we're doing currently. So at a minimum, to address this issue, we would need to add the input group component to the list of elements that creates a margin between it and the helper text. And along with that, I would suggest we look at all of the elements that may go into a form group and add them to the list if they can be followed by helper text.
  * This gives us more control over the spacing, but isn't very flexible as we would need to keep a list of elements the helper text would follow in order for the text to have a top margin. For example, if we need to add a new element to the list, that requires a PR and release. There may also be cases where a user wants to add helper text after some element we don't support in this way in core (like a paragraph or something), and they will get no margin.

We could assume that the helper text will always be displayed below some other element in the form and there should be space between that element and the helper text, and so we just add a default top margin to the helper text and it's always applied and isn't dependent upon the helper text following a particular element.
  * This is a lot more flexible, as any case where the helper text follows another element in a form group, the helper text will have a top margin. However, depending on how folks use it, this may create unnecessary space.

I would probably support the latter. That's how we do it in PF3, and the only issue I see with this is if someone adds the helper text after an element that also has a bottom margin, which would create too much margin. However, we can ensure that elements in the form layout that can be followed by helper text shouldn't have a bottom margin, so if a user ends up in that scenario, it's likely the result of misuse of the component.

**Comment by mcarrano** [comment]
@mcoker I agree with your assessment. I think it's safer to assume that helper text will always have that 4px top margin as I believe we are always saying that it falls below a form element. @stacymcauliffe can you confirm this?

**Comment by stacymcauliffe** [comment]
@mcoker @mcarrano - I can't speak to the right margin, but yes, helper text will always appear below a form field. From a content perspective, there are a few ways to handle contextual help on forms - helper text, placeholder text, and infopops (tooltips/popovers). Helper text should be very short (only a few words). For both examples shown here, I would actually recommend either updating and editing this text for concision or putting it into a tooltip instead. 

Also, just in case you're interested, difference between popover and tooltip = the amount of text you need to provide as well as any need to format text. So for a tooltip - 1-2 sentences or less. Popover - anything longer or anything that requires formatting like links, buttons, bullets, numbers, etc. 

Hopefully this helps.
