### ISSUE TITLE
Form layout issues

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-next#1549]
We have a couple of layout issues in the [horizontal form demo](https://pf4.patternfly.org/demos/BasicForms/examples/)

* The 2 checkboxes beside the "can we follow up" label are misaligned. 
    * The layout currently expects form-control elements in the right column (for the vertical spacing of the layout on the left) and it doesn't support stacking of components in that column. At a minimum, I think we should support stacking components so that, for example, if you stack text input form control components on top of one another (say 2 stacked for the street address in an address form), there should be space between them. 
    * and just for the example's sake, 1) those wouldn't be checkboxes if there were 2 options (since you should only check 1), and 2) there should only be 1 ("yes") - if it's unchecked, it should be implied that the response is "no"
* "remember my password" checkbox is just floating out there by itself, and in a narrow viewport, it wraps to a new line and the label text 
    * should we ever have a label on the left and a solitary checkbox or radio element on the right? I don't see anything like that in the [patternfly3 forms](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/forms.html). It seems like the checkbox and label would be grouped together in the right column. 

Can we revisit the content in the demo, and the form component design to accommodate those sections should we choose to keep them?

<img width="412" alt="Screen Shot 2019-03-11 at 5 12 27 PM" src="https://user-images.githubusercontent.com/35148959/54161692-f44f7100-4420-11e9-8734-aa4e2ddb49e9.png">
<img width="753" alt="Screen Shot 2019-03-11 at 5 12 13 PM" src="https://user-images.githubusercontent.com/35148959/54161693-f44f7100-4420-11e9-95ad-fd4659bc70cc.png">

cc @mceledonia @kybaker @mcarrano

**Comment by karelhala** [comment]
Oh nice, we just experienced some issues with form layout as well so I'll dump it here.

It looks like form actions have margin that expands beyound actions container and this causes that scrollbar is shown in some cases (like if I have form in dialog). Can we add `margin-bottom: 0` to these actions? There will be no visial changes and it will not break some layouts
### Current actions wrapper
![Selection_026](https://user-images.githubusercontent.com/3439771/54185661-eb56b200-44a9-11e9-955d-074bc87bcfb9.png)
### Current actions
![Selection_027](https://user-images.githubusercontent.com/3439771/54185662-eb56b200-44a9-11e9-9b9b-db8fcf361dd2.png)

### Proposed actions wrapper
![Selection_028](https://user-images.githubusercontent.com/3439771/54185663-ebef4880-44a9-11e9-9dae-8738aec86cd3.png)
### Proposed actions
![Selection_029](https://user-images.githubusercontent.com/3439771/54185664-ebef4880-44a9-11e9-818e-a12bd6dad50c.png)

**Comment by mcarrano** [comment]
@mcoker Yes, you are absolutely right about this. Thanks for flagging it. The horizontal form demo has two problems. The "yes and no" options should be radio buttons and not checkboxes since they are mutually exclusive. This can also be accomplished with a single checkbox that has the label to the right, i.e. "Follow up via email"

We should also never have a checkbox that sits alone like this, so yes, I would expect the checkbox in the right hand column with the label "Remember my password for 30 days" to the right.

@stacymcauliffe do we cover this in the Forms design guidelines?

**Comment by stacymcauliffe** [comment]
@mcarrano - in the text/data input guidelines, I have a section about how to choose which input components to use: Checkboxes enable users to select multiple items from a list of 5 or fewer. Radio buttons enable users to select one item from a list of 5 or fewer. 

I also have a section RE: labeling that speaks to how labels for checkboxes and radio buttons should be aligned to the right of the control. 

I think what we're missing in the guidelines is the use case you mentioned about using a single checkbox to enable something like "Remember me." It might also be useful to include a variety of layouts and examples. I'm just not sure whether they should live in forms docs or input docs or both.

**Comment by mcoker** [comment]
@mcarrano thanks! do we want to handle the case where you have multiple checkboxes, radios, form-control (text, select, textarea), input groups, etc in the right column with a single label similar to the "can we follow up via email" form group in the currently example?

And are there any other form layouts not covered in the current examples you'd like me to ensure are supported in the form component?

**Comment by mcarrano** [comment]
The short answer is 'yes' @mcoker . But there is an active issue here that I think is intended to rework and enhance the form examples we provide: https://github.com/patternfly/patternfly-next/issues/919. Can't remember exactly where this sits on our roadmap, but's it's currently assigned to @mceledonia for visual work. 

It might make sense for you, @mceledonia , @stacymcauliffe , and I to sit down and identify all of the cases we need to represent in this demo. Thoughts?

**Comment by stacymcauliffe** [comment]
A convo would be good for me from a docs perspective to make sure I've got everything covered.

**Comment by mcoker** [comment]
@mcarrano sounds great, thanks! So for this issue, I'll just fix the demos and @karelhala's issue, and we can handle the rest in #919.
