### ISSUE TITLE
Background Image Filter unspecified width error

### ISSUE THREAD

**Issue by ryelo** [patternfly/patternfly-next#1550]
[Workspace Example](https://pf4.patternfly.org/demos/Page/examples-full/?component=Page%20Component%20Default%20Nav%20Header%20Example)

On build, we're getting:

`Error: <filter> attribute width: Unexpected end of attribute. Expected length, "".`

across all of our apps regarding an unspecified width with the background image filter because of `width=""`

**Comment by rachael-phillips** [comment]
Hi @ryelo is this currently blocking implementation?

**Comment by ryelo** [comment]
Not blocking implementation, but people are complaining about the error in the console

**Comment by mcoker** [comment]
Looks like this was added here. Will investigate some more.

```
commit 0bc6ad046589c27f826695d16e33f3e79812f765
Author: Andy Braren <andybraren@users.noreply.github.com>
Date:   Fri Aug 17 09:00:45 2018 -0400

    Fix clipped bg image when resizing in Chrome (#607)
    
    Adding an empty width attribute to the SVG’s filter element prevents the background image from getting clipped when resizing a window in Chrome. Other browsers are unaffected by this fix, and did not have the issue initially.
```

**Comment by redallen** [comment]
We've set `width="0"` and `height="0"` to fix this now.
