### ISSUE TITLE
Need the ability to add a Nav separator not on a Nav item

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/patternfly-next#1574]
Currently the Nav separator pattern is a modifier on a Nav item. When nav items can be optional, it is hard to determine which nav item has the separator following it. It would be useful to be able to add a separator without it being on a Nav item.

**Comment by mcoker** [comment]
> When nav items can be optional, it is hard to determine which nav item has the separator following it.

Can you give me an example of what you mean by that? Would moving `.pf-m-separator` to the `li.pf-c-nav__item` parent help?

**Comment by mcoker** [comment]
Looking at this closer, I wonder if we should match what we're doing with the dropdown menus like dropdown, select, options menu, etc.

`<li class="pf-c-dropdown__separator" role="separator"></li>`

what do you think @matthewcarleton @jgiardino

**Comment by jgiardino** [comment]
👍 I like that suggestion
