### ISSUE TITLE
Remove CSS labels from switch

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-next#1581]
From this PR during our next breaking change release

https://github.com/patternfly/patternfly-next/pull/1473/

**Comment by jgiardino** [comment]
Adding a screencap of the changes added in #1473 that we'd want to remove in the next breaking change release.

![image](https://user-images.githubusercontent.com/21063328/54392948-47befa80-467f-11e9-944a-2fdc7233349f.png)
