### ISSUE TITLE
Dark theme with breadcrumbs

### ISSUE THREAD

**Issue by RolandTa** [patternfly/patternfly-next#1594]
Text only breadcrumb elements will not change the textcolor when using with dark theming. 

https://pf4.patternfly.org/components/Breadcrumb/examples/
![image](https://user-images.githubusercontent.com/264579/54557468-7f011480-49bb-11e9-8891-fb72dd59b08c.png)

**Comment by mcoker** [comment]
@RolandTa thanks! This should be fixed in https://github.com/patternfly/patternfly-next/pull/1600

**Comment by mcoker** [comment]
Fixed now
