### ISSUE TITLE
Left-align buttons on modal

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#1599]
There is a current proposal to change our standard for button alignment on modals. Currently, buttons in a modal are defined as having right-alignment with the primary action on the right. The proposal is to make the primary action left-aligned. See the InVision for possible placements: https://redhat.invisionapp.com/share/EBR35AEC6FK  Need to decide whether it makes sense to left-align button group in the window as well as change the button order.

Advantages of this are:

* It provides a consistent ordering of buttons everywhere.
* Making the primary button the first action from left to right should aid accessibility.

Items affected: Modal component and demo (Core and React); Buttons and Links design guideline.

**Comment by jeperry** [comment]
Matt, is the proposal about the alignment of the buttons respective to the modal, or the order of the buttons, or both? Your comment and the wires don't quite make it clear to me.

I have always favored matching the button order and button group alignment. That is, left aligned group has primary action to the left, or right aligned group has primary action to the right. [Example](https://developer.apple.com/design/human-interface-guidelines/macos/windows-and-views/alerts/) 
 This ensures that the primary action is on the dominant edge of the container UI element, and in my opinion, makes it easier to locate and focus on. 

I'm in favor of this if we are matching group alignment AND order.

**Comment by mcarrano** [comment]
Yeah, I made two sets of mockups for discussion. We are meeting tomorrow to clarify this. I agree with your assessment. It is consistent with what has always been the general rule and works for visual users. But it was pointed out recently that when using a screen reader with right-aligned buttons, the Cancel gets announced before the Submit. I appreciate your input on this @jeperry .

**Comment by ryelo** [comment]
@mcarrano Is this going to affect the wizard too? 

I'd assume that the "primary" button for a wizard is going to be the "forward" button. If that's the case, would that mean that the ordering of the buttons would go: "forward" "previous" ?

**Comment by mcarrano** [comment]
Today @kybaker @mceledonia @mcoker @jgiardino @rachael-phillips @stacymcauliffe and I met to talk about the approach that we want to take. We decided that buttons will always be left aligned in a page whether on a full page or a modal. See mockups below:

![Modal_basic_spec](https://user-images.githubusercontent.com/6619860/54708338-93f3ba00-4b19-11e9-8e06-261aa7f255f4.png)

![Modal_form_spec](https://user-images.githubusercontent.com/6619860/54708354-9b1ac800-4b19-11e9-8a17-d6a783089953.png)

All new designs will follow these standards. @rachael-phillips will look at when this rework can be included in the roadmap. In the mean time we will remove the current guideline on this to avert any confusion. A new issue has been created here to make the documentation update: https://github.com/patternfly/patternfly-org/issues/765

**Comment by LHinson** [comment]
Removing the breaking changes label as we will proceed with a opt-in solution first
