### ISSUE TITLE
Make styling updates to the Wizard steps menu

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#1616]
Update wizard steps menu to ensure that unavailable (disabled) steps are clearly differentiated and accessible.

Update design mockups (https://redhat.invisionapp.com/share/W3QA5O64XNQ) and core CSS.

**Comment by mcoker** [comment]
For this issue:
* remove circle behind disabled steps
* use not-allowed cursor
* remove right-align footer option

**Comment by rachael-phillips** [comment]
Will we need a corresponding React issue for this?

**Comment by mcarrano** [comment]
There is one. I will need to find it.

**Comment by mcoker** [comment]
For these updates, just the third bullet

> remove right-align footer option

**Comment by mcarrano** [comment]
It's this issue @rachael-phillips https://github.com/patternfly/patternfly-react/issues/1618
