### ISSUE TITLE
Login Language selector should always be top right positioned.

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-next#1620]
When the header overflows to more than one line, the language selector is vertically centered. It should always sit in the top right corner like when there is one line for the header.

<img width="653" alt="Screen Shot 2019-03-25 at 10 17 11 AM" src="https://user-images.githubusercontent.com/20118816/54927109-ed783200-4ee7-11e9-8fa3-89ad20b173e2.png">

**Comment by mcarrano** [comment]
Closing in favor of #1821 as we will no longer want the language selector in the login form.
