### ISSUE TITLE
Login component to support warning state

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-next#1632]
Right now the login component only supports red text error messaging. Speaking with @priley86, a product he is working on would like to see a warning state that is differentiated visually from the error state, maybe with a different icon and color. Something like this?

<img width="568" alt="Screen Shot 2019-03-26 at 10 18 45 AM" src="https://user-images.githubusercontent.com/35148959/55009469-94280580-4fb0-11e9-952e-21e733ca703f.png">

Is this a good idea? Or should the warning and error states of the component be presented as visually the same with red error text?

cc @kybaker @mcarrano

**Comment by mcarrano** [comment]
@priley86 can you give some examples of what these warning messages would be?

**Comment by priley86** [comment]
cc: @serenamarie125 ^^

**Comment by mcarrano** [comment]
Going to close this out for housekeeping purposes. Needs more information. Can reopen in patternfly-design if this is still a need.
