### ISSUE TITLE
Table select all checkbox disappears on mobile

### ISSUE THREAD

**Issue by ryelo** [patternfly/patternfly-next#1656]
When on a mobile view for the selectable table, you can't check the "select all" checkbox

Steps to reproduce:
1. https://pf4.patternfly.org/components/Table/examples-full/?component=Table%20with%20checkboxes%20and%20actions
2. go to a mobile view

**Comment by rachael-phillips** [comment]
Thanks @ryelo for bringing this to our attention. @mcoker making you aware.

**Comment by mcoker** [comment]
We remove the main table heads on mobile, so I'm not sure where the "select all" option should go. This will need some design input. 

@mcarrano @kybaker

**Comment by mcarrano** [comment]
Interesting question. It may just be that we loose that functionality on mobile. If you think about it, management of large data sets in tables is completely impractical on a mobile device anyway. I don't feel like the user must always have full capability from their phone. What do you think @kybaker ?

**Comment by kybaker** [comment]
@mcarrano I totally agree. Not sure how the user could manage it.

**Comment by ryelo** [comment]
So, to clarify, this is on the `768px` breakpoint where you lose this functionality. Our QE was testing this as one of our valid use cases. If there is no plans to add it, we can put it in a toolbar above the table.

**Comment by mcarrano** [comment]
Yeah, if you must have this then I would recommend adding to the toolbar.

**Comment by mcoker** [comment]
@ryelo is this issue OK to close or do you want to keep it open?

**Comment by ryelo** [comment]
It's good to close!
