### ISSUE TITLE
Enhancement: Dropdown to support more than lists

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#168]
In order to support the application launcher, we need to enhance the dropdown to support more than just the list. There is an existing design for this here: http://www.patternfly.org/pattern-library/application-framework/launcher/#/design  There are versions with and without icons.

Design Folder: https://drive.google.com/open?id=1F-cCkgpWiIGg9BeilKx7ncKxhrVnF-Oe

Once this is complete, we can complete issue #332

**Comment by mcarrano** [comment]
@rachael-phillips In looking at this, I'm not sure it is still a valid issue. This was originally created so that we could build something like this application launcher shown here:

![screen shot 2019-01-07 at 2 01 57 pm](https://user-images.githubusercontent.com/6619860/50787625-ecd6e480-1284-11e9-8e68-29becc766e09.png)

Will the existing dropdown allow for that? If so, I think this can be closed. @mcoker thoughts?

**Comment by mcoker** [comment]
@mcarrano since the current requirement is basically the existing dropdown component with different icon ([font-awesome "fa-th"](https://fontawesome.com/v4.7.0/icon/th)), I think it's OK to close.

**Comment by mcarrano** [comment]
Sounds good. I will close then to get one off our plate.
