### ISSUE TITLE
Expandable section

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#169]
Need an expandable container that allows content to be shown or hidden. Current design can be found here: http://www.patternfly.org/pattern-library/forms-and-controls/expand-collapse-section/#/design

Visuals to refine design approach. We should have all the CSS to create this. 

This can be seen on a form but might have other use cases.

**Comment by mceledonia** [comment]
Expansion Behavior Visuals

![expansion forms](https://user-images.githubusercontent.com/30935938/42052730-9f6de70a-7add-11e8-89c1-65cec7101b85.png)

**Comment by rachael-phillips** [comment]
What ended up happening to this issue? Looking for a status. Thanks! :)
