### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#170]
We should have all the elements in CSS to build the File Uploader pattern. Interaction design and JS (React) conversation should be a first step to determine how this needs to be built and any additional CSS needs. 

#180 has open questions that also impact this issue. Need to determine where the CSS lives and if we are using a third party library.

Allows the user to upload a file or files. There is design work currently in progress here: https://github.com/patternfly/patternfly-design/issues/506

**Comment by mcarrano** [comment]
There is a related design issue open here: https://github.com/patternfly/patternfly-design/issues/741

**Comment by rachael-phillips** [comment]
Hi Matt, is there a product ask for File Upload and do you consider this high priority? For background, this is currently placed in the future section of our roadmap. I am going to organize the workspace using the P1 >> P5 labels. P1 = high priority, P5 = not high priority.

**Comment by mcarrano** [comment]
I don't know that there is an immediate PF4 ask. @ajacobs21e and @mturley were planning to work on a solution. Do either of you have a short term need for this in PF4?

**Comment by mturley** [comment]
Not PF4 on my end, my need for this is in PF3. I'm implementing something downstream in the short term and then planning to loop back to try and make it reusable later on, tweaking it to match the eventual design.

**Comment by rachael-phillips** [comment]
Ok great! Thanks for the update everyone!

**Comment by mcarrano** [comment]
See https://github.com/patternfly/patternfly-react/issues/1254 for related implementation.

**Comment by mcarrano** [comment]
I am going to close this one out as we do have an open design story here: https://github.com/patternfly/patternfly-design/issues/741
