### ISSUE TITLE
Spacing issue in tertiary nav demo

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-next#1710]
the spacing needs to be updated for the tertiary nav in demo here: https://pf4.patternfly.org/demos/Page/examples-full?component=Page%20Component%20Expandable%20Nav%20Example
The vertical nav doesn't align with the tertiary nav as it does in the design.

**Comment by mcoker** [comment]
fixed in https://github.com/patternfly/patternfly-next/pull/1712/
