### ISSUE TITLE
Topology View

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-next#1718]
The OpenShift Developer Console needs to implement a topology view for OpenShift 4.2
OpenShift 4.2 Feature Freeze is June 28th and GA is Aug 21st

There is a working group that's been meeting since last fall around converging the various topology views from different products today.  Here are the documents which have been produced to date:

- https://docs.google.com/presentation/d/1MJgqUCzvvKYAaKa8aZhgfk1W5l3t2JjQSqXliuiIetE/edit#slide=id.gb6f3e2d2d_2_219
- https://docs.google.com/document/d/1SGggBbPGyk2nd46jiy3Kb7_YZ5REVxSjdSlRPyx-UCg/edit

Since the timeline is tight, it would be interesting to see if we can identify a subset of use cases to satisfy for the initial design, and continue to iterate going forward.

**Comment by LHinson** [comment]
I just set up a meeting for 4/17 with the following people to discuss this contribution, the requirements and determine a potential phased approach. 

- Michael Coker 
- Catherine Robson 
- Chris Shinn
- Dana Gutride
- Jeffrey Phillips
- Baker, Kyle
- Matt Carrano
- Michael Celedonia
- Rachael Phillips
- Serena Doyle
- Titani Labaj
- Jan Wright

Please let me know if I missed anyone!

**Comment by mcarrano** [comment]
Topology use cases summarized here: https://docs.google.com/spreadsheets/d/1LYcyTIgLS-R4uCCnXVCQvVQwRGC9sRANyK54gEPg9yg/edit?usp=sharing

**Comment by mceledonia** [comment]
We are going to close this larger issue in favor of more granular task-specific issues for better transparency and awareness.

**Comment by LHinson** [comment]
Thanks @mceledonia I'm going to close this issue in favor of more specific issues as linked (#2157)
