### ISSUE TITLE
Prototypes and Documentation for Accessible Components

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-next#172]
As we're putting into place standards for pf-next, the topic of accessibility has bubbled up toward the top. There are many ways accessibility can be handled and different implementation methods lead to different user experiences depending on which platform/browser/reader combination is in play. 

We need options in the form of documented demos! We'd like to capture the different methods of implementation, and bring these back to the rest of the team so we can evaluate which suit our needs from a business perspective.

**Comment by jgiardino** [comment]
We've been capturing our notes related to navigation in [this document](https://docs.google.com/document/d/1zqKOfaj_ThYhaxN8tsxJnYnr7IYNfF1_-piVWhmzcSI/edit?usp=sharing)

**Comment by jgiardino** [comment]
Closing this issue. We can create new issues later as new test pages are needed.
