### ISSUE TITLE
CSS Needs for Charting

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-next#1723]
- Need a grey color pallet for bullet chart ranges. This is the only chart that uses grey.

- Need to create CSS variables for charts; margins, padding, font sizes, etc. Each chart type has its own style properties, which should all be defined by PatternFly core. An extensive list of properties can be found here https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-4/react-charts/src/components/ChartTheme/theme-common.js

- Need to decide what color themes we want to support for charts? There are multiple color pallets, each could be it's own theme. Currently, we have Victory based themes for both light and dark screens, but should have a discussion with design folks. For example, we have a green-dark theme, which uses the green color pallet and white text for dark backgrounds. And a green-light theme which uses black text for light backgrounds. (This also allows tooltip background colors also change for a dark screen.) We also have a multi-color theme, based on Michael's mocks.

**Comment by rachael-phillips** [comment]
@dlabrecq based on the asks above it sounds like we need to pick a handful of these or less to create for Victory. Is that correct? How may themes could we have?

@mceledonia can you clarify exactly what themes we will need?

**Comment by rachael-phillips** [comment]
@mcoker making you aware of the ask above to have CSS variables for charts; margins, padding, font sizes, etc. Each chart type has its own style properties, which should all be defined by PatternFly core. An extensive list of properties can be found here https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-4/react-charts/src/components/ChartTheme/theme-common.js

**Comment by dlabrecq** [comment]
The number of Victory based themes would be the number of color pallets we intend to support (e.g., blue, green, etc.). (We still need a grey color pallet for bullet charts, but that probably won't be a theme.) Then, one of each theme for light and dark screens.

FYI, Victory themes are just a config file of properties. Instead of adding a CSS selector in the page for a light/dark theme, to change component styles, we use Victory themes to define the various properties associated with that screen. 

For a light screen, we might add properties to style Victory tooltips with white text on a black background. For a dark screen, we would want the opposite (i.e., in  a separate theme).

**Comment by dlabrecq** [comment]
It's also possible that we just have two Victory themes for light and dark screens. Then, define the various color scales differently within the react-charts package, like button variants.

**Comment by rachael-phillips** [comment]
Related issue: https://github.com/patternfly/patternfly-react/issues/1692

Donut charts need a grey fill for unused chart area
Donut charts need another design example that represents thresholds - grey #D8D8D8 fill for unused chart area, blue-300 #73bcf7 fill for 1st level of threshold (no threshold has been reached), gold-400 #F0AB00 fill for 2nd level of threshold (warning threshold has been reached), red-100 #c9190b fill for 3rd level of threshold (danger threshold has been reached)

**Comment by mceledonia** [comment]
@dlabrecq @TheRealJon @rachael-phillips @LHinson 

In progress chart variants specs
https://docs.google.com/document/d/1cw10pJFXWruB1SA8TQwituxn5Ss6KpxYPCOYGrH8qAY/edit?usp=sharing

**Comment by rachael-phillips** [comment]
Thanks for sending, Michael!
