### ISSUE TITLE
Table Drop Column

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-next#1725]
Add option to drop column in mobile view.

**Comment by mcarrano** [comment]
My understanding here is that we will provide the following:

* An option to flag any column to be dropped when the table converts to a mobile table (stacked table).
* When the width of the screen goes below a certain breakpoint and columns designated to be hidden will not be visible on the screen and other data will be moved up to take it's place.

@rachael-phillips @LHinson @mcoker can you just confirm that this is consistent with your interpretation? If so, this can be placed in the queue for CSS.

**Comment by mcoker** [comment]
@mcarrano yep. The way I envision it, it will just be a simple modifier (something like `.pf-m-show-on-lg`) that only shows a particular cell at one of our global breakpoints (in that example, the cell is hidden at any point before the `lg` breakpoint), and you would apply that modifier to all cells in the column that you want to show only at/after a particular breakpoint. @tlabaj does this sound like an approach that would work with the react implementation, or would you propose something different?

**Comment by LHinson** [comment]
@mcarrano agreed. Removing the "ixd" tag and adding "css"

**Comment by dlabaj** [comment]
Sounds good.  We can do this in react.  @mcoker @rachael-phillips
