### ISSUE TITLE
How to expose all global colors as vars

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-next#1735]
We have a lot of colors defined in the global color palette that are not in use with a meaningful name in patternfly, so they only exist as the SASS color var or React token name associated, ie `$pf-color-gold-600`.

At a quick glance, these colors are not tied to CSS variables since we don't use them.

```
$pf-color-black-700
$pf-color-blue-700
$pf-color-cyan-100
$pf-color-cyan-200
$pf-color-cyan-300
$pf-color-cyan-400
$pf-color-cyan-500
$pf-color-cyan-600
$pf-color-cyan-700
$pf-color-gold-100
$pf-color-gold-200
$pf-color-gold-300
$pf-color-gold-500
$pf-color-gold-700
$pf-color-green-100
$pf-color-green-200
$pf-color-green-300
$pf-color-green-400
$pf-color-green-500
$pf-color-green-600
$pf-color-green-700
$pf-color-light-blue-100
$pf-color-light-blue-200
$pf-color-light-blue-300
$pf-color-light-blue-400
$pf-color-light-blue-500
$pf-color-light-blue-600
$pf-color-light-blue-700
$pf-color-light-green-100
$pf-color-light-green-200
$pf-color-light-green-300
$pf-color-light-green-500
$pf-color-light-green-700
$pf-color-orange-100
$pf-color-orange-200
$pf-color-orange-300
$pf-color-orange-400
$pf-color-orange-500
$pf-color-orange-600
$pf-color-orange-700
$pf-color-purple-100
$pf-color-purple-200
$pf-color-purple-300
$pf-color-purple-400
$pf-color-purple-500
$pf-color-purple-600
$pf-color-purple-700
$pf-color-red-300
$pf-color-red-500
```

Should we surface these colors to users as CSS custom properties and react tokens, and if so, what would be the best way?

cc @kybaker @mceledonia @mcarrano

**Comment by mceledonia** [comment]
@mcoker Just to double check, this excludes charting?

**Comment by mcoker** [comment]
@mceledonia correct, this is just for the main color palette in [colors.scss](https://github.com/patternfly/patternfly-next/blob/master/src/patternfly/sass-utilities/colors.scss) and how our global CSS variables and react tokens come from the variables in [scss-variables.scss](https://github.com/patternfly/patternfly-next/blob/master/src/patternfly/sass-utilities/scss-variables.scss). If a person wanted to use a color from `colors.scss` that we don't have in `scss-variables.scss`, they would have to either specify a hex value or use SCSS - it wouldn't be available as a CSS variable or react token.

**Comment by rachael-phillips** [comment]
@mcoker what priority do you think this is?

**Comment by mcoker** [comment]
As people start to use PF4, they're going to need this as they want to reference colors from our global palette that we don't already have defined as global variables. They can currently work around it by using the SCSS global color var or a hex value for the color, but neither of those are ideal. The sooner we can offer a better way for them to use these colors, the better.

I would like to get this done after the release if possible.

**Comment by mcoker** [comment]
This was done in 2551
