### ISSUE TITLE
Allow scaling of the wizard modal to full width of the application

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#1740]
A product implementation of the wizard helped identify that the context area of the wizard need to be, at times, large in order to accommodate larger components, such as data table. In order to do so, the modal should be flexible to allow for "full width".

**Comment by mcoker** [comment]
FYI, we added a full-width/height modifier to the wizard in https://github.com/patternfly/patternfly-next/pull/1721

**Comment by LHinson** [comment]
Oh awesome, sounds like it's been addressed. Feel free to close this issue if so! @mcoker
