### ISSUE TITLE
Additional default state for notifications

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-next#1749]
There are a few needs on the product side to have a default notification.

This would require a generic colour and icon that would show in inline/toast/notification drawer implementations of the notification.

See this comment for a better understanding: 
https://docs.google.com/a/redhat.com/document/d/1ujaWYYvuKE_lK4JmD1DLHwr1zYJ-h5652QMba6TcWo8/edit?disco=AAAACsEDtzU

OpenShift also has a need for this as @cshinn has pointed out. Where a user could create an alert that doesn't fit into the four options we provide. He has made the case for a more generic notification that could be tied to this custom alert.

**Comment by mceledonia** [comment]
Here's my first go at it, thoughts:
- Went with our new cyan color variables as it's a color that we haven't used so it currently holds no association (as compared to blue) which is what we want from an undescriptive alert style.
- Tried grayscale, both light gray or dark background.. Light gray conflicts with the shadow of the alert, blurring the edge of the box which is an undesirable effect. Dark gray forces a white icon which conflicts with current alert styling of a darker icon on a medium color background.
- Flag icon is a generic way of representing something that deserves attention, but does not imply that the notification is inherently good or bad

### Regular alert
Background: `#73C5C5`
Icon fill: `#003737`
![image](https://user-images.githubusercontent.com/30935938/58028986-b2f6d400-7ae9-11e9-9f6e-be68a3a4b813.png)

### Inline alert
Side bar fill: `#009596`
Icon fill: `#009596`
![image](https://user-images.githubusercontent.com/30935938/58029066-d02ba280-7ae9-11e9-8842-2316af2bb43d.png)

### Notification Drawer
Side bar fill: `#009596`
Icon fill: `#009596`
![image](https://user-images.githubusercontent.com/30935938/58030343-6234aa80-7aec-11e9-906f-51323086d79f.png)


FYI
@matthewcarleton @kybaker @mcarrano @cshinn @andybraren

**Comment by mcarrano** [comment]
@mceledonia I'm looking at how the neutral state is being used. Seems like there are two places this is being called for which are slightly different. The first is summarized in this document: https://docs.google.com/document/d/1HTkvK8_zFJAX-rhBw1aNrmZYzywixik31DzaiKCUbW4/edit?usp=sharing from @bdellacio. Ref #1390 This seems more like a prompt than a flag condition. Maybe a "?" would be a better icon?

The other case that is referenced at the top of this issue is for a new status condition. But in re-reading the original request, is there a reason that the Warning state was not acceptable? That's what I would have used to flag a failure to load.

I'm feeling like these are 2 very different use cases so perhaps there is not an easy default. Thoughts?

**Comment by cshinn** [comment]
@mcarrano We also have situations where users can define their own severities for alerts, or leave that field empty. In these cases, we can't necessarily slot the alert into one of the existing states or make assumptions about its relative severity.

**Comment by mcarrano** [comment]
Thanks @cshinn that helps me understand this better. I'm wondering if we can just leave out the icon or use something really generic as in @bdellasc 's mocks. I think the problem with the Flag is that that in itself implies some semantic meaning.

**Comment by mceledonia** [comment]
There's got to be a few super generic icons out there that would work for this, I think I just need to take some time to find those. I like an empty circle but even that has a connotation which might conflict (for example those pf icons that show a circle being filled to represent capacity amount)

**Comment by matthewcarleton** [comment]
ya admittedly I had the same thoughts on the flag but couldn't think of an alternative. I like the consistency of a circle since we use it for most icons in the alerts.

**Comment by cshinn** [comment]
Having no icon at all could reinforce the idea that we are explicitly not assigning state

**Comment by bdellasc** [comment]
Just to verify @mcarrano 's understanding of our case: The icon indicates that the current state is a neutral state and that the user must take action which will result in either a positive or negative outcome. 

We're also utilizing the inline alerts as a more interactive component within its surrounding content as a "checkpoint" for users to verify they did everything correctly.  It's a bit different from what's being described for the OpenShift case, but we felt that there was enough overlap with an alert that it made sense to utilize the basic design, but add a radio button to the content that changes the state of the alert.

**Comment by lboehling** [comment]
Got together with @mceledonia regarding default notification states for alerts. Our recommendation is to use the notification bell as the icon for alerts that have no assigned state. Currently, the notification bell is used to represent all alerts/notifications in the nav, so it’s essentially being used as a neutral alert icon already. We suggest the default color be teal/dark teal, per Michael’s suggestion above. 

<img width="433" alt="Screen Shot 2019-07-03 at 3 49 05 PM" src="https://user-images.githubusercontent.com/46571616/60620835-3e7ea880-9daa-11e9-9bc5-9f512ffef426.png">
<img width="389" alt="Screen Shot 2019-07-03 at 3 49 11 PM" src="https://user-images.githubusercontent.com/46571616/60620836-3e7ea880-9daa-11e9-8710-5033138df95c.png">

If others feel this doesn’t suit each use case discussed above, we can explore making 2 separate icons!

**Comment by mcarrano** [comment]
I like this approach @lboehling @mceledonia . Using the bell to represent notifications, in general, works for me. @matthewcarleton @cshinn @bdellasc do you think this would suit your project needs? If there are no objections, I'd like to review at this week's PF weekly sync and move ahead with this.

**Comment by matthewcarleton** [comment]
@mcarrano this works for me! Really nice work @mceledonia @lboehling !
