### ISSUE TITLE
Update page global spacing, and any components that need to align with the page spacing

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-next#1757]
We want to change some of the global spacing in the page component from 32px to 24px. Specifically....

* Main page sections - the padding all around
* Main page nav section - left and right padding
* Main page breadcrumb section - top, right, and left padding
* Masthead brand - left padding
* Header tools - right margin
* Vertical Navigation links - left and right padding
* Data List - left and right padding
* Data Table - left and right padding
* Toolbar - left and right padding

cc @kybaker @LHinson

**Comment by christiemolloy** [comment]
Will need to change the left/right positioning on the arrow buttons that sit inside of the nav.

<img width="652" alt="Screen Shot 2019-04-25 at 9 12 58 AM" src="https://user-images.githubusercontent.com/20118816/56738320-5e567800-673a-11e9-8654-2071511da839.png">

**Comment by christiemolloy** [comment]
Is the padding for the expandable content in the table changing from 32 to 24px too? And then what is the change on mobile? Right now the expandable is 24px which allows it to stand out from the 16px on the table rows.

Desktop:
<img width="846" alt="Screen Shot 2019-04-25 at 9 24 28 AM" src="https://user-images.githubusercontent.com/20118816/56739098-f30da580-673b-11e9-959c-b4a7f62dc93d.png">

Mobile:
<img width="426" alt="Screen Shot 2019-04-25 at 9 26 22 AM" src="https://user-images.githubusercontent.com/20118816/56739248-38ca6e00-673c-11e9-9e13-966b02566460.png">

**Comment by christiemolloy** [comment]
@kybaker if the left and right space is changing in the masthead from 32 to 24, does that mean that the spacers on everything in the nav should change from 32 to 24 too for consistency. i.e. this example:

<img width="791" alt="Screen Shot 2019-04-25 at 9 38 57 AM" src="https://user-images.githubusercontent.com/20118816/56739977-fa35b300-673d-11e9-9285-0124b0181233.png">

**Comment by kybaker** [comment]
@christiemolloy Only in places that keep the content aligned. The horizontal nav is fine with 32. We will need to change the one above the nav.

**Comment by christiemolloy** [comment]
@kybaker im assuming padding around empty state needs to change from 32px to 24px because if its inside of a card/page main section, and the content inside of the empty state reaches its borders it wont align with the rest of the page?

<img width="1053" alt="Screen Shot 2019-04-25 at 9 51 01 AM" src="https://user-images.githubusercontent.com/20118816/56740826-a926be80-673f-11e9-8f48-7b5638dda6b8.png">

**Comment by kybaker** [comment]
@christiemolloy This is fine you can leave it because it is centered.
