### ISSUE TITLE
How to handle word-wrapping

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-next#1762]
In cases like below where text wraps to the next line should we used the CSS hyphen option to add a hyphen between letters in words that wrap to the next line, like typical text editors do. It would be great to get some guidance from @stacymcauliffe  here.

Related to #1761 

<img width="328" alt="Screen Shot 2019-04-24 at 4 54 43 PM" src="https://user-images.githubusercontent.com/20118816/56693892-818a1480-66b3-11e9-9dc7-0099ee85dbd2.png">

**Comment by stacymcauliffe** [comment]
@christiemolloy - great question! I would recommend we do not allow text to wrap in the middle of a word. Is it possible to force words that do not fit on a line to get pushed automatically to the next line?

In the example you show, we've got a single 16-letter word that doesn't fit on the line, so I could see how that might force us to decide on hyphen or no hyphen... But in an instance where we're using a 16 letter word in a context like this, I might recommend we select a different word.  

We also have [defined standards for PatternFly on how to use truncation](https://www.patternfly.org/v4/design-guidelines/content/grammar-and-terminology#truncation), although we likely wouldn't want to be forced to truncate a title like this unless we were providing a super long host name or something like that. 

Hopefully this helps!

**Comment by christiemolloy** [comment]
@mcoker I think instead of `word-wrap: break-word;` we should use `hyphen: auto` so that if part of an **important word does break to the next line** a hyphen is used to indicate that part of the word has wrapped. 

@stacymcauliffe what do you think about having titles/h1-h6 using `hyphen: auto` ? 

<img width="643" alt="Screen Shot 2019-05-14 at 2 33 42 PM" src="https://user-images.githubusercontent.com/20118816/57722836-5a40ba80-7655-11e9-96ce-91499a455b1b.png">

**Comment by stacymcauliffe** [comment]
@christiemolloy - yep, totally agree, for the edge case where a word must wrap, I think this makes sense. Thanks!

**Comment by christiemolloy** [comment]
Closing this issue for now, because we won't be adding hyphens.
