### ISSUE TITLE
Filter Chip

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#177]
A tag component will be used to address the use case of a Filter Tag/Chip. Current design can be seen as part of the Filter pattern here: http://www.patternfly.org/pattern-library/forms-and-controls/filter/#/design 

Requirement: 
- Needs to be able to close (optional). 
- Multiple value pairs required 
- Address accessibility concerns that were previously seen in PF3 with the hit area of the close button being too small. 

Design Folder: https://drive.google.com/open?id=1hN8CUvcBPI4XcwJdZjHDVaZlkIEucIj8

Open question: 
[visual question] Can the badge be used to address this use case? 

- [x] Interaction design requirements 
- [x] Visuals 
- [x] First checkpoint complete and approved 
- [ ] CSS 
- [ ] React
- [ ] Second checkpoint complete and approved 

Contacts: 
- IxD @mcarrano 
- Visual 
- CSS 

Design revised 10/29: 
The component:
[Filter_Chips_Github_10_29.pdf](https://github.com/patternfly/patternfly-next/files/2527337/Filter_Chips_Github_10_29.pdf)

The component in context:
[Filter_Chips_InContext_GitHub_10_29.pdf](https://github.com/patternfly/patternfly-next/files/2527338/Filter_Chips_InContext_GitHub_10_29.pdf)

**Comment by terezanovotna** [comment]
Hey @christiemolloy! We are in need of this component in our product, and Robin Knaur @PanSpagetka has been working on the pf3 implementation and continues working on the pf4 implementation. I know that the design is not ready, but I think it would be a great moment to start collaborating on this together, so he can revise his implementation while you design it.

**Comment by terezanovotna** [comment]
![tag](https://user-images.githubusercontent.com/36040135/45425624-311cf400-b69a-11e8-9741-d977bd92f2cf.png)

This is what I suggested, but you know how to fit it into the new pf4 system. @PanSpagetka is great at receiving feedback:)

**Comment by christiemolloy** [comment]
Hi @terezanovotna and @PanSpagetka I only just saw this comment - sorry! I recently finished the design in pf4 and had the review today. The pdf is attached now to this issue! Let me know if you want to talk further about it :)

**Comment by christiemolloy** [comment]
@mcarrano @kybaker @LHinson the pdf for the filter chip component has been added. Once its approved this issue can move to CSS :)

Matt - after discussions today should we rename this component to Filter Chip?

**Comment by terezanovotna** [comment]
Looks great @christiemolloy! How would it look like if we had 50 values? Are we going to aggregate it? instead of 50 values - would we show `Category One: 50 values`? 
How about super long values? Do we trunkate?

**Comment by LHinson** [comment]
@terezanovotna I think those are great issues. For now, we just need continue to push forward with the basics. However, I've opened another issue to continue to explore these questions. https://github.com/patternfly/patternfly-next/issues/748
