### ISSUE TITLE
Table with compound expansion - text in first cell shifts position

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-next#1770]
When I hover over the Branches button in one of the last two rows, the text in the first cell will change position. 

Steps to reproduce:
1. Resize your window so that the text in the table cells wrap
2. Hover over the Branches button (i.e. not one that is active)

Result: The text in the first cell will shift position as shown below.

![image](https://user-images.githubusercontent.com/21063328/56827046-b325eb80-682b-11e9-9e43-3ac26ded476b.png)

![image](https://user-images.githubusercontent.com/21063328/56827076-c9cc4280-682b-11e9-8dd0-0d3621accc1e.png)

**Comment by rachael-phillips** [comment]
Hi @jgiardino is this a blocking bug?

**Comment by jgiardino** [comment]
Adding @mcoker to this. I'm not sure what we consider blocking bugs. It doesn't break functionality. But if this is a component that is being requested by a product team, I would bump it up in priority, given the possible visibility of this.

**Comment by mcoker** [comment]
Agreed, it’s just a visual bug and only impacts compound expansion, so it’s not blocking, but we should sort it out after the release.
