### ISSUE TITLE
Background defaulting to transparent after upgrade?

### ISSUE THREAD

**Issue by ibolton336** [patternfly/patternfly-next#1774]
Just upgraded to the latest version of pf-core & I am seeing the background-color being set to transparent

<img width="826" alt="Screen Shot 2019-04-29 at 11 39 19 AM" src="https://user-images.githubusercontent.com/11218376/56908128-b57a8680-6a73-11e9-98ef-4899e0aaa312.png">

**Comment by mcoker** [comment]
Hey @ibolton336! That's a result of our [shield CSS](https://github.com/patternfly/patternfly-next/blob/master/src/patternfly/_shield-noninheritable.scss).

Did you simply update the version of core or did other things change as well (did you update react-core, too, or anything else)? And what version of core were you using before? We haven't made any changes around how we're loading the default CSS in core in a while.
