### ISSUE TITLE
Buttons slightly misaligned in Firefox

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-next#1778]
This is a bit hard to see, but the text is slightly higher (1px) in Firefox than in Chrome.

In the image, the pink box is the same size and exactly aligned under the "g" in "Danger". In the firefox version, the bottom of the pink box is aligned with the bottom of the button.
When the same pink box (same height) is placed exactly under the "g" in "Danger" in a screenshot taken from Chrome, the pink box is outside of the button by 1px

![firefoxbuttons](https://user-images.githubusercontent.com/23172038/56971146-b9231180-6b36-11e9-9bf1-bb9d7d5b0efb.png)

**Comment by kybaker** [comment]
@katierik This is a known issue with Overpass font hinting. This is a big reason for replacing Overpass with the new Red Hat font.
