### ISSUE TITLE
Textbox Filter

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#178]
Introduce a textbox filter component. See current design here: http://www.patternfly.org/pattern-library/forms-and-controls/textbox-filter/#/design

- [x] Interaction design requirements 
- [ ] Visuals 
- [ ] First checkpoint complete and approved 
- [ ] CSS 
- [ ] React
- [ ] Second checkpoint complete and approved 

Contacts: 
- IxD @mcarrano 
- Visual 
- CSS

**Comment by LHinson** [comment]
Closing this as its being addressed in this issue here: https://github.com/patternfly/patternfly-next/issues/347
