### ISSUE TITLE
Drawer component 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#1786]
Introduce the drawer component. The drawer component can be seen in notification drawer as well as in other page layouts, where the drawer slide content over, in addition to the capability to lay over content. 

related to #35

**Comment by mcoker** [comment]
Talked to @mcarrano and @kybaker about this and we're going to go with

* 1 width variation (450px) that can be changed via a CSS var (`--pf-c-page__drawer--Width, `--pf-c-page__drawer--md--Width`)
* The drawer always appears on top of the content
* The sidebar always appears on top of the drawer
   * opened this issue from a discussion around if the sidebar should automatically collapse on mobile if you click on the notification icon to bring up the drawer - https://github.com/patternfly/patternfly-react/issues/2454
