### ISSUE TITLE
Firefox Horizontal Nav Bugs

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-next#1794]
In Firefox the Horizontal nav is taller than the list inside which is causing extra space underneath the list, you can inspect it here: https://pf4.patternfly.org/demos/Page/examples-full/?component=Page%20component%20horizontal%20nav%20example#

This is also causing a bug in the Patternfly website: https://github.com/patternfly/patternfly-org/issues/865

<img width="1222" alt="Screen Shot 2019-05-03 at 9 30 49 AM" src="https://user-images.githubusercontent.com/20118816/57140627-355f6400-6d86-11e9-8bd2-489dffeb3789.png">

**Comment by mcoker** [comment]
Also noticed this when the nav breaks to a mobile layout in firefox, the nav doesn't overflow properly.

<img width="806" alt="Screen Shot 2019-05-03 at 9 10 05 AM" src="https://user-images.githubusercontent.com/35148959/57142943-58d4df80-6d83-11e9-8048-909377ec0710.png">

**Comment by mcoker** [comment]
Also this misalignment
<img width="256" alt="Screen Shot 2019-05-03 at 9 26 24 AM" src="https://user-images.githubusercontent.com/35148959/57143971-9a668a00-6d85-11e9-9d29-1ca7a3447b99.png">
<img width="236" alt="Screen Shot 2019-05-03 at 9 16 21 AM" src="https://user-images.githubusercontent.com/35148959/57143973-9a668a00-6d85-11e9-8fa1-87806fb1683d.png">
