### ISSUE TITLE
Clean up abbreviations

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly-next#1800]
There are lots of instance in the documentation of both "PF" and "Patternfly" being used, as well as whether the 4 is included or not; this should probably be made more consistent.
There are also smaller things like "applauncher" or "app launcher" or should it really be named an application launcher? Also, "Nav" or "navigation"?

**Comment by christiemolloy** [comment]
@jenny-s51 consult @stacymcauliffe for some clarification around the best wording to choose here.

**Comment by jenny-s51** [comment]
Awaiting update from Sarah regarding where to update documentation

**Comment by srambach** [comment]
One example is in https://pf4.patternfly.org/components/AppLauncher/examples/ where we have both "Applauncher" and "App launcher"

Another is here https://pf4.patternfly.org/components/Nav/examples/ where the menu and examples use "Nav" but the page is titled "Navigation"

I think maybe the PF vs Patternfly examples I noticed were in code comments.
