### ISSUE TITLE
Unable to see all items in the subnav area of a nav list

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/patternfly-next#1808]
If there are many items in a subnav area, they are not easily detectable. They are not shown and the scrollbar is hidden.

The area does scroll with the wheelie mouse or via keyboard navigation but there is no way for a user to know that there are more items in the nav.

**Comment by mcoker** [comment]
cc @mcarrano @mceledonia

**Comment by mcarrano** [comment]
@mcoker how is this constructed now? Is the sidebar panel where the nav sits built to scroll if the menu exceeds the panel height?  If so, unclear why a scrollbar does not display. @jeff-phillips-18 do you know if scrollbars are being hidden at the OS level? Does the browser expose a scrollbar if you shrink the window?

**Comment by mcoker** [comment]
@mcarrano the scrollbars are hidden in the CSS. This was part of the original implementation in https://github.com/patternfly/patternfly-next/pull/600

**Comment by mcarrano** [comment]
Based on discussion with @mcoker , looks like the subnav was constrained to be no taller than 600px. My expectation would be that the subnav should grow to be as tall as it needs to be and that any content below (including primary nav items) will just be pushed down below the fold, if necessary. Scroll bars are enabled for the nav panel itself it would be clear that there is more nav content in that case.

@jeff-phillips-18 if we make that change does it solve the problem for you?

**Comment by jeff-phillips-18** [comment]
@mcarrano Yes, that is what I would expect.

**Comment by mcarrano** [comment]
@mcoker I think we should go ahead and do this then unless it will be a breaking change. Thoughts?

**Comment by mcoker** [comment]
@mcarrano Agree we should do it, but it is a breaking change to remove the functionality someone may have been depending upon. If someone had designed their nav in a way that worked with the existing functionality, they may see something unwanted/unexpected if they update the version of core that removes the max-height/scroll. We also have a variable for the max-height of the scrollable menu that a user could override, and if we remove the variable, users will no longer be able to set their own custom max-height.

That said, I think we could just change the max-height from `600px` to `100%`, which means the subnav menu will just grow to fit it's contents. That will leave the variable there for users who may want a custom max-height. That will still be a breaking change if someone was relying on the 600px max-height that is currently there.

We could also offer a modifier for the nav that disables the max-height/overflow, so folks could opt-in to the change. Then in our next breaking change period, we remove the modifier and just make that the default.

Or we could wait until the next breaking change period and just make the change.

What do you think?

**Comment by mcarrano** [comment]
@jeff-phillips-18 what's your preference/priority on this? @LHinson @rachael-phillips you should also be in the loop on this decision.

**Comment by jeff-phillips-18** [comment]
I don't believe the max-height setting would be relied on by a project. Agreed we should leave the variable so that if, for some reason, a product wanted to set a max-height they could easily.

**Comment by kybaker** [comment]
@mcarrano @mcoker I dont think this would affect anyone at this point. The most subnav items I can think of in a product is OpenShift and it does not come close to 600px. This function creates multiple scrollbars and a scroll trap which is not what we intended I think this could be considered a bug.
