### ISSUE TITLE
Enhancement: Add action button with kebab icon to the kebab menu 

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#181]
The kebab menu can be seen here: https://pf-next.netlify.com/components/Dropdown/examples/ It still requires introducing the action button as a result of issue #274. Icon for kebab should use https://fontawesome.com/icons/ellipsis-v?style=solid

Component lifecycle: 
- [x] Interaction design requirements 
- [x] Visuals 
- [x] First checkpoint complete and approved 
- [ ] CSS 
- [ ] React
- [ ] Second checkpoint complete and approved 

Contacts: 
- IxD @mcarrano 
- Visual @kybaker 
- CSS

**Comment by mattnolting** [comment]
@mcarrano noted needing hover state for pf-m-action (icon only) dropdowns. Currently, hover color follows this pattern http://www.patternfly.org/pattern-library/widgets/#kebabs. @kybaker can you confirm this is correct? If not, can you provide direction, please?

**Comment by kybaker** [comment]
@mattnolting That works. Thanks!
