### ISSUE TITLE
Rename DataTable demo to Table

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-next#1814]
It's confusing that we refer to it as DataTable. Users will look for a component named DataTable instead of Table.

We might consider looking through the rest of the codebase and seeing if that pops up anywhere else that should be updated.

**Comment by rachael-phillips** [comment]
@mcarrano making sure you are aware of this, as well. Do you agree?

**Comment by mcarrano** [comment]
I'm fine with this.
