### ISSUE TITLE
RCUE for PF4

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-next#1815]
There are background and logos that we want to deliver for product. In the past, we have called this RCUE (Red Hat Common User Experience) as these visual assets are specific to Red Hat products.

In this issue, we will address adding RCUE for the newest version of PF. First, we should investigate how to achieve this since this isn't a straight lift from pf3 (e.g. separate git?, separate stylesheet?, etc).

**Comment by mindreeper2420** [comment]
@rachael-phillips I'm happy to help with this, as I added RCUE to the PatternFly build as part of pulling it under the PatternFly family.

**Comment by bdellasc** [comment]
I know we're encouraging teams to move to PF4 whenever possible, but I think it makes sense to have a PF3-friendly RCUE that utilizes the new brand assets for those teams who don't have a PF4 migration on their short-term plan, but need to get their branding assets aligned with the latest. We'll ensure much more consistent implementations across products that way.

**Comment by srambach** [comment]
In particular, Business Automation was looking for a way to update the logos that they are currently pulling from RCUE.

**Comment by aljesusg** [comment]
Hi, any news in RCUE for PF4?

**Comment by mcoker** [comment]
@aljesusg sorry for the delay! We are looking to introduce this in our next release, targeted around the 3/10 timeframe.

Closing this issue in favor of https://github.com/patternfly/patternfly-next/issues/2649, where you can track the progress!
