### ISSUE TITLE
Define responsive behavior of masthead utility items

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#1832]
Current implementations of the masthead utility items require rework to display desired responsive behaviors. These changes are required to the Page Layout demos in both [core](https://www.patternfly.org/v4/documentation/core/demos/page-full?component=Page%20component%20default%20nav%20header%20example) and [React](https://www.patternfly.org/v4/documentation/react/demos/pagelayout/pagelayoutsimplenav/). 

New implementation must support the following requirements:

(1) Must support the following Utility bar items
* User Avatar (optional per application support), 
* User menu - dropdown with contents TBD)
* Notification icon - alerts the user of unread notifications and toggles notification drawer. The notification icon must be visible at all viewport sizes.
* utility menus - one or more items represented by an icon. Menus can be either Dropdowns or Options Menus. Typically includes Help and Settings but other menus may be included.

(2) At first breakpoint (tablet), collapse  utility items to kabob.
(3) At second breakpoint, (mobile) collapse user menu into kabob and hide avatar. (Only notification icon and kabob will be shown.)

This issue should address how the combined utility menu is displayed when collapsed, i.e. if User, Settings, and Help live in the same menu, what does that look like - how do we maintain hierarchy.

**Comment by mcarrano** [comment]
@mcoker @LHinson @rachael-phillips I have opened this issue to address revised responsive behavior of the utility bar in the masthead. @maryshak1996 will work on a design proposal that can be reviewed by next week. Per our discussions, this is a prerequisite for implementing the Notification Drawer demo (#35 ).

This issue does not address the content of utility menus. I will open a second issue for that. The intent is to refactor the current masthead implementation to allow for integration of the notification drawer.

**Comment by rachael-phillips** [comment]
Hi @Mcarrano this is great - thank you! Would also love to hear your
viewpoint of the urgency of this work and where it should live on the
roadmap.

**Comment by mcarrano** [comment]
I am hoping we can get this into the June release @rachael-phillips .  It came up as part of the exploration of notification drawer and how that would work in a mobile viewport.

**Comment by LHinson** [comment]
+1 - i'ved added this to the spreadsheet.

**Comment by jeperry** [comment]
We've had some concerns about the interaction of the Avatar name menu, coming from the cloud services platform. I am not sure if raising this here is the right place but wanted to bring it up. @KendraMar also mentions it here. https://github.com/patternfly/patternfly-next/issues/1833#issuecomment-493570413

**Comment by mcarrano** [comment]
Yes, we should consider how the Avatar folds into the menu responsively and how to update.

**Comment by maryshak1996** [comment]
Reviewed this with @mcarrano and @mcoker and we think that this is going in a good direction:
https://redhat.invisionapp.com/share/8BS3SIY4ZDR

**Comment by mcarrano** [comment]
@dongniwang just wanted to make you aware of this as it's closely related to #1833. Let us know if you have any questions or feedback. One open question was what to do about the avatar. Right now that's just static so we were assuming we could hide at mobile sizes, but if the avatar will be interactive, we may need to reconsider this.

**Comment by dongniwang** [comment]
Thanks @mcarrano and @maryshak1996! I left a few comments in the InVision. I think it looks pretty good overall. 

Regarding the avatar action. One solution would be to move the downward facing arrow (caret) to the right of the avatar if the avatar will not be interactive at all and users always have to update it somewhere else.

**Comment by maryshak1996** [comment]
I put together a spec with basic visuals and interaction for what I have above: 
[visual-spec.pdf](https://github.com/patternfly/patternfly-next/files/3214110/visual-spec.pdf)

**Comment by mcarrano** [comment]
I think this all looks great @maryshak1996 !  @kybaker can you take a look when you get a chance?

**Comment by kybaker** [comment]
@mcarrano Looks good to me

**Comment by maryshak1996** [comment]
https://sketch.cloud/s/LeMlW

**Comment by maryshak1996** [comment]
@rachael-phillips @mcarrano I know that you both had some questions yesterday about what would happen if the user clicks on a utility item while the notification drawer is opened. I mocked this up and while it's a bit busy, I don't think that it's terrible. I'd be interested to know what you think
![Screen Shot 2019-05-31 at 4 10 24 PM](https://user-images.githubusercontent.com/19824574/58732183-bd08b480-83be-11e9-98f6-b6a4945f69e4.png)
![Screen Shot 2019-05-31 at 4 09 00 PM](https://user-images.githubusercontent.com/19824574/58732184-bda14b00-83be-11e9-877b-3f47bf73d83e.png)

**Comment by mcarrano** [comment]
I think it's fine @maryshak1996 . Keep in mind that the menus do not sit open after the user selects something. We can never predict what will fall below any dropdown menu.

**Comment by mcarrano** [comment]
This design is approved and ready for CSS implementation.

**Comment by maryshak1996** [comment]
@mcarrano I wanted to ping this issue again, as I talked to @dlabaj about this a bit more today. I wanted to more specifically indicate the states of the masthead icons:
- DEFAULT: global-background-300
- HOVER: white
- OPENED: 36x36px black-800 circle appears behind icon (this is for ALL masthead icons, including notification bell)
I've updated the notification drawer docs as well as the docs for this issue, but here is a quick snapshot of what I'm referring to: 
Default:
![Screen Shot 2019-06-27 at 3 04 47 PM](https://user-images.githubusercontent.com/19824574/60293338-07615080-98ed-11e9-9f9e-f0198a3a1fcd.png)
Hover:
![Screen Shot 2019-06-27 at 3 04 57 PM](https://user-images.githubusercontent.com/19824574/60293376-147e3f80-98ed-11e9-8ac9-a9242cd26af9.png)
Opened:
![Screen Shot 2019-06-27 at 3 05 10 PM](https://user-images.githubusercontent.com/19824574/60293387-19db8a00-98ed-11e9-8835-660472f3d813.png)

**Comment by mcarrano** [comment]
Just opened a new issue here to address behavior of the user menu and avatar: https://github.com/patternfly/patternfly-next/issues/2329  This may impact the desired solution here, and therefore placing this on hold until that direction is clarified.

**Comment by mcarrano** [comment]
Closing in favor of #2482 which reflects updated designs
