### ISSUE TITLE
Demo for Inline Alert requiring user input

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly-next#1838]
An "active" alert requiring user input should be able to be done as a core demo, as no new CSS should be needed.

https://docs.google.com/document/d/1HTkvK8_zFJAX-rhBw1aNrmZYzywixik31DzaiKCUbW4/edit#heading=h.mfv7yeomghd1

See also discussion on #1390 

@mcarrano

**Comment by mcarrano** [comment]
@LHinson @rachael-phillips this is something that was born out of a discussion @srambach and I were having regarding embedding active content in an alert. The good news is there is nothing in the current component implementation that would constrain this and I think a demo would be something nice to add down the road.

**Comment by rachael-phillips** [comment]
Hi @mcarrano this was added this to the unplanned section of the Release Milestone spreadsheet and the 4.x milestone. We should discuss in a future planning meeting with @LHinson

**Comment by mcoker** [comment]
This use case is too specific to be a demo on the website. However if a product needs demo code to reference for building this, let me know and I'm happy to put one together.
