### ISSUE TITLE
Setting a fixed width on a Dropdown component adds extra space to the outside

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/patternfly-next#1847]
Setting a Dropdown component's width (in order to prevent jumping sizes on different selections) causes any extra space to be put on the outside of the text and indicator:

![image](https://user-images.githubusercontent.com/11633780/58114182-3507fb00-7bc5-11e9-8e7f-76d95910e474.png)

IMO the extra space should be between the text and the indicator:

![image](https://user-images.githubusercontent.com/11633780/58114241-579a1400-7bc5-11e9-9f6a-58629949ef9c.png)

**Comment by rachael-phillips** [comment]
@mcoker making you aware of this one. Is this something we need to fix in Core?

**Comment by mcoker** [comment]
@rachael-phillips yep!
