### ISSUE TITLE
Simple Wizard Component and Demo

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#185]
Introduce a wizard component (which will include, title, sequence #767 and content) includes as well as demo. 

PF4 Visuals are located in PatternFly4-Wizard.pdf, pages 1-12: https://drive.google.com/open?id=1vfR1MsCLRQF24qFN1xkgpBRvfXVpGQif

The design established leveraged the existing PatternFly Wizard as a basis for design. http://www.patternfly.org/pattern-library/communication/wizard/

Component lifecycle: 
- [x] Interaction design requirements 
- [x] Visuals 
- [x] First checkpoint complete and approved 
- [ ] CSS 
- [ ] React
- [ ] Second checkpoint complete and approved 

Contacts: 
- IxD 
- Visual 
- CSS

**Comment by LHinson** [comment]
@mcarrano I'm kicking this back to interaction design as the current wizard has the following issues: 
- responsive state 
- currently not a scalable design

**Comment by mcarrano** [comment]
Handing this off to visual design. @kybaker will begin working on design concepts based on the [requirements](https://docs.google.com/document/d/1gzaWCOHilkrKg6VgPivw6juLfYZj4KNOGBFNBVHMNIQ/edit?usp=sharing) and [conceptual wireframes](https://drive.google.com/open?id=1POWW0NKmnt2xAsO9pXOkjdiq9s6iRvHx). @LHinson FYI

**Comment by mcarrano** [comment]
@kybaker Per our discussion in the 9/20 design meeting, can you please add an example that includes a back button and post the final designs here? Then I think this is ready to move to CSS.

**Comment by mcarrano** [comment]
@LHinson @kybaker @srambach I created some samples screens to flesh out the demo. You can see these here: 
[Wizard Demo Screens.pdf](https://github.com/patternfly/patternfly-next/files/2421601/Wizard.Demo.Screens.pdf)

These are in wireframe form and are meant to accompany Kyle's hi-fi designs to provide some context for creating a demo. For the most part these are pretty straight forward and should not require additional visual work. But there were a could of questions that came up as I worked on these.

* I added a back button so that the buttons along the bottom are Cancel, Back, and Next in that order. Wasn't sure if Back should have button or link styling. I opted for the as a button, but would like to hear other opinions.
* For PatternFly 3, in the step bar there was a subtly different styling for steps that have been already visited. @kybaker do you think we should carry that over? I don't feel strongly about it. If we do, we will need visual styling for that.
* I created a sample completion screen using a similar template to empty state. @kybaker please take a look and feel free to provide any guidance on what this layout should be. I feel like this should just be a standard screen that someone can just plug their text into so we have a consistent look across product.

**Comment by mcarrano** [comment]
Today @kybaker @srambach @christiemolloy @rachael-phillips and I met to consider several questions concerning the wizard demo and sequence bar behavior. Here is a quick summary of issues and follow-up actions:

* Question: How should we use Status field in the Sequence Bar? Status field is entirely optional any probably is not needed in most cases. But it's presence allows an application to communicate information about completion or other conditions affecting a step. For examples, leave current default text as "Status" and @rachael-phillips and @christiemolloy will reflect it's optional nature and intended usage in related documentation. We also agreed that If this field is used, it should be used for all steps (no mixed mode).

* There are still some refinements to be made to the visual appearance of the header area, including use of appropriate gray for the status field and adjustments for readability. @kybaker @christiemolloy and @christiemolloy will work together on these updates.

* Discussed when and if steps in the sequence bar are clickable, i.e. if I'm on Step 1, can I use the Sequence Bar to advance to steps 2 or 3? Comparing against, PF3 behavior, the user can only click on an item to advance if required conditions on the current step have been satisfied. This calls for a "disabled state" for a step that is not yet clickable. @kybaker and @christiemolloy will work together to define and implement this.

Let me know if you think I've missed anything.

**Comment by christiemolloy** [comment]
@mcarrano thanks for the summary I think that covers what we spoke about! Going to start implementing these changes.

**Comment by mcarrano** [comment]
@christiemolloy @srambach Yesterday I was reviewing the design documentation for Wizard that @rachael-phillips is working on and saw that we had some visual designs for how the wizard would behave on mobile. See the attached.

![screen shot 2018-11-01 at 10 13 07 am](https://user-images.githubusercontent.com/6619860/47862731-3231ee00-ddcc-11e8-9064-f31eaac5487e.png)

There are two things that caught my attention and I wondered if we factored them into the implementation.

1- You'll see that the wizard consumes the entire screen vs. being contained in a modal when it is compressed to mobile size.
2- The header area compresses when scrolling like we are doing for the primary nav header area.

Do you see any implementation concerns here? Wanted to make sure that this was being accounted for.

**Comment by mcarrano** [comment]
Yes, I think so. We can track under Progressive Wizard moving forward.

**Comment by rachael-phillips** [comment]
Closing this issue to continue work in this issue in #755
