### ISSUE TITLE
Notification drawer - Design revisions

### ISSUE THREAD

**Issue by mceledonia** [patternfly/patternfly-next#1851]
Linking #574 ... Going to try to have a new spec for documentation tomorrow.

I proposed a few design revisions May 21, 2019 to @mcarrano @maryshak1996 @mcoker @matthewcarleton @srambach @bdellasc  ... [Meeting recording here](https://bluejeans.com/s/y2RjB/)

**List of revisions:**
- Increase icon size from 16 to 18px ($pf-global--icon--FontSize--md)
- Decrease header from 24px to 21px ($pf-global--FontSize--xl)
- Decreased "selected state" overlay behind notification panel icon to 15% for better contrast with indicator dot
- Change indicator dot (in masthead icon) color to new blue #519DE9
- Shift alert type icon to left, with title/description aligned next to it. This is an effort to align with inline alert style, making implementation more seamless. 
- Bold text for unread titles, this is to add a familiar visual pattern for read/unread and also to add more visual contrast between the two states.
- Remove indicator dot and utilize side color bars as a third read/unread indicator. Remove color bar for read (alternative is increase thickness of bar for unread)*

*This was the large change here, it is an effort to avoid the dead space that currently appears on unread messages which don't have indicator icons. See the [meeting recording](https://bluejeans.com/s/y2RjB/) for my rambling explanation of how I got to my solution. 3:15 timestamp to skip straight to this revision's thoughts.

**Before and after**
![image](https://user-images.githubusercontent.com/30935938/58127308-0d279000-7be3-11e9-9bc3-1db9c0ca35cd.png)

**Alternate versions**
[Left] Using icon layout with description left aligned on icon rather than title for maximum space efficiency but slightly less clean/tight visuals
[Right] Using color bar thickness to represent read/unread, rather than disappearing altogether

![image](https://user-images.githubusercontent.com/30935938/58127866-60e6a900-7be4-11e9-90cb-654ec73ff966.png)

**FYI**
@kybaker @rachael-phillips @LHinson @cshinn

**Comment by cshinn** [comment]
@mceledonia any thought as to what a "stateless" notification might look in this style?

**Comment by maryshak1996** [comment]
Update mockup based on this discussion with visual spec at end: https://marvelapp.com/5jj15f3
Updated sketch file: https://sketch.cloud/s/y50lz

**Comment by mcarrano** [comment]
This has been addressed.
