### ISSUE TITLE
Add Expand All option for tables

### ISSUE THREAD

**Issue by beanh66** [patternfly/patternfly-next#1861]
OpenShift has an "expand all" action for tables that use the expand option to present additional information. Currently PF only allows for expanding a single row at a time but adding this expand all action would allow users to compare data in subsequent rows if desired. 

@maryshak1996 worked on new OpenShift designs for making this feature more PF4 and can help with a design contribution if desired @mcarrano!

**Comment by beanh66** [comment]
![expand-table](https://user-images.githubusercontent.com/18057044/58442727-1faa3980-80bb-11e9-87ea-d97ad515e783.png)
![collapse-table](https://user-images.githubusercontent.com/18057044/58442728-1faa3980-80bb-11e9-978e-445e622fd629.png)

**Comment by mcarrano** [comment]
@beanh66 Thanks for submitting this request. We will need to consider where to slot this on the roadmap. @LHinson @rachael-phillips FYI.  As for the design proposal included here, we currently have the expansion caret as the first element in a row and I don't expect we would want to change that. @maryshak1996 we should think about a way to make this work with our current expansion design for tables.

**Comment by jeperry** [comment]
@katierik might want to see if this relates to what we need in CMSfR

**Comment by mcarrano** [comment]
Going to close this one as we are working on a more recent issue here: https://github.com/patternfly/patternfly-next/issues/2465 @maryshak1996 and @mmenestr are working on some options.
