### ISSUE TITLE
Action/button spacers and applying gutters by default, allowing for gutter size changes

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-next#1867]
Just wanted to gather my thoughts from a meeting we had today and get others' input.

Someone had a question about what amount of space we should use between buttons in PF4 out of the context of a component that applies spacing between buttons, and I realized we don't have a layout or formal recommendation for that (that I know of). Currently the space between buttons in components is defined in the individual component. We don't have a generic layout or recommendation to space buttons outside of the context of a component that spaces the buttons for you.

I brought up with Kyle that we could add a layout for actions that spaces them using an 8px (small) spacer. That layout could also be used in our components where we have buttons to allow for consistent spacing and less code per component. I brought this up with the CSS team and some suggested just using our existing split layout, but with a modified gutter spacer instead. The split layout only has support for default gutter spacing currently, which is 24px (large). Their recommendation was to allow the split/stack (and presumably the grid, gutter, and level) layouts to allow for a different sized gutter, then we recommend users use the split layout with the small gutter to create space between buttons.

Pros to this approach over a layout for actions:
* We don't go down the road of creating a layout for every type of thing we want to create space for.
* It could be less confusing just to offer a general recommendation for spacing instead of an individual layout, because users might not know which layout to choose from.

Cons:
* If we change the recommendation for spacing between buttons (say from small to medium), using the split with small gutter approach would require users update every instance of that layout to use a medium (or whatever) spacer instead. i.e., change `pf-l-split.pf-m-sm` to `.pf-l-split.pf-m-md` everywhere in their application. With an action specific layout, we could update the layout and the change takes effect everywhere the layout is used.
* Users have to know which layout and which spacer to use to space buttons instead of just having to know which layout to use.
* We don't currently allow for modified gutter sizes in any of our layouts, and Kyle has stated we shouldn't allow that flexibility*.

\* On the point of not allowing modified gutters sizes, if the concern is that people would use gutter sizes inconsistently, what if we made the layouts (grid, gutter, stack, split, level) have a gutter by default, and that gutter is the "large" (recommended) gutter size? Then we add modifiers to change the gutter size and disable the gutter. Giving the correct gutter size by default would enforce consistency in the gutter sized used, and still allows you to change it if you want to. For reference, the layouts currently have no gutter by default, and you add `pf-m-gutter` to add the gutter.

What does everyone think? Should we offer something else entirely? For this kind of thing, should we recommend users use the flex layout which already had the spacing system built in, and specify they use the small spacer? Or even that we just recommend 8px and they can achieve that however they want (utility classes, CSS, etc)?

Also please feel free to add anything I might have left out.

**Comment by mcoker** [comment]
I'll also add that I think allowing users to modify the gutter size on these layouts would be a great feature. I get that we want consistency for things like use of grid/gallery on a page layout, and that the grid/gallery layout gutter matches the page section, navigation, masthead, etc paddings, but you could easily use grid/gallery (and particularly split, stack, and level) outside of the context of a bunch of elements in a page section, and instead, the layout is used just to align a few things on top of or beside one another in a row or a nested layout in a page section, where the spacing doesn't need to match the overall page spacing.

That said, if we want to keep the gutters in those layouts as they are and not allow for deviation in gutter size, we could always just recommend users to use the flex layout to achieve custom layouts with custom spacing, since the flex layout allows for stack, split, level, etc, and has all of the custom spacers built in. The split, stack, and level are just simplified versions of the flex layout anyways.

**Comment by mcarrano** [comment]
@mcoker is this just another version of this request? https://github.com/patternfly/patternfly-next/issues/2021

**Comment by mcoker** [comment]
@mcarrano it is, and the other things I mentioned we've discussed, so we can close this out.
