### ISSUE TITLE
Order of variables causing undefined in IE11 scripts

### ISSUE THREAD

**Issue by dlabaj** [patternfly/patternfly-next#1869]
Order of some of the variables is causing undefined to be created by IE11 script when used as described here:

https://github.com/patternfly/patternfly-next/wiki/IE11-Support

The variables that are being created as undefined are the following:

.pf-c-form__actions {
  display: flex;
  flex-wrap: wrap;
  margin-top: undefined;
  margin-right: undefined;
  margin-bottom: undefined;
  margin-left: undefined;
  overflow: hidden; }

.pf-c-login__main-footer-links {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  padding: 0.5rem 4rem 2rem 4rem;
  margin-bottom: undefined; }

.pf-c-wizard__toggle {
  position: relative;
  z-index: 200;
  display: flex;
  justify-content: space-between;
  width: 100%;
  padding: 1.5rem 1rem 1.5rem calc(1rem + undefined + 0.5rem);

.pf-c-wizard__toggle-list {
  position: relative;
  display: flex;
  flex-wrap: wrap;
  align-items: baseline;
  margin-right: 0.5rem;
  margin-bottom: undefined;
  list-style: none; }

**Comment by mcoker** [comment]
fixed in https://github.com/patternfly/patternfly-next/pull/1871
