### ISSUE TITLE
Link Button: look at adjusting spacing

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-next#1883]
I was using our "Link Button" for the website and I had some feedback that there is no room between the icon and the text, which I also agree. @kybaker or @mceledonia what do you think? Should we look at adjusting it a little?

**Update** React Icons dont take classes, so lets create another div around the icon and add the margin to that div.

<img width="470" alt="Screen Shot 2019-06-04 at 9 22 29 AM" src="https://user-images.githubusercontent.com/20118816/58882557-7c54b800-86aa-11e9-8efc-9ecee49869d6.png">

**Comment by kybaker** [comment]
@christiemolloy I think this may be a website css issue. Or ghost buttons have an affordance built in for accessibility - https://pf4.patternfly.org/components/Button/examples/

**Comment by christiemolloy** [comment]
Closing this issue in favor of https://github.com/patternfly/patternfly-react/issues/2145
