### ISSUE TITLE
Add Context Selector to page header

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-next#1900]
Create a new example that shows context selector placed in a page.

In the page header we have containers for tools/nav etc. I placed the context selector in the nav as a demo and it looks like this:

<img width="1157" alt="Screen Shot 2019-06-05 at 4 06 21 PM" src="https://user-images.githubusercontent.com/20118816/58986652-e3a66100-87ab-11e9-9a72-0b80ff630c46.png">

Visuals look like this:

https://drive.google.com/file/d/1b405W_CGasRR-C7eZZl7KgigYODvtsMi/view

cc: @mcoker 

Then when I put in the nav also it sat in front of the context selector because the `.pf-c-page__header-nav` uses grid columns/rows

**Comment by mcoker** [comment]
@christiemolloy yep, I would expect to need to modify the page component header to position the context selector properly.

**Comment by jenny-s51** [comment]
@nicolethoen Hello! I see you were assigned this issue -- I've been assigned [essentially the same one](https://github.com/patternfly/patternfly-react/issues/2285) in react. @jschuler mentioned that I can continue with it when the context selector functionality is implemented here. Let me know if there's anything I can do to help.

**Comment by christiemolloy** [comment]
@mcarrano @maryshak1996  do you guys have designs of how the context selector should behave on mobile? Or maybe you could point me towards who originally designed the context selector/in the page

**Comment by mcarrano** [comment]
@kybaker can you help here? I know we went through all of these cases very early on when we were designing the PF4 navigation system. There should be mocks that show this.

**Comment by kybaker** [comment]
@mcarrano This designs utilized the larger header and scrolling behavior which has since been changed. I think we will have to look at the behavior again given the new masthead design.

**Comment by nicolethoen** [comment]
@kybaker @mcarrano @christiemolloy 
I have made a lot of progress with this story so far, but believe it is blocked until I have the mobile mockups.

**Comment by mcarrano** [comment]
I will set up some time for us to discuss.

**Comment by mcarrano** [comment]
Met today with @christiemolloy @mcoker @nicolethoen and @kybaker to discuss next steps. Looks like this needs to be pulled back to design to consider what the mobile header should look like when a context selector is present.

I have renamed the issue and changed from a bug to an enhancement as this case was never fully implemented as a demo before. @LHinson @rachael-phillips we should consider what the priority is on this and where it lives on the roadmap.

**Comment by LHinson** [comment]
@mcarrano assigning to you so this get added to the design board

**Comment by mcarrano** [comment]
Actually @kybaker has agreed to take a look at this. We want to take a different approach and move the context selector from the page header to the Nav sidebar.

**Comment by mcarrano** [comment]
Met today with @amysueg and Tiffany Nolan to discuss requirements from Integration products for a context selector in the masthead. This is currently being proposed as a way to switch between applications within the integration suite without the user needing to leave the active window.

Here are some current mockups/ideas (work in progress):

https://marvelapp.com/4i45j22/screen/62949664

https://marvelapp.com/449iacg/screen/61070423

**Comment by mcarrano** [comment]
Upon further discussion, we will not advertise the context selector as a standard component of the masthead. We can work with any product teams that need this feature to create a custom solution but will no longer offer this as a demo.

Have opened https://github.com/patternfly/patternfly-org/issues/1542 to remove references and mocks for this from the related design guidelines.
