### ISSUE TITLE
Login: Elements must have sufficient color contrast

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-next#1907]
This is one of only **two** remaining color contrast issues! It's for login, details from the a11y audit below. The other error in the screenshot is already captured in a separate issue.

<img width="929" alt="Screen Shot 2019-06-06 at 9 20 35 PM" src="https://user-images.githubusercontent.com/5942899/59075971-84c31380-88a1-11e9-9b87-08244cdfe065.png">

It's basically those three links Terms of Use, Help, and Privacy Policy. The axe browser extension is flagging issues with other text on the page also, but I'm not as worried about that as I am getting the automated tooling to a point where we are free of errors. 

<img width="1156" alt="Screen Shot 2019-06-06 at 9 24 10 PM" src="https://user-images.githubusercontent.com/5942899/59075958-770d8e00-88a1-11e9-9c9c-bc646cbeee86.png">

**Comment by mcoker** [comment]
@seanforyou23 is this something you'd like to work on?
