### ISSUE TITLE
Inconsistent button placement for modals and no guidance

### ISSUE THREAD

**Issue by ncameronbritt** [patternfly/patternfly-next#1915]
Currently the design guidelines show buttons on the left side of modal dialogs:
https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/modal

while the react demos for the modal component have buttons on the right:
https://www.patternfly.org/v4/documentation/react/components/modal/

There is no documentation that I was able to find that says which version is correct.

**Comment by rachael-phillips** [comment]
Thanks @ncameronbritt ! @mcarrano should we add this to the org repo?

**Comment by mcarrano** [comment]
@ncameronbritt @rachael-phillips The documentation shows the correct design intent. This was based on a decision that was made to consistently left-align buttons on forms and modals. Our code examples have not caught up to this. There is an issue opened here that was deferred as it is a breaking change: https://github.com/patternfly/patternfly-next/issues/1599. 

I think this issue can be closed as a duplicate.
