### ISSUE TITLE
Update input group button styling to match CopyClipboard

### ISSUE THREAD

**Issue by mceledonia** [patternfly/patternfly-next#1926]
The button styling for copy to clipboard looks better than the input group button styling, and in my opinion these should be consistent. Despite being separate components, to the end user they are the same, a button attached to an input field.

Copy to clipboard styling (currently hovering over copy button, invisible pointer)
https://deploy-preview-1813--pf-next.netlify.com/components/ClipboardCopy/examples/
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/30935938/59456666-d9f0af00-8de4-11e9-8fba-e074a1ad306c.png">
As a side note here, I think changing to 2px/blue on hover looks better than the current black to blue change, which isn't very noticeable. Then in the case of the dropdown arrow, leaving the 2px blue style active. If we made this change it would apply to all buttons/inputs/dropdowns that use this style, something to consider.

Current input group button styling
https://deploy-preview-1813--pf-next.netlify.com/components/InputGroup/examples/
<img width="538" alt="image" src="https://user-images.githubusercontent.com/30935938/59456835-33f17480-8de5-11e9-8ba2-d2049ad85071.png">

How I think it should be:
![image](https://user-images.githubusercontent.com/30935938/59458468-7ec0bb80-8de8-11e9-9848-831335387fcc.png)

![image](https://user-images.githubusercontent.com/30935938/59458585-c34c5700-8de8-11e9-8205-4b3959973949.png)

CC @kybaker @mcarrano @rachael-phillips @LHinson @mcoker

**Comment by mcarrano** [comment]
I like your proposal @mceledonia . If others agree with this, then we should get it on the roadmap. Would this be a breaking change @mcoker ?

**Comment by mceledonia** [comment]
Also includes text buttons - much better.
![image](https://user-images.githubusercontent.com/30935938/59459169-268ab900-8dea-11e9-8e8c-fee13a828893.png)

**Comment by ajacobs21e** [comment]
@mceledonia please let me know when there's a final visual design decision and if I should make this update in the sketch library. Thanks!

**Comment by mceledonia** [comment]
I think there is consensus around the visual design, though I'm not sure if we should update the library before or after the changes are implemented.

**Comment by mcarrano** [comment]
It might be good to get a sense about when this can be implemented before we move on the Setch Library. @mcoker what's the scope of this? Is it an easy change? Is it breaking?

@LHinson @rachael-phillips any sense of where we can fit this on the roadmap?

**Comment by mcoker** [comment]
@mcarrano It's breaking in that we would be removing some variables in core that are currently used to style the component. I think we could position it in a way that isn't breaking though, by leaving the existing variables in place, and redefining them so they work with the new design, then follow up in a breaking change release and remove variables that are no longer necessary.

We share this button style between dropdown components and the input group. Could an approach be to add this style of button as a variation to the button component, then use that variation in context of the input group and dropdown component, and anywhere else we might introduce this in the future?

**Comment by rachael-phillips** [comment]
@kybaker @mceledonia what do you think this priority of this is?

**Comment by mcarrano** [comment]
@mceledonia There was a discussion today between myself, @kybaker and @mcoker that resulted in my opening this issue to change the border styling for the Input Group: https://github.com/patternfly/patternfly-next/issues/2175  Please take a look and let us know if you see any issue with that approach. I believe that Copy to Clipboard can remain as is.

**Comment by ssbarnea** [comment]
That is bit fun as in https://github.com/patternfly/patternfly-design/issues/956 I describe that I am unable to make the copycliboard work without extra border around it. Maybe someone can give me some hints? Thanks.
