### ISSUE TITLE
Custom cursors

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#1927]
Add custom cursors for behaviors like drag and drop or anywhere else that makes sense. This will be needed for supporting Topology views or other direct manipulation features.

**Comment by mcarrano** [comment]
@serenamarie125 @Veethika please add your requirements.

**Comment by rachael-phillips** [comment]
@serenamarie125 @Veethika would you mind adding your requirements here?

**Comment by mcarrano** [comment]
Going to close this out in favor of a newer issue here to address needs for drag and drop. https://github.com/patternfly/patternfly-next/issues/2277
