### ISSUE TITLE
light text on a dark background is hard to read

### ISSUE THREAD

**Issue by garrett** [patternfly/patternfly-next#194]
When using light text on a dark background, it's a lot harder to read than dark text on a light background. Browser font rendering doesn't help, either. This is especially pronounced on lighter weight fonts.

Simply adding `text-shadow: 0 0;` nudges Chrome and Firefox to render text in a more legible way.

This should be added to places where text is light, such as with certain buttons `.pf-is-primary` & `.pf-is-danger`. It should _not_ be added generally.

---

Demo of the difference @ https://codepen.io/garrett/pen/ELXreN

**Comment by garrett** [comment]
Screenshot:
![screenshot-2018-5-3 patternfly next text on a dark button](https://user-images.githubusercontent.com/10246/39588180-8dfd442e-4efb-11e8-8240-8ca474ca3ef3.png)
(...for odd some reason, GitHub seems to upscale this?)

**Comment by garrett** [comment]
Note: Buttons are the most prominent place to see this currently, but it would affect anything with a thin & light font with a dark background.

**Comment by matthewcarleton** [comment]
Thanks @garrett I think this will get resolved when we update the font that PF uses. If it's still an issue we can revisit this. Thanks!
