### ISSUE TITLE
Help icon in masthead

### ISSUE THREAD

**Issue by tiffanynolan** [patternfly/patternfly-next#1940]
Based on a conversation in the uxd-visual Slack channel today, it was decided that we should be using the open circle and question mark "help" icon in the masthead instead of the solid circle one. It should be the help icon from this page: https://www.patternfly.org/v4/design-guidelines/styles/icons

This issue is for updating the icon in any corresponding documentation, page examples, Sketch files, components, etc.

**Comment by tiffanynolan** [comment]
@mceledonia @kybaker FYI

**Comment by rachael-phillips** [comment]
@mcarrano making you aware. Is this something we plan to update in PF4?

**Comment by mcarrano** [comment]
@tiffanynolan @rachael-phillips I'm not aware the closed circle-question-mark is being used in any of our documentation or examples now. Other than the Sketch file, are you aware of other places that need to be changed/fixed?

**Comment by mcoker** [comment]
@mcarrano it's not in the masthead of any of our examples, but it is in an [Input Group example](https://pf4.patternfly.org/components/InputGroup/examples/)

**Comment by rachael-phillips** [comment]
@mceledonia what do you think? I know we opted for the exclamation point and circle for most use cases, but this feels very different. What would you recommend in this case?

**Comment by mcarrano** [comment]
It's unclear whether there is any follow up action here. I am going to close, but feel free to reopen if this is still a problem.
