### ISSUE TITLE
AppLauncher: pf-c-app-launcher__menu-item should be applicable to non-anchor element as well

### ISSUE THREAD

**Issue by jschuler** [patternfly/patternfly-next#1944]
in addition to `a` element for .pf-c-app-launcher__menu-item, make it work also with `button` and maybe `div` as well. In react, if consumer wants to use a routing library, it will often clash if it internally renders also to an anchor and thus it would be a doubly nested `a`.

**Comment by mcoker** [comment]
> In react, if consumer wants to use a routing library, it will often clash if it internally renders also to an anchor and thus it would be a doubly nested a.

@jschuler can you show an example of how that would render? Not sure I understand how you get a nested `a`, and what we need to do to support it. Curious if we need to show an example of this in the core workspace or not. Is the dropdown component currently capable of using a `div` as the menu item?

**Comment by jschuler** [comment]
Yes, so right now, the markup looks like this (for a section)
```
<section class="pf-c-app-launcher__group">
  <ul>
    <li>
      <a class="pf-c-app-launcher__menu-item" href="#">
        <span class="pf-c-app-launcher__menu-item-icon">
            <img src="/assets/images/pf-logo-small.svg" alt="">
        </span>
        <span class="pf-c-app-launcher__menu-item-text">
            Link not in group
        </span>
      </a>
    </li>
  </ul>
</section>
```

The content within the `.pf-c-app-launcher__menu-item-text` span should allow for an `<a>` tag to be placed there. That is because consumers in react often use a routing library (such as reach router), and when they pass the `Link` component into the container for `.pf-c-app-launcher__menu-item-text` it typically renders as an anchor.
Since doubly nested anchor tags are not legal (or having a button within an anchor tag), the `.pf-c-app-launcher__menu-item` container should work as a `div` as well. Then the markup could look like this:
```
<section class="pf-c-app-launcher__group">
  <ul>
    <li>
      <div class="pf-c-app-launcher__menu-item">
        <span class="pf-c-app-launcher__menu-item-icon">
            <img src="/assets/images/pf-logo-small.svg" alt="">
        </span>
        <span class="pf-c-app-launcher__menu-item-text">
            <a href="#">Link not in group</a>
        </span>
      </div>
    </li>
  </ul>
</section>
```

**Comment by jschuler** [comment]
Actually i think we can keep this structure and render the `<a class=".pf-c-app-launcher__menu-item">...</a>` from the passed in router Link component in react. Opened https://github.com/patternfly/patternfly-react/issues/2451 in favor of this issue. Thanks!

**Comment by christiemolloy** [comment]
Oh that makes sense now thanks for explaining that @jschuler ..  I'm going to reopen the issue because we still need the option for the user to add a button variation for the `pf-c-app-launcher__menu-item`
