### ISSUE TITLE
Link Buttons in the Footer of the Card

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-next#1945]
When I drop Link Buttons into the card footer they don't align with the rest of the content which IMO looks odd. Can we take a look into this?

<img width="918" alt="Screen Shot 2019-06-18 at 3 43 59 PM" src="https://user-images.githubusercontent.com/20118816/59714646-1e62bd00-91e0-11e9-95ac-e3b5a825b666.png">

**Comment by mcoker** [comment]
Could you use the inline variation?

**Comment by christiemolloy** [comment]
Yeh that does the job. I thought inline variations were to be used inline with other content, like in a sentence for example @mcoker

**Comment by mcoker** [comment]
@christiemolloy ah gotcha. Yeah they're just for any time you want it to display as inline. Not necessarily used inline with anything else. Another idea I had was to offer like an `pf-m-offset-[top/right/bottom/left]` that would move a button in whatever direction(s) to offset it's padding

**Comment by christiemolloy** [comment]
@mcoker I really like the offset idea because that would help the variation with the icon inside of it.

**Comment by mcoker** [comment]
Yah I remember you wanting to do that in some other context with the plain button.... can't remember where now :) If you have a use case, do you want to create an issue proposing the change and tag design?
