### ISSUE TITLE
Investigate the changes needed to build variations of our components where we're currently style a component in another component

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-next#1958]
Let's go through the components and see where we're overriding styles of a component in another component and see what would be involved in making the overriding styles a variation of the original component instead. And if it doesn't make sense to create a variation of the original component, if it makes sense just to create a new element in the component with the override styles instead.

If we're creating common variations of a component (making a smaller/larger button, for example, in multiple components), let's see if we can use the new variation in multiple contexts.

An example would be styling `.pf-c-form__helper-text` in the login component, `.pf-c-button` in the chip component, `.pf-c-button` in the about modal box, etc.

**Comment by jgiardino** [comment]
I'm not sure if this is related, but I'd like to raise an additional question of whether we can have a thing that is both a _component block element_ and a nested child component within the _component block_? Like can a button be both the Button component, and assigned a .block__element class from the wrapping component? And when do we make that distinction?

The scenario I'm thinking about is where most of the element styles are consistent with the child component css, but the element is also getting styles from the parent component, and those styles don't work outside the context of that parent component.

**Comment by mcoker** [comment]
Closing this, as we chose not to go this route.
