### ISSUE TITLE
Tool tip

### ISSUE THREAD

**Issue by yfrimanm** [patternfly/patternfly-next#1961]
I was looking at the PF4 guidelines for tooltips and wondered what was the reason for the text to be center aligned. I believe a left alignment is easier to handle, especially with 3 lines and more use cases.
https://www.patternfly.org/v4/documentation/core/components/tooltip
Thanks!

**Comment by rachael-phillips** [comment]
Hi @yfrimanm would you mind adding a description here of the issue? :D

**Comment by yfrimanm** [comment]
![image](https://user-images.githubusercontent.com/44577420/59975879-074c1280-95c6-11e9-8b9e-166ef664f07e.png)

**Comment by rachael-phillips** [comment]
I'm closing this issue and consolidated the comments here with #2131
