### ISSUE TITLE
Stepper visual design update

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-next#1970]
Proposed visual design update for a stepper.

The existing Wizard and in-progress Progressive Form designs both have a progress indicator / stepper that uses circle icons to show the state of each step. This proposal from Krystal Moore & @kybaker reduces the number of colors used for the states:

![image (1)](https://user-images.githubusercontent.com/6415742/59943265-cae6ae00-942f-11e9-8083-ff1af8ca4cbf.png)
Completed - #0066cc filled with #ffffff checkmark
Current / Active - #0066cc filled
Future - #d2d2d2 filled

@mcarrano @kybaker @mceledonia @LHinson @rachael-phillips It would be ideal if this change, if accepted, can be applied to both components simultaneously.

**Comment by mcarrano** [comment]
@mcoker if we were to update the Wizard with this styling, would that be a breaking change?

**Comment by mcoker** [comment]
@mcarrano I think it would be since introducing an icon wouldn't really work with the way we draw the step circle/number currently, so we would likely want to refactor that part of the wizard.

**Comment by rachael-phillips** [comment]
@mcarrano have you discussed next steps here at all?

**Comment by mcarrano** [comment]
@rachael-phillips we should take this up in the context of the work to implement the Progressive Form.

**Comment by mcarrano** [comment]
I've moved this over to the CSS/HTML backlog. @rachael-phillips @LHinson we should queue this up as a change to Wizard for the breaking change release.

@mcoker should we consider breaking the Stepper out into it's own component as it will be used for both Wizard and Progressive Form?

**Comment by ajacobs21e** [comment]
@matthewcarleton 
1. I would expect so for future steps. Would it make sense to have the numbers come back on hover for completed steps?
2. I'd expect the substeps to look the same as they do now for the wizard.
3. It looks like the current wizard does validation within the content area and doesn't have an error state on the stepper. Is that correct?

**Comment by matthewcarleton** [comment]
@ajacobs21e 
1. Ya that could be useful for hover/focus(for keyboard users). In dev it would be nice to consider how a screen reader interprets this as well. 
2. I might be missing something but this looks like it's changing how the parent steps look (a connecting vertical line). Just wondering if that line extends when the substeps are shown. Likely a question that will come up when this gets implemented. 
3. Yup it does have inline errors. There are cases where errors could occur after the user has moved on from the step. We see this in our use case in CNV where a virtual machine could have errors on creation and the user would need to navigate back to a step to make corrections. In that case it could be helpful to see the step highlighted. 

Another question :)
The Future step has a colour of #d2d2d2 which doesn't pass contrast requirements for accessibility. Has there been any discussion about this? I know we use this for disabled buttons but I'm not sure this future state would be the same as disabled. Has there been any discussion about this?

**Comment by mcarrano** [comment]
These are good questions @matthewcarleton . Right now this is on-hold as a breaking change for the Wizard. I think it requires more design consideration. @kybaker any thoughts?

**Comment by kybaker** [comment]
@mcarrano I agree with @matthewcarleton here. We will need to have answers for this design for it can move on to development.

**Comment by mcarrano** [comment]
Agree. I'm going to pull this back into the design backlog for further consideration. We should also consider in the context of progressive form user research. @sjcauffm FYI

**Comment by mcarrano** [comment]
See questions and issues noted here: https://github.com/patternfly/patternfly-next/issues/1242#issuecomment-541230229

**Comment by mcarrano** [comment]
Closing this until we have better definition on progressive form direction per https://github.com/patternfly/patternfly-design/issues/750
