### ISSUE TITLE
Update flex layout

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly-next#1979]
relates to: #1984 

The flex layout can be used to very simply `display: flex` and add simple spacing. This should be achievable without having to import all of the extra features. Let's look at a way to accomplish a lightweight base stylesheet and a modifier stylesheet that can be imported for more complex layouts.

**Comment by rachael-phillips** [comment]
Hi @mattnolting are you still working on this? If not, I'll unassign you for the time being :)

**Comment by mattnolting** [comment]
@rachael-phillips I'm currently working on the toolbar, but will move to this right after. I'd like to keep:)

**Comment by rachael-phillips** [comment]
Closing this in favor of #1984
