### ISSUE TITLE
Data List component 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#198]
The data list component enables the user to view a data set as a single column list. Each list row may display multiple elements including text, simple form elements, buttons, and/or dropdowns. Within a row, content may be either left aligned, right aligned, or have mixed alignment. Beyond that, the data list component is agnostic to the content placed within a row. In addition:

- List rows should optionally support expansion.
- The following states must be represented: hover, selected, expanded, collapsed)
- It should accommodate for infinite amount of expansions

List + Specs: https://drive.google.com/drive/u/1/folders/1cKk-HnEJFcB4w6sgl05NeLPVLRUUiNUW

Component lifecycle: 
- [x] Interaction design requirements 
- [x] Visuals 
- [x] First checkpoint complete and approved 
- [ ] CSS 

Contacts: 
- IxD @mcarrano 
- Visual @kybaker 
- CSS

**Comment by kybaker** [comment]
Lists + Specs

[Lists.zip](https://github.com/patternfly/patternfly-next/files/2036557/Lists.zip)

**Comment by mcarrano** [comment]
I have updated the title and requirements of this component per 5/29 meeting with @kybaker @matthewcarleton @mceledonia and @andresgalante

**Comment by mcarrano** [comment]
@mceledonia One additional requirement that occurs to me is that it should be possible to select one or more items in a list. Had you given any though to how selection would be represented? I don't necessarily think we need to include checkboxes for the simple list. Perhaps just toggle selection when clicking on a row? Let me know your thoughts.
