### ISSUE TITLE
Update padding for chip group label

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-next#1983]
@ajacobs21e pointed out that we have 12px of space between the chip group label and the chip group, which doesn't align with our spacer system. Lets update the padding-left on our chip-group label so that it is 0, and the total space between chip group label and the group is 8px.

cc: @gdoyle1 to update the symbol library.

<img width="631" alt="Screen Shot 2019-06-26 at 9 53 19 AM" src="https://user-images.githubusercontent.com/20118816/60185684-55485c80-97f8-11e9-8ff6-3401e4ddc17f.png">

**Comment by gdoyle1** [comment]
Thanks @christiemolloy ! Updated in symbol library
