### ISSUE TITLE
List-Table View demo 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#199]
Large data sets must be displayed in a usable, responsive format. This demo will show how lists and tables can be used to address a variety of use cases.

Requirements and interaction concepts: https://docs.google.com/document/d/1gyD2_Boy3gOHNl5KVo86274HTT_aqZMQz3coviJZIt8/edit?usp=sharing

Design Folder: https://drive.google.com/open?id=1cKk-HnEJFcB4w6sgl05NeLPVLRUUiNUW

In this issue, we will address what the requirements are for a content views as well as the visuals for that. Once these are completed, we will proceed with implementation.

- [x] Interaction design requirements 
- [x] Technical Feasibility conversation with design and react @mcarrano @mceledonia @dmiller9911 
- [ ] Visuals 
- [ ] First checkpoint complete and approved 
- [ ] CSS 
- [ ] React
- [ ] Second checkpoint complete and approved 

Contacts: 
- IxD @mcarrano 
- Visual @mceledonia 
- CSS

**Comment by LHinson** [comment]
@mcarrano will you loop back around with me after you meeting to determine if we need simple table issue.

**Comment by mcarrano** [comment]
I have an initial draft of requirements and interaction requirements here for review: https://docs.google.com/document/d/1gyD2_Boy3gOHNl5KVo86274HTT_aqZMQz3coviJZIt8/edit?usp=sharing  There are still a number of requirements that require further elaboration.

**Comment by LHinson** [comment]
@mcarrano React is interested in continuing to use https://reactabular.js.org/#/. Let's have a conversation about technical feasibility about how reactabular fulfills the requirements of this design and what might need to be customized.

**Comment by mcarrano** [comment]
Requirements and concept wireframes for data lists and data tables are outlined here: https://docs.google.com/presentation/d/1Ye5Vhj3AqQStZINtqUJ4Y8-mzKX3qBWRmlMQdP-lnwY/edit?usp=sharing.  More analysis is required on optional features including inline editing, row pinning, and Show, Hide, and Reordering table columns. Separate issues have been opened for these as noted above.

A technical feasibility review will be scheduled before handing off to visual design.

**Comment by mcarrano** [comment]
A technical feasibility review of current IxD proposal was held on 6/27 that included @andresgalante @dmiller9911 @priley86 @sjcox-rh and @kybaker .  While there are some concerns about the feasibility of the proposed responsive table approach from a CSS perspective, the general consensus was that the Reactabular component referenced above is flexible enough to accomodate this.

Agreed that next steps should be to move along to visual design and then have another feasibility review when high-fidelity mockups are available. We can then prototype and iterate as needed.

**Comment by LHinson** [comment]
This has been broken down into smaller issues: 
* Data List #198
* Data Table #513
