### ISSUE TITLE
Long texts in tooltip are truncated

### ISSUE THREAD

**Issue by karelhala** [patternfly/patternfly-next#2013]
When there is long text in tooltip it is runcated and not visible. Can we add `word-break: break-all;` in there?

**Comment by karelhala** [comment]
ping @rachael-phillips

**Comment by christiemolloy** [comment]
@karelhala are you referring to the Modalbox, because the title in there truncates and theres an issue I created for it #1825 (we can make it a higher priority), otherwise can you send me a screenshot of the tooltip text truncated?

**Comment by karelhala** [comment]
I am refering to tooltip overflow text if there are really long words (for instance URLs) background is red on purpose so you can see it.
![Screenshot from 2019-07-10 16-53-11](https://user-images.githubusercontent.com/3439771/60979574-3c30c700-a333-11e9-8335-e4831f3f4d78.png)

**Comment by christiemolloy** [comment]
Ah ok thank you! I'll start working on this!
