### ISSUE TITLE
New component for group of actions that get condensed

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-next#2041]
cc: @mattnolting @mcoker 

Can we create a component for a group of actions that condensed down into a dropdown with a menu, as a specific, functional component?

Looks like its used in the page, card, table, toolbar etc. component

**Comment by rachael-phillips** [comment]
@mattnolting @mcoker any thoughts here?

**Comment by mattnolting** [comment]
@rachael-phillips I'm including an experimental version of this as an abstracted component for #1528.

**Comment by mcoker** [comment]
@rachael-phillips yeah, this sounds good and super smart to me. @mattnolting went over the concept with @dlabaj and he's on board, too.

**Comment by rachael-phillips** [comment]
Ok great! Thanks. Do you think I should create an experimental label, as well to start adding?
