### ISSUE TITLE
Table grid responsive heading css 

### ISSUE THREAD

**Issue by priley86** [patternfly/patternfly-next#2045]
Seeing this today after experimenting again w/ the vanilla responsive table... thanks @mcoker for helping resolve... we should possibly remove that `width` specifier?
![detail-table](https://user-images.githubusercontent.com/4237045/61080731-b6c11b80-a3f3-11e9-9a0c-41f9589eddaf.gif)

**Comment by mcoker** [comment]
Looks like this is due to improperly scoped expandable table styles...

https://github.com/patternfly/patternfly-next/blob/master/src/patternfly/components/Table/table.scss#L221-L240

**Comment by spadgett** [comment]
cc @rhamilto

**Comment by priley86** [comment]
Closing, this ended up being an issue w/ downstream style overrides applied. Updated this in the PR notes of [2014](https://github.com/openshift/console/pull/2014).
