### ISSUE TITLE
Improvements to Type-Ahead Select

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#2052]
Based on project feedback, there are a couple of improvements/additions that are needed to the Type-Ahead Select component. These include:

* Add support for pagination, i.e. the ability to progressively disclose the contents of a long list. See https://github.com/patternfly/patternfly-react/issues/2445

* Add support for a "loading" state. See https://github.com/patternfly/patternfly-react/issues/2444

cc: @LHinson @rachael-phillips @tlabaj

**Comment by rachael-phillips** [comment]
Hi @mcarrano what priority do you think #2445 and #2444 are? Do you see these as critical enhancements?

**Comment by LHinson** [comment]
See issue here: https://github.com/patternfly/patternfly-react/issues/2531
Assuming the evaluation goes well, this might help address these additional needs. 

@rachael-phillips I'd like to prioritize getting the investigation of this component completed sooner than later.

**Comment by rachael-phillips** [comment]
Let's try to assign it out in sprint planning.

**Comment by mcarrano** [comment]
I don't think there's anything needed from design here. https://github.com/patternfly/patternfly-react/issues/2445 can be addressed directly in React, I believe.
