### ISSUE TITLE
PF4 website documentation clarification on Inline Alerts

### ISSUE THREAD

**Issue by Rohoover** [patternfly/patternfly-next#2057]
I was reading through the Inline Alert documentation at:
https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/alerts-and-notifications#inline-alerts

And noticed the icon is specified but not the color used, or the color of the type.

**Comment by mcoker** [comment]
Hey @Rohoover, this issue needs to be created in the [patternfly-org](https://github.com/patternfly/patternfly-org/issues/new) repo, would you mind closing this one and creating one there? Thanks!
