### ISSUE TITLE
Navigation System

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#207]
Introduce a navigation system that accommodates 3 levels. Use the the [latest high fidelity visual design and specs](https://drive.google.com/open?id=1GjlO9Bxluh_IO3dm45FSNAKHbqCnjarz) (notes are in comments) to implement. 

Prior interaction design information: 

- [Research outlining the pros and cons of different menu styles](https://patternfly-blog-patternfly.b9ad.pro-us-east-1.openshiftapps.com/navigation/going-vertical-a-look-at-multi-level-vertical-navigation-for-enterprise-applications/)
- [Set of collected requirements and product examples ](https://drive.google.com/open?id=16klf8Iep05T4uckRYjZLrAoaNQFhKC6mlVlx6OmMgd4)
- [Wireframes show how vertical nav is used in context](https://drive.google.com/open?id=1Q6T734QWVEQ-Gjw0jlRf1StxdK8_Z43C)
- [The latest high fidelity designs and specs](https://drive.google.com/open?id=1GjlO9Bxluh_IO3dm45FSNAKHbqCnjarz)

Component lifecycle: 
- [x] Interaction design requirements 
- [x] Visuals 
- [ ] First checkpoint complete and approved 
- [ ] CSS 
- [ ] React
- [ ] Second checkpoint complete and approved 

Contacts: 
- IxD @mcarrano 
- Visual @kybaker 
- CSS @mattnolting

**Comment by LHinson** [comment]
@mcarrano will you update the description with the latest wireframes that visuals are meant to work from?

**Comment by mcarrano** [comment]
I added that link @LHinson . This is also something that should probably have an interaction spec prior to implementation to clarify behaviors.

**Comment by mcarrano** [comment]
This deck includes various navigation options that support a variety of page layouts. Navigational elements include a horizontal primary nav, a multi-level vertical nav, and a teritiary horizontal nav. https://docs.google.com/presentation/d/1Ye5Vhj3AqQStZINtqUJ4Y8-mzKX3qBWRmlMQdP-lnwY/edit?usp=sharing

**Comment by LHinson** [comment]
Closing issue since #503 merged. Will follow up with @mattnolting @kybaker regarding next steps. 
Known to-dos: 
* Nav + page layout 
* Other to-do for nav?

**Comment by LHinson** [comment]
Closed this one prematurely. @mattnolting will update.

**Comment by LHinson** [comment]
#523 will be addressed in this issue as well.

**Comment by LHinson** [comment]
Closed by #600
