### ISSUE TITLE
Pagination with 0 items allows clickable next page button

### ISSUE THREAD

**Issue by johnsonm325** [patternfly/patternfly-next#2072]
We'd like to update the pagination component so that when you have 0 items, you cannot click the next page. It causes a new render and will get caught in an infinite loading state in our app.

![image](https://user-images.githubusercontent.com/15373136/61399351-fc6e6000-a89b-11e9-9d5e-e554271e9af7.png)

**Comment by mcoker** [comment]
Hey @johnsonm325, there should be no changes needed in the PatternFly 4 CSS to support this. Would you mind filing an issue in the [patternfly-react repo](https://github.com/patternfly/patternfly-react), and closing this one? 

https://github.com/patternfly/patternfly-react/issues/new

**Comment by johnsonm325** [comment]
Yes, sorry about that. Thanks! There is already an issue for it: https://github.com/patternfly/patternfly-react/issues/1949
