### ISSUE TITLE
Filter component in PF4

### ISSUE THREAD

**Issue by lucasponce** [patternfly/patternfly-next#2077]
Kiali uses PF3 Filter component [1] to implement one of the main features which requires multi-dimensional + multi-value filtering.

Patternfly 4 has some design guidelines in [2] but there is not an implementation for PF4 + React.

So, that limitation prevents us to run a full migration to PF4, as we should to implement a custom filter to have same features we had in PF3.

Our expectation is if PF4 could also provide a similar component that exists in PF3.

[1] https://github.com/patternfly/patternfly-react/tree/master/packages/patternfly-3/patternfly-react/src/components/Filter

[2] https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/filters

**Comment by rachael-phillips** [comment]
Hi Lucas - we will be working on a filter demo in months to come. Would this suffice for your needs? https://github.com/patternfly/patternfly-next/issues/457

**Comment by rachael-phillips** [comment]
Hey @lucasponce did you see my above comment?

**Comment by lucasponce** [comment]
Sorry @rachael-phillips, I was on PTO and I'm now catching up with the email.
"months" sound a little bit far from our needs.
Kiali started using PF3 as base framework, for OpenShift console integrations we introduced also PF4 as required to have visual compatibility.

But having PF3 and PF4 frameworks in the same project is adding an overhead and technical debt with custom adjustments on styles and others, so we need to move to a single framework (PF4).

The problem happens when PF4 doesn't have the same components as PF3, and the filter is one key for Kiali, as List views use multidimensional and multiple values.

Changing a key feature due a limitation in the PF4 sounds a regression to us, so that's why we would need a solution for this use case in PF4.

**Comment by rachael-phillips** [comment]
Hi @lucasponce we are looking into this and and will try to get back to him sometime next week about next steps

**Comment by LHinson** [comment]
@lucasponce I understand that you don't want to change a key feature. I believe we can achieve this either with the components seen today or adding a component to PatternFly. Let me follow up with you and team to ensure we are better aligned and discuss the options and path forward.

**Comment by lucasponce** [comment]
@LHinson what we need is an example in PF4 to achieve the same feature described in PF3.

https://patternfly-react.surge.sh/patternfly-3/index.html?selectedKind=patternfly-react%2FForms%20and%20Controls%2FFilter&selectedStory=Filter&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

The same example published in the PF3 works for us.

And this issue is open for more than 30 days, so, we need some action in PF4 about this.

**Comment by LHinson** [comment]
@lucasponce check out https://www.patternfly.org/v4/documentation/react/demos/filtertabledemo This should resolve this issue. If not, please re-open and specify what else is required. Thanks!

**Comment by lucasponce** [comment]
Thanks @LHinson we'll review it and try to migrate to this standard component within kiali in following sprints.
