### ISSUE TITLE
Charts - add color to black color range

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-next#2093]
We need `#ededed` in the black color range to support qualitative range bars in bullet charts.

cc @dlabrecq

**Comment by dlabrecq** [comment]
I'm not seeing this change reflected in the react-tokens package.

I pulled the latest source from PatternFly core and see the change in _chart-globals.scss; however, I don't see the change in patternfly-charts.sccs, which is what react-tokens uses.

<img width="499" alt="Screen Shot 2019-08-13 at 9 03 01 PM" src="https://user-images.githubusercontent.com/17481322/62987493-0f7a3e80-be0e-11e9-9597-06948297ffa4.png">

**Comment by dlabrecq** [comment]
I'm see the updated values in react-tokens
