### ISSUE TITLE
Modal component 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#210]
This is related to #104. There are two different types of modal, one for general modals as well as one for for the specific case of the About modal. In this issue, we will define the visual styling for the general modal as well as introduce the component implementation.

**Comment by mcarrano** [comment]
Existing design here for reference: http://www.patternfly.org/pattern-library/forms-and-controls/modal-overlay/#design

**Comment by mceledonia** [comment]
@srambach @andresgalante 

Here is the modal design with the reconsidered spacing structure. Let me know how it looks!

[Basic Modal.zip](https://github.com/patternfly/patternfly-next/files/2014039/Basic.Modal.zip)

**Comment by mceledonia** [comment]
@srambach @andresgalante 

Here is the latest design of the general modal which shows a couple different variations of body content. Also defined a regular size and a large size. Luckily the spec I gave you before was the perfect width so nothing has really changed there :) I also show an example of how copy/pasting something like forms would look.

Max Width - Regular: 560px
Max Width - Large: 1120px

Regular size max width was determined by finding an optimal line length sized for readability of paragraph text, then adding our already defined spacing system to form the rest of the modal. Large size is just 2x regular, and in my example I show a split view where the body section has 2 columns.

[General Modal.zip](https://github.com/patternfly/patternfly-next/files/2032551/General.Modal.zip)

**Comment by mcarrano** [comment]
Reviewed during PatternFly Design Sync on 5/24. 

* Want to allow for the possibility to scroll body of the modal; this may also affect the Box component.
* Also consider whether there should be a provision/example of a standard confirmation dialog with an icon. Reference https://github.com/patternfly/patternfly-design/issues/632 for current direction on confirmation or error dialogs.

**Comment by LHinson** [comment]
I'd like to discuss the scroll requirement at the next pf-design meeting scheduled for tomorrow. Let's proceed without the scroll within the modal for now.

**Comment by srambach** [comment]
@mceledonia, Is the modal full width on narrow screens? If so, what is the breakpoint at which the switch happens? The breakpoints available are 576, 768, 992, and 1200px.

**Comment by mceledonia** [comment]
Yes @srambach it would go full width on narrow screens, similar to the about modal. I'd think we should use the same breakpoint for that which I would say would be 768. Want to CC @kybaker on this to check that he agrees.

**Comment by srambach** [comment]
@mceledonia @kybaker Also, for the large split modal window, which says max width 1120px, what would you expect the behavior to be?

**Comment by dgutride** [comment]
Closed via #301
