### ISSUE TITLE
`.pf-c-app-launcher__group` results in dropdown item spacing that differs...

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-next#2102]
from app launcher's without `.pf-c-app-launcher__group` or standard dropdowns.  This results in dropdowns with an inconsistent appearance, which is especially noticeable when the app launcher sits alongside other dropdowns (as it does in OpenShift console).  We've applied a workaround with https://github.com/openshift/console/pull/2170.

App launcher without `.pf-c-app-launcher__group`
![Screen Shot 2019-07-25 at 9 35 33 AM](https://user-images.githubusercontent.com/895728/61879117-6f8d5d00-aec0-11e9-83e4-cd348d031121.png)

App launcher with `.pf-c-app-launcher__group` (note the extra spacing highlighted)
![Screen Shot 2019-07-25 at 9 35 16 AM](https://user-images.githubusercontent.com/895728/61879154-85028700-aec0-11e9-83cf-7f09746eda25.png)

cc: @spadgett, @jeff-phillips-18

**Comment by mcoker** [comment]
+ @kybaker this mimics the groups in the Dropdown component where, the first group in the menu has a top padding of `--pf-global--spacer--sm`, and any group that comes after that has a top padding of `--pf-global--spacer--md`.

It's also worth noting that the Select component doesn't define a top padding for the first group, but subsequent groups have a top padding of `--pf-global--spacer--sm`

Should we revisit this design?

**Comment by kybaker** [comment]
@mcoker Yeah we should revisit. It doesn't make sense why it wouldn't be the same in both the select and dropdown here. The only reason I could think of is to keep the content center aligned. We should explore this further.
