### ISSUE TITLE
All dropdown components do not change dropdown icon if switched between closed and expanded

### ISSUE THREAD

**Issue by SpyTec** [patternfly/patternfly-next#2112]
The Select, Dropdown, and Context Selector components does not change or rotate the dropdown icon as of right now. One exception is going on with Dropdown (direction up), but with that I'd expect the arrows to be switched - point up when closed, point down when expanded.

This is happening on both HTML and React versions.

In the Sketch files provided in design guidelines the dropdown components always display the arrow in the direction it will expand, and once expanded it displays the opposite direction.

I'd expect the arrow to always point away from the expanded dropdown, and always display the arrow towards where the dropdown will appear.

## Expected behaviour
1. Dropdown is closed and has arrow pointing down
1. User expands dropdown
1. Dropdown is open and has arrow pointing up

## Actual behaviour
1. Dropdown is closed and has arrow pointing down
1. User expands dropdown
1. Dropdown is open and has arrow pointing down

**Comment by rachael-phillips** [comment]
Hi @mcarrano making you aware of this one! Should we open this up in Core?

**Comment by rachael-phillips** [comment]
@SpyTec thanks for filing! How urgent is this change for you at this time?

**Comment by SpyTec** [comment]
Since this is a minor UX issue, it's very low on my list. Thanks for asking though

**Comment by rachael-phillips** [comment]
@mcoker fyi I'm adding a p3 here. Feel free to update if you think that this label priority should be different.

**Comment by mcarrano** [comment]
@SpyTec in my experience the current behavior is what I expect. The dropdown toggle typically does not change direction for dropdown menus as it would for an expansion panel. In this case the Sketch file is incorrect. Are you aware of any examples where a dropdown works as you suggest?

**Comment by SpyTec** [comment]
@mcarrano I do not think I have seen this in any PatternFly components except the Sketch file. Since there was a discrepancy I wanted to point it out

The only one that changes icon is the Dropdown (direction up)

**Comment by gdoyle1** [comment]
Removed this from the symbol library!

**Comment by mcarrano** [comment]
@SpyTec I checked with @gdoyle1  and the Sketch Library has been fixed. If you update, you should no longer see this. Thanks for bringing this to our attention. I will close.
