### ISSUE TITLE
Where do we put ApplicationLauncher in top navigation?

### ISSUE THREAD

**Issue by xtrasmal** [patternfly/patternfly-next#2113]
Where do I composition the ApplicationLauncher component? 
Right now I tried some ways, but I couldn't get a better result than what is shown in the picture below.

App.js:
-----

![image](https://user-images.githubusercontent.com/1174877/62125078-4f004100-b2cc-11e9-9420-1b400ceca7d5.png)

ApplicationLauncher.js
------

![image](https://user-images.githubusercontent.com/1174877/62125210-cdf57980-b2cc-11e9-9b57-54155fe86b5f.png)

Website:
--------
![image](https://user-images.githubusercontent.com/1174877/62125108-6b9c7900-b2cc-11e9-9a4d-cb849410e7a1.png)

**Comment by rachael-phillips** [comment]
@mcoker making you aware of this one.

**Comment by mcoker** [comment]
Hi @xtrasmal, have you seen the [react page demo](https://patternfly-react.surge.sh/patternfly-4/demos/pagelayout/) which shows you how to add icons to the toolbar in the masthead?

**Comment by xtrasmal** [comment]
Hi @mcoker, yes but it seems to drop off the screen as you can see in the image below.

Therefore I thought that the ApplicationLauncher is meant to be the icon version of the context selector(https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/navigation-system#context-selector) and tried it on the left side of the menu. 

![image](https://user-images.githubusercontent.com/1174877/62244110-05544b00-b3df-11e9-8c3b-f5022b34079c.png)

**Comment by mcoker** [comment]
@xtrasmal ah, you need to apply the `position` prop. `position=DropdownPosition.right` should position the menu so that the right edge of the menu is aligned with the right side of the toggle icon.

**Comment by xtrasmal** [comment]
awesome, that solved it. Thanks.
