### ISSUE TITLE
Investigate addition of a "definition tooltip" to PF

### ISSUE THREAD

**Issue by stacymcauliffe** [patternfly/patternfly-next#2122]
Should we add a new pattern to PF that enables users to provide contextual information in a word or phrase via a tooltip using an underline rather than an info icon?

https://docs.google.com/document/d/1GkPSkSXbb4V-wtX6SrJp7_buQgu6iBDnaS303SKRejQ/edit?usp=sharing

**Comment by rachael-phillips** [comment]
@stacymcauliffe @katierik is there a specific time in mind that you would like to see this brought into PatternFly?

**Comment by mcarrano** [comment]
Will close in favor of a more recent issue being addressed here: https://github.com/patternfly/patternfly-next/issues/2383  (Same ask)
