### ISSUE TITLE
Tooltip text alignment - allow different alignments

### ISSUE THREAD

**Issue by nlcwong** [patternfly/patternfly-next#2131]
Currently, the PF4 tooltip component's text is centered aligned.  Would like to request an enhancement to allow the customization of the text alignment to be either left or right as well as centered.

Use case:  It is possible the tooltip could be used to show more information of a status or data on a data table and might show multi-line data that would be easily scannable if they were either left or right aligned.

**Comment by rachael-phillips** [comment]
@nlcwong do you have a timeline or priorities around this you could provide me?

**Comment by nlcwong** [comment]
I guess this is a low hanging fruit type of priority because the Charting use case is more important for my product personally.

Also, it seems like this issue is a duplicate of #1961 issue that @yfrimanm had opened back in June!

**Comment by rachael-phillips** [comment]
@nlcwong if this is a duplicate do you mind if I close this one out. and we'll keep #1961 open?

**Comment by nlcwong** [comment]
I'm OK with that.  I just feel bad that i could find it before i opened up this one. Thx for following up!

**Comment by rachael-phillips** [comment]
Also referencing #1961 where Yifat had commented "I was looking at the PF4 guidelines for tooltips and wondered what was the reason for the text to be center aligned. I believe a left alignment is easier to handle, especially with 3 lines and more use cases.
https://www.patternfly.org/v4/documentation/core/components/tooltip
Thanks!"

**Comment by rachael-phillips** [comment]
@kybaker @mcarrano what are your thoughts on what we should bring in design wise from this issue?

**Comment by mcarrano** [comment]
I think we should just expose a setting to select either left or center alignment. No further design work needed IMO @rachael-phillips

**Comment by yfrimanm** [comment]
Thank you @mcarrano <https://github.com/mcarrano>, @rachael-phillips
<https://github.com/rachael-phillips>. I think it will be useful to have
both options.
