### ISSUE TITLE
Chart Tooltips Text alignment

### ISSUE THREAD

**Issue by nlcwong** [patternfly/patternfly-next#2134]
Currently, the charting tooltip component's text is centered aligned. Would like to request an enhancement to allow the customization of the text alignment to be either left or right as well as centered.

Use case: In the case where we have multiple data sets on a single (line, time series) chart, we would require a single tooltip to show all the data points' values that intersect at that same time. Each line would effectively be a data points' value.  It would ease scanning abilities if they were left or right aligned w/in the tooltip, rather than the default of center-aligned.

**Comment by dlabrecq** [comment]
Victory provides the ability to show multiple data points in a single tooltip, via the `voronoiDimension` property but the text is centered. This is similar to the existing PF4 tooltip component, which also centers text. 

If multiple lines of centered text is not desirable, data points can be shown one at a time. This is the default Victory behavior.

It may be possible to create our own custom tooltip, but that's not a trivial task. The Victory folks also stated that tooltip improvements will be available with their next major release.

**Comment by dlabrecq** [comment]
It may be possible to override the tooltip's `labelComponent` prop and use VictoryLabel's `textAnchor` to change the text position? Although, I have not tried this.

FYI, Victory provides the ability to show multiple data points in a single tooltip, via the voronoiDimension property, but the text is centered. This is similar to the existing PF4 tooltip component, which also centers text.

If multiple lines of centered text is not desirable, data points can be shown one at a time. This is the default Victory behavior.

We might consider creating a custom tooltip component, but that's not a trivial task. The Victory folks also stated that tooltip improvements will be available with their next major release.

**Comment by LHinson** [comment]
@dlabrecq FWIW, we have talked about this on the design side and will also introduce the ability to left align on the PF tooltip as well. 

Do you know what the victory improvements include? Think that the flexibility to left align will be included?

**Comment by dlabrecq** [comment]
No details regarding alignment, but that functionality may already be available? I suspect improvements will include the option to confine tooltips to the boundary of the chart, without relying on overflow.

**Comment by mcoker** [comment]
@dlabrecq just following up on this - do you know if this functionality was included in the latest victory update?

**Comment by dlabrecq** [comment]
No, nothing specifically for tooltip label alignment. However, users can override the text alignment via a custom theme. We use a custom theme in Cost management to define our own chart padding, so that would be an easy add.

FYI, I did prototype a few examples, but could not set this at the component level. I attempted to override Victory's `labelComponent` property in order to provide a new `textAnchor` value (i.e., 'start', 'end', etc.) for the tooltip. Also tried overriding the component's `style` prop to set `textAnchor` differently. 

I also encountered the same behavior with the raw Victory components (i.e., I was able to reproduce the same result on the Victory site). Seems like Victory is overriding label props with theme values -- there are many label props applied for tooltips, so that may be intentional?

**Comment by mcoker** [comment]
What do you think would be the best way to move forward with this? Maybe create a demo that shows how to apply a custom theme and align the tooltip to the left?

**Comment by dlabrecq** [comment]
I just put up a PR to demo how to create a custom theme. Perhaps we could include that `textAnchor` property there?

**Comment by LHinson** [comment]
Per @dlabrecq 

>you can left-align tooltips via a theme property...  I can implement that in Cost management -- close it. It was more a matter of figuring out how this could be achieved 

@gdoyle1 I'm closing this issue, I don't think there is any update for sketch but let's chat if you know something that I don't!
