### ISSUE TITLE
Minifier doesn't convert all grid values

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-next#2135]
A user reported a bug that as of v2.22.0, the page layout CSS has a bug if you're using `patternfly.min.css`. 

This is due to `grid-template-areas` for the page component being converted from:

`grid-template-areas: "sidebar" "main";`

to

`grid-template-areas: "c" "k";`

In v2.22.0, we added `--pf-c-page__main--GridArea: main;` and `grid-area: var(--pf-c-page__main--GridArea)` to the main element as a reference for which `grid-area` it should occupy. However, the minifier is not converting the value `main` in the `--pf-c-page__main--GridArea` variable to `k`, so the grid positioning is broken.

FWIW, I tried changing `--pf-c-page__main--GridArea: main;` to `--pf-c-page__main--GridArea: "main";` and it's the same problem.

cc @redallen @dgutride @seanforyou23

**Comment by dgutride** [comment]
closing this as it's now a documentation issue #2141
