### ISSUE TITLE
Select - add support for toggle icon

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-next#2152]
For use with the filter select

<img width="186" alt="Screen Shot 2019-08-15 at 2 27 05 PM" src="https://user-images.githubusercontent.com/35148959/63120852-c7bbfa00-bf68-11e9-9c80-982f46649c47.png">

**Comment by dlabrecq** [comment]
Here are a couple screen shots of what Boaz created in an attempt to match the PatternFly design. The icons are clearly outside the dropdown and input text.

<img width="560" alt="Screen Shot 2019-08-16 at 11 08 51 AM" src="https://user-images.githubusercontent.com/17481322/63177868-d06b0980-c016-11e9-98cd-6b891a491a5f.png">

This is another example of a form input field with a percentage. Some of our inputs use dollar symbols, instead.

<img width="486" alt="Screen Shot 2019-08-16 at 11 03 12 AM" src="https://user-images.githubusercontent.com/17481322/63177896-e2e54300-c016-11e9-9a0e-9d1a4ec25ea6.png">

**Comment by dlabrecq** [comment]
Will the text input be addressed along with this issue as well?

**Comment by mcoker** [comment]
@dlabrecq can you use the [input group component](https://patternfly-react.surge.sh/patternfly-4/components/inputgroup/) there?

**Comment by dlabrecq** [comment]
I'll defer that question to @boaz0, since he did the implementation

**Comment by boaz0** [comment]
Hi @mcoker 

Nope, I tried this using input group but I can see them as two separated items
![image](https://user-images.githubusercontent.com/2453279/63379061-2f74a980-c39c-11e9-82b2-83b8640b10fc.png)

Here's my code:

```js
      <React.Fragment>
        <InputGroup style={{width: '300px'}}>
          <TextInput/>
          <InputGroupText>%</InputGroupText>
         </InputGroup>
      </React.Fragment>
```

**Comment by mcoker** [comment]
@boaz0 @dlabrecq gotcha. This issue was just intended for the icon in the custom select. Re: the text input + search icon, I would like to open a separate issue and chat with design/IXD about the best way to implement as it's a bit more complicated. I'll tag the both of you in that issue.
