### ISSUE TITLE
Cannot specify custom padding in CardBody

### ISSUE THREAD

**Issue by rawagner** [patternfly/patternfly-next#2153]
I'd like specify custom padding for `CardBody`. Im passing new class such as `<CardBody className="co-dashboard-card__body">` which sets padding to 0, however that does not work because `pf-c-card__body` style has precedence over mine.

I solved by setting negative margins for now.

**Comment by andybraren** [comment]
Some related discussion in [this comment thread](https://github.com/openshift/console/pull/2360#discussion_r314257647).

**Comment by mcoker** [comment]
Hi @rawagner, if you're attempting to remove the padding from `.pf-c-card__body` by adding the class `.co-deshboard-card__body` and applying padding styles to your custom class, that should work so long as the override CSS you're applying comes after the patternfly CSS.

You can apply custom padding styles one of 2 ways - either using the `padding` property, or redefining the padding custom properties. I've demonstrated this in a codepen - https://codepen.io/mcoker/pen/WNewzGg

If that's not what you're attempting to do, can you show an example or provide more details?

**Comment by rawagner** [comment]
thanks for the codepen @mcoker . I took a closer look and the style which is causing the issue is actually coming from `@patternfly/react-styles/css/components/Card` - this one has always a precedence over mine and it also overrides the one coming from `@patternfly/patternfly/components/Card`. I have a similar issue with `Accordion` component https://github.com/patternfly/patternfly-react/issues/2694#issuecomment-522888136 . I will close this one and continue the discussion at `patternfly-react` repo
