### ISSUE TITLE
Update Table to allow bulk selection to be controlled externally

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#2162]
In order to implement the bulk selection design as defined in #1089, need to enable an option to allow bulk selection to be controlled from outside of the table rather that via the checkbox in the header. We should support both options. When externally controlled, the Table must be able to accept Select All and Select None actions via an external call as well as reporting it's selection status when users manually select individual rows.

**Comment by LHinson** [comment]
For this special case, skipping the core implementation in favor of https://github.com/patternfly/patternfly-react/issues/2910

@mcoker are you ok to close this one?

**Comment by mcoker** [comment]
@LHinson yep, I'm fine not having this demo in core in favor of having it on react.
