### ISSUE TITLE
Horizontal form label alignment

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-next#2167]
The labels in a horizontal form group layout have top-padding to align the label text with a form control element.

<img width="708" alt="Screen Shot 2019-08-20 at 9 36 29 AM" src="https://user-images.githubusercontent.com/35148959/63356793-01f11700-c32e-11e9-9d73-b42767cd8893.png">

This alignment doesn't work when there is something other than a form control element in the horizontal form group.

<img width="710" alt="Screen Shot 2019-08-20 at 9 35 17 AM" src="https://user-images.githubusercontent.com/35148959/63356871-20571280-c32e-11e9-997e-b71d134a0840.png">

Also if the label text is more than a single line, the alignment looks a little off, though I'd like to confirm with design if this is intended or not.

<img width="593" alt="Screen Shot 2019-08-20 at 9 38 57 AM" src="https://user-images.githubusercontent.com/35148959/63357042-6d3ae900-c32e-11e9-8e32-9ff3a2254311.png">

**Comment by jgiardino** [comment]
When adding examples that show a label for a group of checkboxes, we should also make sure that example uses semantic elements and provides labels in a way that is accessible. My last comment in this issue includes a suggestion for this: patternfly/patternfly-next#953
