### ISSUE TITLE
Clarify design for empty state in a table

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#2171]
Want to clarify design for placing an empty state within a table view. Ref React issue https://github.com/patternfly/patternfly-react/issues/1433

There are two use cases to consider:

1. What to display when a filter operation returns null results.

2. What to display when data is being loaded.

PatternFly 3 designs for reference: https://www.patternfly.org/v3/pattern-library/communication/loading-state/ and https://www.patternfly.org/v3/pattern-library/forms-and-controls/filter/#design

**Comment by lboehling** [comment]
Here are mocks for empty state in data table when there is a null query, and when the data is loading. https://marvelapp.com/cd929d4/screen/61020716 

I put a static image of the spinner in the loading empty state, but ideally this would be the animated spinner component when it is available. 

@mcarrano

**Comment by mcarrano** [comment]
@mcoker @kmcfaul This should be ready for implementation. See the Marvel prototype from @lboehling for designs. There is an existing React issue here: https://github.com/patternfly/patternfly-react/issues/1433  that was blocked by this, but will this need CSS work first? I think so.

I'm think that this should be added to the Table rather than the empty state component since the patterns are Table specific, but I'll defer to you guys for the best approach. 

@tlabaj FYI
