### ISSUE TITLE
Split button with title

### ISSUE THREAD

**Issue by karelhala** [patternfly/patternfly-next#2174]
We'd like to use input dropdown with some text next to checkbox to indicate how many items are selcted. Without this information users are lacking visual interpretation of how many items are selected on multiple pages.

![Screenshot from 2019-08-21 15-26-26](https://user-images.githubusercontent.com/3439771/63435981-2c26ff80-c428-11e9-9512-e5106903c877.png)

Eventually the DOM would look like
```HTML
<label class="pf-c-dropdown__toggle-check" for="toolbar-simple-example-split-button-dropdown-simple-example-check">
  <input type="checkbox" id="toolbar-simple-example-split-button-dropdown-simple-example-check" aria-label="Select all">
  <span>12 Selected</span>
</label>
```

**Comment by karelhala** [comment]
@rachael-phillips this is rahter urgent issue because have mocks and we can't continue without it. Also it should be low hanging fruit.

**Comment by rachael-phillips** [comment]
Hi @karelhala , this is in progress and currently being worked on here: https://github.com/patternfly/patternfly-next/issues/2161

**Comment by rachael-phillips** [comment]
Do you want to add any details to #2161? If not, do you mind if I close this issue in favor of #2161

**Comment by karelhala** [comment]
Oh I didn't noticed it. Thanks for pointing it out, I'll monitor #2161 and close this one!
