### ISSUE TITLE
Update Input Group styling and examples

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#2175]
In order to better support the implementation of components that are built on top of an Input Group, Filter and Touchspin are two that come to mind, propose to adjust our styling to remove the border enforced on button elements placed within an input group. This would allow us to create something more aligned with our design intent that looks like this:

<img width="473" alt="Screen Shot 2019-08-21 at 10 45 17 AM" src="https://user-images.githubusercontent.com/6619860/63458663-31cd1700-c421-11e9-8df1-0c938c5ea527.png">
 
Here usage of a ghost (borderless) button allows us to place either an icon or text button directly to the right of an input field without the heavy black border as in the current implementation:

<img width="464" alt="Screen Shot 2019-08-21 at 10 44 28 AM" src="https://user-images.githubusercontent.com/6619860/63458836-82447480-c421-11e9-8ef6-39bdd2d136a2.png">

As part of this we should revise the example in the Input Group page to use ghost buttons for actions following an input field (as opposed to primary, secondary, and tertiary buttons) as the preferred approach from a design standpoint. 

This should address the issues raised in https://github.com/patternfly/patternfly-next/issues/2172 and #362 with a single fix, I believe.

**Comment by mcarrano** [comment]
@rachael-phillips @LHinson I created this issue following a discussion with @mcoker and @kybaker about Input Group styling. We believe this addresses issues that have been raised about the use of input groups in toolbars and forms. I should be a minor change with limited to no risk. @mcoker can you comment further on what this will entail?

**Comment by ajacobs21e** [comment]
FYI @cshinn for the sketch library

**Comment by mceledonia** [comment]
@mcarrano @kybaker looks good to me!

**Comment by mcoker** [comment]
@mcarrano I just double checked in the input group component, and this is currently supported by using a plain button variation in the input group. So for this update, we should only need to update the examples in the workspace, then at a later date during a breaking change release, remove the input group CSS that creates a square border-radius where a form control element and a button meet.

**Comment by mcarrano** [comment]
@mceledonia @mcoker @christiemolloy @maryshak1996 and I met today to review this issue and decide on a consistent approach that can be used across different use cases requiring an input group including a search field, copy to clipboard, and touchspin. We agreed that the styling recommended by @mceledonia in https://github.com/patternfly/patternfly-next/issues/1926 makes the most sense to move forward with as it provides the desired grouping without the heavy button boarder as is currently present.

Examples for Input Group will be updated using this as a unique styling of the Button component to be used for input groups, only.

**Comment by mcoker** [comment]
Closing per #1926
