### ISSUE TITLE
Button alignment in data toolbar

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-next#2179]
See my comment here: https://github.com/patternfly/patternfly-next/pull/2119#discussion_r315355517

I think this could be worth investigating as it seems like we could see other scenarios where the `pf-c-button.pf-m-link` button doesn't get left aligned b/c the spacing makes it look misaligned. 
<img width="493" alt="Screen Shot 2019-08-22 at 10 55 08 AM" src="https://user-images.githubusercontent.com/287880/63520608-5f6e9a80-c4cb-11e9-878b-ba38013118eb.png">

**Comment by mcoker** [comment]
Hey @matthewcarleton I talked to @kybaker and @mcarrano and they suggested using the inline button variation for this.
