### ISSUE TITLE
Request for demo - form validation/instruction

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-next#2183]
When using a form control that includes some syntax instruction, that text is supposed to be placed below the form control. When validation errors are thrown, our current forms solution (based on formik) swaps the instruction text with the validation error. This has been seen as problematic, and when looking to the patternfly [demos](https://pf4.patternfly.org/demos/BasicForms/examples/) for a tiebreaker recommendation on how to treat this, I don't find any examples that show both field-level instruction and validation at the same time.

Should the validation error be shown above the form control? If it replaces the instruction, users seem to get confused as to what a correct value could be. It's basically the same issue as we had when relying on placeholder text. Users have to delete their value to get the instruction back, then attempt to get it right again.

Can someone help me understand the UX recommendation here? Also is there any way we can add this to the form examples so the solution is there for future reference? At the very least it could make a good post on the forum. I think we've come to conclusion on this before in the past, but I struggle to remember where we landed, and there's no record of it.

Thanks!

<img src="http://g.recordit.co/gEkB2OifCF.gif" alt="Example of confusing behavior">

**Comment by mcarrano** [comment]
@seanforyou23 The intent is for the error message to replace the instruction. Error messages should not only flag the problem but provide useful instruction about for to fix it so the user is not left wondering what to do. I this particular case, I would recommend keeping the original instructional text, but changing it to red and appending the test "Condition is required" at the end. It may even be that the error text is not required and simply changing the instructional text to red with a red border for the field is enough of a clue that the field cannot be left empty.

Please see the appropriate field styling for reflecting an error. I could not tell from looking at this whether you are working with PF3 or PF4 as the field styling is different. Guidance for PF4 can be found here: https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/forms

Does that help? I do agree that a demo would help to better illustrate this.

**Comment by seanforyou23** [comment]
@mcarrano it helps a lot! Yea we're actually in between PF3 and PF4 so there's a little of both in there :) We're making our way toward PF4 though so looking to make sure we have the interaction pattern down correctly, even if some of the aesthetic styles remain looking like PF3 for a little while. Thank you!

**Comment by mcarrano** [comment]
Closing per discussion above.
