### ISSUE TITLE
Inconsistency between data lists and tables

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-next#2185]
Data lists and table have some differences that should probably be the same - eg: borders and border colors

_Differences illustrated in these slides and document:_ https://docs.google.com/presentation/d/1fLp8424_ykHEyS5K2kkGsfklE3tfIQCBy0eTu1G19go/edit?usp=sharing & https://docs.google.com/spreadsheets/d/1vqv6I00urK2YIyKZB320lUcYAhy54GVnfjXyqQgE2PA/edit?usp=sharing

**Symbol wide**
In multiples instance both in Desktop and Mobile view, border colors for data list rows are #D2D2D2, but #EDEDED for tables

**Expandable table**
1. Line between expandable row and content row is EDEDED in one, and D2D2D2 in the other
2. Data lists have a line at the bottom of the content row (both with padding and not), where as table content rows don’t have a border line at the bottom

**Comment by mcoker** [comment]
@kybaker
