### ISSUE TITLE
Full page previews on surge previews strip query strings from URL

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-next#2187]
When you click on a full-page preview (for example, any of the page demos here - https://patternfly-next-pr-2186.surge.sh/demos/Page/examples/), the query string is removed from the URL so you end up on `/examples-full/`, which lists all of the examples for that demo.

**Comment by redallen** [comment]
This has to do with the way Surge's http server works. Doing client-side rendering based on a query string is a little suspect to begin with. I never got proper per-example full screen pages working for patternfly-react, so I'll start there and then bring MDX and the config for fullscreen examples here to patternfly-next.

Related: https://github.com/patternfly/patternfly-react/issues/2775
