### ISSUE TITLE
Catalog component

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-next#2188]
After talking with @kybaker, Susan Buenafe, and @bmignano on 8/23, I learned of the needs of both OpenShift and Ansible for a catalog component. Ansible will be demoing this feature on 9/24 or 9/25.

Here is Susan's design in progress: https://marvelapp.com/4dijjai/screen/60302754
And Brie's designs in progress: 
![image](https://user-images.githubusercontent.com/40275806/63692477-c0ee7c00-c7df-11e9-82da-e1ac80e1b686.png)

The description of this feature is that it is a catalog of filters that lives out side of the main or side navigation to expose the filters available to the user. @mcoker and @kybaker can adapt the wizard to create this design. We have part of the code, and we would just need to turn it into a component.

**Comment by beanh66** [comment]
This is the latest designs, right @kybaker @bmignano?  https://marvelapp.com/cc94cbh/screen/60777676

**Comment by rachael-phillips** [comment]
I'm closing this issue because it is redundant to https://github.com/patternfly/patternfly-next/issues/2213
