### ISSUE TITLE
Allow Optional Header in Wizard Component

### ISSUE THREAD

**Issue by mmocniak-rh** [patternfly/patternfly-next#2191]
Some workflows do not require the header to display on every step of the wizard. Since each step dynamically changes what displays in the primary section of the wizard, the header does not always need to be present.

This issue is being logged to make allow for an option to disable the header in the wizard component.

**Comment by mcarrano** [comment]
@mmocniak-rh I feel like the Wizard title is important for the reasons @jeperry stated. It reinforces that intended outcome of the wizard. I agree that our design guidelines could be better and we should clarify what these fields are used for and how to reflect the current step as @jeperry suggests. I don't want to make the header optional, but I do have one question for you @mcoker . Description is optional, I believe. If a consumer of this chooses not to add a description, is the space collapsed or does that space just remain blank? If the later, we might want to make a change to reduce the space that the header consumes. Thoughts?

**Comment by mcoker** [comment]
@mcarrano since it's optional, we balance out the layout when the description isn't present.

<img width="1117" alt="Screen Shot 2019-08-30 at 11 45 01 AM" src="https://user-images.githubusercontent.com/35148959/64037601-9e2fd080-cb1b-11e9-83a9-79f79581d80b.png">

**Comment by mcarrano** [comment]
That's great @mcoker .

**Comment by mcarrano** [comment]
@mmocniak-rh thanks for submitting this, but after discussion with @mcoker and @kybaker we have determined that the Wizard header should not be optional and this issue will be closed. It is important that the Wizard always have a title to identify the action that they will take. Being able to hide the description as shown above helps compress the space required. Also note that the height and width of the wizard modal can be adjusted if you need to create more space for content.

A related documentation issue has been created to provide better guidance about this (https://github.com/patternfly/patternfly-org/issues/1454).
