### ISSUE TITLE
Modal footer buttons overflow

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-next#2207]
https://github.com/patternfly/patternfly-react/issues/2800

cc @mcarrano any concern with allowing the actions in the footer to wrap by default?

**Comment by mcarrano** [comment]
Yeah, I guess that makes sense @mcoker

**Comment by mcoker** [comment]
Closing in favor of https://github.com/patternfly/patternfly-next/issues/2021, as that layout should take care of this.
