### ISSUE TITLE
Figure out demo layout in workspace

### ISSUE THREAD

**Issue by dgutride** [patternfly/patternfly-next#221]
Currently - our demo layout is just a full page with no navigation back/forward into the regular workspace.  It's a bit jarring and not intuitive.

Figure out what should be done and implement in the workspace

**Comment by mcarrano** [comment]
@dgutride Demos (if we continue to call them that) will need a similar level of documentation as Components. For example, if the Login Page is presented as a demo, there may be a significant amount of documentation that is required to provide guidance on things like authentication, how to handle errors, and various options available, etc. Today that's captured on our website here: http://www.patternfly.org/pattern-library/application-framework/login-page/#overview  My take is that we need a layout similar to our component pages that allows for launching the full screen demo in a new window and also allows for users to get the code for that demo page and provides usage guidelines.

Would be glad to help by wireframing something out.

**Comment by dgutride** [comment]
Closed via https://github.com/patternfly/patternfly-next/pull/226
