### ISSUE TITLE
Design input needed for closing chip group 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#2225]
https://github.com/patternfly/patternfly-react/issues/2867

**Comment by mcarrano** [comment]
@kybaker @mceledonia @gdoyle1 @bmignano I wanted to get some opinions about this. If you look at the design guidelines here, https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/filters#filter-chips, you will see that a chip group has a remove (x) button in addition to each chip having a remove button. Plus there is a 'Clear filters' action to remove all chips and groups. The implementation does not include a remove button for the chip group which resulted in this issue being filed.

IMO, we should simplify this design and either be able to remove individual chips (i.e. filters) or clear all filters. There would be no removal at the group level. Does anyone have a problem with that or have an alternate suggestion? I feel like the current design is just too complex. If we go that route, the implementation would remain unchanged, but the Sketch mockups and the documentation would need to change.

**Comment by ajacobs21e** [comment]
I wasn't aware of this until I saw the Sketch update come through. A use case on the Portal is to be able to select a product and then one or more versions for that product. That selection is displayed with the chip group as the product and the versions as individual chips. In this use case it's useful to be able to clear the whole product (and the selected versions) in one click.  Is it possible for that to be an option in the implementation?
If not, @mceledonia and/or @kybaker can we chat about other ways to meet my use case please?

**Comment by mcarrano** [comment]
@ajacobs21e Is it reasonable to add a "Clear all" or something like that outside the chip group as we do for the toolbar or do you really need the ability to clear one product at a time (from multiple products selected)?  If so, we could add this as an optional variant. In a meeting today with @mceledonia @bmignano @gdoyle1 and I we did decide to remove this from the filter bar as it adds unnecessary complexity.  Is your use case for filtering or something else?

**Comment by ajacobs21e** [comment]
@mcarrano I would like a clear all option but yes also a way to clear product by product. Yes it's a filtering use case.

**Comment by ajacobs21e** [comment]
I'm open to looking into other solutions for showing product & version filters. I have this other issue open for RHDDS. The use case of selecting product + version will come up a lot on the Portal, rh.com, and apps like Subscription Management or Insights. RHDDS might be the right place to solve this but then that would be contributed back to PF4.
https://github.com/patternfly/patternfly-unified-design-kit/issues/71

**Comment by mcarrano** [comment]
@ajacobs21e Thanks for the feedback. Given this, what I recommend is that we support a close button on a chip group as an optional feature. By default I still feel like we do not need the close button and we will need to open an issue to add this feature to the current implementation. IMO this does not need to be a blocker for current work on a filter demo, but is something we can add and update our design docs accordingly. @gdoyle1 this does represent a change from what we discussed yesterday relative to the Design Kit. Can we keep the chip group with a Close but also add a new variation to not have the Close button?

@LHinson let me know if you see any problems with this approach. I can add issues for implementing a ChipGroup variant with a close button that we can roadmap as a future add.

**Comment by gdoyle1** [comment]
@mcarrano @ajacobs21e Happy to bring back the variation with the close button!

**Comment by ajacobs21e** [comment]
Thank you Matt Gina and Leslie! That will help a lot to have it as an optional variant.

**Comment by mcarrano** [comment]
@gdoyle1 Can you just attach a spec for this with the proper spacing so we can hand off to CSS for implementation? Should simply be what we have in the Sketch file. Thanks!

**Comment by gdoyle1** [comment]
@mcarrano Here you go! 
![Expanded dismissible Chip Groups ](https://user-images.githubusercontent.com/30870144/65781548-cb22d380-e119-11e9-9022-8e7e259adc99.png)

**Comment by mcarrano** [comment]
Thanks, @gdoyle1 !

**Comment by mcarrano** [comment]
Design complete
