### ISSUE TITLE
Clipboard copy: Add option/prop to expanded variants to expand upon load

### ISSUE THREAD

**Issue by tiffanynolan** [patternfly/patternfly-next#2228]
I have a few use cases within both the Mobile Developer Services app and the Solution Explorer (for RHMI) where we would like to be able to show the contents of the clipboard copy by default instead of making the user interact to expand it. Could a prop be added to select to have this expanded by default?

cc: @christiemolloy @jessiehuff @dlabaj

**Comment by christiemolloy** [comment]
Issue in MDC: https://github.com/aerogear/mobile-developer-console/issues/406

**Comment by christiemolloy** [comment]
@rachael-phillips could we put this on the roadmap. We need it within the next two weeks in MDC and it would be a lot quicker to update in pf-react. I can also take it on.

**Comment by christiemolloy** [comment]
Closing this as an issue was created in React ^
