### ISSUE TITLE
Fix focasble border in Data Toolbar

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-next#2236]
Saw this occuring in https://github.com/patternfly/patternfly-next/pull/2229

<img width="478" alt="Screen Shot 2019-09-09 at 2 02 06 PM" src="https://user-images.githubusercontent.com/20118816/64555012-7a823c80-d30a-11e9-93fb-c87f9dfd694b.png">

**Comment by mattnolting** [comment]
relates to : #2184

**Comment by christiemolloy** [comment]
thanks Matt ^ ill close this
