### ISSUE TITLE
Provide webpack example/guidance to help users exclude unused fonts

### ISSUE THREAD

**Issue by dgutride** [patternfly/patternfly-next#2245]
Based on the comment here: https://github.com/patternfly/patternfly-next/pull/1813#issuecomment-528864618 by @rhamilto, we'd like to investigate either adding build guidance or a webpack example in the seed that would demonstrate how to make sure that unused fonts are not included in the final distribution when users are consuming PatternFly

**Comment by redallen** [comment]
I'll talk to @rhamilto and take a look.

**Comment by redallen** [comment]
Added a wiki page as well: https://github.com/patternfly/patternfly-next/wiki/Overpass-vs-Red-Hat-Font
