### ISSUE TITLE
Javascript doesn't work in the demos

### ISSUE THREAD

**Issue by valleedelisle** [patternfly/patternfly-next#2250]
Trying to get examples of how to implement JS for various components, that would be great to have functional demo, imho.

**Comment by mcoker** [comment]
Hey @valleedelisle the patternfly-next repo is just for the core html and CSS code to build PatternFly, so there is no javascript. The https://github.com/patternfly/patternfly-react repo is where we build out our components using the react framework. You can find fully functional react  component examples and demos here - https://www.patternfly.org/v4/documentation/react/components/aboutmodal

**Comment by valleedelisle** [comment]
@mcoker Thanks I get this, I was hoping that we have a react-less standalone version of the javascript required. I'm not sure I understand the point of having the standalone HTML version demo'ed when nothing works. It leaves the impression that we can use patternfly without react when it fact, we can't?

**Comment by mcoker** [comment]
@valleedelisle ah gotcha. These demos are primarily to illustrate how to use the core components that don't require javascript, and to provide blueprints for how to build the interactive components and tie them all together in javascript. You could use these demos to create components in your own language/framework if you'd like. The only framework PatternFly supports is React, so [patternfly/patternfly-react](https://github.com/patternfly/patternfly-react) is where the javascript version of our demos live.

**Comment by valleedelisle** [comment]
All right, thanks for the clarification. We can either close this issue or convert it to an RFE?

**Comment by mcoker** [comment]
No problem! We can leave it closed as there are no plans to introduce PatternFly components in vanilla JS or another framework at this time.

**Comment by dwasyl** [comment]
@mcoker Just stumbled across this issue and it would be handy if this was noted up front somewhere on the Core docs side of things. There was quite a bit about beginning a site in vanilla HTML/JS for v3, and to me it just seemed as if I couldn't find it for v4 (rather than it was by design not available).

**Comment by mcoker** [comment]
@dwasyl thanks for the feedback, I understand how this can be confusing, especially coming from PatternFly 3. We have added this topic to our roadmap of changes coming to the patternfly.org website.
