### ISSUE TITLE
Master-Detail design pattern 

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-next#2256]
A few apps in cloud.redhat.com are looking at a master-detail style design pattern. This is a pattern that needs to be defined with a focus on accessibility & responsiveness. 

![master-detail](https://user-images.githubusercontent.com/23172038/64791776-33808b00-d546-11e9-9355-768eb714acec.jpg)

**Comment by rachael-phillips** [comment]
Thanks for filing @katierik ! @LHinson is going to touch base with you about this in the next planning meeting you have.

**Comment by mcarrano** [comment]
@lboehling I've assigned this issue to you as we discussed. Let's continue to gather requirements and make sure we are covering all potential use cases. At a minimum, we need to consider use of either a list, table, or card view as the master.

**Comment by sbuenafe-rh** [comment]
@mcarrano mentioned that I should add in my other use case for my documentation screen. Currently, we are using the navigation component in the light theme for the left panel. The only issue is that it would be nice to have tighter spacing between the menu items. This design could potentially use the master detail pattern. 

![Docs Copy](https://user-images.githubusercontent.com/43220036/67430829-0e555280-f5b1-11e9-8f0b-937784a9b832.png)

**Comment by mcarrano** [comment]
@lboehling @mceledonia @mcoker and I met today to discuss the scope and requirements for this design issue to determine what we should deliver. Here are some assertions we can make:

* By master-detail, we mean a side-by-side view where the master lives on the left and the detail lives on the right. There may be other forms of master-detail (e.g. top-bottom), but those will not be considered here. 

* The master can be anything that presents a summary view of a set of content, i.e. a vertical menu, a list, a table, a tree, or a card grid. The details are presented in a drawer on the right where the contest of the drawer can be entirely consumer defined.

* We must consider responsiveness. How does this master-detail view behave on small devices?

* We must consider how functions like searching, sorting, global actions, and pagination would be supported to manipulate the data set that is displayed in the master.

@lboehling will create some layout ideas to address these requirements. Most likely we will want to create PatternFly demos to show working examples.  Let me know if I missed anything above.

**Comment by deernano** [comment]
Hi, I would like to share with you the Master /Details examples that are used in Integration products.
Still working in progress, currently, AMQ, Fuse and Apicurio are ready, need to spend some time finding 3scale screenshots.
[](https://docs.google.com/document/d/1OsAeRYf5aH7JZkJCrO0uLMlcScIJXB_inuRiIcv2jbI/edit?usp=sharing)
Thank you!

**Comment by mceledonia** [comment]
Another thing to consider here is a condensed modifier for the new tabs which decreases padding for tighter spaces such as dashboard cards, side panels, and mobile breakpoints.

**Comment by lboehling** [comment]
Here are content, layout, and interaction guidelines for the master-detail pattern:
[Guidelines](https://docs.google.com/document/d/1kzGP37tb-lf7sVz43xBnnoYEWPsQN4GvNvffebxiuTE/edit#) and Visuals: https://marvelapp.com/9iefh5b/screen/63567619

@mcoker and I met today to discuss implementation. For the demo, we will use the existing drawer component but add enhancements to it. 

Enhancements will include the ability to…
- add/remove the padding from drawer panel and content
- pass widths/define specific widths in react
- define width of the drawer in relation to content
- have fluid resizing of drawer/content
- add variations to remove drop shadow on left of drawer, and to use a vertical divider between drawer panel and content
- add variations to display the drawer on the left of the content. 

We may also want to consider maintaining a version of the light-themed simple nav to be offered as a compact/simple list component in the master pane. 

@mcarrano @rachael-phillips @LHinson

**Comment by mcarrano** [comment]
This all looks great @lboehling ! 

@mcoker do you want us to open new core issues for these updates? Looks like we require:

* Updates to the Drawer component as above
* Master-pane list as a variation of the vertical nav
* Master-detail demo that implements Lucia's layouts in a page

**Comment by mcarrano** [comment]
After seeing @lboehling 's preso today, looks like we will also want a selectable state for a card.

**Comment by mcarrano** [comment]
Created the following issues for core implementation:

#2467 - Drawer updates
#2468 - Simple list component
#2470 - Add hover and select state to Card
#2471 - Master-Detail demo

Also created https://github.com/patternfly/patternfly-org/issues/1544 to introduce mater-detail design guidelines. Will close this design issue. Thanks for all your work on this @lboehling !
