### ISSUE TITLE
Enhancements to font 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#2268]
- What's our recommendation for fall back system font? 
- Requirement to have a monospaced font option for the Red Hat font family. 

Specific request from: 
Cockpit 
Integration 
Integreatly 
cloud.services.com

**Comment by LHinson** [comment]
Copying from slack convo regarding the fallback options: 

> What is our current font stack?
> 
> If you’re using overpass, it’s https://github.com/patternfly/patternfly-next/blob/master/src/patternfly/sass-utilities/scss-variables.scss#L187-L189
> 
> if you’ve opted in to the new font, it’s https://github.com/patternfly/patternfly-next/blob/master/src/patternfly/sass-utilities/scss-variables.scss#L190-L191

**Comment by rachael-phillips** [comment]
Hi @mcoker we would like to open a CSS issue for the Core work once the clarity of this design is resolved. Did you and Kyle meet about implementation at all before he left?

**Comment by LHinson** [comment]
![image](https://user-images.githubusercontent.com/7924406/67039561-98a04100-f0ef-11e9-9c43-16760412053e.png)

**Comment by mcoker** [comment]
@rachael-phillips @LHinson - @kybaker, @mceledonia and I just talked about what mono stack we offer currently and Kyle had a suggestion he wanted to explore more for updating the stack.

If the stack we want to provide is [Liberation Mono](https://github.com/patternfly/patternfly-next/issues/2268#issuecomment-543317854), I can go ahead and add support for this.
