### ISSUE TITLE
Gather requirements for the date and time picker to help inform direction 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#2291]
Understand product technical product requirements for date and time picker to help drive the direction for a spike, 
related to https://github.com/patternfly/patternfly-react/issues/2947

**Comment by dgutride** [comment]
Added technical requirements here:  https://docs.google.com/document/d/1HCUTWCk3It3pIRYFLD83H-wThA10yUs7KLJM3fU5Q7Y/edit?usp=sharing

**Comment by mcarrano** [comment]
I reviewed the requirements document above and don't see any disconnects from a design standpoint.  The Time Zone selector can be optional and I would be even fine if that's considered as a separate element. I assume that in most cases it will not be needed. 

This document summarizes the functional requirements based on our design approach: https://docs.google.com/document/d/1hlS0R1l7gnoe-YDu1SEHpUSrf6WMuZPejR5AwYr0a20/edit?usp=sharing.

**Comment by rachael-phillips** [comment]
I'm closing this because all of our requirements have been covered. We will open a subsequent issue to begin development.
