### ISSUE TITLE
Responsive behavior of filter chips

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#2301]
Revisit how filter chips in the second row of a toolbar should respond when the viewport shrinks. In the current React implementation, ChipGroups will just wrap below the toolbar. While this approach works, would be good to identify an approach that uses less vertical space.

Design investigation needed.

**Comment by mcarrano** [comment]
@rachael-phillips @LHinson I opened this following a review of DataToolbar behavior with @nicolethoen We agreed that this is something that should be refined in a future release. Can we get this into the next milestone (or soon after)? I don't see this as a large effort.

**Comment by rachael-phillips** [comment]
@mcarrano I'll put it on the list to discuss for planning

**Comment by mcarrano** [comment]
This document includes an analysis of current differences between core and React implementations and a proposed path forward: https://docs.google.com/document/d/1sJrXtLaFtazsfQ1uhmBakP6mCFjCnjFTka589DiEe0Y/edit?usp=sharing

**Comment by mcarrano** [comment]
There is a PR up here that includes these changes: https://github.com/patternfly/patternfly-next/pull/2342
