### ISSUE TITLE
Spike: Design review of empty state usage

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#2302]
There is a need for improved guidelines and/or examples to guide usage of empty state patterns. See summary here submitted by Cloud Mgmt: https://marvelapp.com/7db34h9/screen/61596960

**Comment by mcarrano** [comment]
@mmenestr can you post the slides from last week's meeting here?

**Comment by mmenestr** [comment]
@mcarrano Here it is: [](https://docs.google.com/presentation/d/1E7TrgXnbmuLaL0MGtYRglgcfd_AT_Mt_gA6y-k5f7Nc/edit?usp=sharing)

**Comment by mmenestr** [comment]
@mcarrano Here is the link! https://docs.google.com/presentation/d/1E7TrgXnbmuLaL0MGtYRglgcfd_AT_Mt_gA6y-k5f7Nc/edit?usp=sharing

**Comment by rachael-phillips** [comment]
We want to close this one because it is complete.
