### ISSUE TITLE
[design] Hover on data lists / tables

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-next#2307]
The OpenShift team needs a hover state for data lists and tables. 

Appears on the last page of this document: https://docs.google.com/document/d/15fIOME4BUWil5rjN4jgw0i5HvHDuRDqFVJCjDJX12G8/edit

Latest Designs: 
Mocks: https://marvelapp.com/69dc1eg/screen/62345709
Sketch File: [PF Hover & Select States (Data Tables, Lists, Cards).zip](https://github.com/patternfly/patternfly-next/files/3751740/PF.Hover.Select.States.Data.Tables.Lists.Cards.zip)

**Comment by lboehling** [comment]
**in progress** mocks: https://marvelapp.com/69dc1eg/screen/62345709
mock up [video](https://drive.google.com/file/d/1_Kfdpiyt1zK3u8YUW9Yi_Zz6qL1FlH6N/view?usp=sharing)

**Comment by mcarrano** [comment]
This is looking good @lboehling . The only change I think we need to make is to disconnect the row selection checkbox from the row selection. This gets into the discussion we had about using this as part of a master-detail view where I might want global actions that operate on multiple rows independent from single row selection to view object details.

Does this make sense?

**Comment by lboehling** [comment]
yep, makes sense @mcarrano. I just updated the designs.

**Comment by rachael-phillips** [comment]
We can close this out, and open the CSS issue.
