### ISSUE TITLE
Button variation for a split button

### ISSUE THREAD

**Issue by tiffanynolan** [patternfly/patternfly-next#2326]
As discussed with @mcarrano, the Integreatly project has a need for a split button which is a button first and then a variation on top of that. This varies from the bulk selector as that component is primarily a drop-down style first. This request is for a button which has a default primary action, similar to all the other buttons it appears with in a data list. There is an alternate action for this variation though that has at least one secondary action. 

We are hoping to be able to use this by the end of Oct to coincide with some changes to our home page. 

Here's an example in context for our Open console button use case: https://marvelapp.com/cf986ih/screen/61486145

**Comment by mcarrano** [comment]
Thanks for filing this @tiffanynolan .  Please consider for prioritization @rachael-phillips @LHinson . I had a bit of prior discussion to @mcoker about this and there are a couple of ways we could approach it. Most likely we would create a new variant of the existing Split Button to support the needed behavior.
