### ISSUE TITLE
Refine User Menu/Avatar behavior

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#2329]
Questions have been raised about the expected behavior of the user menu/avatar in the PatternFly masthead. See https://projects.engineering.redhat.com/browse/RHCLOUD-1068 for example.

Currently the User menu and Avatar are independent elements with the avatar being static (non-interactive). There is an expectation that the user menu and avatar are integrated so that the user can click on either the username or avatar to reveal the user settings menu. Any solution needs to consider that the avatar is an optional element and that some applications may not use an avatar.

This is closely related to #1832 which specifies how the menu and avatar should behave responsively. That issue could be impacted by what we define here.

cc: @LHinson @jeperry @KendraMar

**Comment by mcarrano** [comment]
Capturing recommendations from @jeperry 

> I'd like to see variants spec'ed out where avatar + user name and menu are considered as one thing. When together, I think the caret is not needed and the avatar + name should trigger the user menu. Would also expect a variation where the name goes away and the avatar alone can be used to show a menu. The latter is a common pattern in web apps.

> combos I think we need:
Username only (with or without menu)
Username + Avatar (with or without menu)
Avatar only (with or without menu)

**Comment by maryshak1996** [comment]
Working doc: https://docs.google.com/document/d/1iN-FV-JsS1kial7wza7GG4Vu4jA0KfaXaxz5a0lrYcU/edit?usp=sharing

**Comment by mcarrano** [comment]
This design was reviewed with the UX stakeholders today and I believe we are ready to move forward. There was some discussion about the usefulness of the avatar, in general. But we think this approach makes the masthead more flexible to work with/without the avatar.

@mcoker can you take a look at this design and let us know if you see any implementation challenges? My only concern is whether this can be done without being a breaking change, or if we would need to offer as an "opt in." 

cc @rachael-phillips @LHinson

**Comment by mcarrano** [comment]
Design is complete. Have opened #2482 to track core changes.
