### ISSUE TITLE
Options menu - support for groups and group titles

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-next#2361]
Options menu lacks the ability to add a group and group title.

@mcarrano any reason we wouldn't want to add this?

**Comment by mcarrano** [comment]
Is this being requested by someone @mcoker ?

**Comment by mcoker** [comment]
@mcarrano no, I'm refactoring the spacing around groups in dropdown, app launcher, and select, and just noticed options menu doesn't have the ability to define groups like those menus do.

**Comment by mcarrano** [comment]
@mcoker I can see where the ability to have groups and group titles could be useful. @christiemolloy had pinged me about a similar issue for Selects: https://github.com/patternfly/patternfly-next/issues/2078
