### ISSUE TITLE
Application launcher enhancements

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#2365]
Introduce an enhanced Application Launcher that adds the following functionality:

* Search/filter capability to filter the list of applications. Should behave like the current type-ahead select to filter as list of choices while typing.

* Marking items as favorites and exposing a list of favorites at the top of the menu.

**Design doc:** https://docs.google.com/document/d/1jSQV48VBeavFG37akVGojfb6RpOq6r_14ebsTKntm3k/edit?usp=sharing

**Sketch file:** https://sketch.cloud/s/ezjkj

**Comment by maryshak1996** [comment]
@mcarrano here is my design doc for this
https://docs.google.com/document/d/1jSQV48VBeavFG37akVGojfb6RpOq6r_14ebsTKntm3k/edit?usp=sharing

**Comment by mcarrano** [comment]
Looks great @maryshak1996 .  @beanh66 can you take a look and see if there are any issues before we hand off for development?

**Comment by maryshak1996** [comment]
These links are in the above doc as well, but here is my design file:
https://sketch.cloud/s/ezjkj
