### ISSUE TITLE
Fix internal documentation links

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-next#2389]
We have links in the workspace that link to other places in the workspace that are currently broken. For example

"The chip group requires the chip component." on https://pf4.patternfly.org/documentation/core/components/chipgroup

"A good example of this approach is the table component." on https://pf4.patternfly.org/contribution

**Comment by redallen** [comment]
We fixed this a while ago as a part of the gatsby-theme-patternfly-org refactor.
