### ISSUE TITLE
Define a standard icon for field level help

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#2392]
Define a standard icon for field level help (i.e. (i) or (?)) and the styling. Also clarifying the appropriate color.

**Comment by mcarrano** [comment]
There is a related issue here that takes a different approach to exposing field level help: https://github.com/patternfly/patternfly-next/issues/2383 @bdellasc @kybaker @mceledonia I'm curious whether you think we should move in that direction and negate the need to define as an icon.

**Comment by kybaker** [comment]
@mcarrano I think it might be worth exploring this further. This way we at least have a definitive direction. I know this has been ambiguous in the past.

**Comment by mcarrano** [comment]
I am going to close this one out and have opened a new design documentation issue here: https://github.com/patternfly/patternfly-org/issues/1606  Based on conversation with @bdellasc @mceledonia and @kybaker , the answer may depend on context and we should communicate the design intention better through documentation and examples.
