### ISSUE TITLE
Select component enhancements

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-next#2414]
Kiali is looking for enhancements to the PF4 context selector after working with the PF3 component. They are looking for multi select, a clear all, and when selection is made, indicating what's selected

<img width="287" alt="Screen Shot 2019-10-29 at 2 14 15 PM" src="https://user-images.githubusercontent.com/40275806/67805490-7c918d80-fa67-11e9-8a8a-38374f9f06ab.png">

An additional request comes from @bmignano for adding an item count to each item in the menu.

![image.png](https://images.zenhubusercontent.com/5ce816524e6c594dc1b0df4d/def7ee3a-bd1a-4fab-8007-b11554e9cc9b)

cc @mcarrano @LHinson @serenamarie125 @mtho11

**Comment by mcarrano** [comment]
I was going to be looking at issues with the context selector in the upcoming sprint anyway, so I will include this in the mix.

**Comment by mcarrano** [comment]
Based on discussion with @serenamarie125 and @bmignano , we should design this as a new variant of Checkbox Select. Have named the issue accordingly.

**Comment by lucasponce** [comment]
cc @aljesusg

**Comment by yih-wang** [comment]
@mcarrano Keycloak is going to use this component too. Except for the ability to indicate what is selected, we also need a feature to show recent selected options. An illustration is like this - 

![image](https://user-images.githubusercontent.com/23331885/68915777-70633b00-079e-11ea-8f7b-6346527fce12.png)

**Comment by mcarrano** [comment]
@yih-wang thanks for bringing this to my attention, but per our discussion, I'd advise creating a custom component to satisfy your use case or filing this as a separate request. This issue will focus on delivering multi-select functionality from a searchable menu.

Here are some preliminary concepts for adding the following functionality to the existing Checkbox Select component. Enhancements include:

* Adding a type-ahead filter inside the menu.
* Adding a clear function to clear all selections.
* Adding item counts to the menu.

![Checkbox (adding filter field and clear).png](https://images.zenhubusercontent.com/5ce816524e6c594dc1b0df4d/f058deb0-7dac-4289-80af-97fa8ce301b0)

![Checkbox (with badges).png](https://images.zenhubusercontent.com/5ce816524e6c594dc1b0df4d/4d2c4841-6914-4d62-8993-ffe3a12b4476)

@serenamarie125 @rachael-phillips @bmignano @jgiardino @jessiehuff please review and let me know what you think. Some specific questions I had were:

* Are there accessibility concerns with combining a search field and checkboxes for selection?
* Does adding a badge to reflect item count lead to potential confusion with the badge to indicate the number of selected filters? If so, do you have other ideas?

Thanks

**Comment by yih-wang** [comment]
@mcarrano We'll continue with a customized dropdown. Thanks!

**Comment by catrobson** [comment]
@mcarrano would like to ensure that as we finalize this component we have considered click and keyboard navigation into the component to search/filter/select.  If we require the users to click before they can type, it might be cumbersome.  If the user has to keyboard navigate onto the component, then press enter, then type, then press enter again that might also be cumbersome.  Would like to see the component allow users to type as soon as the component is in focus.

**Comment by mcarrano** [comment]
I am closing this issue in the interest of ongoing work to better define the requirements and design guidance for a context selector. That work will be tracked in a new issue here: https://github.com/patternfly/patternfly-next/issues/2495
