### ISSUE TITLE
Enhancing Read only state

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-next#2420]
Peter Kreuser and @mceledonia raised the need to enhance the read-only state to distinguish it from the disabled state seen on PatternFly 4. The proposal is to make these two states look more noticeable different in order to have the read-only state stand out as truly a read-only state. Here is more about Peter's use case:

"The example where I saw this most recently was we use similar (the same code) forms for both creating and editing an object. Perhaps when creating a particular value is editable (like some name,) but once it is set it cannot be changed. The next time that form is opened in an edit mode, I was hoping to see that value as read-only plain text, as it can never be changed, not just disabled as that sort of gives the sense that there is some scenario where it could become enabled again.
This would be another similar example, we have this form to create a new object, this was me launching it from a general area

![image (4)](https://user-images.githubusercontent.com/40275806/67984765-d5932a00-fbfd-11e9-8cb6-428e923a59e0.png)

I now just launched that same form from within the context of a role, so in this case the role binding must have it's role value set to the role I launched it from.

![image (5)](https://user-images.githubusercontent.com/40275806/67984823-ed6aae00-fbfd-11e9-8150-a4bfadaae664.png)

I like that this form shows that role as plain text, and not just a disabled field with that value in it, as it gives me more the sense that it could never be changed
I am not sure how dev implemented this particular example, but I thought the paradigm might be worth discussing more and possibly incorporating into the read only styling."

**Comment by itsptk** [comment]
The thought is that the disabled state should more convey that this value is not able to be changed at this time, but could be enabled somehow. The read-only state would convey there is nothing the user could do to enable that field, and it's purely for informational purposes.

**Comment by andybraren** [comment]
See [Bootstrap's "Readonly plain text" form field](https://getbootstrap.com/docs/4.0/components/forms/#readonly-plain-text) for an example. It's still a form element structurally, but that email field doesn't visually hint that editing the email address would even be possible.

**Comment by andybraren** [comment]
And I +1 this by the way, for use cases very similar to @itsptk's (same product).

**Comment by lizsurette** [comment]
Yep, +1 to this from my point of view as well!

**Comment by itsptk** [comment]
In the 11/21/19 patternfly sync meeting @mcarrano mentioned that Definition List is a to be implemented component that could satisfy this need: https://github.com/patternfly/patternfly-next/issues/1919

I think that this change to the read-only styling could co-exist with that component but also think that component could be used for most use cases I can think of.

**Comment by andybraren** [comment]
I agree that the upcoming Definition List component is very likely what we'd use for the example above.

The almost-but-not-quite-disabled `readonly` styling we have in the [Form control component](https://www.patternfly.org/v4/documentation/core/components/formcontrol) should be fine until we encounter a use case for something like [Bootstrap's plainer-looking variant](https://getbootstrap.com/docs/4.0/components/forms/#readonly-plain-text) in the future.

I think this issue can be closed @rachael-phillips if you're cool with it.

**Comment by rachael-phillips** [comment]
I'm closing this issue @andybraren and @itsptk. I will update the definition list component issue with this requirement.
