### ISSUE TITLE
Checkbox in table missing hover style

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-next#2431]
I noticed there is no `cursor: pointer` style applied on checkbox hover when inside a table - https://www.patternfly.org/v4/documentation/core/components/table#with-checkboxes-and-actions

The table checkbox used to use the `Check` component which applied the style as expected, but has since become a normal `<input type="checkbox" />` element for which there is no [global cursor style](https://github.com/patternfly/patternfly-next/blob/master/src/patternfly/_globals.scss#L125-L128) available.

Another option could be to modify the check component to work as a standalone check without the label, and ensure hover states are applied in this scenario.

**Comment by rachael-phillips** [comment]
At a later point in time we'll look at creating a PF checkbox. For the time being I'll close this issue.
