### ISSUE TITLE
Navigation - TertiaryList: Font weight increase for active item causes visual issues

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-next#2436]
Font weight increase for active item causes a "shimmy" of the nav items on select, and the last nav item can end up clipped.

![nknYg1HqRK](https://user-images.githubusercontent.com/895728/67802911-6cc37a80-fa62-11e9-87f3-a3e5f63e4fe7.gif)

**Comment by mcoker** [comment]
@nicolethoen is this all just an artifact of the nav elements shifting in size when the font weight changes? If so @tlabaj has an open issue that we can add to the backlog - https://github.com/patternfly/patternfly-next/issues/2027

**Comment by mceledonia** [comment]
The blue color shift and underline is plenty in terms of visual indications of the selected state. Let's drop the unnecessary bolding and fix this one!
