### ISSUE TITLE
Wizard sub-steps not fully accessible

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-next#2443]
Currently the wizard sub steps only indicate an active item via the colour. We should add a second visual indicator for an active item to pass for colour vision deficiency. 

This is what it could look like if we bumped the font weight up to 700 (--pf-global--FontWeight--redhatfont--bold)

<img width="302" alt="Screen Shot 2019-11-14 at 2 45 30 PM" src="https://user-images.githubusercontent.com/287880/68886337-6b927e80-06ed-11ea-951a-83968d94dd25.png">

**Comment by mcoker** [comment]
Sounds good to me, we do the same in the navigation component. @mcarrano @jessiehuff wdyt?

**Comment by mcarrano** [comment]
I'd be fine with that. @mceledonia what do you think?
