### ISSUE TITLE
.pf-c-backdrop backdrop-filter causing visual defects in Chrome 78

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-next#2447]
We're seeing this in OpenShift console, but it also reproduces on https://www.patternfly.org/v4/documentation/react/components/aboutmodal.  Workaround fix is to override backdrop-filter (set it to none), which is what we're doing for OpenShift 4.3 since we can't bump PatternFly at this point in the dev cycle.

![Screen Shot 2019-11-18 at 10 08 30 AM](https://user-images.githubusercontent.com/895728/69065096-2623c900-09ed-11ea-9b66-a52e50990f09.png)
![Screen Shot 2019-11-18 at 9 38 56 AM](https://user-images.githubusercontent.com/895728/69065097-2623c900-09ed-11ea-9f7e-eea77e3d440b.png)
![Screen Shot 2019-11-18 at 9 52 29 AM](https://user-images.githubusercontent.com/895728/69065099-291eb980-09ed-11ea-84f9-346ad4cb0ded.png)

**Comment by rhamilto** [comment]
Override fix for OpenShift https://github.com/openshift/console/pull/3449

**Comment by mcoker** [comment]
Hey @rhamilto, thanks for reporting this. We have a forum post with this recommended workaround, too - https://forum.patternfly.org/t/bug-with-the-backdrop-component-in-chrome/277

The issue has since been resolved in Canary, and I expect a fix in Chrome soon.

**Comment by mcoker** [comment]
@rhamilto this appears to be fixed in the latest versions of chrome. If you can confirm, are you OK with us closing this issue?
