### ISSUE TITLE
[Spike] Investigate HTML+CSS for Tree View / Tree Table

### ISSUE THREAD

**Issue by mturley** [patternfly/patternfly-next#2455]
With the assumption that we need to build the tree view as a new in-house component, we need to determine the best way to structure the HTML and CSS of a tree view. A discussion on the design of this component can be found in https://github.com/patternfly/patternfly-next/issues/348, but here is a summary of the constraints that make the HTML structure difficult:

* The view contains a list of items which each contain a hidden list of children.
* At least on desktop, it has to use an underlying tabular or grid structure so that tree view items can have more than one column. On mobile, these extra columns should collapse similarly to how our current table component collapses.
* On desktop, an item can expand to reveal the child items, and children can also expand with nested indentation of their own children. The first column of each item is indented to indicate its depth in the tree, but all other columns are aligned.
* On mobile, instead of expand/collapse, a user can click an item to navigate to a deeper list of its children, which includes context from the no-longer-visible parent.
* All items can have checkboxes.

Originally I was investigating this by looking for third-party libraries we can use, and starting to attempt a quick-and-dirty React prototype (https://github.com/patternfly/patternfly-react/issues/3141) to see if the functionality we need can be achieved without duplicating a lot of third-party effort. We determined that for the initial component we shouldn't have any sorting or filtering functionality (since the implications of those on a tree structure are unclear), and in my research on third-party libraries, I could find none that we could theme to match the design and meet all the constraints above (particularly, none of them would adapt well to a mobile view).

In attempting to build a prototype based on our Table styles, these are the issues I ran into which indicated that this should be a core spike:
* A tree with one level of children can be built as an HTML `<table>` with each top-level item being a `<tbody>` that contains some hidden rows which are shown when the first row is expanded. This is similar to the structure of the existing expandable-row support in Table. However, when trying to nest a second level of children, this structure no longer works because you cannot put a `<tbody>` inside another `<tbody>`.
* Nested `<div>`s or `<ul>`s could work for arbitrary levels, but in order to align another column of data across multiple levels of the tree, we start needing to assign static widths to things and it felt wrong.
* I started investigating whether we could use a CSS grid solution, then realized I was out of the scope of a React spike.
* With any of these solutions, it was unclear to me whether it would be possible to have one singular HTML structure for a tree, and then use only CSS to switch between the desktop (indented rows) and mobile ("Miller columns") layouts of this HTML. It seemed to me like we may need two different HTML structures, and the React component would need to render one or the other depending on the window size.

**Comment by mcarrano** [comment]
@mattnolting Here is a link to the final designs: https://docs.google.com/document/d/1I0DhtexeBnrtF8EUB-MuAkYic_UBK-50ElAuvFZ283A/edit?usp=sharing  I will remove the mocks from the description to avoid confusion.

**Comment by mattnolting** [comment]
Here are my findings:
- **Subgrid** would solve this very well. It would allow us to use nested lists and maintain columnar alignment. But without subgrid being broadly supported, nested `<ul>`s are not a viable solution as complex width declarations would be necessary, which @mturley notes in the description. 
- There's no way (at least that I could find or create) to use pure css to show/hide mixed depth (aria-level) siblings when there is no actual DOM hierarchy to target. We would need JS to handle that. Example `aria-level="1"` element is activated (clicked), append `.pf-m-visible` to all `aria-level="2"` elements until the next `aria-level="1"` element.

> A tree with one level of children can be built as an HTML <table> with each top-level item being a <tbody> that contains some hidden rows which are shown when the first row is expanded. This is similar to the structure of the existing expandable-row support in Table. However, when trying to nest a second level of children, this structure no longer works because you cannot put a <tbody> inside another <tbody>.

- Can emulate this hierarchy by assigning managing `aria-level', `aria-posinset`, `aria-setsize`.
- Can target `aria-level` to affect indention

Recommendation: 
- Use flat table
- Create hierarchy with `aria-level', `aria-posinset`, `aria-setsize`
- Apply responsive modifications from `.pf-c-table.pf-m-grid`
- Further explore nested `<ul>` option built on `subgrid` for when that option becomes available

Vertical alignment testing:  https://codepen.io/bobcatTaco/pen/OJJeJzp
Subgrid testing (view if Firefox): https://codepen.io/bobcatTaco/pen/LYEVdPZ
`[aria-level="#{$i}"].pf-m-expanded ~ [aria-level="#{$i + 1}"]` test: https://codepen.io/bobcatTaco/pen/xxbbvrJ

**Comment by mturley** [comment]
(@mattnolting I hope you don't mind I edited your comment to fix the formatting issues from pasting my quote that included HTML tags)

I thought maybe this would be a good candidate for subgrid! Dang, I wonder if we can polyfill it or something. When browser support for it becomes widespread enough we should probably plan to rewrite those parts of this component.

One other thought: In the original issue I had proposed we call this component simply "Tree" to avoid the implications of "TreeTable" and keep it clearly separate from Table and all its complexity. I was discussing this stuff with @seanforyou23, and he feels strongly that we should reserve the name "Tree" for possible future use as a very basic tree that doesn't concern itself with grid/columns/etc. Maybe instead we should call this one "TreeGrid" or "GridTree"?

**Comment by mattnolting** [comment]
> (@mattnolting I hope you don't mind I edited your comment to fix the formatting issues from pasting my quote that included HTML tags)

@mturley Much appreciated!

I think there's much value in exploring a subgrid + polyfill solution.

I agree w/@seanforyou23, this shouldn't be associated w/`table`.

**Comment by mturley** [comment]
@rachael-phillips @evwilkin was this closed because it's no longer on the roadmap? Has it been totally replaced by the Tree Menu design? (https://github.com/patternfly/patternfly/issues/3206)

There is a new downstream need for a tree view with multiple columns, but I might just implement it with some custom stuff on top of Table. Was just curious where we landed with this component.

**Comment by mcoker** [comment]
+ @mcarrano

**Comment by evwilkin** [comment]
@mturley I'm not familiar with this work, I'll defer to @mcarrano

**Comment by mcarrano** [comment]
I believe that the Tree Table ran into multiple complications and after consultation with the original requestor was dropped from the roadmap. @LHinson or @mattnolting may be able to elaborate more on this. The Tree menu referenced about is just a single column tree browser. If you have new requirements @mturley , I'd be glad to reopen the discussion, but a custom solution might be the way to go.

**Comment by mturley** [comment]
Yeah, I'm thinking a custom solution is the answer for now, but I'll post about my implementation here in case we ever pick this back up. Thanks @mcarrano!
