### ISSUE TITLE
Drawer updates to support master-detail pattern

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#2467]
Require the following updates to the drawer component to support a master-detail pattern in PatternFly 4.

* add/remove the padding from drawer panel and content
* pass widths/define specific widths in react
* define width of the drawer in relation to content
* have fluid resizing of drawer/content
* add variations to remove drop shadow on left of drawer, and to use a vertical divider between drawer panel and content
* add variations to display the drawer on the left of the content.

Here are content, layout, and interaction guidelines for the master-detail pattern:
Guidelines: https://docs.google.com/document/d/1kzGP37tb-lf7sVz43xBnnoYEWPsQN4GvNvffebxiuTE/edit# and Visuals: https://marvelapp.com/9iefh5b/screen/63567619

cc: @mcoker @rachael-phillips @LHinson

**Comment by mcoker** [comment]
closed via https://github.com/patternfly/patternfly-next/pull/2520
