### ISSUE TITLE
Introduce Simple List component for master-detail pattern

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#2468]
One variation of the master-detail pattern calls for a simple list component in the master panel that can be implemented as a compact variant of the simple light nav. An example of what that looks like can be seen here: https://marvelapp.com/9iefh5b/screen/63567619 This is useful in cases where use of a DataList as the master is not appropriate. The component should support both grouped and ungrouped items.

cc: @mcoker @rachael-phillips @LHinson

**Comment by mcoker** [comment]
@mcarrano this looks like the simple-list element that is currently part of the nav component. Do you think it makes sense for these 2 to be different? Or would you expect that they are always the same thing?

I'm thinking we could build this as its own component and 1) leave the nav component as it is, allowing them to be completely different or 2) rework the nav component to include this simple list component.

**Comment by mcarrano** [comment]
@sbuenafe-rh had a use case for this and we found that while the nav component worked, the spacing was probably bit bit larger than it needs to be for this purpose. I saw this less as a variant of Navigation than a simple list component that can be dropped anywhere to display a long list of items. So I'm thinking (1) but am open to discussion.

**Comment by lboehling** [comment]
Hey @mcarrano! I can provide specs for more compact spacing in the simple list. Should I open a new design issue, or just attach the specs here when I'm finished?

**Comment by mcarrano** [comment]
I don't think we need a design issue. You can just attach your specs here. Is that OK with you @mcoker @christiemolloy 

Thanks, @lboehling

**Comment by lboehling** [comment]
Here's a spec with updated spacing in the simple list component! 

https://marvelapp.com/dcf643h/screen/65422152 

[PF- Compact Simple List.zip](https://github.com/patternfly/patternfly-next/files/4055744/PF-.Compact.Simple.List.zip)

@christiemolloy @mcarrano
