### ISSUE TITLE
Add hover and select states for Cards

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#2470]
To support the master-detail pattern we want to all for the possibility of a card grid to be used as part of the master panel. This will require the possibility for cards to have a select and hover state as was implemented for the DataList.

See designs here: https://docs.google.com/document/d/1kzGP37tb-lf7sVz43xBnnoYEWPsQN4GvNvffebxiuTE/edit?usp=sharing

master/detail sketch file: 
[Master:Detail.zip](https://github.com/patternfly/patternfly-next/files/3893514/Master.Detail.zip)

cc @mcoker @rachael-phillips @LHinson

**Comment by mcoker** [comment]
@mcarrano we already have a [hoverable state for cards](https://www.patternfly.org/v4/documentation/core/components/card#hover) - is the expectation we will re-use that, and add just a selected state?

**Comment by mcarrano** [comment]
Yes, that makes sense @mcoker

**Comment by lboehling** [comment]
@mcoker the selected state will keep the hover drop shadow, but also will have a 3px primary blue border along the top.

Side note, it looks like the small drop shadow that appears behind cards (non hovered/unselected state) was replaced with a gray outline around the card [here](https://www.patternfly.org/v4/documentation/core/components/card). Is this a bug?

**Comment by mcoker** [comment]
@lboehling yep, thanks for noting that! It's just an issue with the website, not patternfly, and opened an issue here - https://github.com/patternfly/gatsby-theme-patternfly-org/issues/132

**Comment by lboehling** [comment]
I know there have also been requests for PF to support tiles (with hover and selected states). I made a design proposal for tiles in this doc https://marvelapp.com/50eh328/screen/64407411 (C., or last listing on the second page). 

@mcoker would tiles be a variant of cards or a new component? The specs I made are using the same padding as compact cards, but have borders with rounded edges in lieu of a drop shadow, and different hover/select treatments. 

@mcarrano

**Comment by mcoker** [comment]
@lboehling what's the difference between a tile and a card? And what all goes into a tile? At first glance, they look like different components.

**Comment by lboehling** [comment]
@mcoker I believe tiles act more like form elements. They can include more grouped info than just radio/check boxes (i.e. icons, longer titles/descriptions) and can be placed within a card/in a gridded layout. Typically these will be pretty plain and compact. 
@katierik opened an issue with a few more use cases for tiles here https://github.com/patternfly/patternfly-next/issues/2310

Visually, there would need to be different styling btwn cards and tiles, since tiles can be placed within a card/wizard/modal/components with white backgrounds. This would also eliminate unnecessary stacking of cards with box shadows.

<img width="667" alt="Screen Shot 2019-12-05 at 4 31 40 PM" src="https://user-images.githubusercontent.com/46571616/70275900-1a6e2b80-177d-11ea-979c-751fc3c069ee.png">

**Comment by mcoker** [comment]
@lboehling thanks, tiles should definitely be a new component.

**Comment by mattnolting** [comment]
@lboehling nice!

**Comment by mcarrano** [comment]
@mcoker @lboehling I'm a little bit hesitant to see us create a new component for this since I don't really see anything functionally different between a Card and a Tile and it will be easy to confuse them. Just looks like a different visual treatment of the card. Is the issue that we need a card that can be placed on a while vs gray background? Maybe this is just a new variant of Card.

**Comment by mcoker** [comment]
@mcarrano visually I think there are enough stylistic differences that I think it's a valid approach to separate them. If they're the same component, there will be a lot of style overrides of the existing component for the tile variation. Also functionally it looks like tiles have a very specific use and cards do not, so I'm not sure it makes sense to have them tied together as the same component. Meaning if we make changes or add enhancements to either the card or tile, would we likely want those changes to also apply to the other?

That said, you know better than I how you see envision the structure and their intended use, so I'm fine with this being a variation, too, if you think they're similar enough.

**Comment by mcarrano** [comment]
All fair points @mcoker . There is a separate issue opened for tiles that @lboehling referenced above, so let's keep this work focused on Cards and we can take up the Tiles question at another time. @LHinson @rachael-phillips are you aware of the request for a "Tiles" component? See #2310
