### ISSUE TITLE
Introduce Extra-Large empty state variant

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#2472]
We want to add a new empty state variant to be used for certain full screen empty state patterns like welcome and success screens.

Final designs here: https://marvelapp.com/504hec7

cc: @mcoker @rachael-phillips @LHinson

**Comment by mcarrano** [comment]
@mmenestr can you edit the description to include your final designs for this? Just adding these to a Marvel prototype or a Google doc and pasting the link will be fine.

**Comment by mmenestr** [comment]
Here is the link to a marvel project which includes 3 pages: 
1. XL as get started
2. XL as success
3. XL with specks

https://marvelapp.com/504hec7
