### ISSUE TITLE
Reconsider design of Tertiary Nav to address bugs

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#2473]
There are two bugs that have been opened against the tertiary nav that require us to reconsider the design. These include:

#2435 - Disappearing scroll button
#2436 - Change in font weight on selection causes the nav bar to "shimmy" on click.

Want to provide direction for fixing these issues in core.

**Comment by mceledonia** [comment]
@mcarrano Left comments on both of these issues, to summarize here:
- Make arrows in tabs/nav persistent so they don't disappear, have them go to a custom disabled state (drop arrow icon opacity to 50%) when at either end of the tabs
- Drop unnecessary bolding of the selected tab, two visual indications (blue color change + underline) is plenty.

**Comment by mcarrano** [comment]
Design recommendations have been posted directly to the related issues. Will close this out.
