### ISSUE TITLE
Masthead - refine responsive behavior and avatar behavior

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#2482]
Need to refactor the masthead utility menu area to address the following issues:

* Want to better define how the utility menu should respond with the viewport width shrinks.
* Want to integrate the user menu and avatar to make the avatar interactive (when used).

New implementation must support the following utility items:
* Integrated user menu and avatar
* Notification icon - alerts the user of unread notifications and toggles notification drawer. The notification icon must be visible at all viewport sizes.
* utility menus - one or more items represented by an icon. Menus can be either Dropdowns or Options Menus. Typically includes Help and Settings but other menus may be included.

Designs can be found here: https://docs.google.com/document/d/1iN-FV-JsS1kial7wza7GG4Vu4jA0KfaXaxz5a0lrYcU/edit?usp=sharing

This replaces issue #1832 which will be closed

cc @mcoker @rachael-phillips @LHinson

**Comment by mcarrano** [comment]
@mcoker per our discussion, I have opened a new issue to track requested masthead changes. I'm thinking this is likely a breaking change, but please confirm and tag as such if that makes sense.

**Comment by mattnolting** [comment]
Closing and moving to #2800
