### ISSUE TITLE
Bug - Mobile expand pane is missing styling

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-next#2512]
The expandable table has a blue line when expanded on the row and child expand pane. When responsive on mobile, this line is different.

Seen in product and also on the PF website
https://www.patternfly.org/v4/documentation/react/components/table
![Xnip2019-12-10_08-13-51](https://user-images.githubusercontent.com/23172038/70532569-53175780-1b25-11ea-9bda-1109271a5185.jpg)

Product example: https://github.com/RedHatInsights/insights-advisor-frontend/pull/500#issuecomment-564025255

**Comment by christiemolloy** [comment]
Also happening on desktop

<img width="883" alt="Screen Shot 2019-12-19 at 11 29 41 AM" src="https://user-images.githubusercontent.com/20118816/71190691-10572d00-2253-11ea-8a74-c8030bb4a526.png">

**Comment by christiemolloy** [comment]
<img width="815" alt="Screen Shot 2019-12-22 at 11 53 20 PM" src="https://user-images.githubusercontent.com/20118816/71336709-509a0200-2516-11ea-870b-e173eb00cae4.png">
This is also occurring
