### ISSUE TITLE
Label on chip groups can run out of room

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-next#2524]
Label on chip groups can run out of room.

Same problem for chips themselves. Possibly adding a tooltip to the label or chip would be sufficient?

![Screen Shot 2019-12-13 at 1 37 05 PM](https://user-images.githubusercontent.com/26305082/70935992-705d9180-200f-11ea-8bcd-23ad119deb31.png)

![Screen Shot 2019-12-17 at 1 29 16 PM](https://user-images.githubusercontent.com/26305082/71024066-2093ce80-20d2-11ea-8820-8a4d65d24b97.png)

**Comment by jlmitch5** [comment]
@mcoker @mattnolting @nicolethoen this fixes the issue _visually_, but it looks like there needs to be an update to allow the full information for both key and value to show up via tooltip on hover:

![Screen Shot 2020-01-08 at 1 49 31 PM](https://user-images.githubusercontent.com/1342624/72006593-fab7a080-321d-11ea-96db-0376efe827be.png)

**Comment by mcoker** [comment]
@jlmitch5 the tooltip is enabled on chips with overflowing text in the react component, since the tooltip component requires JS for its positioning - https://www.patternfly.org/v4/documentation/react/components/chipgroup#single

**Comment by mcoker** [comment]
@jlmitch5 agreed, opened an issue in react to add that functionality https://github.com/patternfly/patternfly-react/issues/3490
