### ISSUE TITLE
Upstream and Downstream Branding System

### ISSUE THREAD

**Issue by kybaker** [patternfly/patternfly-next#254]
Need to define the system of visuals which define the upstream and downstream applications.

[Final design PDF](https://drive.google.com/open?id=1PtsS5vS91--CaRtpi8cyEC8Zuql2jqXw)

Please note the demo Michael gave at the PatternFly demo around accessibility and determining colors with CSS gradient.

**Comment by kybaker** [comment]
Updated with the latest PDF above.

**Comment by LHinson** [comment]
No additional action needed beyond visuals.
