### ISSUE TITLE
Expandable Table is missing border

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-next#2547]
<img width="883" alt="Screen Shot 2019-12-19 at 11 29 41 AM" src="https://user-images.githubusercontent.com/20118816/71191599-bfe0cf00-2254-11ea-9cab-494f407112cd.png">

**Comment by mcoker** [comment]
Looks like this is a workspace issue. Closing in favor of https://github.com/patternfly/patternfly-org/issues/1615
