### ISSUE TITLE
Modal, SideBar, Page Header Z-Index Issue?

### ISSUE THREAD

**Issue by alexfdezsauco** [patternfly/patternfly-next#2555]
Hi I'm writing Blazor wrappers for patternfly components.

Here is the repository https://github.com/WildGums/Blorc.PatternFly.

I'm running into an issue with Modal, SideBar, Page Header z-index. There is no issue in your demo website https://www.patternfly.org/v4/documentation/react/components/modal, but is not working properly on my live demo http://blorc-patternfly.wildgums.com/components/modal.

![image](https://user-images.githubusercontent.com/1785664/71527027-825cf100-28a7-11ea-8d95-99c67afe13e9.png)

Can you help me to identify what I'm doing wrong?

To reproduce the issue just click the first Show Modal button.

Thanks in advance.

**Comment by alexfdezsauco** [comment]
**Workaround:** <main role="main" class="pf-c-page__main" tabindex="-1" style="z-index: unset">

**Comment by mcoker** [comment]
Hey @alexfdezsauco, the modal component is intended to be rendered outside of the `.pf-c-page` element in the DOM. If you look at the [modal demo](https://www.patternfly.org/v4/documentation/react/components/modal), you’ll see that the modal is appended to the `<body>` element. Are you able to do that with your implementation of this component?

**Comment by alexfdezsauco** [comment]
Thanks, I can try. 

I will have to do some DOM manipulation after render the component to move it outside the `.pf-c-page`.

**Comment by mcoker** [comment]
@alexfdezsauco just checking to see if you were able to resolve this issue?

**Comment by mcoker** [comment]
Hey @alexfdezsauco following up again to see if you were able to find a resolution to this issue?

**Comment by alexfdezsauco** [comment]
In the current implementation I just set 

    <main role="main" class="pf-c-page__main" tabindex="-1" style="z-index: unset">

as workaround.

At this point, I'm not sure how to render (or move) the modals to another container outside the page in blazor.  Probably I can try get the full _RenderFragment_ and render it in the other component, but as it is working fine with this _style="z-index: unset"_ I didn't try the other option.

**Comment by alexfdezsauco** [comment]
I was able to move the render fragments out of the page component and works without the workaround. 

![image](https://user-images.githubusercontent.com/1785664/76713906-5741ab00-66fa-11ea-98f1-58e12dd08a81.png)

Thanks.
