### ISSUE TITLE
tables: no way to let sortable column headers wrap

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-next#2584]
This issue was first created in React: https://github.com/patternfly/patternfly-react/issues/3520 however it is an issue we need to fix in Core first.

Right now, `pf-m-wrap` applied to a sortable table's `<th>` doesn't work because the modifier only applies to a direct descender of `<th>` and in the sortable table there is a button in the `<th>`.

We need to consult design because of the arrow icon to the right of the `<th>` . When `white-space: normal` is applied, the arrow icon drops to the next line:

<img width="395" alt="Screen Shot 2020-01-16 at 11 17 18 AM" src="https://user-images.githubusercontent.com/20118816/72542259-d5e0b000-3851-11ea-8740-365350d58d6c.png">

So we may need a different solution here like truncating for example. @mcarrano 

@rachael-phillips making you aware too.

**Comment by mcarrano** [comment]
@mceledonia @kybaker @maryshak1996 @gdoyle1 @lboehling I'd like to open this up to some design brainstorming here. I'm not crazy about the idea of truncating the column header, but I don't really see any other way. Any thoughts?

**Comment by gdoyle1** [comment]
@mcarrano I agree that truncating is probably the best solution here. Others are doing it too - screenshots from Google Firebase.
![Screen Shot 2020-01-16 at 2 00 06 PM](https://user-images.githubusercontent.com/30870144/72554415-9d989c00-3868-11ea-853f-ea1ab3a3fd6b.png)

**Comment by maryshak1996** [comment]
@mcarrano truncation is definitely where my head went as well

**Comment by gdoyle1** [comment]
@christiemolloy my thoughts for headings that are non-sortable and suuuuuper long (yes this example is a bit ridiculous)
![Screen Shot 2020-01-31 at 4 45 50 PM](https://user-images.githubusercontent.com/30870144/73576842-6837a500-4449-11ea-8a0a-7eb807a4a4ad.png)

**Comment by gdoyle1** [comment]
@mcarrano @maryshak1996 I'm thinking we set a rule that if one column header is truncated, then they all are. What do you both think? Just looking at the example I provided above, it doesn't make sense not to truncate all headers

**Comment by maryshak1996** [comment]
@gdoyle1 so to clarify, you're suggesting that, when a header is long in length, the designers should choose
(1) make all long headers in the table truncated 
or 
(2) make none of the long headers in a table truncated 
Is that correct?

**Comment by mcarrano** [comment]
Not completely sure what you are asking @gdoyle1 . Are you saying that we should truncate long headers whether they are sortable or not? I assumed that we would. It would be odd for some headings to wrap and others to truncate.

**Comment by gdoyle1** [comment]
@mcarrano @maryshak1996 Yes to what Mary said. I think the solution the devs have come to right now is just wrapping all table headers. They figure out how to do so while leaving the sort icon to the right. Thoughts? I think this is a good alternative to truncating _all headers_.
<img width="449" alt="Screen Shot 2020-02-03 at 1 44 47 PM" src="https://user-images.githubusercontent.com/30870144/73783464-bd352d00-4761-11ea-83da-13668a134e1b.png">
