### ISSUE TITLE
Enhancement to the form component: required fields

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#259]
Current required fields approach is seen here: https://www.patternfly.org/pattern-library/forms-and-controls/field-labeling/

[Latest forms design PDF](https://drive.google.com/open?id=1anOBa2h0jq2fN2r0i36hBVuI6wGoYerf)

Component lifecycle: 
- [x] Interaction design requirements 
- [x] Visuals 
- [ ] First checkpoint complete and approved 
- [ ] CSS 
- [ ] React
- [ ] Second checkpoint complete and approved 

Contacts: 
- IxD 
- Visual 
- CSS

**Comment by mcarrano** [comment]
@LHinson can you elaborate on the concerns here?

**Comment by thomasmaas** [comment]
I was actually hoping we would consider marking optional fields with "(optional)" in the label instead of marking required fields.

**Comment by kybaker** [comment]
Added the updated PDF above.
