### ISSUE TITLE
Enhancement to the forms component: error validation

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#260]
Current documentation for error validation: http://www.patternfly.org/pattern-library/forms-and-controls/help-on-forms/#overview

[Latest forms design PDF (See page 1)](https://drive.google.com/open?id=1anOBa2h0jq2fN2r0i36hBVuI6wGoYerf)

- [x] Interaction design requirements 
- [x] Visuals 
- [ ] First checkpoint complete and approved 
- [ ] CSS 
- [ ] React
- [ ] Second checkpoint complete and approved 

Contacts: 
- IxD 
- Visual 
- CSS

**Comment by mcarrano** [comment]
This will be addressed as part of #200 See requirements there.

**Comment by dabeng** [comment]
Hi @mcarrano  Is it necessary to submit jquery code implementation for "errors and validation" pattern?

**Comment by mcarrano** [comment]
Not sure I understand your question @dabeng . We are not doing jquery implementations for PatternFly-Next.

**Comment by kybaker** [comment]
Updated with the latest PDF above.

**Comment by matthewcarleton** [comment]
@kybaker @mceledonia  when implementing the help text for errors I've noticed that the standard help text uses `$pf-color-black-700` can we change this to `$pf-color-black-600`? We can add the new colour in the global variables but wanted to make sure we needed it first.

**Comment by kybaker** [comment]
@matthewcarleton I am okay with that change.
