### ISSUE TITLE
Make all DropdownItem elements pointer cursor

### ISSUE THREAD

**Issue by SpyTec** [patternfly/patternfly-next#2629]
As seen in SCSS file, there is no cursor styling for dropdown items. Should one use different elements than button or anchor, such as a div for more advanced dropdown items, we would not get a pointer cursor.

https://github.com/patternfly/patternfly-next/blob/master/src/patternfly/components/Dropdown/dropdown.scss#L357-L392

**Comment by mcoker** [comment]
Closing via these issues that should resolve the need for a pointer cursor 

https://github.com/patternfly/patternfly-next/issues/2667
https://github.com/patternfly/patternfly-react/issues/3641
