### ISSUE TITLE
Begin pf/pf repo cleanup

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-next#2670]
Prepare patternfly/patternfly repo for eventual transition of code from patternfly-next into patternfly/patternfly

**Comment by redallen** [comment]
It's prepared. The last commit released just fine to the various release streams on Travis.

Is there anything else that needs cleaning @dgutride ?

**Comment by dgutride** [comment]
I think we are good @redallen

**Comment by redallen** [comment]
Awesome! Closing.
