### ISSUE TITLE
Dev:lite - div.ws-preview-html should wrap examples. Make "workspace" dir the docroot?

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-next#2676]
To match the existing workspace markup and for our example styles to work correctly, we need `<div class="ws-preview-html">` to wrap the example code.

https://github.com/patternfly/patternfly-next/blob/master/build/gulp/codeTransformer.js#L10

could be something like:

```
<div class="ws-preview-html">${toWrap}</div>
```

You can verify this fixes this big space between the dropdown kebab icon and the menu on the dropdown component's examples (it's the 5th example).

<img width="249" alt="Screen Shot 2020-02-04 at 5 09 38 PM" src="https://user-images.githubusercontent.com/35148959/73795984-a4347800-4771-11ea-97b9-a264b3de2e32.png">

Also is there any value in using this workspace to navigate anything outside of the "workspace" dir at http://localhost:3000/workspace? Assuming not, can that dir just be the document root for this server so that `/` shows you components, layouts, demos, and utilities?

cc @mattnolting @christiemolloy

**Comment by redallen** [comment]
The workspace has to load files from `/dist` and `/assets`, so that's why we can't just serve the `/workspace` directory.

As for the `ws-preview-html`, you found the right place to add it at https://github.com/patternfly/patternfly-next/blob/master/build/gulp/codeTransformer.js#L10!
