### ISSUE TITLE
Form control invalid/success icon not showing

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-next#2704]
@jeff-phillips-18 is encountering a bug in OpenShift where the background-image for invalid/success state form controls is not showing up. However replacing the shorthand `background` declaration in our form control component CSS with individual declarations for the `background-[image/size/position/repeat]` properties resolves the bug.

I'm unable to reproduce in either the core or react workspace, but Jeff can spin up an OpenShift instance for us when we're ready to start troubleshooting this.

**Comment by jeff-phillips-18** [comment]
Mostly the issue is due to a font sizing override and that has been resolved. However, when using the text input w/ auto complete, the background image will not show in chrome when selecting from the auto complete list.

**Comment by mcoker** [comment]
closing in favor of https://github.com/patternfly/patternfly-next/issues/2702
