### ISSUE TITLE
Body class for full-page examples in dev:lite

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-next#2723]
Can we add a class to the `<body>` element for full-page examples? We style the body element here https://github.com/patternfly/patternfly-next/blob/master/build/gulp/ws-lite.css#L1-L4 but need to remove those styles on full page examples - so the selector would change to something  `body:not(.full-page-example) {...}`

**Comment by mcoker** [comment]
cc @redallen

**Comment by redallen** [comment]
A couple lines of logic needs to change here: https://github.com/patternfly/patternfly-next/blob/master/build/gulp/html.js#L114

I can do it when I have a minute.
