### ISSUE TITLE
Styling for Victory charting

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#276]
We want to introduce to charing to the PF JS framework repos however the styling and any necessary css classes should be defined in core. 

Design Folder: https://drive.google.com/open?id=1tt4CP2TVvgxLC5Tq1D5kxnUIc6FVidhe

- [x] Interaction design requirements 
- [x] Visuals 
- [ ] First checkpoint complete and approved 
- [ ] CSS 

Contacts: 
- Visual @mceledonia 
- CSS @michael-coker 
- React @jschuler

**Comment by michael-coker** [comment]
@LHinson I started working on this today, and as far as I can tell, Victory isn't designed to work with CSS. It looks like you can style the charts using a custom [theme](https://formidable.com/open-source/victory/guides/themes/), and looks like you can add classes in the react code building the chart that I'm assuming we could style with an external stylesheet, but I'm not sure if that's how we want to do it. I wanted to check in with you first before proceeding. Here are 2 threads I found about it:

https://github.com/FormidableLabs/victory/issues/721     
https://github.com/FormidableLabs/victory/issues/559

**Comment by michael-coker** [comment]
Also just read https://forum.patternfly.org/t/patternfly-charts-unmaintained-dependency/87/3 and looked at the Victory styling on Koku, and color vars are coming from a react-tokens file and being used directly in the react code, so no CSS to style the charts. I brought this up on slack #patternfly-react, and @dmiller9911 said this, which looks like what is being done in Koku currently.

>  I think all react needs is a guideline or design doc and then variables to use. We can use react-tokens to set the styles

**Comment by michael-coker** [comment]
FWIW, I took a stab at creating a bar chart and styling by adding a class to the `dataComponent`, which works well, but doesn't when trying to use that technique group charts. My branch is here - https://github.com/michael-coker/patternfly-react/tree/pf-core-issue-276

**Comment by LHinson** [comment]
Per @michael-coker 

> there shouldn't be anything added in core for that, unless we potentially add new global vars for some of the additional colors in Michael's designs

For this reason, we will continue to follow this issue on the React side https://github.com/patternfly/patternfly-react/issues/408
