### ISSUE TITLE
Enhancement: breadcrumbs switcher 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#277]
There is something called a breadcrumb switcher. This issue is related to #33 and current documentation can be found here: https://github.com/patternfly/patternfly-next/issues/33

This issue is being marked as something that should be considered for deprecation. Is this a common requirement? The components to build this feature will be available. If this is built, it would simply be a demo.
- CSS

**Comment by LHinson** [comment]
This issue is being marked as something that should be considered for deprecation. Is this a common requirement? The components to build this feature will be available. If this is built, it would simply be a demo.

**Comment by matthewcarleton** [comment]
@LHinson @mcarrano is this being implemented?

**Comment by LHinson** [comment]
@matthewcarleton This will require a conversation down the road. Not a priority at this time. We can revisit later. Want to keep this issue open so it remains on our radar.

**Comment by rachael-phillips** [comment]
@matthewcarleton and @mcarrano This is currently on the Future 4.x category on our spreadsheet, and I'm wondering if this is a conversation we need to pick back up? Was this a product ask?

**Comment by mcarrano** [comment]
This falls into the category of a thing we have a design for on the PF3 website, but it was never implemented in PF3. No, I'm not aware that there is a product ask.

**Comment by mcarrano** [comment]
I am going to close this one out. We can revisit if it becomes a product ask.
