### ISSUE TITLE
Can't use Text component

### ISSUE THREAD

**Issue by SS-TT** [patternfly/patternfly-next#2778]
Hi there,
I just pasted the `Text` sample in one of my components, but I can't get it to work.

Here's what I'm rendering:

```tsx
<TextContent>
  <Text component={TextVariants.h1}>Hello World</Text>
  <Text component={TextVariants.h2}>Second level</Text>
  <Text component={TextVariants.h3}>Third level</Text>
  <Text component={TextVariants.h4}>Fourth level</Text>
  <Text component={TextVariants.h5}>Fifth level</Text>
  <Text component={TextVariants.h6}>Sixth level</Text>
</TextContent>
```

Launching `yarn build` doesn't cause any issue, but as long as I navigate to that page, I get a blank page.
Hovering on my `Text` components shows this message:

> JSX element type 'Text' is not a constructor function for JSX elements.
  Type 'Text' is missing the following properties from type 'ElementClass': render, context, setState, forceUpdate, and 3 more.ts(2605)
JSX element class does not support attributes because it does not have a 'props' property.ts(2607)

I'm quite new to React, so sorry if this is a stupid issue/question, but I find it odd that I'm having issues with one of the simplest components out there while I could setup a complex `Wizard` with no problems at all.

Thanks.

**Comment by mattnolting** [comment]
Issue moved to [patternfly/patternfly-react #3878](https://github.com/patternfly/patternfly-react/issues/3878) via [**ZenHub**](https://www.zenhub.com/)
