### ISSUE TITLE
Spinner 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#279]
The spinner component needs introduced. Check out the accessibility concerns https://github.com/twbs/bootstrap/pull/22960

Design Folder: https://drive.google.com/open?id=1ObtKD1QavVL3p1hQ0aIXpoaJCzLHDYDx

Component lifecycle: 
~- [ ] Interaction design requirements~ 
- [ ] Visuals 
- [ ] First checkpoint complete and approved 
- [ ] CSS 
- [ ] React
- [ ] Second checkpoint complete and approved 

Contacts: 
- IxD 
- Visual 
- CSS

**Comment by bdellasc** [comment]
Here's a really basic proposal for the spinner. If there is more needed from a visuals standpoint, please let me know. Maybe small and large variants in addition to this default medium one?

https://redhat.invisionapp.com/share/2FQI0EGQ7NR

**Comment by bdellasc** [comment]
Here is the Sketch source file
https://drive.google.com/open?id=1D0j5GL4NVajwElfS9tuyR22jXv6TsS2q

**Comment by mcarrano** [comment]
@kybaker @mceledonia can you guys take a look?

**Comment by matthewcarleton** [comment]
just had a conversation with @mceledonia about this. He walked me through the design that he came up with.
for reference we also looked at 
https://material.io/design/components/progress-indicators.html#circular-progress-indicators
https://codepen.io/mrrocks/pen/EiplA

**Comment by rachael-phillips** [comment]
@matthewcarleton just to clarify, do you want to take on this issue?

**Comment by rachael-phillips** [comment]
Leaving an explanation here of @mceledonia, @kybaker's and my recent discussion on Spinner. @bdellasc I took the design back to Michael, we had a discussion, and we decided to move forward with a more robust spinner design which should work well across products. Let me know if you have any questions!

**Comment by bdellasc** [comment]
@rachael-phillips thanks for the update. Do we have a sense of when the chosen spinner will be implemented? We have need for one in the short term for our upcoming release. @dlabaj built the simple one I proposed already for our immediate needs/current page. I assume we'd just consume and replace it with the chosen one once it's been implemented.

**Comment by rachael-phillips** [comment]
Hi @bdellasc that's a great question, and yes, that sounds like a good plan. Spinner is on the roadmap to be available on the React side by March 22, and I will keep you updated.

**Comment by ryelo** [comment]
Is there any update on the spinner and if it'll hit the March 22 date?

**Comment by rachael-phillips** [comment]
Hi @ryelo it will no longer be available for the March 22 date. Per our release plan it will now be available May 5. Can you tell me more about your product timeline for spinner @ryelo? Thanks!

**Comment by katierik** [comment]
@rachael-phillips @ryelo Spinner is needed for MCOM apps that are launching at summit. May 5 is too late. We're looking at an April 8th feature freeze for these apps. Can this get moved back up?

**Comment by rachael-phillips** [comment]
Hi @katierik per our release plan I sent out earlier this month, this is the component timeline we decided on with product leads: https://docs.google.com/document/u/1/d/1xMQBWVX0RZqCv1N5hAH-82T78SrJxqSBu1ihF-ytqfI/edit#heading=h.pr9zj26f2jlv
We won't be able to offer spinner until after our release.

**Comment by tiffanynolan** [comment]
Given the timeline, the Integreatly team went with @bdellasc's proposal as a custom, interim solution for now. @katierik We're happy to share the code if you wanted to be consistent with our interim solution. @dlabaj worked on it as an animated icon. We'll circle back to consume the PF4 approved spinner post-Summit.

**Comment by ryelo** [comment]
@tiffanynolan that would be awesome. Do you have a source file for this that I could port over?

**Comment by katierik** [comment]
> Leaving an explanation here of @mceledonia, @kybaker's and my recent discussion on Spinner. @bdellasc I took the design back to Michael, we had a discussion, and we decided to move forward with a more robust spinner design which should work well across products. Let me know if you have any questions!

Can someone expand on what "more robust" means here? Are there specific technical and/or accessibility issues that need to be addressed?

**Comment by rachael-phillips** [comment]
Hi Katie, When I spoke with @mceledonia we discussed that this spinner would work better across all applications. All I mean by "more robust" is that you can see there are adjustments to the animation. That was my wording. @mceledonia do you feel there are anymore technical or accessibility issues that your design will address?

**Comment by mceledonia** [comment]
No big technical or accessibility issues that are solved here, it is purely an aesthetic improvement that will help the overall experience look and feel more modern. A custom implementation does give us more control which I suppose is a technical benefit. From a developmental perspective it will serve as the kickoff or gateway to figuring out how and where to implement animation across the rest of the system. 

I'll attach a video file here... Download and enable loop on your video player for the full effect. This is just a concept and no development work has been done on it yet. We would ideally want to build and animate this in the browser, as opposed to using something like an animated gif.


[Spinner Test 2.mov.zip](https://github.com/patternfly/patternfly-next/files/3004859/Spinner.Test.2.mov.zip)

**Comment by bdellasc** [comment]
@mceledonia can you please provide @srambach with the source files for the chosen spinner direction? We're assuming you have some source files used to generate the animation you posted in that last post?

She came to me asking for the old InVision links that no longer exist, but those aren't aligned with the chosen direction anyway. I checked the Google drive folder in the original story description and didn't see anything up there aligned with the final decisions made.

**Comment by mceledonia** [comment]
Adding this breakdown of our proposed spinner design:

![Spinner Breakdown 2](https://user-images.githubusercontent.com/30935938/62150379-e2854200-b2cb-11e9-99a9-afd43fbf43df.gif)

**Comment by SpyTec** [comment]
Spinner looks great! Will there be design recommendations for the usage of the spinner? 

For my application I need to load the initial state, so I was thinking of putting a spinner inside a modal that covers part of the application which you can't use yet, but this might be different to how other people are or will be doing it

**Comment by bdellasc** [comment]
For our product's current need, we're planning on using the animation it in the PF empty state (where the icon typically appears) to indicate an indefinite loading state. We're planning on only using the title and not the description or action button. This is a temporary approach we're taking until PF could come back with more specific guidance around the idea of the indefinite loading state.

**Comment by mcarrano** [comment]
There is an open issue in our backlog here for writing guidelines regarding data loading: https://github.com/patternfly/patternfly-org/issues/717  Any comments, input is welcome.
