### ISSUE TITLE
Forms design review

### ISSUE THREAD

**Issue by andresgalante** [patternfly/patternfly-next#291]
Review with the design team how to handle require fields, info tips, and states like error, success and warnings

**Comment by mcarrano** [comment]
@andresgalante @LHinson I've captured requirements for these items in an issue here #200 . @sjcox-rh is working on visuals after which time we should definitely have this review.

**Comment by LHinson** [comment]
Thanks @andresgalante. I'm going to close this issue since it's being tracked in a number of other places including: 
- #200
- #260
- #259
