### ISSUE TITLE
Canvas View Demo (on hold)  

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#292]
Canvas is not seen in PF3 core there is not required for feature parity for core. 

This feature requires conversation about the appropriate place this should live. Angular has a canvas component: https://www.patternfly.org/angular-patternfly/#/api/patternfly.canvas.directive:pfCanvas but there is no canvas seen today in core. 

If this moves forward, this issue will require to be kicked back to discovery/ixd/visuals before moving on to development. 

https://www.patternfly.org/pattern-library/content-views/canvas-view/

**Comment by matthewcarleton** [comment]
@LHinson should this be moved to React?

**Comment by LHinson** [comment]
@matthewcarleton  It's a core issue because the issue will require to be kicked back to discovery/ixd/visuals before moving on to development. That design work is tracked in this repo.

**Comment by rachael-phillips** [comment]
We are closing this because it is a large effort and there has been no ask to date.
