### ISSUE TITLE
Empty State Component

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#293]
Visuals want to look at this to refine that visual approach. 
The ixd/behavior will remain as seen here: https://www.patternfly.org/pattern-library/communication/empty-state/

**Comment by mceledonia** [comment]
Screens shared at demo 9/18/18
[Empty State Demo.pdf](https://github.com/patternfly/patternfly-next/files/2393889/Empty.State.Demo.pdf)

**Comment by mcarrano** [comment]
Per discussion in 9/20 PF Design Sync, want to add an example that shows what to do if there are multiple secondary actions or links.

**Comment by mcarrano** [comment]
Per discussion with @kybaker I am marking this as 'design approved' and ready for implementation. In HTML/CSS creating examples, however, we should allow for multiple secondary actions using the link-button style defined in the visual mockups.

**Comment by mcoker** [comment]
@mcarrano re: 

> we should allow for multiple secondary actions using the link-button style defined in the visual mockups.

would those additional actions stack vertically so you might have primary on top, secondary under primary, tertiary under secondary?

@mceledonia it looks like the empty state is always vertically centered in its parent? Assuming so, can you explain what this variation represents where it's vertically aligned to the top of its parent?

<img width="1229" alt="screen shot 2018-11-13 at 3 52 11 pm" src="https://user-images.githubusercontent.com/35148959/48445552-73c38100-e75c-11e8-9c07-8c6edd27b672.png">

**Comment by mcoker** [comment]
@mceledonia

* how big should the icon be? Is this size icon something we'll re-use? As in, should I create a variable for it (or even create sm, md, lg, etc sized vars for creating different sized icons)? Or is it a one-off?
* what should the max-width be? 
* can you confirm the padding to use around the whole component (top/bottom/left/right), between each section, then between buttons?

**Comment by mceledonia** [comment]
@mcoker Great questions!

- The icon size should be 54px. I suspect this is a one-off, as any other icons will be significantly smaller.
- In my mockups I am using a max-width of 400px, let's try that and see how it works.
- Padding
     - Between icon and header: 32px
     - Between header and description: 16px
     - Between description and button: 32px
     - Between button and secondary button: 16px
     - Padding around entire component, all sides: 32px
     - Note about padding:
          - In my mockups, in addition to the padding, I have the entire component centered in whatever it is contained in, both horizontally and vertically. Often times the component is in a space that is larger than the padding anyways which is why I wanted to note this.

**Comment by mcoker** [comment]
Also from @mceledonia 

* the title is the only required element in empty state
* action buttons should vertically stack on top of one another
* empty state should always be vertically centered (even in responsive view)

**Comment by mcarrano** [comment]
@mceladonia is it true that the secondary actions will always stack even it there are multiple secondary actions? That's not necessarily what I expect.

**Comment by mcoker** [comment]
@mceledonia ^^

**Comment by mcoker** [comment]
we also updated the spacing so there is

* 24px between icon and title
* 16px between title and body
* 32px between body (or title, if body not present) and actions
* 8px between buttons
