### ISSUE TITLE
Inline Edit on Forms

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#295]
Use the current documentation to mock up what inline edit would look like for pf-next: https://www.patternfly.org/pattern-library/forms-and-controls/inline-edit/

From these designs, CSS/Visuals/IxD to have conversation on how to build to it and break down into small issues.

**Comment by mcarrano** [comment]
@LHinson Note that the current Inline Edit pattern really contains 3 separate things: an editable list view, an editable table view, and an editable text field. I think this issue really addresses the last item. Inline editing for lists and tables will be covered in the List/Table component that I am writing requirements for.

**Comment by mcarrano** [comment]
Since I opened a separate issue (#404) to address inline edit in lists and tables, I have renamed this to "Inline Edit on Forms." This refers to the ability to make single fields editable so changes can be made without reloading the form.

**Comment by mcarrano** [comment]
Capturing requirements and concepts here: https://docs.google.com/document/d/1oTqG-Ow6qk-9_3Vw-EVKx2RkHLBe8cuwqkpPferWSg4/edit?usp=sharing

**Comment by rachael-phillips** [comment]
Hi Matt and @bkjeffer how is this coming along? Curious to hear an update

**Comment by mcarrano** [comment]
@rachael-phillips I believe that the basic interaction pattern is defined pretty well in the attached document. The only thing missing may be some visual design attention before this is ready to hand off to development.

**Comment by mcarrano** [comment]
I think that we have a good conceptual approach on this. I am going to kick it back to the backlog and tag for Visuals as I think that is the next step.

**Comment by mcarrano** [comment]
I agree that it makes sense to look at form level and table level edit together so I am going to assign this one to you, also.

**Comment by maryshak1996** [comment]
@mcarrano @kybaker 
I made the updates since our sync up yesterday and have updated this document: 
https://docs.google.com/document/d/15aOWgpkd0Zp0hvbKM4jfG6Jf00FHjY_f92bkosbo1Ds/edit?usp=sharing
As far as I'm concerned this is ready to move to CSS

**Comment by mcarrano** [comment]
This looks great @maryshak1996 ! Much simpler. I agree that this is ready to move along. Was the Marvel prototype also updated?

**Comment by maryshak1996** [comment]
@mcarrano great! The Marvel and SketchCloud links are in that doc at the top, but I'll attach them here as well:
Marvel: https://docs.google.com/document/d/15aOWgpkd0Zp0hvbKM4jfG6Jf00FHjY_f92bkosbo1Ds/edit?usp=sharing
SketchCloud: https://sketch.cloud/s/dWE5m

**Comment by mcarrano** [comment]
Design complete. @gdoyle1 does this require an addition to the symbol library?
