### ISSUE TITLE
Card View Demo

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#297]
Card view demo includes: 
- Navigation/header 
- page layout
- Toolbar 
- pagination 
- card examples as seen here: http://www.patternfly.org/pattern-library/content-views/card-view/#design

**Comment by matthewcarleton** [comment]
@LHinson this seems to be the same as what we have for page layout. Do we just want to add pagination to that when it's ready and close this?

**Comment by LHinson** [comment]
again, an issue for a demo - will be leveraged for the website

**Comment by mcarrano** [comment]
I have created an initial design doc here that includes requirements and some wireframes: https://docs.google.com/document/d/1NCjv5HbpjLbBwgpb4WcY4YMnE1hub4SJvMUfvycvPX8/edit?usp=sharing  These closely mirror what we have for PF3. I have reviewed these with @mceledonia and am ready to hand this off to visual design. @mcoker you might also want to take a look to see if this is consistent with your expectations. Basically I see the need for a Card Grid component to support this which would be a way to lay out cards in a flexible responsive grid.

In the doc, you'll see some designs for dragging and dropping cards to reorder the grid. While this is typical functionality for such a component, the design and implementation cost of this is potentially high. For PF3, we have a design but no implementation for this. @rachael-phillips do we have this requirement for PF 4.0? If not, I think we can defer to later. What do you think?

**Comment by mcarrano** [comment]
@gdoyle1 will create hi-fidelity mockups based on my wireframes for the basic card view, only (no drag and drop). @mcoker let @gdoyle1 or I know if you have any questions as you begin to implement, but this should be a pretty straight forward grid of cards with appropriate spacing. The grid must be responsive, of course. 

The contents of the cards can be any layout based on the card variations that @mceledonia has worked on. Perhaps like for list view, we can pick something that makes a good demo. Assumption is that like the data list, all cards must adopt the same layout.

**Comment by mcoker** [comment]
@mcarrano looks good.

> I see the need for a Card Grid component to support this which would be a way to lay out cards in a flexible responsive grid.

Are you proposing a new layout/component that is different from the existing grid layout? You can see an existing demo of cards in the [page component demo](https://pf4.patternfly.org/demos/Page/examples-full/?component=Page%20Component%20Default%20Nav%20Header%20Example) that uses our existing grid layout.

**Comment by mcarrano** [comment]
The existing grid layout should suffice @mcoker  . So then I think all this story is about is creating a demo that adds a toolbar above the card grid and an optional pagination footer in a full page layout (like what we did for data list and table demos). We can define some sample card content that is representative to support checkbox selection and/or actions. This should not require any new components or layouts IMO.

I think next steps then are to wait for mockups from @gdoyle1 and then have you or another CSS implement those. Does this make sense?

**Comment by mcoker** [comment]
Yep, great, thanks @mcarrano.

**Comment by rachael-phillips** [comment]
@gdoyle1 how is this one going? Can you give me a status on design?

**Comment by gdoyle1** [comment]
@rachael-phillips @mcoker @mcarrano Sorry guys! I didn't see this notification until now. Here's what I came up with! https://redhat.invisionapp.com/share/ZFQQYJQGWHV

**Comment by gdoyle1** [comment]
https://redhat.invisionapp.com/share/ZFQQYJQGWHV#/352046639_Toolbar_In_Card_View_Example @mcarrano Updated the wireframe here - thoughts?

**Comment by mcarrano** [comment]
@gdoyle1 I think this is now on the right track. There are just a few small things I would ask you to consider. Would we want the title of the card and the checkbox to be inline in the header area? It feels like wasted space to have the checkbox occupy a row to itself. Also, should buttons at the bottom of a card be center-aligned or left-aligned as you have them. @mceledonia perhaps you can give this a look as I know you were working on a set of generic card layouts for something like this.

The only other thing I wonder is if we should show a version with pagination. I'm wondering what the pagination below the card grid needs to look like. is this just in a card that sits below the grid as the toolbar sits above? Also, in the absence of pagination, do we need an item count to the right?

**Comment by gdoyle1** [comment]
@mcarrano I talked with @mceledonia about this and we agreed upon this card view https://redhat.invisionapp.com/share/ZFQQYJQGWHV#/352046639_Toolbar_In_Card_View_w-out_Pagination_Example. I created another mockup with pagination in the InVision project as well. Let me know if you need me to make any changes!

**Comment by gdoyle1** [comment]
@mcarrano I'm not sure about the checkbox - I assume it'll have to be it's own element but I'm probably not the right person to ask about that. The extension of the pagination footer is something I did so that it would be consistent with the toolbar. I expected it would act as it does on data tables/lists and would fall at the bottom of the content view. It looks funny when not extended because it just floats.

**Comment by mcarrano** [comment]
Regarding the pagination footer, I think what you say makes sense @gdoyle1 . So the footer would just extend to the bottom of the page then. @mcoker let me know if you see any difficulty with this layout.

**Comment by gdoyle1** [comment]
I think this is good to go now @mcarrano - https://redhat.invisionapp.com/share/ZFQQYJQGWHV

**Comment by mcarrano** [comment]
Looks great @gdoyle1 !

**Comment by gdoyle1** [comment]
After our conversation last week, here's what I came up with. If anyone has an idea of what the description text should be, please let me know! https://redhat.invisionapp.com/share/ZFQQYJQGWHV @kybaker @mceledonia @mcarrano

**Comment by mcarrano** [comment]
Looks good to me. I don't have a better idea for description text. What you have is fine @gdoyle1 or you can just use "lorem ipsum" placeholder text.
