### ISSUE TITLE
Background image system

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-next#323]
This is in regards to #322 

There are still things we need to decide with the backgrounds:

1. Will we support retina devices.
2. Do we have one solution that works in all scenarios (full page, dashboard, other layouts). This will mean full page images all the time vs background images provided for the specific layout.
3. Do we provide multiple image options? These wouldn't get shipped but be offered as additional downloads.
4. Do we provide an automated technique to create the  images required for different screen sizes/resolutions? The alternative is creating a document that states the details to produce the images required.
5. What are the break points for the images?

This is what I can think of after discussing with @kybaker and @mceledonia. I'm assuming as layouts come together we will have a better idea of is needed.

There was further discussion about this with @dmiller9911 and @srambach about using variables to set the images which makes a lot of sense.

**Comment by matthewcarleton** [comment]
Just met with @kybaker and @mceledonia and came to these conclusions:

We will support retina via media queries

We should use one image for all components to take advantage of caching. So regardless of the size of the image required we will use the same large image. This means we will need an image that fits the largest use case.
We ship with just image.

@andresgalante I'd like to discuss this a bit more with you, but my thought is the background image component will just apply the filter to the background but leave the component to handle the image.

**Comment by andresgalante** [comment]
3 and 4 are out of scope for this issue since they are built related questions.

the answer to 5 is to follow our breakpoints.

The background image has a bug at this moment that is not covering the screen, probably related with the background size. Let's address that too.
