### ISSUE TITLE
Application launcher demo 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#332]
Once #168 has been completed, we can build a demo for the application launcher as seen ehre: http://www.patternfly.org/pattern-library/application-framework/launcher/#/design

**Comment by rachael-phillips** [comment]
Supporting Wireframe from OpenShift:

![image from ios](https://user-images.githubusercontent.com/40275806/50226677-d4546800-0371-11e9-9d9f-ca930df18950.jpg)

**Comment by dlabaj** [comment]
Added an example in react on how to implement this with the drop down.  See PR 1127 in @patternfly/react-core .  

https://github.com/patternfly/patternfly-react/pull/1127
https://1127-pr-patternfly-react-patternfly.surge.sh/patternfly-4/components/dropdown

**Comment by dlabaj** [comment]
After discussion with team we are going to add a React PF4 component for the app launcher. 
This is currently being tracked by the following issue:

https://github.com/patternfly/patternfly-react/issues/1130

**Comment by rachael-phillips** [comment]
@dlabaj can we go ahead and close this?
