### ISSUE TITLE
Create example pages demonstrating before and after migration from PF3 to PF-next

### ISSUE THREAD

**Issue by dgutride** [patternfly/patternfly-next#334]
Create simple HTML files files to show the class structure differences between PatternFly 3 and PatternFly 4.

Files can be gists that are shared.

**Comment by mindreeper2420** [comment]
@dgutride what type of example pages are you looking for? Something that mimics the current [Dashboard layout example](http://www.patternfly.org/pattern-library/dashboard/dashboard-layout/), or something simpler, like an OSIO dashboard?

**Comment by mindreeper2420** [comment]
[PatternFly 3 Card Example](https://gist.github.com/mindreeper2420/a623ceba6331e39a4b3cc137da45bb3d)

[PatternFly 4 Box Example](https://gist.github.com/mindreeper2420/d3c1ce839b9a702c33ba2f937e51d8e9)

**Comment by mindreeper2420** [comment]
@dgutride as part of the Upgrade Guide that was merged to master, do we want to add these examples to that guide, or just have a separate section of the repo for them?

**Comment by mindreeper2420** [comment]
@dgutride I created a test demo on a branch, showing the differences between PF3 and PF4 Cards: https://github.com/mindreeper2420/patternfly-next/tree/upgrade-examples. Both are viewable on the page, so users can easily compare the two.

**Comment by dgutride** [comment]
Closing based on above PR (#387)
