### ISSUE TITLE
Modal: Add the close btn as part of the modal component

### ISSUE THREAD

**Issue by christianvogt** [patternfly/patternfly-next#336]
The modal demos which include a close button seems overfly complex.

The button could be placed in the header and floated right to achieve the same result.

```html
        <div class="pf-c-modal-box__header">
          <button class="pf-c-button pf-m-action fa-pull-right">
            <i class="fas fa-times"></i>
          </button>
          <h1 class="pf-c-title pf-m-xxxl" id="titleID">
            Overwrite existing file?
          </h1>
        </div>
```

vs
```html
        <div class="pf-c-modal-box__header ">
          <div class="pf-l-split ">
            <div class="pf-l-split__item pf-m-primary">
              <h1 class="pf-c-title pf-m-xxxl" id="titleID">
                Overwrite existing file?
              </h1>
            </div>
            <div class="pf-l-split__item pf-m-secondary">
              <button class="pf-c-button pf-m-action">
                <i class="fas fa-times"></i>
              </button>
            </div>
          </div>
        </div>
```

**Comment by andresgalante** [comment]
We don't have a `fa-pull-right` class or any utility class in PF4.

We chose to use the split layout because since users heavily modify patternfly depending on their usecases, by position items within layouts across the system, we are giving them more flexibility at the cost of having more markup.

Ideally it'd be a spaced-between flex displayed `header` and the `title` and close `btn` would accommodate themselves. Since the modal should always have a close btn, have it as a default scoped to the component is not a bad idea.

What do you think?

**Comment by christianvogt** [comment]
Sorry the class name `fa-pull-right` was used in my testing and didn't change it. But as an example it's still valid.

If consistency is the goal, then I think treating the close button as a first class element is better. `pf-c-modal-bos__close` could be used instead of a utility class.

Since the button needs to appear inside the content area of the modal, absolute positioning of the button could cause layout issues. The layout needs to flow. This is why I suggested floating it.

It's also possible that one might use a modal without a header? If so, what's the markup for this use case with a close button? Using a flex layout here would create a vertical dead space beneath the close button as an entire column of space is reserved.

**Comment by andresgalante** [comment]
You are absolutely right, if the header is not present the close btn should be there, therefor is part of the component.

@LHinson Should I create a issue to make this change or can this issue became the task?

**Comment by LHinson** [comment]
We can use this issue, just update the description as necessary @andresgalante

**Comment by andresgalante** [comment]
After talking with the CSSers we've decided to create defaults for the modal box. This means:

- It should have a close btn.
- It should have a title.
- the footer should position the action btns.

While making this change lets make sure that this can easily be modifiy with the layout if the user wishes to.

**Comment by mattnolting** [comment]
The demos also share a common title styling, I think that too should be a first class element. @andresgalante @christianvogt What do you think?

```
  <div class="pf-c-modal-box__header">
    <button class="pf-c-modal-box__close" aria-label="Close Dialog">
      <i class="fas fa-times"></i>
    </button>
    <h4 class="pf-c-modal-box__header-title" id="modal-example">
      Modal Header
    </h4>
  </div>
```

**Comment by christianvogt** [comment]
@mattnolting yes agreed

**Comment by dmiller9911** [comment]
@christianvogt @mattnolting  Why is the modal close button different from other action (icon) buttons?

**Comment by christianvogt** [comment]
@dmiller9911 from a button perspective it's no different. My original concern was with regards to layout.

**Comment by dmiller9911** [comment]
would it be possible to just do `<button class="pf-c-button pf-m-action pf-c-modal-box__close">X</button>` the modal close taking care of the positioning? Or would that stray too far from principles? 

The alert component has something similar where the element inside the component is just a container with the positioning, and then a button is placed inside of that. For modal it might be something like
```html
...
<div class="pf-c-modal__header">
   ...
  <div class="pf-c-modal__close">
    <button class="pf-c-button pf-m-modifier">X</button>
  </div>
</div>
...
```

**Comment by christianvogt** [comment]
@dmiller9911's suggestion aligns with what I originally proposed.
