### ISSUE TITLE
Syntax Highlighter 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#344]
Identify a syntax highlighter to use with PF4. 

Notes: 

- PF3 used Google Code Prettify. 
- Once this has been identified and introduced, we need to create an issue to introduce a theme. There is an open question on where the theme should live (e.g new repo with a highlighter theme that PF can consume or have the CSS live within PF core or contribute upstream to that library)

**Comment by matthewcarleton** [comment]
@LHinson @dgutride is this a concern for core or can we close this?
