### ISSUE TITLE
Language selector demo 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#349]
The language selector is a dropdown. A demo would need to be created to show specific example. https://www.patternfly.org/pattern-library/forms-and-controls/language-selector/#design

**Comment by matthewcarleton** [comment]
I think we can close this. We can create this with the dropdown component.

**Comment by LHinson** [comment]
@matthewcarleton exactly. This issue is not to create a new component but to create a demo that can be used to show a specific example via our website.

**Comment by matthewcarleton** [comment]
ok thanks @LHinson. Do we want a demo specifically for the language selector? We already have it included in the login demo.

**Comment by mcarrano** [comment]
IMO, we should have a demo that shows how/where this sits in the utility area as we do for PF3. In that case it's part of the User menu. I don't know if we have a PF4 design for that. @matthewcarleton, perhaps you @kybaker and I should sync on this.

**Comment by LHinson** [comment]
@mcarrano makes sense to sync but, for now, these demos are not priority. We have a number of components and css architectural discussions/efforts that should be priority right now.

**Comment by mcarrano** [comment]
I agree @LHinson . This is way down on the priority list IMO.

**Comment by mcarrano** [comment]
Need to reconsider placement on login page over dark background.

**Comment by rachael-phillips** [comment]
@mcarrano I see this and will keep this in mind that we will need visual work done on this.

**Comment by mcarrano** [comment]
I think we resolved this. Can open a new issue if there is still something to address. Will close.
