### ISSUE TITLE
Tour

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#351]
Introduce a pattern for "Tour". We should look at the design defined for pf3 [1] and determine if the design to improve it and ensure it's common.

[1] https://www.patternfly.org/pattern-library/communication/tour/#design

**Comment by sdash-redhat** [comment]
Here is the link to the document 

**https://docs.google.com/presentation/d/18AWdUxsQjvXxHNB9lw1IbuSUmLhezP8ikOCZormq4dE/edit?usp=sharing** 

where I have tried to identify and group the different types of tours, that we can make as a part of the proposal. 

Each type can be explained based on when to use and the details of its components. 
Please let me know your thoughts on this approach.

 @mcarrano  @muruGanesan @catrobson @stacymcauliffe

**Comment by sdash-redhat** [comment]
Here is the initial explorations  document created by  @muruGanesan 
**https://docs.google.com/document/d/1XVlj58ddsCxd2_LoszxskttzJ95Ejs23eUApGipw93E/edit#heading=h.exfq7bu9rdpp**

We can use both the documents to aid the discussions. 
@mcarrano @muruGanesan @catrobson @stacymcauliffe

**Comment by rachael-phillips** [comment]
Hi @sdash-redhat thank you for adding all of this helpful information. A few quick questions:
* What product/project does this impact?
* List any product/project release(s) and timelines your trying to align with
* Are you interested in HTML/CSS only or leveraging a PF-React implementation?

**Comment by muruGanesan** [comment]
> Hi @sdash-redhat thank you for adding all of this helpful information. A few quick questions:
> 
>     * What product/project does this impact?
> 
>     * List any product/project release(s) and timelines your trying to align with
> 
>     * Are you interested in HTML/CSS only or leveraging a PF-React implementation?

Currently, there is no impact i.e. we are not targeting any project/product.
Regarding HTML/CSS - it is too early to decide

**Comment by SpyTec** [comment]
Just wanted to give my use case. Though this component would help, it's a low-priority for my project

I have an internal application which might be confusing for some. Of what each field does, what is taken into account when changing a specific field, or how it all hangs together.

Right now we’re putting all the details on a Confluence page which is linked at the top of the application. Having a tour that the user can initiate would make it possible to reduce that confluence page a lot and streamline the process to on-board people with the project a lot better

**Comment by rachael-phillips** [comment]
Thanks for posting this Eric!

**Comment by mcarrano** [comment]
I am going to close this out for now. Have archived the current set of designs for future reference. The feeling was that while Tours are definitely useful, this may be too product specific to warrant a general PatternFly solution. We can revisit when/if specific component needs arise.
