### ISSUE TITLE
Dashboard Card demo variations

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#355]
- http://www.patternfly.org/pattern-library/cards/aggregate-status-card/

Note: 
Cards seen in PF3 with chart examples will be introduced to react. 
http://www.patternfly.org/pattern-library/cards/trend-card/
http://www.patternfly.org/pattern-library/cards/utilization-bar-card/
http://www.patternfly.org/pattern-library/cards/utilization-trend-card/

**Comment by matthewcarleton** [comment]
I think this will need to be moved to React due to the JS requirements. I'm going to create an issue in React for this. Created [this issue](https://github.com/patternfly/patternfly-react/issues/862) in React repo.

**Comment by LHinson** [comment]
@matthewcarleton re-opening because this is tagged with "interaction design". Since we track interaction and visual design in this repo but not it might skip over to react.

**Comment by mceledonia** [comment]
Cards - New spacing logic

![cards spacing](https://user-images.githubusercontent.com/30935938/52368934-91337e80-2a1d-11e9-9b0b-e64c12424498.png)


@mcoker

**Comment by rachael-phillips** [comment]
@mceledonia are these the final designs on this issue?

**Comment by mceledonia** [comment]
@rachael-phillips Yes these are the final designs for the card structure.

**Comment by rachael-phillips** [comment]
Thanks so much @mceledonia !
