### ISSUE TITLE
Switch

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#361]
http://www.patternfly.org/pattern-library/widgets/#bootstrap-switch

**Comment by andresgalante** [comment]
@guillaumevincent has done a prototype of the switch toggle: https://codepen.io/guillaumevincent/pen/XEgxJB

**Comment by LHinson** [comment]
@guillaumevincent we would love for you to contribute this component. The switch does require some visual input and recommendation on how it should be styled and all of our visual designer are currently tied up with other priorities atm :/ 

Would you prefer to start a WIP or shall we wait until one the visual designer frees up to partner with you? 

FYI @kybaker

**Comment by guillaumevincent** [comment]
Started https://github.com/patternfly/patternfly-next/pull/724

**Comment by LHinson** [comment]
Great, sounds good @guillaumevincent! @kybaker is aware of this issue and PR and will review once he gets an opportunity to do so! Thanks for the help and your patience while we juggle priorities in PF4 :)

**Comment by maryshak1996** [comment]
I put together some component-type ideas for the switch, an mocked them up in a few different contexts. I'm not sure if I'm completely understanding the scope of what this issue is, so if anyone could provide some guidance on what what direction I should be moving in, that would be great!
![pf4-switcher-components](https://user-images.githubusercontent.com/19824574/45836367-a57b1700-bcda-11e8-9903-2a5d5775936e.png)
### Toggle Examples in Context 
**On-Off Switch with Exterior Text**
https://redhat.invisionapp.com/share/YVO65OIBR64
**On-Off Switch with Interior Text**
https://redhat.invisionapp.com/share/VXO65RJY35N
**Switch with Interior Symbols**
https://redhat.invisionapp.com/share/8YO65SS7RS3
**Switch with Text and Status**
https://redhat.invisionapp.com/share/VBO65S4SQCY

**Comment by guillaumevincent** [comment]
Thank you @maryshak1996,
I updated my pull request #724.
but I have some questions:

 * looks like in your example you have 3 states for the switch (off `#333333`, disabled `#AAAAAA`, on `#007ab9`) am I right? I find the state "off" very pronounced. And looks active.
 * IMO a switch should not have a disabled state. If we want a disabled state, we should had 2 disabled state (one for the `switch on disabled` and one for the `switch off disabled`) wdyt?
 
@mcarrano can we continue the discussion here about label inside the switch? Because my work use a fixed width for the label. If we use text inside the label, we will need to find another strategy to create the switch without javascript

@andresgalante I didn't find the good css rule for the label margin. I used the helper `pf-u-mr-md` directly applied to my label. Can you tell me wdyt?

**Comment by maryshak1996** [comment]
@guillaumevincent thanks for the feedback! To address your questions:

- The three states (on, off, and disabled-viewable in both on and off options), these options were pulled directly from the PF4 visual assets for form and control elements so I'm not sure that I can speak to that portion, as I didn't propose the styling of the basic toggle element. I am meeting with @kybaker soon and we can discuss this
- Similarly to above, I didn't propose the treatment of the states, so I will have to get back to you on this!
- In terms of the margins and sizing of the switch, I wasn't aware of how sizing is being dealt with for PF4 so I can certainly create some updated mocks where the size/margins of the switch is dependen on the context of what it's in, as opposed to set margins for the switch itself
Stay tuned for some more updates :)

**Comment by mcarrano** [comment]
@guillaumevincent While I agree that it's not typical to have disabled switches, if you think of the switch as an alternative to a checkbox, there could be situations where you would use a switch to reflect current state but not allow the user to change this setting. To be safe, I think we should support a disabled state.

As for your other question about the label, are you saying that we should not support an option with the text ("on" or "off") inside the switch? If that's an implementation concern, I'm OK with that as long as it's clear visually what state the switch is in and there are no accessibility concerns.

**Comment by guillaumevincent** [comment]
@maryshak1996 thank you

@mcarrano we can probably do a survey and ask people if the grey switch in a form mean disabled switch. I think it requires a cognitive effort to understand that it's a disabled state. And I found weird the same color for disabled switch on and off. But it's just my feeling so maybe not relevant.

> are you saying that we should not support an option with the text ("on" or "off") inside the switch?

If we want to add a text `on` and `off` inside the switch, we will probably need to make the size of the switch variable (to support i18n for example or different text) Without JavaScript and with the actual CSS code only we can't do this. Solutions are:

 * I stop what I'm doing and work on a CSS only solution making the switch width adjustable (different switch width could be bizarre)
 * Keep the switch as today and accept label inside the switch between 3/4 chars length max. So on/off are good labels but active/inactive are not good label.
 * Keep only "on" and "off" text and don't think about i18n
 * Drop text inside the switch < this is the actual code

is that clear?

Thanks

**Comment by mcarrano** [comment]
@guillaumevincent Good point about using the same color treatment for disabled-on or disabled-off. @maryshak1996 @kybaker what do you think?

Yes, I understand now what you are saying about the label. Again, I'll defer to the visual designers on whether this is important. Agree we should not over-complicate it.

**Comment by maryshak1996** [comment]
Hi all! Thanks again for the feedback. I met with @kybaker to discuss visuals more in-depth and made some adjustments and, for the scope of this issue, some simplifications as well. 
### General Updates Made
- I got rid of the concepts that had anything _inside_ the toggle (be that text or icons) to alleviate any issues with sizing and i18n conflicts
-Revisited the colors used for the different states, and I think that having the disabled colors be the same for both on and off is how we should move forward. It is more streamlined that way, and would help avoid any confusion around if something is disabled or not. If a toggle is not enabled, it seems most important that it be clear that the toggle is disabled (once in that state, a user can tell if the toggle is switched to the left or right). And I think that it makes sense that the color reflects that level of importance. I did update the color used for the text in both enabled and disabled states based on the most up-to-date PF4 color guidelines (see attached screenshot) so now the text label colors are aligned with the general text treatment. 
### Mockup Updates | Toggle with Text Labels & Toggle without Text Labels
- Take a look at this new InVision : https://redhat.invisionapp.com/share/DGO8O3Y592Z
### PF4 State Colors
![statecolors](https://user-images.githubusercontent.com/19824574/46026315-15154b80-c0b9-11e8-89ca-d84a306fda63.png)

**Comment by guillaumevincent** [comment]
@maryshak1996 thank you for removing the need of inner icon or text. It will help to start with something simpler.

To be sure I understand correctly

 * disabled toggle

label off `#72767B` `50%` 
toggle background `#bababa`
toggle thumb `#ffffff`
label on `#72767B` `50%` 

 * off toggle

label off `#72767B`
toggle thumb `#ffffff`
toggle background `#bababa`
label on `#72767B` `50%` 

 * on toggle

label off `#72767B` `50%` 
toggle thumb `#ffffff`
toggle background `#0085ca`
label on `#72767B`

I will try to find the appropriate colors in the variables css.
I will update my pull request tomorrow.

> and I think that having the disabled colors be the same for both on and off is how we should move forward

I think you're right. For me the visual difference should be in the labels and the mouse pointer :no_entry_sign:.

**Comment by mcarrano** [comment]
Looks good to me!

**Comment by maryshak1996** [comment]
@LHinson for some reason a couple of those hex colors aren't what I have on my end in the sketch file -- I'm attaching a screenshot of color specs to make sure it's clear!
<img width="478" alt="color specs" src="https://user-images.githubusercontent.com/19824574/46036648-08eab780-c0d4-11e8-8c69-012d799bf48c.png">

**Comment by guillaumevincent** [comment]
Thank you, I updated my pull request.
You can see it live https://deploy-preview-724--pf-next.netlify.com/components/switch/examples/

I don't know yet why an active label doesn't look like your image with the color `#72767b`.
I probably miss something.

**Comment by mcarrano** [comment]
These looks great @guillaumevincent . But I do have one general question. Should we have a variant of this without labels? There may be situations where I am space constrained and I just want a switch. I'm thinking for example within a table where I have a heading at the top of the column and I don't want to allocate so much column width to have the Off and On labels.

**Comment by guillaumevincent** [comment]
@mcarrano I will add one variant yes

**Comment by guillaumevincent** [comment]
I updated my PR
[demo](https://deploy-preview-724--pf-next.netlify.com/components/switch/examples/)

**Comment by mcarrano** [comment]
Looks good. Thanks @guillaumevincent !

**Comment by LHinson** [comment]
@mcarrano mind adding your review over on the PR? 
I'll see if we can get a CSS review on the PR as well to keep this moving along. @guillaumevincent will you remove "WIP" so that everyone knows this is in a more final state?

**Comment by guillaumevincent** [comment]
@LHinson done

**Comment by maryshak1996** [comment]
Here's an updated PDF of form-related elements where my mockups can be found (not sure where this PDF should go in the PF4 folder so I'm just sharing this file individually and can move it if needed) and the master sketch file is updated with mocks as well :) 
https://drive.google.com/file/d/1OgNHIjLWRONEmMC0D-elWdeukX9m0w1Z/view?usp=sharing

**Comment by mceledonia** [comment]
Here is an animated mockup of how I envision the final switch behavior.


[Switch Animated 1.mov.zip](https://github.com/patternfly/patternfly-next/files/2465775/Switch.Animated.1.mov.zip)

**Comment by mcarrano** [comment]
@mceledonia Thanks for creating the animated mockup. I like the position and use of the single label. But to me this feels a bit backwards. Usually when I see switches, swiping to the right turns the switch on. Looks like you have this reversed. Was that the intent? What do others think?

**Comment by mceledonia** [comment]
@mcarrano You are completely right, I don't know how I missed that! Let's pretend it's flipped here.

**Comment by maryshak1996** [comment]
@mceledonia I really like this!

**Comment by LHinson** [comment]
Closed by #724
