### ISSUE TITLE
Global variables: Make sure variables values are correctly name

### ISSUE THREAD

**Issue by andresgalante** [patternfly/patternfly-next#365]
Global variables values are oddly named, for example

```scss
$pf-global--Color--light-100:      $pf-color-white !default;
$pf-global--Color--light-200:      $pf-color-black-200 !default;

$pf-global--Color--dark-100:      $pf-color-black-900 !default;
$pf-global--Color--dark-200:      $pf-color-black-600 !default;
```

Make sure that 100 is lighter than 200, the lower the number, the lighter the color is.

**Comment by matthewcarleton** [comment]
This is something I did. At the time I thought it made sense that light-100 would start with the lightest and dark-100 would start with the darkest.

**Comment by andresgalante** [comment]
ok, lets see if it makes sense to others and close this issue if it does

**Comment by andresgalante** [comment]
I'll close it since for theaming this makes sense
