### ISSUE TITLE
Icon Demo

### ISSUE THREAD

**Issue by mindreeper2420** [patternfly/patternfly-next#370]
Create a demo page showing the icons that are available in PatternFly 4.

Based off of the simplified icon list from PR https://github.com/patternfly/patternfly-next/pull/325.

**Comment by matthewcarleton** [comment]
@LHinson I think there's lots of work around icons that needs to be addressed and having a list of what we offer is a great idea. This could be moved up on the list of priorities.

**Comment by rachael-phillips** [comment]
@matthewcarleton are we ready to close this out based on #830 and the icon list we offer in the Sketch file?

**Comment by mcarrano** [comment]
We are addressing icon issue elsewhere.
