### ISSUE TITLE
Avatar - Design Doc

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#372]
Document usage guidelines for Avatars.

Related issue: https://github.com/patternfly/patternfly-next/issues/135

**Comment by matthewcarleton** [comment]
@mcarrano is this completed now? Can we close this?

**Comment by mcarrano** [comment]
No, please keep open @matthewcarleton . There are a bunch of doc issues that I added to the backlog months ago. We may or may not decide that we need a design doc here, but want to keep this open until we have more clarify about the organization of content on the website.

**Comment by maryshak1996** [comment]
@mcarrano I'm not sure if it's anything that would be of use to you but we have this issue about the visual design of the PF4 avatar too https://github.com/patternfly/patternfly-next/issues/826
