### ISSUE TITLE
Icons - Add PatternFly 3 icons

### ISSUE THREAD

**Issue by mindreeper2420** [patternfly/patternfly-next#375]
Add the PatternFly specific icons from PatternFly 3 that were not transitioned to Font Awesome 5 icons.

![pf4icons](https://user-images.githubusercontent.com/4032718/41484193-e6c53d08-70a9-11e8-85e5-482db6ad92d7.png)

**Comment by mindreeper2420** [comment]
Here is a zip of the icons as SVGs with SCSS variables and the proper font files. Built on a 16px grid.

[patternfly4.zip](https://github.com/patternfly/patternfly-next/files/2111925/patternfly4.zip)

**Comment by mcoker** [comment]
These were added - https://pf4.patternfly.org/icons
