### ISSUE TITLE
About Modal - Design Doc

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#383]
Introduce design documentation for the About Modal demo. Considerations to include:

* What types of content should be present in an about modal.
* Content guidelines.
* Guidance on version numbering
* Variations and usage.

Related issue: #104 

Existing PatternFly 3 About Modal documentation: https://www.patternfly.org/pattern-library/communication/about-modal

**Comment by stacymcauliffe** [comment]
Submitted PR for review

**Comment by mcarrano** [comment]
PR has been merged.
