### ISSUE TITLE
Abstract disabled styles

### ISSUE THREAD

**Issue by ryelo** [patternfly/patternfly-next#392]
Looking at how disabled styles are implemented, there's probably a way to make things less repetitive.

Issues that can be solved:
* Disabled buttons, dropdown anchors don't have a `cursor: not-allowed` whereas SecondaryNav and Forms do.
* SecondaryNav disabled elements can still be hit with a tab key unlike Buttons and Forms

**Comment by rachael-phillips** [comment]
Hi @ryelo is this still a need or has this need passed?

**Comment by ryelo** [comment]
@rachael-phillips I think this is good to close now.
