### ISSUE TITLE
Upgrade Example Questions

### ISSUE THREAD

**Issue by mindreeper2420** [patternfly/patternfly-next#395]
In reviewing the Card Upgrade Example PR, it was found that there are discussions that need to be had around long-terms plans for showing how to upgrade from PatternFly 3 to PatternFly 4.

So far, we have the following concerns:
- Copying styles from PF3 to PF4: do we need to do this for all examples?
- A dedicated site for showing upgrade examples
  - can we do this?
  - is it necessary? (how many examples will there be?)
- We need to determine how many upgrade examples are needed
  - how many variations of a component are needed?

@matthewcarleton @jgiardino

**Comment by jgiardino** [comment]
Thanks for creating this issue, @mindreeper2420!

Some other things that came up when we were chatting about this:

- For viewing before/after examples, would another layout work better than the current one?
- Should we isolate examples, and separate layout examples from component examples? There are some cases in PF3 where parent wrapper classes are needed for the component to render correctly, like with cards, which makes decoupling component from layout a little weird.
- Should there be 3 examples in a migration demo?: 
  1. show the PF3 component
  2. show the PF4 component with PF3 theme
  3. show the PF4 component with PF4 theme

**Comment by rachael-phillips** [comment]
Closing this as we decided to remove upgrade examples from the workspace.
