### ISSUE TITLE
Review and consolidate modifiers class names

### ISSUE THREAD

**Issue by andresgalante** [patternfly/patternfly-next#398]
The list of modifiers has grown since we started: https://pf-next.com/modifiers

This task is to review the modifiers we've created, remove inconsistencies, and defined what each modifier does so in the future we can reuse them.

**Comment by matthewcarleton** [comment]
note: there is a script that updates the modifiers `npm run update-modifiers`

**Comment by michael-coker** [comment]
@matthewcarleton @jgiardino @srambach @andresgalante @mattnolting 

I created this document with my review. I have some action items at the top, some questions I'd love y'alls input on, and my review below that. Feel free to look over the whole thing or just the parts with questions and leave feedback in the document. We can also discuss this in a CSS meeting if that's easier.

https://docs.google.com/document/d/1pUnjn65G65vhv1aWQyarpRjD1_o0KsoFeQpeR5IPatw/edit?usp=sharing

**Comment by michael-coker** [comment]
We still have #538 and #539 that are related, but this issue doesn't need to be open for them to be completed. I'll go ahead and close it.
