### ISSUE TITLE
Design the inline editing for Tables

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#404]
Introduce inline editing to data tables. This should expend the basic design approach described in #199.

**Comment by LHinson** [comment]
@mcarrano #295 is redundant. Please confirm and close whichever one make sense.

**Comment by rachael-phillips** [comment]
Is the design on this complete?

**Comment by mcarrano** [comment]
No. This still requires design attention. I have not had time to get to it.

**Comment by katierik** [comment]
I've got a use case for this in Cloud Services Vulnerabilities. I want to be able to click a line in a table and edit the values involved. 

Rox gave me a demo of what they currently have in Satellite where the entire table is editable vs the row being editable on its own (which I see in the PF3 docs). I'd prefer row, but could make the other work.

**Comment by rachael-phillips** [comment]
Thanks @katierik ! Can you list any product/project release(s) and timelines your trying to align with?
Are you interested in HTML/CSS only or leveraging a PF-React implementation?

**Comment by mcarrano** [comment]
I reviewed requirements in the PF design sync meeting today and we agreed to start with looking for parity with current PF3 offering as implemented in the PF3 React repo. Corresponding PF3 designs can be found here: https://www.patternfly.org/pattern-library/forms-and-controls/inline-edit/  There should be three possible levels of editing:

* At the cell level, where user can make a single cell editable. [PF3 React implementation](https://rawgit.com/patternfly/patternfly-react/gh-pages/patternfly-3/index.html?knob-Edit%20whole%20table=true&selectedKind=patternfly-react%2FContent%20Views%2FTable%20View&selectedStory=Table%20With%20Inline%20Edit%20Cells&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)
* At the row level, where user can make an entire row editable. [PF3 React implementation](https://rawgit.com/patternfly/patternfly-react/gh-pages/patternfly-3/index.html?knob-Edit%20whole%20table=true&selectedKind=patternfly-react%2FContent%20Views%2FTable%20View&selectedStory=Table%20With%20Inline%20Edit%20Row&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)
* At the table level, where the entire table can be made editable. [PF3 React implementation](https://rawgit.com/patternfly/patternfly-react/gh-pages/patternfly-3/index.html?knob-Edit%20whole%20table=true&selectedKind=patternfly-react%2FContent%20Views%2FTable%20View&selectedStory=Table%20With%20Inline%20Edit%20Column&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)

Based on these requirements, next step would be to create visual mockups that consider how these interactions can live in the PF4 table approach.

**Comment by mcarrano** [comment]
@bkjeffer thanks for agreeing to create initial wireframes and interaction spec for this feature. @rachael-phillips FYI.

**Comment by mcarrano** [comment]
Capturing requirements and initial design concepts here: https://docs.google.com/document/d/1oTqG-Ow6qk-9_3Vw-EVKx2RkHLBe8cuwqkpPferWSg4/edit?usp=sharing

**Comment by bkjeffer** [comment]
Proposed wireframes in Invision: https://projects.invisionapp.com/boards/VR3U6GU9BM4/

**Comment by mcarrano** [comment]
I think that we have a good conceptual approach on this. I am going to kick it back to the backlog and tag for Visuals as I think that is the next step.

**Comment by maryshak1996** [comment]
Here's my working doc that outlines inline editing in different contexts, including tables: https://docs.google.com/document/d/15aOWgpkd0Zp0hvbKM4jfG6Jf00FHjY_f92bkosbo1Ds/edit?usp=sharing

**Comment by maryshak1996** [comment]
@mcarrano @kybaker 
I made the updates since our sync up yesterday and have updated this document: 
https://docs.google.com/document/d/15aOWgpkd0Zp0hvbKM4jfG6Jf00FHjY_f92bkosbo1Ds/edit?usp=sharing
As far as I'm concerned this is ready to move to CSS

**Comment by mcarrano** [comment]
Design complete.
