### ISSUE TITLE
Show, Hide, and Reorder Columns for Data Tables

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#406]
Introduce optional column management features for a data table, including show/hide rows and column reordering. This should extend the basic data table design described in #199.

**Comment by LHinson** [comment]
@mcarrano this should start with an evaluation of the reactabular behavior and identify any required adjustments to behavior. Also need to identify an required styling requirements.

**Comment by rachael-phillips** [comment]
Hi Matt, is this an issue that can be closed?

**Comment by mcarrano** [comment]
@rachael-phillips This is functionality that existed in the PF3 data table that I think fell off the table for PF4. It's still a valid issue, but not sure it has priority. Not clear if there's a need.

**Comment by mcarrano** [comment]
Will close. We can take on any future table enhancement requests as they come. There is currently an active request to show/hide columns here: https://github.com/patternfly/patternfly-next/issues/2461
