### ISSUE TITLE
Example of the PF3/PF4  HTML structure: Login page (demo)

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#420]
Create simple HTML files files to show the class structure differences between the login page for PatternFly 3 and PatternFly 4.

For this first issue, this migration doc will only address the basic login seen here: https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/login-basic.html

Note:
- Do not include additional components such as the toast alert
- Content/text of the two examples should match
- Since these are full page examples, this migration doc will require linking out to the examples
- Create notes that highlight the differences between these two implementations. You can see an example of this if you scroll down to the bottom of the Badge example https://pf-next.com/upgrade-examples/BadgeUpgradeExamples/examples/

**Comment by jameslau** [comment]
Not sure if there is an easier way to add an additional folder under upgrade examples on pf-next.com. @michael-coker suggested `pf generate demo`, but swapping out the `demo` for `upgrade-examples` does nothing.

<img width="750" alt="screen shot 2018-10-28 at 1 44 17 pm" src="https://user-images.githubusercontent.com/1402829/47619736-4d44eb00-dab8-11e8-9f8b-2252c781e831.png">

Any suggestions?

**Comment by LHinson** [comment]
looping in @dgutride

**Comment by jameslau** [comment]
Hey @LHinson & @dgutride, as of right now, I'm just moving files and folders along manually. Already have the login section going.

**Comment by dgutride** [comment]
Manual is good for now - we need to spend a little more time on this before we can update the generators.
