### ISSUE TITLE
Spike: PF3 theme for PF4

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#423]
Evaluate if and how we can provide a PF3 theme for PF4. This spike includes a test page that includes PF3 themed PF4 components with PF3 components.

**Comment by matthewcarleton** [comment]
I believe this is in a good place to move forward with. Please see [this document](https://docs.google.com/document/d/1h0-BgWvpYTQf6uYxQFdrgyslOqWR9xnRvk_Fzfuh8UY/edit?usp=sharing) which outlines this approach.
