### ISSUE TITLE
utilize handlebars consistently across all components and document

### ISSUE THREAD

**Issue by jlmitch5** [patternfly/patternfly-next#424]
currently, there are a few different approaches to using handlebars within the app.  All of these work (and they aren't hard to switch from one or the other), but it can be difficult for new devs to know which pattern is the one they should follow.  Discrepancies in the standard "one .hbs file in the root of the componet" include:

- Alert - has most of the markup in the examples/*.hbs files
- Card, Modal, SecondaryNav, Form - has separate root level components as well as root level components for sub elements

---

May also be good to document what the correct pattern to use is in the contributing guidelines.

**Comment by dgutride** [comment]
Closed via #399
