### ISSUE TITLE
create a pf version of the sr-only class

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-next#431]
Currently, the `sr-only` class is used for cases where additional text needs to be made available to screen reader users (e.g. it's announced by the SR, but not presented on the screen).

As part of this issue, we should 
- include "pf" for namespace and "u" for utility in the class name
- investigate alternative properties that we could use instead of the ones currently defined for `sr-only`
  - @andres mentioned that this was added to the html5 boilerplate but later removed. There might be some helpful information that we could dig up on that
  - He also mentioned that this class has come up a lot in the bootstrap project issues, so there may be helpful info there as well
  - I've also come across an example of this type of class in one of the examples at https://inclusive-components.
- Let's test whatever we come up with across different screen readers

**Comment by jgiardino** [comment]
@andresgalante @LHinson @dmiller9911 
Do you think this is blocking any of the work that is happening? Should this get moved up in priority?

**Comment by LHinson** [comment]
@jgiardino is this class standard across all screen readers or is this class targeting a specific one? If the latter, which one?

**Comment by jgiardino** [comment]
@LHinson The class isn't specific to any type of screen reader. It's a way of styling text so that we can include text that isn't visible on the screen but still have it announced by screen readers.

**Comment by matthewcarleton** [comment]
It might be worth mentioning that we are already getting a `.sr-only` through font awesome.
