### ISSUE TITLE
Backdrop + modal height issue

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly-next#433]
When the modal header text wraps (2+ lines) and viewport height is limited, modal breaks. This is due to the calculated height not including the extra lines of header text and the parent element flex positioning.

![modal-overflow](https://user-images.githubusercontent.com/5385435/42173664-cefb84e2-7ded-11e8-835a-038cfd93462a.gif)

Possible solutions:
- At a viewport minimum height, truncate text
![modal-overflow](https://user-images.githubusercontent.com/5385435/42173999-dde30e66-7dee-11e8-94f4-bdd266b478c5.gif)

- Set overflow of all content to auto (scroll)
![modal-scroll](https://user-images.githubusercontent.com/5385435/42174226-8fc569d0-7def-11e8-973c-c5b14e53943a.gif)

**Comment by mceledonia** [comment]
It looks like whole modal scroll is the best solution here, I know there was a larger conversation around this earlier though so want to confirm with @kybaker @mcarrano @andresgalante

**Comment by LHinson** [comment]
Modal scroll for the smaller height would be consistent with the decision to scroll within the modal for taller modals. +1 for the first solution proposed.

**Comment by mcarrano** [comment]
@mattnolting I also like the first solution (to truncate the title). This allows us to scroll the body of the modal, only, which was the desired outcome. In actuality, the need to truncate the title should be rare as I would say it's bad design practice to have a dialog title that is so long that it needs to wrap.
