### ISSUE TITLE
Wizard - Design Doc

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#437]
Introduce design documentation for the Wizard demo. To include:

* Wizard variations
* Basic workflow
* Wizard step structure

Related issue: #185

**Comment by rachael-phillips** [comment]
After reading up on Wizard best practices I've learned a few key pointers about wizards that should influence the design. If you are curious to learn more about wizards please take a look at Nielson Norman Group's article on wizards: https://www.nngroup.com/articles/wizards/

What I've learned, and I've tried to capture in this wireframe:
1. Use wizards for novice users or infrequent processes (e.g., configuration or setup).
2. Communicate a clear mental model of the process by displaying a list or a diagram of the steps involved and highlighting the current step.
3. Enforce a clear sequential order of the steps.

And here's the point to drive home: 
If there are substantial benefits to users from being able to complete steps in an arbitrary sequence, then this is an indication that this functionality is not suited to be provided as a wizard. That being said, if we need a non sequential set of steps it is best to move to a dynamic form. 

Here is the wireframes I've created so far with the hope of addressing this research.

<img width="836" alt="screen shot 2018-12-07 at 3 39 37 pm" src="https://user-images.githubusercontent.com/40275806/49671568-58cfee00-fa36-11e8-8480-e3ed5b9ffb7b.png">

**Comment by mcarrano** [comment]
A draft of the wizard design guidelines doc is available for review here: https://docs.google.com/document/d/1rgAXIBFGfeDwHTjVvHvKzD5Zqtro6kQkpt3PJvK0kkg/edit?usp=sharing Following a quick review, I hope to get a PR up next week. @stacymcauliffe @rachael-phillips @LHinson FYI Any feedback or suggestions welcome.
