### ISSUE TITLE
Dropdown styling updates

### ISSUE THREAD

**Issue by mceledonia** [patternfly/patternfly-next#455]
A couple (hopefully quick) updates to dropdown component visuals based on new designs - 

- Dropdown panel BG should be white with medium box shadow, see reference below.
- Text and icon inside dropdown should be vertically centered, see #453 

![image](https://user-images.githubusercontent.com/30935938/42583613-4d01e864-84ff-11e8-92ca-6f13ed19942d.png)

**Comment by mceledonia** [comment]
Just want to point out here re: @matthewcarleton that we are using the caret icons "caret-down/right" for dropdowns as opposed to the angle icons for notifications. The justification for this difference is the difference in action. Carets for simple form dropdown lists, angles for expansion behavior of more rich content such as notifications or context selector.

**Comment by thomasmaas** [comment]
@mceledonia 2 possibly naive questions: 

- What is the thinking behind the top and bottom paddings on the drop down panel?
- What is the thinking behind the 0 border radius on the drop down panel? (it kind of feels weird next to the border radius of the drop down)

**Comment by mceledonia** [comment]
The top and bottom paddings help the top and bottom list items sit a little further away from the top and bottom edges of the panel. When you don't have spacing there, the items feel like they're inconsistently spaced and too close to those edges, sort of an optical illusion kind of thing. The padding here may be too much, it should be subtle enough to fix the illusion but not too much to where it's noticeable.
