### ISSUE TITLE
Close button icon: Visual Feedback 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#473]
Originally filed by @trahman73 via #184. Separating this issue out so it's not lost. 

> From an Ansible Tower implementation standpoint, we were hoping to have a version of the close icon [on the popover] that is a little bit lighter as compared to the title font weight. My eyes are directly drawn to the close (a secondary function) vs the actual content.

**Comment by LHinson** [comment]
I know we'll want to address this systematically and avoid a special case for popover so this will require visual investigation and evaluation beyond just the popover.

**Comment by jeperry** [comment]
I agree with the concern. I have not seen this outside of the mockups in #184 but It seems like the visuals are not using pficon-close, which is a lighter 'X'. Is this intentional?

**Comment by kybaker** [comment]
@jeperry The mockups in 184 are using the new Font Awesome 5 icons which are heavier vs the pficon-close which is a custom icon based on FA4. The new styling makes the icons sharper on the pixel grid. I just checked in the Sketch file for the example on 184 and the icon is a bit larger than it should be and also converted to a shape which adds to the issue. Some of it is an artifact of Sketch and *should* appear lighter in the browser.

@trahman73 @LHinson We need to look at the icons systematically and figure out what colors should be applied throughout the library. I want to make sure all of the control icons use the same default color. I also want to make sure we consider the other states to ensure if we lighten the icon there is enough color contrast to between the active and disabled states. Also need to verify levels for accessibility and add colors for hover. Leslie - please make a story for this and prioritize it in the backlog.

**Comment by LHinson** [comment]
This will be addressed in #510
