### ISSUE TITLE
Tooltip: Visual Feedback 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#474]
Originally filed by @trahman73 via #113. Separating this out so it's not lost. 

-----

For implementation into Ansible Tower, we feel that 32px padding is very large in relationship to the icon that will trigger the tooltip itself. We also feel the the white background of the tooltips do not provide any contrast against the application even with a drop shadow.

Example of size and background issue:
![image](https://user-images.githubusercontent.com/13351591/42843917-841bdcf8-89df-11e8-91e8-0ab2e147b839.png)

We are proposing a 16px padding tooltip with a dark background (exact color to be suggested by design team) and no drop shadow (shown below). We can offer the choice of dark vs light background as a variable if necessary.

![image](https://user-images.githubusercontent.com/13351591/42844769-030f3c60-89e2-11e8-80bb-a5efe95c34ca.png)

Slack Tooltip Example:
![image](https://user-images.githubusercontent.com/13351591/42845101-efc0b746-89e2-11e8-9e5e-2713185b835f.png)

Github Tooltip Example:
![image](https://user-images.githubusercontent.com/13351591/42845335-96c8b9ee-89e3-11e8-8a40-af029004feef.png)

**Comment by jeperry** [comment]
+1 This seems to be the norm for other design systems like [Material](https://material.io/design/components/tooltips.html#placement) and [Lightning](https://www.lightningdesignsystem.com/components/tooltips/). Using an inverted color scheme also helps the tip stand out on the typically light background. I think using 16px is harmonious with the overall system since it is half the standard padding.

**Comment by kybaker** [comment]
@trahman73 This is a good place to differentiate from the systematic approach and create something unique for tool tip. My only concern with what you have shown above is that the background is dark enough to have AA contrast against the white text. 

@LHinson Should this change me noted in the original issue?

**Comment by LHinson** [comment]
The tooltip PR is still open for technical reasons as well therefore, +1 on tagging this onto the original issue. I've created a checklist over on #113. @kybaker please check it and verify that I've covered everything. 

@trahman73 @jeperry sorry to keep bouncing you around github issues but, given we have agreement to make adjustments. I'll close this issue and we'll track the progress back over on the actual tooltip component issue. Let me know if there are any questions / concerns about this!

**Comment by trahman73** [comment]
@kybaker I was just using the gray background color as an example. I agree that it would help to go darker and am open to whatever you suggest for it. Also, how would this impact anyone using a dark theme?

**Comment by kybaker** [comment]
@trahman73 Good question - The tooltip will need to go through a design iteration to account for this. We may be able to use the outer glow from the modal as a base and modify it to fit. We also might be able to utilize the theme css system but I am not sure.

**Comment by LHinson** [comment]
Just to clarify here, we will proceed with the visual suggestions made by @trahman73 and @jlmitch5. Their styling recommendation should be used as the defaults in the next PR.
