### ISSUE TITLE
Copy to Clipboard Component

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#505]
Introduce Copy to Clipboard. For PatternFly 3 design, see https://www.patternfly.org/pattern-library/forms-and-controls/copy-to-clipboard

IxD:
Visual Design:
HTML/CSS:

**Comment by mceledonia** [comment]
Copy to clipboard, Patternfly 4:

![image](https://user-images.githubusercontent.com/30935938/51122290-818e9480-17e7-11e9-9cc3-26af1cf2ab8b.png)

CC @mcarrano @matthewcarleton @kybaker

**Comment by mcarrano** [comment]
Works for me @mceledonia .  The [PF3 design](https://www.patternfly.org/pattern-library/forms-and-controls/copy-to-clipboard/#design) shows some feedback by changing the copy icon to a check after the operation completes. Should we carry that over here?

**Comment by mceledonia** [comment]
@mcarrano I think the idea of providing some feedback (copied to clipboard) is great and I usually see that with this sort of pattern. I am a little weary of converting to a check, as it seems like that would disable the action. I can imagine a situation where the action either fails to actually copy, or the user accidentally copies over that item in their clipboard. Maybe we can use a tooltip or inline alert to provide the success feedback? Something that says "Successfully copied to clipboard."

**Comment by mcarrano** [comment]
I think you make a really good point @mceledonia . The tooltip (as you are showing is the way to go IMO.
