### ISSUE TITLE
Button html/css across repos

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-next#506]
There are some differences in the implementation of Buttons in pf4 core vs pf4 react.

Since Buttons are inline-block elements, additional space is inserted between the buttons as a result of the white space between the html element, and not styles.

In the react implementation, the white space does not exist between the html elements, and therefore additional css is applied to the react buttons to insert the visual spacing between the buttons, to better match the pf core example.

Ideally, these examples would be identical.

**Comment by rachael-phillips** [comment]
Hi @jgiardino is this issue still relevant? Trying to learn a bit more about this one.

**Comment by rachael-phillips** [comment]
Hi @jgiardino is this issue still relevant? Trying to learn a bit more about this one.

**Comment by jgiardino** [comment]
Yes, I checked, and it appears this issue is fixed on the React side so that the spacing matches what we have in Core.
