### ISSUE TITLE
Utility class enhancements - Add title as a utility rather than a component

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly-next#509]
@matthewcarleton posed the question, "Should we also consider adding title as a utility rather than a component?"

Relates to:
#397 
#507 
#508

**Comment by andresgalante** [comment]
I'd leave them as components since they modify more than one propierty. 

Unless we want to create font size utilities, what do you think?

**Comment by mcoker** [comment]
I think we can close this in favor of https://github.com/patternfly/patternfly-next/issues/1534. If you think we need a font-size and font-weight utility, let's track it there.
