### ISSUE TITLE
revisit page layout and address existing issues/comments

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-next#523]
[This PR](https://github.com/patternfly/patternfly-next/pull/488) was merged because it was blocking other component from moving forward, specifically Navigation. 

After speaking with @kybaker it was clear that the best path forward is to merge now and revisit the comments/questions on the PR rather than leaving it open and not have the navigation work started.

**Comment by LHinson** [comment]
This will be addressed with a PR for #207
