### ISSUE TITLE
Remove workspace classes from code samples in Popover/Tooltip

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-next#526]
Any workspace classes we use to adjust an example preview should not be included in the code sample.

The classes added to the Popover/Tooltip examples should be moved to examples/index.js. Refer to https://github.com/patternfly/patternfly-next/pull/442#discussion_r207653162 for more details.

**Comment by dgutride** [comment]
Took a look at the code and it will require some refactoring in the tooltip and popover to accomplish this since they can't stand along without the Preview__overlay and &-container classes being applied to the outside divs.

**Comment by michael-coker** [comment]
This was addressed via #688 with PR https://github.com/patternfly/patternfly-next/pull/747
