### ISSUE TITLE
Popover/Tooltip documentation

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-next#527]
There are a couple of updates needed in the documentation (both accessibility and usage sections) for the Popover/Tooltip examples as noted here: https://github.com/patternfly/patternfly-next/pull/442

**Comment by mcoker** [comment]
@jgiardino can we close this one? I reviewed the 2 comments that referenced this issue and looks like they have both since been resolved.

**Comment by jgiardino** [comment]
Yes, thanks for catching this!
