### ISSUE TITLE
Popover: remove extra variable

### ISSUE THREAD

**Issue by andresgalante** [patternfly/patternfly-next#531]
There is a variable declared on popover that is never used: https://github.com/patternfly/patternfly-next/blob/master/src/patternfly/components/Popover/styles.scss#L48

Maybe we should consider removing it

**Comment by christiemolloy** [comment]
@andresgalante could you clarify which variable on popover should be removed?

**Comment by christiemolloy** [comment]
Nvm, I see that it is L48!
