### ISSUE TITLE
Create hi-fi mockup to guide developers on one page screen 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#54]
* Create hi-fi mockup to guide developers on one page screen 
* Developers will break down screen, identify layout, patterns, demos or components to contribute to -next.

**Comment by kybaker** [comment]
@andresgalante @dgutride @LHinson @mceledonia @jennyhaines @matthewcarleton I created the mockup using the latest components, type and spacers. I included mockups for the open menus and responsive states. Some of the new line height is not totally accounted for, but these should be good for the dev meet-up.

[Mockups](https://drive.google.com/open?id=15UtPH4VF1m2KReIQ6jNUkgl8nz4Jk0PZ)
[Editable File](https://drive.google.com/open?id=1B4FzciZa5aaHwJKUgToGuYXP7EdjkBNH)

**Comment by dgutride** [comment]
I think this one is done - we have what we need for meetup
