### ISSUE TITLE
Address accessibility for visuals

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#55]
Revise the components board to address accessibility

**Comment by LHinson** [comment]
@matthewcarleton will you add what you did for accessibility for visuals in addition to highlight what you addressed specifically?

**Comment by matthewcarleton** [comment]
Initially I went through and updated the contrast of all the elements making sure they met WCAG 2.0 level AA rating. I also updating font size/weight. 

@jennyhaines has done a lot of great work to continue this effort which can be seen [here](https://github.com/patternfly/patternfly-next/issues/61).
