### ISSUE TITLE
Message dialog demos

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#556]
https://www.patternfly.org/pattern-library/communication/message-dialog/

Clarify requirements and design for these examples so kicking this to IxD phase.

**Comment by mcarrano** [comment]
@jknilans I am assigning this to you to evaluate the requirements and design based on what we did for PF3 and any improvements that we might make. There is a standard design already for modals so this may just be a matter of defining a common template for how to present these. @mceledonia can consult on visuals. I think the first step would be to identify demos we want to hand off to development and design doc can follow. Similar as we did for Login page.

**Comment by mcarrano** [comment]
There is a dependency on this issue: https://github.com/patternfly/patternfly-next/issues/1599

**Comment by mcarrano** [comment]
This demo should provide sample implementations for the examples documented here: https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/modal. Handing off to CSS for implementation when ready (contingent on #1599). @LHinson @rachael-phillips FYI

**Comment by mcarrano** [comment]
We have these cases documented here: https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/modal Demo should not be necessary.
