### ISSUE TITLE
Dropdowns - Design Doc

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#568]
Introduce design documentation for Dropdowns.

No existing PatternFly 3 documentation. Should include guidelines on when to use a dropdown (vs. a select list?). Content guidance on labeling dropdown and menu items. When to use separators.

Related issue: #23

**Comment by mcarrano** [comment]
Noticed that Kabob is shown as a type of dropdown in the HTML/CSS workspace. Didn't we decide to separate kabob out as a separate component @LHinson ? If not, then these guidelines should address use of the kabon vs. standard dropdown.

**Comment by LHinson** [comment]
@mcarrano yes, somewhere along the line it got consolidated to be included in dropdown. Is there a use case for kebab outside of dropdown?
