### ISSUE TITLE
Modal - Design Doc

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#573]
Introduce design documentation for Modal.

Existing PatternFly 3 design doc: https://www.patternfly.org/pattern-library/forms-and-controls/modal-overlay/#design

Visual Design Spec: https://drive.google.com/open?id=1WTIXpB9KZOjRWUOHmspxaBJ6RAudvsgF

Should include guidance on when to use a modal, standard buttons and placement, titles for modals

**Comment by stacymcauliffe** [comment]
PR was merged
