### ISSUE TITLE
Theme colors need defined 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#58]
Theme colors need to be defined (badges, alerts, etc) 

VC: 
* Theme colors defined
* Review with visual design and css 
* Add info to issues on Github for badges and alerts and any other applicable issues. 
* Transform into sass variables

**Comment by mceledonia** [comment]
[Theme colors working file ](https://drive.google.com/open?id=1Bta878rFdeTgKY6EPutyFJmXTq2IXrAF)

**Comment by matthewcarleton** [comment]
@kybaker @mceledonia I've taken a look at the theme colours and have some questions. 
Do we need a blue background? We already have `$pf-global--primary-color` which is used for buttons, badges etc.

I believe we also need to add another alternative to the dark grey. In the component board I see the calendar widget using pf-black-800, this will likely be used again right? 
Do we need to another colour to the alerts for `info`?  

I just want to nail these down before I get into creating the variables for them.
We can also set up a sync on this if that makes more sense. @andresgalante feel free to join in here :)

**Comment by matthewcarleton** [comment]
@mceledonia that sounds good. I will get this started, when you have a chance can you update that doc with those changes?

**Comment by matthewcarleton** [comment]
I spoke @mceledonia yesterday. We confirmed that this doc is ok as is for now but will grow as components get finalized. @LHinson we can probably close this out unless you want to keep it open as reminder that the theme doc will likely change. @mcarrano @kybaker is the idea with docs like this to inform the final design docs?

**Comment by mcarrano** [comment]
I'm not really sure how to answer your question @matthewcarleton . Eventually we will want to include this type of info somewhere on the website, not we're a ways from knowing where that will live. If this is going to be an evolving artifact, I guess the question I have is how that is getting managed. Is this currently being documented in the form of a Sketch file? If so, where should those Sketch files live? Should they be checked in to the repo somewhere and updated like any other project asset?

**Comment by matthewcarleton** [comment]
@mcarrano I agree, this seems like a larger discussion about how things get tracked/documented. Ultimately all of this info should exist on the site and the sketch source file. We need to decide where things live in the meantime. It's good to have these docs to inform the devs.

**Comment by matthewcarleton** [comment]
I'm closing this with the expectation that we will address additional theme requirements as they come up.
