### ISSUE TITLE
Don't include modifier classes that are for demo purposes only

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-next#592]
Currently these classes (`.pf-m-hover`, `.pf-m-focus`, etc) add a bunch of unnecessary noise to the code docs and probably shouldn't be in the production code. Should we remove classes that are used for demo purposes only from the...

1. HTML output
1. code docs
1. the production CSS?

This could also include removing classes like `.Documentation-container-tall` from example code, too.

@matthewcarleton @mattnolting @srambach @jgiardino @andresgalante @dgutride

**Comment by matthewcarleton** [comment]
I think this makes a lot of sense. We have talked pretty extensively about how these classes should be used to ensure they don't get miss-used so it makes sense to remove them altogether if possible. I can't see any reason why we shouldn't do this. @dmiller9911 do you have an opinion on this from the React side?
