### ISSUE TITLE
Improve linter

### ISSUE THREAD

**Issue by andresgalante** [patternfly/patternfly-next#593]
I'd like to improve our linter to follow as close as possible our guidelines. The idea is that the code should feel like it was written by just one person and the stronger our linter is, the closer we would get to that.

This task has 2 steps:

1. Improve stylelintrc to follow our guidelines
2. Change our codebase so it doesn't have limiting errors.

This work started on #117

**Comment by michael-coker** [comment]
@andresgalante The guidelines say "Don't use `@extend`", which I can enforce via `"at-rule-blacklist": ["extend"]`, but we use `@extend` for theming. Should we consider a different approach for theming?

Also, I'm not sure about these. I didn't find them in any CSS guidelines, although I probably missed them. I don't see anything wrong with them, but wanted to run them by someone before moving forward.

```
    "selector-max-attribute": 2,
    "selector-max-class": 4,
    "selector-max-combinators": 4,
    "selector-max-compound-selectors": 4,
    "selector-max-type": 2,
    "selector-no-qualifying-type": true,
```
