### ISSUE TITLE
Update npm package to include pfbg images

### ISSUE THREAD

**Issue by marshmalien** [patternfly/patternfly-next#595]
##### Summary
Default background images `pfbg_:id.jpg` are missing from the published npm package. 
@dgutride 

##### STEPS TO REPRODUCE
1. Include `"@patternfly/patternfly-next": "1.0.15"` in package.json
2. Run npm install successfully
3. Search within `patternfly-next` directory for image file extension `find . -name "*.jpg"`  

##### EXPECTED RESULTS
Background images directory located within `@patternfly/patternfly-next/assets/`.

##### ACTUAL RESULTS
No images in published repo.

**Comment by dgutride** [comment]
Package contains these now - closing
