### ISSUE TITLE
add notes to release docs

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-next#596]
I've mentioned this on Slack but thought it would be good here too. I've found that it would be useful to have release notes that outline what's been done. This summary could be very useful to those that are not familiar with what's going on. Bootstrap is a great example of this done well. 

https://github.com/twbs/bootstrap/releases

I'm not sure how manual this is but it's worth considering.

**Comment by LHinson** [comment]
Commit messages needs to follow guidelines. Closing since there is not more to do here other than better enforcing the rules during PR reviews. If we need to add more tooling around this to help improve release notes, we can add issues.
