### ISSUE TITLE
change scss file names from `style` to the name of what it is

### ISSUE THREAD

**Issue by andresgalante** [patternfly/patternfly-next#598]
After discussing with @dmiller9911 we think that having the name of the component for the scss file would be beneficial. For example instead of `button/styles.scss` we would have `pf-c-button.scss`

This task is to change all the scss file names.

**Comment by michael-coker** [comment]
We decided to have the stylesheet name match the component name without the `pf-[clud]-` prefix, or match the main handlebars partial filename. So `AboutModalBox/styles.scss` changes to `about-modal-box.scss`
