### ISSUE TITLE
Component board 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#61]
Create a visual component board to help identify that pf-next styling and serve as a guide for development. 

Refine and organize the component board to be leveraged as a reference for the broader team. Also includes incorporating accessibility work.

* Board is updated 
* Organize the files and folders 
* Review with visual design team 
* Share the link to the PF Swarm team

**Comment by jennyhaines** [comment]
@LHinson @kybaker - here is the updated component board! Feel free to close :) https://drive.google.com/drive/folders/1kOzgBU64TDkMNoi_1YX9NQ4kyu1OmRX6?usp=sharing

**Comment by LHinson** [comment]
Thanks @jennyhaines!
