### ISSUE TITLE
Alert Toast Demo

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#625]
Create a demo that shows the various ways you can use Alert. Specifically: 

- [Toast](https://www.patternfly.org/pattern-library/communication/toast-notifications/)

Demo lifecycle: 
- [x] Interaction design requirements 
- [x] Visuals
- [ ] CSS

**Comment by mcarrano** [comment]
Here are some rough wireframes for Inline Notifications and Toast Notifications. https://docs.google.com/document/d/1UH6J2Mf1Nqx4zUx-TzO6MCgPFq6NJatRb0kagmGN5yE/edit?usp=sharing

For Toast Notifications, I tried to address some use cases that are not currently addressed in PF 3 documentation. These include how multiple notifications should stack and what to do when the numbers grow. @LHinson @kybaker please take a look. @jgiardino would also like to get any input from an a11y perspective. Note that I have not addressed content guidelines for alerts, only their behavior and positioning on the screen.

I think that next steps are to get some hi-res visual mocks and specs for these. Considerations should include size, positioning, and spacing of inline or toast notifications. We should also consider how these animate, but I'm not sure where that gets addressed in the process.

Lastly, as I worked on this, I started to think about the relationship between these alerts types and the notification drawer. I'm wondering whether this demo should encompass all of those pieces to show how they work as a system. Thoughts anyone?

**Comment by mcarrano** [comment]
@LHinson per our discussion today, I think that this is ready to hand off to visual design. @kybaker let me know if you have any questions. I think this is mostly about how alerts are presented in context.

**Comment by jgiardino** [comment]
Hey @mcarrano, 

The only question or concern I have regarding accessibility is how to handle the inclusion of actions in the toast notification. I had included a suggestion on how to implement this type of notification in issue #299. 

But other than that, the designs you have look fine from an a11y perspective.

**Comment by maryshak1996** [comment]
Reviewed with @kybaker , @andresgalante , @mcarrano 

https://redhat.invisionapp.com/d/main/#/projects/prototypes/15554709
<img width="1011" alt="toast2" src="https://user-images.githubusercontent.com/19824574/46555211-971f2480-c8b0-11e8-9878-54469576844f.png">

**Comment by LHinson** [comment]
Great, thanks @maryshak1996! Given those reviews, sounds like this ready to move onto CSS?

**Comment by maryshak1996** [comment]
@LHinson yup I would think so!

**Comment by mcarrano** [comment]
@LHinson I'd like to hold on this for the moment. I've been working on demo requirements and design guidelines here: https://drive.google.com/open?id=1UH6J2Mf1Nqx4zUx-TzO6MCgPFq6NJatRb0kagmGN5yE  While I don't see any disconnects, I'd like to roll these out for stakeholder review at the same time to make sure we are all synced. I can target this by next week. Does that cause a problem?

**Comment by christiemolloy** [comment]
@rachael-phillips the alert is done, not the toast notification, I wonder if we should close this issue and create a new issue just for a toast notification demo (seeing as we dont really have that component right now)

**Comment by mcarrano** [comment]
@christiemolloy The demo looks great. But I am curious what you mean by a "toast notification" demo. The demo I see shows 3 toast alerts (aka notifications). Were you thinking something different? We probably to want an inline notification demo in the future but I know there are still some design issues being worked out.

**Comment by mcoker** [comment]
Yeah, the alert demo is a toast demo. Should we close this issue and open another issue for the inline notification once the designs are ready?

**Comment by mcarrano** [comment]
Yes, I think so @mcoker
