### ISSUE TITLE
Extract components from page layout

### ISSUE THREAD

**Issue by andresgalante** [patternfly/patternfly-next#637]
Some parts of the page layout should be independent components, for example, the toggle btn.

The task is to read the page layout and extract any structure that is not layout related to independent components.

**Comment by LHinson** [comment]
@michael-coker I'm curious if the brand component #134 is closed out as a result of this exercise.

**Comment by michael-coker** [comment]
@LHinson there is a brand component now - the component's CSS is applied to an image file, but the CSS doesn't do anything. https://pf-next.com/components/Brand/examples/
