### ISSUE TITLE
Components links are incorrect for hyphened Component names

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-next#638]
1. Navigate to an example page like [ModalBox](https://pf-next.com/components/ModalBox/examples/)
2. Scroll to a section of the page that displays: "Components used: `modal-box`"
3. Click the component link (any component with a hyphen, like `modal-box`)

**current behavior:**
  An [error page](https://pf-next.com/components/modal-box/examples) displays.

**expected behavior:**
 The component page should display

**Comment by michael-coker** [comment]
@jgiardino The search pattern for how we find these classes isn't finding all components, either (for example, `ModalBox` is listed in the second example, but not the others, even though it's in all of the examples).

Should the list of components include the component you're currently looking at? So in the case of the `ModalBox` component page, should that component be included in the lists under the examples?

And we currently look for components and layouts for the list in "components used". Should that just look for components? Or separate out "components used: ..." and "layouts used: ..."?

**Comment by jgiardino** [comment]
Good catch on the issue that not all components are listed!

I don't have a strong opinion about listing the current component in the list of components. It seems a little weird, but I don't think it would be confusing for anyone if it's impossible to fix that.

I like the idea of listing Layouts along with components. Layouts are an important part of PF4, and if someone is looking at an example, whether it's a component or a demo page, and they're wanting to implement that or create a customized implementation of it, it's helpful to know all the parts that make that work, and to be able to see those parts in isolation. 

Related to this feature, at defConf.us, the PatternFly booth had an activity where they asked what information or features are important to consumers when using a design system, and one of the comments had to do with how difficult it is to work with the source code that's provided when the source code sample is _everything_ on a page. I think this feature is a very important for satisfying the use case where consumers want to see examples of full page layouts to see what's possible, but want the source code for the components and layouts that are needed for building it in separate chunks.

**Comment by michael-coker** [comment]
Cool thanks! Do you think we leave it as "Components used:" or change it to like "Includes:" or "Components and Layouts used:", or just leave it as is?

**Comment by jgiardino** [comment]
"Components and Layouts used:" sounds good to me.
