### ISSUE TITLE
Custom Selects

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#651]
We require a custom Select component to satisfy several use cases. This can be used as an alternative to the Native Select either outside of a form or when advanced capabilities are required. Besides supporting standard select list functionality, the Custom Select must support multi-select, type-ahead, and checkbox select (faceted filtering) use cases. A first iteration of the multi-select dropdown can be seen here: https://pf-next.com/components/Dropdown/examples/ 

Requirements and concept wireframes for select list variants are included here: https://docs.google.com/document/d/1Byw_diVKuyLfm6uRLVD7bJpjwhPBd16BQdNxMhSX-RY/edit?usp=sharing

Dropdown Select/Multi-Select Design at October 30
[Dropdowns_GitHub_10_30.pdf](https://github.com/patternfly/patternfly-next/files/2529842/Dropdowns_GitHub_10_30.pdf)

Dropdown Select/Mutli-Select Type-Ahead at October 30
[Dropdown_TypeAhead_GitHub_10_30.pdf](https://github.com/patternfly/patternfly-next/files/2529891/Dropdown_TypeAhead_GitHub_10_30.pdf)

CheckboxSelect 
https://github.com/patternfly/patternfly-next/files/2539791/Dropdowns.zip

**Comment by christiemolloy** [comment]
@jgiardino do you mind reviewing the accessibility levels of the custom multi-select component that I have designed and attached as a PDF above.

**Comment by christiemolloy** [comment]
@jgiardino I was building off of the current design in Sketch where the dropdown multi select incorporates checkboxes and filter chips. Should this design be distinguished from the [current example](https://pf-next.com/components/dropdown/examples/#dropdown-multi-select-example-button) where we have no filter chips, or did this example not include filter chips because they were not designed yet? 
@mcarrano do you have an example of a page layout where this dropdown multi select with filter chips would exist?

**Comment by jgiardino** [comment]
We might have the current example only because we didn't have filter chips available yet?

@srambach Can you comment on this? Was the expectation that the current multi-select example would get updated when filter chips were available?

**Comment by mcarrano** [comment]
Yes, this is a bit confusing. Seems like we have two design approaches for the same thing. I don't see any reason that we need both the approach that is implemented the the current Dropdown component and the new approach specified here. I could live with either one. I also don't have an immediate example to show the multi-select dropdown in the context of a page. But one place I'd expect to find this is in the toolbar for example as part of a filter. Maybe I want to filter objects by status and want to be able to select multiple values to display.

@LHinson this question seems to go along with what we were discussing about use of Selects - custom vs. native, etc. Maybe we need a meeting with everyone involved to sort out what we want?

**Comment by jgiardino** [comment]
+1 to meeting to discuss

Also, it would be nice to know what the expectation is when there are too many selected items to fit. Is this handled by purely CSS, purely JS, or a combination of both? Does the main input area grow in width or height? Do the contents ever get truncated?

Here's a similar example in PF3 for the [Type-Ahead Select component](https://patternfly-react.surge.sh/patternfly-3/?knob-Clear%20Button=true&knob-Multiple%20Selection=true&selectedKind=patternfly-react%2FForms%20and%20Controls%2FTypeAhead%20Select&selectedStory=Multiple%20Selection&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs). I'm not sure that the Type-Ahead Select PF3 component behaves as expected relative to where we would plan to use the PF4 multi-select component (i.e. is it ok that it grows in height to show the full selection if it's used in the context of a toolbar?).

Here's [an alternate method](https://mdbootstrap.com/javascript/bootstrap-multiselect/), where it switches from listing individual selections to displaying the number of items selected. 
I could see this method working well with the variation that doesn't use chips, but is this method weird for the variation that does use chips?

**Comment by christiemolloy** [comment]
+2 to meeting 

@jgiardino After I designed the filter chips, Leslie created [#748](https://github.com/patternfly/patternfly-next/issues/748) which addresses what you are speaking about above, but I dont believe it is a huge priority right now. But if it is something that we need to address before we move forward then I can help with it.

**Comment by christiemolloy** [comment]
I also think the design of how we treat filter chips when there are too many values or it needs to be truncated, will be determined by how we plan on using them, whether that be in a dropdown and/or on the toolbar under the filter component.

**Comment by mcarrano** [comment]
I have updated this issue to be inclusive of the work on all custom selects. @christiemolloy I think the next steps are to provide visual designs for the required variations as we discussed.

**Comment by christiemolloy** [comment]
Designs for Dropdown select/multi-select and Dropdown Type-Ahead Select/Multi-select have been added

**Comment by mcarrano** [comment]
These look great @christiemolloy . Can I infer that you are still working on what I called the "Checkbox Select"?

**Comment by christiemolloy** [comment]
@mcarrano Michael has the designs for those, and will be uploading them to here

**Comment by srambach** [comment]
@mcarrano @christiemolloy @mceledonia I pasted in what I think are the corresponding visuals for the wireframes. Let me know for sure if that seems correct please. I had to place them "near" and mark up one based on our conversation this afternoon.
https://docs.google.com/document/d/1Byw_diVKuyLfm6uRLVD7bJpjwhPBd16BQdNxMhSX-RY/edit#

**Comment by srambach** [comment]
@mcarrano @mceledonia I noticed that in the typeahead variations, the wireframes maintain the dropdown caret as well as an X to clear the field, but the visual designs change the caret to an X. Can you two clarify which way it should be and also verify that the X should clear the entire field, not just anything that's been typed?

**Comment by christiemolloy** [comment]
@srambach I did those typeahead variations. I believe you should follow what is in the wireframes that @mcarrano did

**Comment by srambach** [comment]
Oh, sorry @christiemolloy! I will keep the caret then and add the X.
