### ISSUE TITLE
Alert (Toast Notification) List Layout 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#654]
We need a layout to stack toast notifications on the page. See PF3: https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/toast.html

Visuals/layout for different amounts of toast notifications can be seen at :
https://redhat.invisionapp.com/d/main/#/projects/prototypes/15554709

<img width="1011" alt="toast2" src="https://user-images.githubusercontent.com/19824574/46555211-971f2480-c8b0-11e8-9878-54469576844f.png">

**Comment by lwrigh** [comment]
In PF 4 is there any talk of notification settings?

**Comment by andybraren** [comment]
@lwrigh Not that I know of. Might be worth asking in #35.

**Comment by lwrigh** [comment]
No problem, I'll ask there. Thanks for finding the issue!
