### ISSUE TITLE
List enhancement: compound expansion 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#657]
view compound expansion here: https://www.patternfly.org/pattern-library/content-views/list-view/#design

**Comment by mcarrano** [comment]
I don't think this is relevant to PF4. We do have a compound expansion option for the Table which is all I think we need. @rachael-phillips @LHinson can we close?

**Comment by rachael-phillips** [comment]
Yes, I think we can close until we hear of more product needs.
