### ISSUE TITLE
Update handlebar modifier syntax

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-next#660]
We need to update the docs to show handlebar modifiers/attributes format to `component--modifier` and `component--attribute`.

This would also be a good opportunity to go through and clean up anywhere this format is not followed. The buttons for example are rolling their own format simply b/c they were the first component and we hadn't set these rules yet.

**Comment by srambach** [comment]
To clarify, componentName--attribute with the first part camel case?

**Comment by mattnolting** [comment]
relates to #499

**Comment by michael-coker** [comment]
@srambach  it looks like the string before `--modifier` and `--attribute` matches the handlebar filename. Like [about-modal-box](https://github.com/patternfly/patternfly-next/blob/master/src/patternfly/components/AboutModalBox/about-modal-box.hbs) or [nav-section-title](https://github.com/patternfly/patternfly-next/blob/master/src/patternfly/components/NavSystem/nav-section-title.hbs)

**Comment by matthewcarleton** [comment]
I'm going to close this and let #499 stand alone. Didn't realize that already existed.
