### ISSUE TITLE
Align spacers between inputs and buttons

### ISSUE THREAD

**Issue by andresgalante** [patternfly/patternfly-next#674]
There is an issue with btns and inputs spacers. They should both share the same top and bottom spacer so they can align horizontally.

Apart from that the plain btns have a different padding than the normal ones. This means that they wouldn't align correctly with other btns if we put them together inline.

Since plain btns are implemented in different places like the page header, we should take care of what this change impacts, @mattnolting what do you think?

Also, the workspace is missing an example of a plain btn.

@mceledonia can provide the correct spacers

I need to talk to @kybaker, @mattnolting and the rest of the CSSers about this change.

**Comment by matthewcarleton** [comment]
I believe we'll need to make the same change to the dropdown spacers as well.

**Comment by mcoker** [comment]
@matthewcarleton should this be resolved in https://github.com/patternfly/patternfly-next/pull/899?

**Comment by rachael-phillips** [comment]
Following up on this one - was this resolved or should we leave it open?

**Comment by mcoker** [comment]
I remember looking at this in some browser (Safari I think?) and the form control text inputs were 1px taller than the dropdown component. I haven't had a chance to revisit. What do you think @matthewcarleton, should we try and handle this before beta?

**Comment by rachael-phillips** [comment]
Hi, I'm following up on this issue as we wrap up this milestone. Should I push it out to Beta 2?

**Comment by mcoker** [comment]
please :)
