### ISSUE TITLE
Further testing of tooltip/popover

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-next#688]
We need to test further what the tooltip and popover look like when in use. As far as I know we have yet to test this in any real world scenarios. There could be a separate issue to update depending on the findings of this test.

Also address issue #526 in this issue. 
Additionally, the popover icon is impacted by #510 and needs updated.

**Comment by jgiardino** [comment]
Can we add `aria-haspopup="dialog"` to the toggle that displays a popover, as part of this issue?

Also, it's possible that any updates for this issue would result in closing a related issue to update the documentation sections: #527
