### ISSUE TITLE
Missing link to a public-facing component demo

### ISSUE THREAD

**Issue by himdel** [patternfly/patternfly-next#704]
Currently it's impossible to find a running instance of the pf-next demo, making it much harder to look for existing components.

This repo should have such a link in the header. (similar to how [patternfly/patternfly-react](https://github.com/patternfly/patternfly-react) links to https://rawgit.com/patternfly/patternfly-react/gh-pages/index.html)

I'm guessing the link is https://deploy-preview-14--mnolting-deploy.netlify.com/components/table/examples/# but I can't add it ;)

**Comment by mcoker** [comment]
This is now in the repo description:

> Working repo for PatternFly 4 https://pf4.patternfly.org
