### ISSUE TITLE
custom Select component

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-next#708]
Add a custom Select component.

There are some cases where the standard html `<select>` element is not sufficient, and where a custom implementation of a Select component is needed, such as the Filter input group in the Toolbar demo or the page size select menu in Pagination.

The html structure and interaction is similar to the Dropdown component, and like the Dropdown component, it might have a visible text label (as in the filter example), or it might not (as in the pagination example). 

The primary difference between these components are semantics and the indication of the currently selected option. 

Refer to the [listbox example](https://www.w3.org/TR/wai-aria-practices-1.1/examples/listbox/listbox-collapsible.html) documented by the wai-aria authoring practices for an example of what roles and aria attributes we can use for this component.

**Comment by mcarrano** [comment]
Note that this custom select must support either single select of multi-select use cases for equivalence withe PatternFly 3. See functionality for the [Bootstrap Select](https://www.patternfly.org/pattern-library/widgets/#bootstrap-select). This would be useful whenever you want to assign multiple values to an attribute, for example, as shown in this filtering use case here: https://docs.google.com/document/d/15w2gpUb7__4oINMtnU7hwSqtlD6cwDIvkDeHM1TMfiQ/edit?usp=sharing See Attribute-Value filter. 

@kybaker did we ever do a PF4 design for this?

**Comment by jgiardino** [comment]
Regarding the select menu in pagination (see the [Pagination design](https://github.com/patternfly/patternfly-next/issues/32) and [Pagination a11y review](https://github.com/patternfly/patternfly-next/issues/627)), I'm wondering if this version of a custom Select component would be implemented and styled as part of the Pagination component, only. And if we would ever need an icon-only version of the Select menu outside of that use case. If so, then I can update the description of this issue to not include an icon-only variation. cc'ing @andresgalante to comment on that.

@mcarrano Looking at the Filter design, I have a few questions:

1. Is ability to group menu items a requirement, as shown in the example below. 
2. In the example below, the checkbox is visible in front of the label, but in the Bootstrap Select example, it's only a checkmark icon to the right. Do you expect both variations to be supported, or are we moving toward using checkboxes in front of the label?
3. In other examples from the design document, the selected values display in the button toggle, but in the example below, they don't. Do you expect selected values to always display in the toggle, or are there use cases where it wouldn't?

![image](https://user-images.githubusercontent.com/21063328/45495486-56187200-b741-11e8-8810-1c390192d541.png)

@LHinson are there demos that are dependent on this component, besides Toolbar and Pagination? Should this issue should only address the variation needed by the demos we have planned, and should we create separate issues to address other variations?

**Comment by mcarrano** [comment]
In the Filters design document there are really two things that are related but different. The first is a select list that supports multi-select like Bootstrap Select does. Whether the styling for that should match Bootstrap Select or something else is a TBD. I think we need some visual work here. This could be useful in many places as the single-select is.

The second component is a faceted filter like what you pasted above @jgiardino . This would be something that is useful for filtering and could be contained in a drop-down panel as shown or a sidebar. I think this should definitely be tracked separately and I didn't mean to bring that into the select-list discussion. So sorry if I created some confusion.

Does this help clarify?

**Comment by jgiardino** [comment]
Yes, thanks. That makes sense.

Additional details are provided by the WAI-ARIA APG for [Listbox](https://www.w3.org/TR/wai-aria-practices-1.1/#Listbox) about how to implement this type of control for a menu with multi-select. 

If we do decide to use checkboxes, then I'm not sure that the APG for Listbox is the pattern we'd want to use for multi-select. We might instead be better off representing the multi-select menu semantically as a popup dialog instead of a popup listbox (i.e. `aria-haspopup="dialog"` instead of `aria-haspopup="listbox"`).

**Comment by mcarrano** [comment]
Sounds good @jgiardino . I also want to add @mceledonia to this thread as he will be working on some visuals for multi-select filters.
