### ISSUE TITLE
Toolbar demo: Update dropdown with select component 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#709]
The toolbar demo should be updated to replace drop down with the select dropdown variant. https://pf-next.com/components/Dropdown/examples/

Please note, there is a known issue with the dropdown select that will impact this demo. See: https://github.com/patternfly/patternfly-next/issues/792

**Comment by rachael-phillips** [comment]
Referencing #959 for continued work on Toolbar Component
