### ISSUE TITLE
Type Ahead Select (needs info)

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#722]
PF3-React has the [type ahead component](https://rawgit.com/patternfly/patternfly-react/gh-pages/index.html?knob-Max%20Shown=5&knob-Leeway=2&selectedKind=patternfly-react%2FForms%20and%20Controls%2FTypeAhead%20Select&selectedStory=Menu%20Alignment&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs). This still needs to go through design. Need to determine what is required for core. 

Initial discussions about Type-Ahead Select: 
- There will be a select and multi-select Type-Ahead implementation. The component will act just like the select and multi-selects however in the filter the user will be able to type and search. Idea is to turn this on/off in React. So it may not be a separate component?

**Comment by mcarrano** [comment]
We will track all custom select work as part of #651 . This issue will be closed.
