### ISSUE TITLE
The topology icon is missing in PF4 and react-icons.

### ISSUE THREAD

**Issue by martinpovolny** [patternfly/patternfly-next#729]
The topology icon from PF3 is not present in PF4. Can you add it, please?

I need it for the Topology inventory UI.

FYI: @terezanovotna

**Comment by LHinson** [comment]
@martinpovolny I'm working on sprint planning now and trying to balance a number of priorities. Do you have a product release/timeline to help us understand when this icon must be introduced by? Thanks for the additional info!

**Comment by terezanovotna** [comment]
@LHinson We are already demoing first UI attempts in a Topology Sprint Reviews. The product release is planned for January, but having it earlier would be helpful. 

@martinpovolny as a temporary solution, we can just replace the nonexisting icon with "topology" text and once it's ready, we can just replace it.

**Comment by LHinson** [comment]
OK, there are number of things in motion at the moment but I've marked this as one of the next issues for a dev to pick up.... It's currently included in alpha.6 which means a October 12 delivery, however we will try and shoot for sooner if we can.

**Comment by LHinson** [comment]
Closing this issue as #766 has introduced PF icons to PF4.
