### ISSUE TITLE
Type-Ahead Filter

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#731]
We require a Type-Ahead Filter component that supports a variety of filtering use case across products. Some requirements for this can be found here: https://docs.google.com/document/d/15w2gpUb7__4oINMtnU7hwSqtlD6cwDIvkDeHM1TMfiQ/edit?usp=sharing and also a preliminary design here: 

Unified Filter Design Concept: https://docs.google.com/presentation/d/1yK7HUtUQZLBZGv-NjHGuMpDTs5Iq1mTqQCggGfDb1AQ/edit?usp=sharing 

This should be designed and implemented to use a consistent type-ahead approach with the Type-Ahead Select (Ref #722 ).

**Comment by rachael-phillips** [comment]
Closing this because this example will appear in Filter Demo
