### ISSUE TITLE
revise toolbar layout

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-next#740]
This was discovered in the form revisions when using the toolbar [here](https://github.com/patternfly/patternfly-next/pull/728)

@mattnolting pointed out: 

> Immediate descendants of pf-l-toolbar should provide margins, whether group or item. If pf-l-toolbar__item is an immediate descendant of pf-l-toolbar__group, it should not provide margin by default.
> Also, adding a small margin-top/bottom would separate items and groups when they wrap.

**Comment by michael-coker** [comment]
Let's open a separate issue for the new toolbar layout.
