### ISSUE TITLE
Tag / Filter Chip Enhancement

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#748]
How would the tag/filter chip look if we had 50 values? Are we going to aggregate it? instead of 50 values - would we show Category One: 50 values? How about super long values? Do we truncate?

This is a continuation of #177 

Truncated Filter Chips:
[Filter_Chips_Github_10_29.pdf](https://github.com/patternfly/patternfly-next/files/2527343/Filter_Chips_Github_10_29.pdf)

Overflow Filter Chips:
[Filter_Chips_InContext_GitHub_10_29.pdf](https://github.com/patternfly/patternfly-next/files/2527345/Filter_Chips_InContext_GitHub_10_29.pdf)

**Comment by Mgranfie** [comment]
Apicurio is implementing this or a very similar design and are also looking at addressing issues around scaling. Let's remain connected around this issue so we can look to align within the product, or if you are interested in input from use cases within a product.

**Comment by LHinson** [comment]
@Mgranfie: @mcarrano has a doc that is tracking product requirements and use cases as well as various filter designs. Looping him in here as well so he's aware of the Apicurio examples.

**Comment by christiemolloy** [comment]
@LHinson I just updated this issue with the designs that address it. It has been approved by interaction design and visual design

**Comment by mcarrano** [comment]
One question that I have is whether Tags and Filter Chips are the same thing. I think that they could be, but then calling the component Filter Chip sounds very use case specific. In PF3 we called this a [compound Label,](https://www.patternfly.org/pattern-library/forms-and-controls/labels/#overview) but we already have a different component in PF4 called Label.

@christiemolloy @LHinson Let's have some conversation before closing this. Not sure what the right answer is, but we should sort this out.

**Comment by christiemolloy** [comment]
@mcarrano we could just call it a "chip" so that it isn't specific to the filter. Or a Pill (Salesforce does that)

**Comment by LHinson** [comment]
@mcarrano I agree that "Filter Chip" is too use case specific.

**Comment by mcarrano** [comment]
I looked at some other design systems and I'm seeing this called either a Tag, Pill, or Chip. I could live with any of these, although we've never used "pill" in PatternFly so I hate to introduce yet another term. Do any of you have a strong preference for "Tag" or "Chip?"  I'm leaning towards Chip only because it does not imply any use case. Thoughts?

**Comment by christiemolloy** [comment]
I'm also leaning towards Chip, because Tag seems too similar to Label and when we had that meeting people thought strongly about replacing "tag" with "filter chip"

**Comment by christiemolloy** [comment]
@LHinson @rachael-phillips I believe this issue can be closed because it was addressed in the Chip component :)

**Comment by LHinson** [comment]
Great, thanks @christiemolloy
