### ISSUE TITLE
List/Table Demo

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#756]
Create a demo that illustrates usage of data lists and data tables in different contexts. When do we use a list? When do we use a table? Consider following use cases:

- Editable rows
- Expandable rows
- Drag and drop to reorder rows

IxD: 
Visual: 
CSS:

**Comment by gdoyle1** [comment]
@mcarrano To confirm what examples we need for this story based on our last meeting:

1. Compound data list with new toolbar design (One with header and navigation, one without)
2. Expanded data list with new toolbar design (One with header and navigation, one without)
3. Compound data table with new toolbar design (One with header and navigation, one without)
4. Expanded data table with new toolbar design (One with header and navigation, one without)

Does that sound right to you? Am I also addressing the capabilities mentioned in this issue (i.e editable rows, expandable rows, drag and drop to reorder rows)?

**Comment by mcarrano** [comment]
@gdoyle1 Not quite sure what you mean by "Compound data list/table"  There is a data list and a data table. The table can take two types of styling, the "hybrid list" type styling and the compact styling. Any of these can also support expansion. If this is still confusing, I'm glad to go over again via bluejeans.

As for the other capabilities, I had not thought about those. But if you have time to address them, we will need this eventually. I left out because they are not high priorities right now to implement.

Does that help?

**Comment by gdoyle1** [comment]
@mcarrano That helps! I'll send over what I have at that moment to make sure we're on the same page.

**Comment by gdoyle1** [comment]
@mcarrano Here's what I have ([link to Sketch file in GD](https://drive.google.com/open?id=1MeaDaCAzCo_g-lxj3vcQ0YGiII3JyhFO)). I haven't added it to the master file yet and won't do so until we meet on Tuesday. Let me know if you need any other examples that are not there.

Examples that are included are:
1. Simple Data List
2. Actionable (with actions and check boxes) Data List
3. Expanded Data List
4. Compact Data Table
5. Expanded Date Table
6. Simple Data Table
7. Sortable Data Table
8. Compound Expanded Data Table

**Comment by gdoyle1** [comment]
@mcarrano As for uses of data lists vs tables, my thoughts are to use a Data List when there is an unordered amount of content (so no column headers are necessary). Data Lists would not allow for items within rows to be selectable. Data Tables would be used for organized content, with column headers, and could allow for items within rows to be selected (as seen in the compound expanded data table example). For design purposes, Data Lists have shadows on each node (and therefore the entire table) that are used to separate row from row. Data Tables use dividers to separate row from row.

**Comment by gdoyle1** [comment]
@mcarrano Just updated this ([link to Sketch file in GD](https://drive.google.com/open?id=1MeaDaCAzCo_g-lxj3vcQ0YGiII3JyhFO)) based on what we talked about today!

Changes made:
1. Sorting feature from #1046 
2. Removed sort icon from toolbar in data table examples
3. New content in data list examples

**Comment by mcarrano** [comment]
These look great @gdoyle1 I think the new examples for Data List really help to differentiate between a data list and a data table. @kybaker @mceledonia do you guys have any feedback?

**Comment by gdoyle1** [comment]
All final designs of these can be found in this [Sketch File](https://drive.google.com/open?id=1RbOmDbxp-rkJgJ-rklhhIyppHSbMC3nl).

**Comment by christiemolloy** [comment]
Closing this issue as these are completed now.
