### ISSUE TITLE
PF4 Loading screen/text/animation/guidence

### ISSUE THREAD

**Issue by AllenBW** [patternfly/patternfly-next#758]
In pf4, when we're loading anything, but do not have a percentage status, whats the plan? 🤔
Think loading screen!  Or text, or animation, or something like `Loading ...`  How might loading data look in a card? Or maybe you don't show a card thats loading data? But what if there's a whole dashboard with ah so many cards and some load have data instantly while some... wait...

If this reads as a silly non-situation feel free to close this issue. 👍🏽🤗

**Comment by LHinson** [comment]
Hey @AllenBW.... A few questions to help us understand how to handle this request.... 

- What product/project does this impact?
- List any product/project release(s) and timelines your trying to align with
- Are you interested in HTML/CSS only or leveraging a PF-React implementation?

**Comment by AllenBW** [comment]
@LHinson 
* Insights Advisor https://github.com/RedHatInsights/insights-advisor-frontend
* @kenhoes  would be best to advise on this but I believe early next year is the timeline
* if yah give me the html/css I can roll with that, <3

**Comment by mcoker** [comment]
related https://github.com/patternfly/patternfly-next/issues/279

**Comment by mcarrano** [comment]
This is being address as a documentation story here: https://github.com/patternfly/patternfly-org/issues/717 Will close.
