### ISSUE TITLE
Contextual Help Demo

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#762]
Introduce a demo that illustrates use of contextual help in forms or elsewhere. This addresses the following topics:

* Use of placeholder text
* Popovers and info tips
* Use of tooltips

**Comment by mcarrano** [comment]
@stacymcauliffe I have created this new issue to capture the work that we agreed needed to happen coming out of yesterday's meeting on this topic. I'm assigning to you as a first step. Please post any preliminary document here. I think that ultimately this will lead to a demo that shows how these elements are used on forms and elsewhere. Let me know if you have questions.

**Comment by stacymcauliffe** [comment]
Drafted the preliminary document and am interested to get feedback. Thanks for starting this issue, @mcarrano - Great topic!

https://docs.google.com/document/d/1RehnQ1GQLYwZqHxYjUm8Du6zNRyyv3nNrwEVHfrxSaw/edit?usp=sharing

**Comment by stacymcauliffe** [comment]
Due to significant overlap with forms guidelines, we will be rolling this content into the PF writing standards being tracked in issue #722 in pf design repo. Closing this issue.

**Comment by rachael-phillips** [comment]
Closing this issue.
