### ISSUE TITLE
Create a container layout

### ISSUE THREAD

**Issue by cliffpyles** [patternfly/patternfly-next#77]
A Container layout is a layout that positions it's children vertically and centers them horizontally. They often have a maximum width, but can also expand to fill the parent completely if needed.

Example:

![image](https://user-images.githubusercontent.com/904039/37797063-33d13dc0-2def-11e8-8436-6c091f507e27.png)

**Comment by LHinson** [comment]
Still TBD whether or not PF needs this. Let's hold off until we determine that it is needed. @cliffpyles any concerns with going ahead and closing this one and we can add it later if needed?
