### ISSUE TITLE
Source SVGs from JSON

### ISSUE THREAD

**Issue by priley86** [patternfly/patternfly-next#771]
In #766, I noted that some downstreams prefer to source JSON configuration of icons vs individual SVG files. It would be nice to consider consolidating the SVG definitions into a single JSON and extracting SVGs in the build step so that JSON and SVG are always in sync.

**Comment by mcoker** [comment]
@priley86 we build the icons at https://pf4.patternfly.org/icons from a JSON file, and those are added but not checked in, so the icons are always up to date with what's in the JSON file. Is that what you were going for here, or were you looking for something else?

**Comment by mcoker** [comment]
@priley86 should we leave this one open?

**Comment by rachael-phillips** [comment]
@priley86 did you see Michael's comment above? :)

**Comment by priley86** [comment]
sorry @mcoker @rachael-phillips ! I have notifications from this repo going to a different inbox 😆 - I will try to watch these more closely...

I am fine w/ closing the issue. It seems like we have a good process for now on this.
