### ISSUE TITLE
Addressing Popover Color 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#772]
@andresgalante states in #747 review: 

> The popover doesn't work well on dark environments. I don't know what the design ask for, do they want it to change to dark bg and white fonts, like the card, or they want it to stay white bg with dark fotns.
>

Design advised to follow the design suggested in issue #474 - the dark. 14px font and 16 px margin however, we should address the issue of what happens when this is on a dark bg.

**Comment by rachael-phillips** [comment]
Closing this issue
