### ISSUE TITLE
Nav: CSS specificity issue

### ISSUE THREAD

**Issue by jschuler** [patternfly/patternfly-next#779]
https://github.com/patternfly/patternfly-next/blob/199e4c18aa6d8cd96afa4c2f4e0b66893b23dbe5/src/patternfly/components/Nav/styles.scss#L300

When nesting the Nav inside of page layout, i noticed that the expanded modifier on the `<aside>` was affecting the chevrons for the expandable lists. It appears that this class is not specific enough.

**Comment by priley86** [comment]
any updates?
