### ISSUE TITLE
Page layout - Header: Overflow hidden

### ISSUE THREAD

**Issue by jschuler** [patternfly/patternfly-next#780]
https://github.com/patternfly/patternfly-next/blob/199e4c18aa6d8cd96afa4c2f4e0b66893b23dbe5/src/patternfly/layouts/Page/styles.scss#L117

While creating a page layout demo in react i noticed the following:
I added a toolbar to the page header that has a dropdown item. The dropdown item menu was cut off once it reached the header boundary. Unsetting the overflow-x made it visible again.

**Comment by LHinson** [comment]
@jschuler is this completed and ready to close?

**Comment by mcoker** [comment]
Also, dropdown is hidden behind sidenav in a narrow viewport - http://patternfly-react.surge.sh/patternfly-4/demos/pagelayout/examples/page-layout-default-nav/
