### ISSUE TITLE
Background image treatment system

### ISSUE THREAD

**Issue by mceledonia** [patternfly/patternfly-next#79]
As a part of theme colors work #58 , defining multi-level overlay system to be used with header background images.

Overlay system must ensure text is accessible while overlaying any image (using straight white as a baseline) while still ensuring the image still has a noticeable impact on the overall look and feel of the page.

Also defining the text colors to be used on various levels of overlay.

[Overlay system (dev meetup version) working file](https://drive.google.com/open?id=1Bta878rFdeTgKY6EPutyFJmXTq2IXrAF)

Component lifecycle: 
- [x] Interaction design requirements 
- [x] Visuals 
- [x] First checkpoint complete and approved 
- [ ] CSS 
- [ ] React
- [ ] Second checkpoint complete and approved 

Contacts: 
- Visual: @mceledonia 
- CSS: @matthewcarleton

**Comment by mceledonia** [comment]
@kybaker @jennyhaines @andresgalante @matthewcarleton @LHinson 

Hey everyone so these overlays that I’m working on, like Kyle mentioned, are an integral part of the visual system so it’s really important that we nail them down. **I have come up with fixed values, that for the dev meetup, will be perfect.** 

As a system-wide solution however, I am beginning to think that this might not be the best approach. 

The problem is that the image itself will have a larger impact on the general brightness of the page than the overlays . Here is a visual example using the two images I've been using for the concept mockups. 

![image](https://user-images.githubusercontent.com/30935938/37841432-22dcaa5c-2e96-11e8-93ff-eb0ce5df4603.png)


Both of these have the same overlay values applied to them. Note how the left feels much darker, and the right feels much lighter. Ideally while making these mockups I would adjust the overlays to make them fit perfectly. But as a system wide solution that won't work, we can't realistically create values on a per-image basis.

I have two solutions to offer:

1. We stick with a predefined set of images that we manipulate the brightness/contrast of so that they all work perfectly with our fixed overlay values`*`. 
`*These values were created using the baseline of white text being accessible when placed on top of them. In other words, the lightest overlay value is the lightest color that white text can be accessible on, and I increased the values from there to match what looked best in the overall layout. `

2. We use a more flexible solution that allows for a larger variety of images to be used without the need for manipulation by creating a system of percentages. We allow the user to define a baseline overlay value (with guidelines of course) and define each of the specific overlays as percentages of that baseline. I can illustrate this by using the values I've already determined for the dev meetup (these are illustrator values not CSS):

- Top left overlay: Black at 72% opacity
- Header overlay: Black at 42% opacity

So for example, say that we use the header background overlay as the baseline since we already know white text is accessible on it. Well our system would define the top left overlay as always being 170% of the baseline. So we find that the top left overlay should be 72% opacity. 

This would ensure consistency in applying the overlays without restricting the overlays to fixed values or forcing us to only allow a pre defined set of images for the world to use. Obviously for internal efforts we would control the images and make sure they were the best, but if Coder Cody out there wants to use our system, I feel like we should offer a solution where he can use any image he wants and still achieve a desirable outcome. 

The images are what really drive the look and feel of the page with this system, they are the most important part from a visual perspective, so it makes sense to me that we would develop a solution that encompasses all images rather than a select few. 


Sorry for the novel! Like I said, don't worry about this for the dev meetup. I've got values that will work perfectly for that.

**Comment by jennyhaines** [comment]
@mceledonia - I think that realistically, option 2 is what we should go with. Awesome idea with the percentages of a baseline! I agree that "Coder Cody" might not be able to create a desirable outcome with option one :) We would have to include a good amount of documentation around this since it is sort of inventive.

**Comment by mceledonia** [comment]
@jennyhaines Thanks, and I totally agree the documentation is the most important part of that solution. The missing key is finding a simple and reliable way for the user to find their ideal baseline. I think that is totally possible but I just don't have the time to invest in figuring that out right now so I just wanted to propose it!

**Comment by kybaker** [comment]
@mceledonia @jennyhaines I completely agree with both of you. I love this new overlay system and I think it will serve us well. I think the latitude with the overlays will allow us to evolve in the future.

**Comment by LHinson** [comment]
CSS / Visuals to work on Header first before moving onto this one.

**Comment by LHinson** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/e61326c5-7936-4cca-9de3-f1b5975413fb-15206079-98a4-479e-bb46-baa63bbd1a81-v1.png?transparent=1&palette=1&width=246)

**Comment by mceledonia** [comment]
Pivoting this concept to a more simple solution (minutes after I present of course!) 

### Percentage-based solution 
Is this juice worth the squeeze?

**Pros**
- "Gradient" of flexibility rather than limited options

**Cons**
- Relies on the user choosing a sensible baseline value
- Relies on the user being able to do simple math to calculate other percentages (we could provide a chart I suppose)
- Not as much flexibility as initially thought for the complexity of the system
     - Calculations show that 54% is the lightest overlay possible to ensure accessibility with our secondary text on top. With our designed hierarchy, this leaves the darkest value of that set (the set based on the lightest possible baseline) at 90%. This means that increasing the baseline value can only go so far before the dark value ends up at 96%+, which ends up just being straight black, which we don't want because it will ruin the effect. So really this system is only flexible between 54% -> 58%, which is like 4 different options of overlays. 
     - This isn't nearly as much flexibility as I thought the system would bring which is why I'm proposing another solution.


### Set-based solution

**Proposal**
- Instead of the above, we design 3 sets of overlays: light, medium, and dark, that the user can choose from and pick what works/looks best for their chosen image. These overlay sets would be carefully designed by us to ensure accessibility and hierarchy, but would also allow us to ensure the darker end doesn't get so dark that it defeats the purpose of the system.

**Pros**
- [K.I.S.S.](https://getyarn.io/yarn-clip/eed08f4f-d1c9-4cc0-b041-f280a5dbf0a5)
- The percentage based solution only really offered 4 options of overlays anyways, by making it 3 we can tailor each level to look exactly how we want (the overlay values may not increase consistently as the percentage solution would dictate, this would give us more control)
- Don't have to rely on the user as much to make sensible decisions

**Cons**
- User still has to pick one of the 3 options, but hey that's one less option than 4 choices and having to worry about percentages and stuff.

### FYI

@kybaker @jennyhaines @matthewcarleton @andresgalante @LHinson

**Comment by mceledonia** [comment]
Realized I never finished/posted this, here is the new set-based solution. 

[Theme Colors / Overlays Working File](https://drive.google.com/open?id=1Bta878rFdeTgKY6EPutyFJmXTq2IXrAF)
[Overlays PDF](https://drive.google.com/open?id=1vtj_1yE1Nr6DpjCdZJgzTpnoY_KRN673)

**Comment by mceledonia** [comment]
The final iteration of this system has arrived. See the attached PDF for a visual walkthrough. I will also try to summarize below:

## Problem
Our current system is comprised of multiple layers.
1. The original image
2. Grayscale SVG filter*
3. Header overlay
4. Top left overlay

- The reason the header overlay exists is to ensure a baseline minimum-brightness color on our background images, it guarantees that we will never have colors below the threshold of white text accessibility by providing a layer of darkness.
- The reason we needed this is because the grayscale SVG filter just maps all colors of the image to grayscale. The pixels can be mapped to anything from pure white to pure black and everything in between. 
- The header overlay effectively darkens the pixels that are too bright, but it also darkens the pixels that are dark, meaning a dark image is always going to look very different after applying our system than a bright image.

## Solution

The new system is comprised of three layers instead of four, reducing complexity and simultaneously increasing consistency and quality.
1. Image
2. SVG gradient map filter
3. Top left overlay

- With the SVG grayscale filter, the image can end up containing pixels of any grayscale color from pure white to pure black. With the SVG gradient map filter, we have control over those two ends of the spectrum (pure white and pure black) and can change those to be any color we want.
- By assigning the lightest values to a color that is accessible under white text (this is the color that grayscale filter assigns to pure white), we ensure that after only this one filter, all text will be accessible over the image. 
- By assigning the darkest values to a color that is still dark, but not pure black (this is the color that grayscale filter assigns to pure black) we ensure that the image will never have areas that are "too dark" and will always work with our top left overlay. 
- With this massive amount of control over the range of values in every image that the filter is applied to, we ensure maximum consistency across all images and simplify the system at the same time.

## Reference
[CSS Tricks: SVG Gradient Map](https://css-tricks.com/using-svg-to-create-a-duotone-image-effect/)
[ImageTreatmentSystem.pdf](https://github.com/patternfly/patternfly-next/files/2063347/ImageTreatmentSystem.pdf) - Visual Walkthrough



### FYI
@kybaker @andresgalante @matthewcarleton @LHinson

**Comment by dgutride** [comment]
Closed via https://github.com/patternfly/patternfly-next/pull/322
