### ISSUE TITLE
Avatar: Default icon 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#826]
The avatar component needs updated with a default icon. 
![spec-overview](https://user-images.githubusercontent.com/19824574/47670031-a37e6080-db82-11e8-95da-486d3ed1c672.png)

**A few notes on this:**
1. The overall size of the avatar area has changed (this includes the size of the avatar in when the user uploads a photo to use). The new size is 36x36px, which better supports the size of the masthead when it compresses for the on-scroll height. 
2. The photo version is still to be cropped with a circular mask, and the default avatar is available here as both a PNG and SVG
[PF4 Avatar.zip](https://github.com/patternfly/patternfly-next/files/2526466/PF4.Avatar.zip)
3. Here is a spec/ contextual mockup for both the photo avatar and the default
![spec-photo](https://user-images.githubusercontent.com/19824574/47670023-9b262580-db82-11e8-8ab3-666e5eb3b223.png)
![spec-default](https://user-images.githubusercontent.com/19824574/47670202-0243da00-db83-11e8-8d87-0c4b6ede5f22.png)

**Comment by maryshak1996** [comment]
Worked with @kybaker and @mceledonia on this. 
![spec-overview](https://user-images.githubusercontent.com/19824574/47670031-a37e6080-db82-11e8-95da-486d3ed1c672.png)

**A few notes on this:**
1. The overall size of the avatar area has changed (this includes the size of the avatar in when the user uploads a photo to use). The new size is 36x36px, which better supports the size of the masthead when it compresses for the on-scroll height. 
2. The photo version is still to be cropped with a circular mask, and the default avatar is uploaded here as both an SVG and a PNG
![pf4-final-avatar](https://user-images.githubusercontent.com/19824574/47669975-7df15700-db82-11e8-8608-a3c5b93a24e2.png)
3. Here is a spec/ contextual mockup for both the photo avatar and the default
![spec-photo](https://user-images.githubusercontent.com/19824574/47670023-9b262580-db82-11e8-8ab3-666e5eb3b223.png)
![spec-default](https://user-images.githubusercontent.com/19824574/47670026-9cefe900-db82-11e8-8bbe-f8b71764d4ec.png)

**Comment by LHinson** [comment]
thanks @kybaker @mceledonia @maryshak1996! I've updated the description with all the great info from you latest comment. I'll be moving this over to CSS.

**Comment by maryshak1996** [comment]
@matthewcarleton I wanted to also readdress your question during yesterday's demo about the responsiveness of this - I've mocked up this avatar at all page widths and with the on-scroll condensed masthead height, and keeping the size at always 36x36px is in fact the way that we want to move forward! I'm attaching mockups of the different mastheads here (both for photo version and default avatar version) here for reference too :) 
![default-avatar](https://user-images.githubusercontent.com/19824574/47796854-89b45900-dcfb-11e8-8736-61e362e2f832.png)
![photo-upload](https://user-images.githubusercontent.com/19824574/47796860-8b7e1c80-dcfb-11e8-978c-a6de2aea23fd.png)
