### ISSUE TITLE
Update breadcrumb with requested changes

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-next#832]
In this PR #819 we have a number of changes that need to be done.
There are a number of small changes that need to be updated in the css, as well as the docs and the handlebar files.

@michael-coker and I also discussed creating global vars for icons as well as font family. He created issue #830 for this. I think we could create the global var for the font-family in this PR though.

@mcarrano also pointed out a small correction in the content of the breadcrumbs

>Just one small thing... In the first example it goes "Section Home > Section Title > Section Home > >Section Landing." Shouldn't the third item be labeled "Section Title?"

**Comment by matthewcarleton** [comment]
This PR #819 has been merged with most of the issues resolved. @mattnolting is going to take care of the rest in his next PR which should close this issue.

**Comment by LHinson** [comment]
addressed by #912
