### ISSUE TITLE
Dropdown update: class shuffle

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-next#836]
Currently, the top-aligned and right-aligned Dropdown components rely on a specific html structure for the css selectors to apply the necessary styles. For example, the following selector requires the menu to be an immediate child of the dropdown wrapper: 
`.pf-m-align-right > .pf-c-dropdown__menu`

But with recent updates to the dropdown (https://github.com/patternfly/patternfly-react/pull/815), the html structure has been modified and breaks this selector.

After chatting on the #css-army channel in slack, the recommendation is to move the modifier classes to the menu element, so that the selector is not dependent on html structure. 

For example, if we update the selector to be this:
`.pf-m-align-right.pf-c-dropdown__menu`
Then we can move the modifier class to this element:
`<div class="pf-c-dropdown__menu pf-m-align-right">`

These updates should be made for the following classes:

- pf-m-align-right
- pf-m-align-top

**Comment by michael-coker** [comment]
https://github.com/patternfly/patternfly-next/pull/838 merged
