### ISSUE TITLE
Demo: Add table and/or data list example to card

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly-next#841]
Since we're updating card to allow use as a generic container, documentation for using without `header`, `body` and `footer` needs to be provided. An example would be adding filters and pagination to a table.

**Comment by rachael-phillips** [comment]
Closing since #842 merged.

**Comment by mattnolting** [comment]
Hey @rachael-phillips, I think we need to leave this one open bc it refers to creating a demo. But you're correct in that it required #842 to merge:D

**Comment by rachael-phillips** [comment]
Thank you for the info!

**Comment by rachael-phillips** [comment]
Christie addressed this issue #756
