### ISSUE TITLE
Sequence Component (Modifications)

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-next#848]
This issue is created to make changes to the Sequence PR that has already been merged: 

- increase the content min-height so that a user can have title + status for one step, and just title for the next step, without styling errors occurring.
- update documentation to better describe how the control arrows work on an overflow as well as how if status is used on one step, it should be used on all
- include a second example with 3 steps to show how the wizard looks on no overflow
- create a disabled modifier for a step, it wont be clickable until requirements are met
- scrollbar should be visible to indicate scrolling (avoids issue with hiding them)
- fix coloring so that it matches design but also works for light and dark

**Comment by LHinson** [comment]
Closing this issue for now. We'll revisit wizard issue once the design is complete.
