### ISSUE TITLE
Investigate requirement for Switch Enhancement: Tri-State

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#862]
When reviewing the [PF-React switch component PR](https://github.com/patternfly/patternfly-react/pull/761), it was identified that PF3 has a [tri-state](http://patternfly-react.surge.sh/patternfly-3/index.html?knob-Size=normal&knob-On%20Color=primary&knob-Off%20Color=default&knob-animate=true&selectedKind=patternfly-react%2FWidgets%2FSwitch&selectedStory=Switch&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs). PF3 react implementation uses a library called react-bootstrap-switch.  It allows for a triState, where the 3rd state is null, meaning it is an indeterminate state.

In this issue, we will validate whether or not the tri-state is a requirement and determine if this is something we want to proceed with implementing.

**Comment by jgiardino** [comment]
Just wanted to share this bit of info. If we were to implement a tri-state switch, it would help for the designers think about how this control should be announced in screen readers, and also what the keyboard interaction would be.

Currently, we repurpose a checkbox to look like a switch, and this handles both of those for us. If we were to adopt the [aria `role="switch"`](https://www.w3.org/TR/wai-aria-1.1/#switch), we would still be stuck with a `true/false` value, as a mixed value is invalid. 

_Maybe_ if we're repurposing a checkbox button to look like a switch, we could do the same with radio buttons to create the tri-state?? Which would give us keyboard and screen reader accessibility for free. I don't even know if this is possible, so it's a big fat **_MAYBE_**

**Comment by mcarrano** [comment]
Closing. Can revisit in the future should the need arise.
