### ISSUE TITLE
Bullet Chart

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#871]
Add Bullet Chart CSS for PF-React to leverage. 

Bullet chart is included in this PDF with charting styles
[PF4 Charting.pdf](https://github.com/patternfly/patternfly-next/files/2469563/PF4.Charting.pdf)

**Comment by rachael-phillips** [comment]
@dlabrecq have we started any work on Bullet chart and/or would you be interested in working on this?

**Comment by dlabrecq** [comment]
I do have a bullet chart available in Cost Management. It's based on the Victory chart library, using a couple horizontal bar charts.

In general, the charts package still needs more work regarding colors, styling, themes, etc. (I know color pallets have been added to core, but not react-tokens. And we still need grey color scales for the bullet chart -- that's not part of the new color pallets.) Thus, this would be more of a first pass, similar to the charts I've already contributed.

I had asked if I could contribute this component to the patternfly/react-charts package 4-6 weeks ago. However, I was asked to keep the bullet chart in the Cost Management repo -- not sure why. :( It wouldn't take much to submit an initial PR and get the process going.

Here is a snapshot:
![screen shot 2019-02-19 at 3 18 02 pm](https://user-images.githubusercontent.com/17481322/53044657-a4047500-3459-11e9-897c-3a0dde1886d7.png)

**Comment by dlabrecq** [comment]
Note that the colors and layout was based on Kyle's high fidelity mocks:

https://redhat.invisionapp.com/share/ENPJQTBXTAC#/screens/336165167

Colors are slightly different, but quite similar to Micheal's version:

https://drive.google.com/file/d/1jCxBH0niB78V0PJvzHDBr8Hm5wKmDlgH/view

**Comment by rachael-phillips** [comment]
Thanks for offering to contribute, and sorry for any delay.  @mcarrano , @kybaker, @mceledonia can you weigh in here from a design perspective? We will be contributing this in React whenever we are ready.

(FYI @mcoker )

**Comment by mcarrano** [comment]
OK with me. I will defer to @kybaker and @mceledonia regarding visual design.

**Comment by mceledonia** [comment]
The colors for the implementation should probably follow the new color palette colors. Then if we need to diverge from those, like in the cost management mocks, we can do that. I'm thinking we want to be consistent with other chart colors.

**Comment by rachael-phillips** [comment]
@dlabrecq does that sound like a good plan to you? @mceledonia does that mean you are ready to move forward with @dlabrecq building this out?

**Comment by rachael-phillips** [comment]
@dlabrecq we are good to move forward here! All looks good according to design!

**Comment by rachael-phillips** [comment]
We are opening a corresponding React issue
