### ISSUE TITLE
Disabled plain button design

### ISSUE THREAD

**Issue by guillaumevincent** [patternfly/patternfly-next#878]
Hello PF team,

In some design like the pagination design (https://drive.google.com/open?id=1PpIo3-cZeUdVsq9WsG-LmbDj0Vwb6A5E) the disabled icon button is different from the current disabled icon button in pf-next (called plain button).

disabled button icon in the pagination component:

![screenshot from 2018-10-31 10-54-56](https://user-images.githubusercontent.com/943762/47780632-0d6e4580-dcfc-11e8-9fbb-041ef2ee1996.png)
![screenshot from 2018-10-31 11-10-29](https://user-images.githubusercontent.com/943762/47781311-b2d5e900-dcfd-11e8-8233-0938840d72a2.png)

disabled button icon the the current implementation of pf-next:

![screenshot_2018-10-31 pf next 1](https://user-images.githubusercontent.com/943762/47781487-1102cc00-dcfe-11e8-972d-9103759bc5ae.png)

It will be great, in term of composition and consistency if we can have the same look and feel for the disabled button icon the the current implementation of pf-next.

wdyt ?

my request: remove the grey background and use the lighter gray on the icon for the disabled button icon

cc @andresgalante @mceledonia @maryshak1996

**Comment by mceledonia** [comment]
I agree @guillaumevincent , I actually have a disabled icon button state in my initial icon design proposal. I will attach a quick screenshot for reference:

<img width="447" alt="image" src="https://user-images.githubusercontent.com/30935938/48132826-d00d3900-e262-11e8-8a5c-5b9a58971c61.png">

Thanks for bringing that to attention!

**Comment by matthewcarleton** [comment]
thanks @guillaumevincent! @mcoker just put a PR that addresses this #899 please close this issue if you are satisfied with his solution.

**Comment by guillaumevincent** [comment]
@matthewcarleton amazing!
Thanks @mcoker
