### ISSUE TITLE
Workspace Enhancement: Migration Docs need to support full page layouts 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#880]
We have a number of migration doc issues that require linking/showing full page examples (e.g. navigation, login, etc). This issue is to identify how we can approach this as well as updating the workspace to accommodate this requirement.

**Comment by dgutride** [comment]
I don't think this is beta necessary.

**Comment by redallen** [comment]
This was fixed by each fullscreen example getting its own page in the gatsby-theme-patternfly-org conversion.

Example: https://www.patternfly.org/v4/documentation/react/components/accordion/definition-list
