### ISSUE TITLE
Remove workspace classes from handlebars code

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-next#887]
For example, the [Stack](https://pf-next.com/layouts/Stack/examples/) layout uses `.Documentation-container-xtall` to make a tall container. That should be removed and we should use `minHeight` on the `Example` react component or style that preview body in `workspace.scss`. Look through the site for any instances of this kind of thing and update appropriately.

**Comment by redallen** [comment]
I think we should prioritize removing ALL workspace classes higher. They cause issues when rendering fullscreen pages or loading example CodeSandboxes as well.

**Comment by mcoker** [comment]
Looks like this issue has since been resolved.
