### ISSUE TITLE
Address CSS that isn't properly scoped

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-next#888]
For example, in the dropdown component we have:

```
.pf-c-dropdown__menu {
  ...
  .pf-m-align-right > & {
```

In this case, `.pf-m-align-right` is intended to be used with `.pf-c-dropdown`, but the way it's currently written, if the entire dropdown is nested inside an element that also has `.pf-m-align-right`, then the CSS for the dropdown menu will trigger unintentionally.

We need to go through the code and look for selectors written like this, and scope them properly.

**Comment by christiemolloy** [comment]
Closing this issue as it does not apply anymore (was addressed in previous issues).
