### ISSUE TITLE
Add anchors to example headings

### ISSUE THREAD

**Issue by andybraren** [patternfly/patternfly-next#892]
For sharing purposes, it would be helpful for example headings to automatically include a unique `id` (probably based on the heading name) that could be linked to directly.

For example: [https://pf-next.com/components/Table/examples/#expandable-table](https://pf-next.com/components/Table/examples/#expandable-table)

Exposing this link within the Workspace itself can be figured out later (I'd vote for subheadings in the navigation sidebar, but that's a lot more work).

**Comment by mcoker** [comment]
This has since been resolved.
