### ISSUE TITLE
Add type="submit" to the Login Demo's button

### ISSUE THREAD

**Issue by andybraren** [patternfly/patternfly-next#895]
As discussed [here](https://github.com/patternfly/patternfly-react/pull/874#issuecomment-435999073), the demo's "Log in" button should always include `type="submit"` since that's what it's intended to do. Adding this attribute ensures that browsers notify the user of any unfilled inputs prior to form submission.

**Comment by The-lady-developer** [comment]
Hi @andybraren, Can I work on this?

**Comment by andybraren** [comment]
Hello @The-lady-developer sure!

**Comment by mcoker** [comment]
@The-lady-developer thanks for offering to help! I was able to address this as part of https://github.com/patternfly/patternfly-next/pull/964. Feel free to reach out if you would like to work on anything else! We have lots of fun issues open, and I would be happy to help you find something if you want to contribute. 😁
