### ISSUE TITLE
Links as Buttons text not vertically centered

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-next#897]
![screen shot 2018-11-05 at 3 00 41 pm](https://user-images.githubusercontent.com/895728/48023359-937af980-e10b-11e8-9aa1-68b967af8ce9.PNG)

**Comment by mcoker** [comment]
@rhamilto thanks! Once merged, this issue should be addressed in https://github.com/patternfly/patternfly-next/pull/899
