### ISSUE TITLE
Login demo for PF4 missing an example on how to handle server side errors

### ISSUE THREAD

**Issue by dlabaj** [patternfly/patternfly-next#910]
Current PF3 implementation can handle server side errors that aren't related to username and password.  How do we handle this in PF4?  Took a look at toast notifications but they look like they will overlap the top of the login page or push it down.  Need some design input and an updated example for the demo.

**Comment by jknilans** [comment]
@mceledonia and I were working through this for the log in page documentation. 
![login with social example](https://user-images.githubusercontent.com/25486044/49823521-e456c100-fd4d-11e8-85a2-567ac311b5d4.png)
This version would push the content down the page to make room for the alert, but if the page jumping is an issue he space could be built into it when an alert isn't present. Thoughts?

**Comment by mcarrano** [comment]
This issue will be addressed as part of #1069. Will close this out.
