### ISSUE TITLE
Switch enhancement: update css so that label changes depending on state

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-next#915]
Currently, the switch is only partially a css only solution, where a checkbox is styled to look like a switch and can be toggled without using JS. However currently, the label does not update to indicate selection state (e.g. "On" vs "Off"). 

Updates for this issue include:

- Adding a label for each selection state, like "On" and "Off", instead of the single "label"
- Add css to toggle the display of the two labels based on the state of the checkbox
- Make sure the styles that are applied to the visible label based on state in the current implementation are applied to the new labels (e.g. when off, the text is lighter in color)

**Comment by garrett** [comment]
I believe this demo should fulfill the requirements:
https://codepen.io/garrett/pen/Rqapxm

---

### Explanation

First, we duplicate the text and give each a class, like `is-on` and `is-off` and remove `aria-hidden`:

```html
<label class="pf-c-switch" for="switch-on-example">
  <input class="pf-c-switch__input" type="checkbox" id="switch-on-example" aria-label="..." checked>
  <span class="pf-c-switch__toggle">
  </span>
  <span class="pf-c-switch__label is-off">
      Message when off
  </span>
  <span class="pf-c-switch__label is-on">
      Message when on
  </span>
</label>
```

Then we target the selectors and hide with `display: none` based on the checkbox's state:

```css
.pf-c-switch__input:not(:checked) ~ .is-on,
.pf-c-switch__input:checked ~ .is-off {
  display: none;
}
```

Screen readers are supposed to not render `display: none`, hence the removal of `aria-hidden` earlier. This solution should work purely in CSS, without JavaScript.

**Comment by jgiardino** [comment]
> Screen readers are supposed to not render display: none, hence the removal of aria-hidden earlier.

During previous testing, I had noticed some odd behavior in JAWS with using just `display:none;` to hide elements. 

[This article](https://medium.engineering/five-goofy-things-medium-did-that-break-accessibility-3bc804ae818d) is a great summary of this issue with a css-only recommendation. I tested the suggestion to use both `display:none; visibility:hidden;` together and it works fine in the [screen reader / browser combinations](https://pf-next.com/accessibility-guide/#testing) that we test against. 

I just wanted to share that tidbit of info, even though I don't think it's necessary in this case.

Also, we might not need `aria-hidden`, but I'd have to test this across the screen readers just to check. Ultimately, we want to control what the label is for the checkbox using `aria-label` or `aria-labelledby` on the `<input>`. And doing this _might_ override any text included inside the `<label>` element as the accessible label, which would be ideal. But if not, then we'd definitely want to include `aria-hidden` on these `<span>`s to avoid having them announced at a time that would be confusing. I'm wondering if it's better to include this anyway, just to be safe. 

Essentially, this raises the question of what we want the screen reader to announce. And sense the screen reader sees this control as a checkbox, it would announce something like "[checkbox label] checkbox checked" or "[checkbox label] checkbox not checked". 

In my opinion, hearing "Disabled Enabled checkbox not checked" would be really confusing. Below are two examples of what I think the right screen reader experience would be:

1. Use case 1 - the meaningful label is included in the switch
    - For the visible label `(  o) Enabled`
      the screen reader should announce: `"Enabled checkbox checked"`
    - For the visible label `(o  ) Disabled`
      the screen reader should announce: `"Enabled checkbox not checked"`
      - My thinking here is that if the control is presented as a checkbox to screen reader users, then we should always announce the label associated with the checked state, since the "checked"/"not checked" information is handled by the screen reader (e.g. "Disabled checkbox not checked" would be really confusing).
2. Use case 2 - the meaningful label precedes the switch
    - For the visible labels `Notify by email (  o) On`
  the screen reader should announce: `"Notify by email checkbox checked"`
    - My thinking here is that if there is an additional label that precedes the switch, we should incorporate that, and not just say "On checkbox checked".
      - For the visible labels `Notify by email    (o  ) Off`
  the screen reader should announce: `"Notify by email checkbox not checked"`

To accomplish this, I think the right approach is to: 

1. Define the accessible label on the checkbox using `aria-labelledby`:
    ```
    <input class="pf-c-switch__input" type="checkbox" id="switch-on-example" aria-labelledby="..." checked>
    ```
    And depending on the use case, use the id of the label that communicates what it means to be on.
2. Apply `aria-hidden` to the `<span>`s containing the visible labels, so that they aren't announced unless referenced by `aria-labelledby` on the checkbox.

I'm totally open to other suggestions on this. These are just the best suggestions I can come up with at the moment.

**Comment by jgiardino** [comment]
Oh, I just found this. I created it the day before a week of PTO and had completely purged it from my brain. In captures some issues I had noticed before adding the aria-hidden attribute.

https://github.com/patternfly/patternfly-next/issues/858

**Comment by mcoker** [comment]
resolved in https://github.com/patternfly/patternfly-next/pull/1300
