### ISSUE TITLE
Data Input - Design Doc

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#917]
Introduce a design guidelines page that provides guidance on using different input components on forms and elsewhere.

**Comment by mcarrano** [comment]
@stacymcauliffe as discussed, I've created this new issue and assigned to you. Feel free to update the description with more specifics.

**Comment by stacymcauliffe** [comment]
@mcarrano - when you get a chance, can you review this draft of text and data input: 
https://docs.google.com/document/d/1d1WYPcNaWMZeHKdqur2mvPTz96O7YAQkbQ2VetPPezg/edit?usp=sharing

I still need to create images. For help and validation/errors, I pulled that content from forms. Let me know if you think it belongs in both places or maybe one or the other. 

Thanks!

**Comment by stacymcauliffe** [comment]
@mcarrano - I split the text input and data input as we discussed, and also worked to remove duplicated info and cross link to forms guidelines. I'm still working on creating images, but I think the text is in a good place. 

Data input:  https://docs.google.com/document/d/1d1WYPcNaWMZeHKdqur2mvPTz96O7YAQkbQ2VetPPezg/edit?usp=sharing
Text input: https://docs.google.com/document/d/1tjJYqhgI7-M68K0t4qbfM4tUKWHZ0zwWszuDKaN-YJU/edit?usp=sharing

**Comment by mcarrano** [comment]
@stacymcauliffe I reviewed these and left a few comments. I think they are pretty close to done.
