### ISSUE TITLE
Order of Padding is Wrong for Page Component

### ISSUE THREAD

**Issue by bianca-sparxs** [patternfly/patternfly-next#942]
@mcoker 
The order of the padding is wrong, when specifying size of PaddingLeft it is changing Padding Bottom and vice versa.

https://github.com/patternfly/patternfly-next/blob/53c34eaf8b74d7327d4f974f4aad7d18b366c18f/src/patternfly/layouts/Page/page.scss#L274-L279

**Comment by jschuler** [comment]
Hi @bianca-sparxs, nice find! Looks like this got fixed a few days ago in #908 which appears to be included in v 1.0.71. We just have to pull this newer version into @patternfly/react-core now and then this should be fixed there as well!

**Comment by mcoker** [comment]
Thanks @bianca-sparxs! Going to go ahead and close since this was addressed in core already. The PR in the patternfly-react repo to pull in this change is https://github.com/patternfly/patternfly-react/pull/920 if you want to follow that.
