### ISSUE TITLE
Investigate CSS in BackgroundImage and LoginPageHeader components

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-next#954]
These PF4 react components are using custom CSS in their component, and all of the CSS should be coming from core. We should investigate these components and figure out why the custom CSS is necessary and figure out a way to deliver it in core instead.

**Comment by christiemolloy** [comment]
@mcoker could you clarify where you're seeing the custom CSS in BackgroundImage and LoginPageHeader? I'm having a hard time finding the extra CSS

**Comment by dlabaj** [comment]
BackgroundImage.js

  const bgStyles = StyleSheet.create({
    bgOverrides: `&.pf-c-background-image {
      ${Object.keys(variableOverrides).reduce(
        (prev, size) => `${prev.length ? prev : ''}${variableMap[size]}: url('${variableOverrides[size]}');`,
        {}
      )}
    }`
  });

**Comment by dlabaj** [comment]
Only style sheet create left in the Background image is needed for when users specify their own images.  Closing based on updates and no need for changes to BackgroundImage.js
