### ISSUE TITLE
Update expanded table row styles

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-next#956]
The row that expands should have a blue left border and the top shadow of the expanded panel (where the row that expands and the expandable content blow it meet) shouldn't be visible. The shadow on the left/right of the expanded table row is also darker than the rest of the table's shadows.

The expanded table row should match the data list expanded row in those regards.

Expanded table row
<img width="1059" alt="screen shot 2018-11-19 at 4 43 16 pm" src="https://user-images.githubusercontent.com/35148959/48739664-3c504b00-ec1a-11e8-9cfd-39646331bf8d.png">

Expanded data list row
<img width="1051" alt="screen shot 2018-11-19 at 4 43 06 pm" src="https://user-images.githubusercontent.com/35148959/48739661-39edf100-ec1a-11e8-92fa-ec169007347f.png">

cc @mceledonia

**Comment by mattnolting** [comment]
This issue will be fixed in https://github.com/patternfly/patternfly-next/issues/721 and https://github.com/patternfly/patternfly-next/issues/1001. Thanks for looking into it @jameslau!

**Comment by rachael-phillips** [comment]
Closing this issue addressed in #721 and #1001
