### ISSUE TITLE
Introduce new flexbox layout

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-next#957]
This is related to #886 
Our currently toolbar layout needs to be updated to be a component which leaves us with a need for a more generic type of layout to meet the needs that our current toolbar layout was fulfilling. 
This should be a flexbox layout with modifiers for spacing.
We still need to investigate the overall requirements and use cases for this layout to ensure it is flexible enough.

**Comment by mcoker** [comment]
I don't think we need this anymore. The flex layout is nearly done, but we've replaced the current uses of the toolbar component with regular ol' CSS.
