### ISSUE TITLE
Toolbar Component

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#959]
Introduce a Toolbar component that can be used whenever a toolbar is required for a table, list, card, or similar data view. 

Toolbar design doc: https://docs.google.com/document/d/1F6K7FdpcRuyFssPhenyLQqo5-_247dQW_TkrU8CpTT4/edit?usp=sharing

Wireframe designs: https://drive.google.com/open?id=1zpNYyxM0_AKcIXlU6YanRk93cpLuUjaw

Toolbar is a complex component that can contain other components as outlined in the document. This is intended to supersede the earlier Toolbar Demo.

**Comment by mcarrano** [comment]
@kybaker @mceledonia @LHinson @mattnolting 

I have created this issue to track work on a Toolbar component as discussed in a meeting on Nov 19. Links to a preliminary design doc and wireframes are included. Next steps are to create high-fidelity visuals. 

I have follow-on work to consider how the toolbar appears in the context of a page for list, table, and card views. That work will be tracked separately and should drive full-screen demos. Related issues already exist as https://github.com/patternfly/patternfly-next/issues/756 and https://github.com/patternfly/patternfly-next/issues/297

**Comment by gdoyle1** [comment]
I've finished basic necessary states for the toolbar. I'll finish up some additional states (options with the bulk selection) and the mobile design tomorrow! Here's the link to see it in InVision: https://redhat.invisionapp.com/share/67PFEYCRWZF#/334794735_Toolbar_Components

**Comment by gdoyle1** [comment]
@mcarrano I've made some updates based on your feedback here https://redhat.invisionapp.com/share/67PFEYCRWZF#/335107769_V2_Toolbar_-PDF-. I ended up also tweaking some other things to try to alleviate the crowdedness.

**Comment by gdoyle1** [comment]
@mcarrano @kybaker @mceledonia I updated the toolbar based on our conversation today [here](https://redhat.invisionapp.com/share/67PFEYCRWZF).

I was able to add examples of the toolbar on a table, hybrid list, and mobile list. I am working on getting a card view as well.

For mobile - I still think we need more than just the hover interaction. I suggest we go with the focus state as I think that is more obvious and already implemented.

Let me know your thoughts when you get a chance!

**Comment by mcarrano** [comment]
I think this all looks great @gdoyle1 There was just one small comment about the pagination in the footer. Otherwise I am good with this. @kybaker @mceledonia what do you think?

**Comment by gdoyle1** [comment]
@mcarrano @mceledonia @kybaker Based on our call today, all updates have been made [here](https://redhat.invisionapp.com/share/67PFEYCRWZF)! I added the spec in there as well.

**Comment by mcarrano** [comment]
Reviewed lastest toolbar designs with devs today. The following are open issues and follow-up items.

* When filter controls collapse to an overlay panel for mobile access, unclear best approach to show/hide panel via keyboard controls. Requires further exploration.

* Need a new component (or extension to Dropdown) that supports option selection as shown for Sort. Added https://github.com/patternfly/patternfly-next/issues/1088.

* Screen reader behavior for selecting items per page in Pagination needs clarification. @mattnolting and @jgiardino to explore.

@mcarrano and @gdoyle1 will update design docs and visual mockups, respectively to make design clarifications.

**Comment by rachael-phillips** [comment]
Dependency on #651 Custom selects merging

**Comment by christiemolloy** [comment]
FYI, This component is currently waiting on the following to be merged:
- Flex Layout
- Custom Selects
- Pagination

**Comment by mcoker** [comment]
Tablet mocks:

<img width="714" alt="screen shot 2019-01-17 at 2 31 57 pm" src="https://user-images.githubusercontent.com/35148959/51345466-af324280-1a60-11e9-9ed2-b3ab4b60b570.png">
<img width="713" alt="screen shot 2019-01-17 at 2 32 05 pm" src="https://user-images.githubusercontent.com/35148959/51345465-af324280-1a60-11e9-8408-06cee4dfeef6.png">

**Comment by gdoyle1** [comment]
Here's the newest version of the toolbar with mockups of desktop, tablet, mobile screen sizes. https://redhat.invisionapp.com/share/67PFEYCRWZF

Things to note:
- Right-aligned the item count in the mobile toolbar and left-aligned the actionable icons to stay consistent with the desktop and tablet toolbar designs.
- I couldn’t fit the caret icon in the tablet pagination alongside the item count BUT ideally it would be there still (if not then we can just show the item count as mocked up). If there’s no bulk selector in the toolbar, it should be able to fit at least.
- As the full size toolbar goes responsive, pagination would drop first, then action items would combine into the kebab, then filter dropdown and input field would combine into filter icon.
- Desktop and mobile pagination designs are included in the actual data table examples. Tablet pagination designs are included in the toolbar spec and toolbar examples screens.
