### ISSUE TITLE
Page Layout Demo Audit

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-next#977]
Audit of all examples under the Page Layout Demo produced these bugs in comparison with design:

1. "Page Layout Default Nav Tall Header Example" :
a) menu/kebab icon is not centered with Patternfly logo. 

2. "Page Layout Expandable Nav Example": 
a) space between nav item and its bottom-border isn't large enough to reflect designs.
b) on the mobile view, the text area with main title doesnt have the correct padding-left to align with the nav and cards
c) on mobile view, the avatar icon doesnt have the correct spacers to the top and right of it.
d) menu/kebab icon is not centered with Patternfly logo. 

3. "Page Layout Horizontal Nav Example":
a) missing the "My Project" dropdown
b) nav items need correct spacing between text and border-bottom
c) the entire nav needs the correct spacers at the top
d) on the mobile view, the text area with main title doesnt have the correct padding-left to align with the nav and cards
e) on mobile view, the avatar icon doesnt have the correct spacers to the top and right of it
f) menu/kebab icon is not centered with Patternfly logo. 

4. "Page Layout Simple Nav Example"
a) menu/kebab icon is not centered with Patternfly logo. 
b) on mobile view, the avatar icon doesnt have the correct spacers to the top and right of it

5. "Page Layout Grouped Nav Example"
a) menu/kebab icon is not centered with Patternfly logo. 
b) on mobile view, the avatar icon doesnt have the correct spacers to the top and right of it

**Comment by matthewcarleton** [comment]
We'll have to recheck this list once the PR's I have open get merged b/c they will fix some of these bugs.

**Comment by christiemolloy** [comment]
@matthewcarleton definitely, I can handle that

**Comment by christiemolloy** [comment]
Across all example Page Layouts is a bug in the dropdown kebab menu see this issue https://github.com/patternfly/patternfly-next/issues/1027

**Comment by rachael-phillips** [comment]
Are we ready to close this out based on #955?

**Comment by christiemolloy** [comment]
@rachael-phillips yes I believe so!

**Comment by rachael-phillips** [comment]
Closing this out based on #955
