### ISSUE TITLE
Review Global Variables for Border sizes, Colors and Shadows

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#99]
CSS and visual design to work together to determine what additional global variables need to be defined. 

Known gaps are: 
* Border sizes 
* Colors for states (visuals has defined it, this is a CSS task) 
* Colors in general require discussion between CSS and visuals 
* Review and test shadows (CSS)

**Comment by LHinson** [comment]
related to #58

**Comment by LHinson** [comment]
@kybaker do we have assets/specs yet for border sizes, color and shadows?

**Comment by kybaker** [comment]
@LHinson We do. This was most of the work done leading up to the dev meetup. We have designed most of the global styles and met with CSS to verify the validity. 

[Most of everything we have defined can be seen across these PDFs](https://drive.google.com/open?id=13-PvTNhHhoGZ3mB4j9g-emEdPR5WL3nJ)

**Comment by LHinson** [comment]
Variables have been introduced, this will be continued to be refined as we build components.
